#define MODEL_Root              0x15
#define MODEL_g13               0x14
#define MODEL_o49               0x13
#define MODEL_g19               0x12
#define MODEL_o48               0x11
#define MODEL_g18               0x10
#define MODEL_o47               0xF
#define MODEL_g17               0xE
#define MODEL_o44               0xD
#define MODEL_g16               0xC
#define MODEL_o46               0xB
#define MODEL_g15               0xA
#define MODEL_o45               0x9
#define MODEL_Default           0x8
#define MODEL_kusa              0x7
#define MODEL_o42               0x6
#define MODEL_ido               0x5
#define MODEL_kabe              0x4
#define MODEL_yuka              0x3
#define MODEL_exit              0x2
#define MODEL_o37               0x1
#define MODEL_doa               0x0

