#define MODEL_Root              0x1E
#define MODEL_dai               0x1D
#define MODEL_waku1             0x1C
#define MODEL_kusa3             0x1B
#define MODEL_iwa4              0x1A
#define MODEL_iwa3              0x19
#define MODEL_g78               0x18
#define MODEL_o349              0x17
#define MODEL_o350              0x16
#define MODEL_yuka5             0x15
#define MODEL_yuka4             0x14
#define MODEL_g49               0x13
#define MODEL_waku2             0x12
#define MODEL_kusa2             0x11
#define MODEL_iwa2              0x10
#define MODEL_kusa1             0xF
#define MODEL_kusa4             0xE
#define MODEL_ki1               0xD
#define MODEL_iwa1              0xC
#define MODEL_g93               0xB
#define MODEL_o399              0xA
#define MODEL_o398              0x9
#define MODEL_g92               0x8
#define MODEL_o403              0x7
#define MODEL_o381              0x6
#define MODEL_o395              0x5
#define MODEL_kabe2             0x4
#define MODEL_kusa5             0x3
#define MODEL_iwa5              0x2
#define MODEL_waku              0x1
#define MODEL_yuka1             0x0

