#define MODEL_Root              0x20
#define MODEL_g12               0x1F
#define MODEL_g13               0x1E
#define MODEL_o39               0x1D
#define MODEL_g14               0x1C
#define MODEL_o40               0x1B
#define MODEL_o47               0x1A
#define MODEL_o38               0x19
#define MODEL_o37               0x18
#define MODEL_o36               0x17
#define MODEL_o35               0x16
#define MODEL_Default           0x15
#define MODEL_iwa4              0x14
#define MODEL_iwa3              0x13
#define MODEL_iwa2              0x12
#define MODEL_iwa1              0x11
#define MODEL_sigemi            0x10
#define MODEL_ki                0xF
#define MODEL_ki3               0xE
#define MODEL_ki2               0xD
#define MODEL_ki1               0xC
#define MODEL_g1                0xB
#define MODEL_miti              0xA
#define MODEL_tuti2             0x9
#define MODEL_o48               0x8
#define MODEL_kusa2             0x7
#define MODEL_g4                0x6
#define MODEL_o49               0x5
#define MODEL_kusa              0x4
#define MODEL_waku              0x3
#define MODEL_exit              0x2
#define MODEL_exit2             0x1
#define MODEL_exit1             0x0

