#define MODEL_Root              0x1B
#define MODEL_g6                0x1A
#define MODEL_o44               0x19
#define MODEL_o37               0x18
#define MODEL_o21               0x17
#define MODEL_o19               0x16
#define MODEL_yabu              0x15
#define MODEL_kusa1             0x14
#define MODEL_iwa               0x13
#define MODEL_1wa8              0x12
#define MODEL_1wa7              0x11
#define MODEL_1wa6              0x10
#define MODEL_1wa5              0xF
#define MODEL_iwa4              0xE
#define MODEL_1wa3              0xD
#define MODEL_1wa2              0xC
#define MODEL_iwa1              0xB
#define MODEL_g1                0xA
#define MODEL_o6                0x9
#define MODEL_o3                0x8
#define MODEL_g2                0x7
#define MODEL_waku              0x6
#define MODEL_soku              0x5
#define MODEL_kusa              0x4
#define MODEL_tuti              0x3
#define MODEL_exit              0x2
#define MODEL_exit2             0x1
#define MODEL_exit1             0x0

