#define MODEL_Root              0x16
#define MODEL_dai               0x15
#define MODEL_o349              0x14
#define MODEL_waku1             0x13
#define MODEL_kabe3             0x12
#define MODEL_yuka              0x11
#define MODEL_jun               0x10
#define MODEL_o343              0xF
#define MODEL_o342              0xE
#define MODEL_o341              0xD
#define MODEL_o340              0xC
#define MODEL_o339              0xB
#define MODEL_o338              0xA
#define MODEL_o337              0x9
#define MODEL_o348              0x8
#define MODEL_g49               0x7
#define MODEL_kusa              0x6
#define MODEL_waku2             0x5
#define MODEL_kabe4             0x4
#define MODEL_kabe2             0x3
#define MODEL_kabe1             0x2
#define MODEL_yuka2             0x1
#define MODEL_waku              0x0

