#define MODEL_Root              0x1D
#define MODEL_dai               0x1C
#define MODEL_waku1             0x1B
#define MODEL_kusa3             0x1A
#define MODEL_iwa4              0x19
#define MODEL_iwa3              0x18
#define MODEL_g78               0x17
#define MODEL_o349              0x16
#define MODEL_o350              0x15
#define MODEL_yuka5             0x14
#define MODEL_yuka4             0x13
#define MODEL_g85               0x12
#define MODEL_waku2             0x11
#define MODEL_kusa2             0x10
#define MODEL_ki1               0xF
#define MODEL_iwa1              0xE
#define MODEL_kusa1             0xD
#define MODEL_yuka3             0xC
#define MODEL_iwa2              0xB
#define MODEL_ki2               0xA
#define MODEL_g73               0x9
#define MODEL_o332              0x8
#define MODEL_g49               0x7
#define MODEL_koya              0x6
#define MODEL_o333              0x5
#define MODEL_o330              0x4
#define MODEL_o328              0x3
#define MODEL_o327              0x2
#define MODEL_waku              0x1
#define MODEL_yuka1             0x0

