#define MODEL_Root              0x12
#define MODEL_dai               0x11
#define MODEL_o354              0x10
#define MODEL_waku1             0xF
#define MODEL_kabe3             0xE
#define MODEL_yuka              0xD
#define MODEL_g49               0xC
#define MODEL_waku2             0xB
#define MODEL_kabe4             0xA
#define MODEL_doa2              0x9
#define MODEL_o349              0x8
#define MODEL_o350              0x7
#define MODEL_doa1              0x6
#define MODEL_o348              0x5
#define MODEL_o351              0x4
#define MODEL_kabe2             0x3
#define MODEL_kabe1             0x2
#define MODEL_yuka2             0x1
#define MODEL_waku              0x0

