#define COLLIDER_Root           0x26
#define COLLIDER_g23            0x25
#define COLLIDER_o75            0x24
#define COLLIDER_iwa            0x23
#define COLLIDER_o37            0x22
#define COLLIDER_o92            0x21
#define COLLIDER_o60            0x20
#define COLLIDER_o53            0x1F
#define COLLIDER_o38            0x1E
#define COLLIDER_1wa5           0x1D
#define COLLIDER_g2             0x1C
#define COLLIDER_o91            0x1B
#define COLLIDER_o90            0x1A
#define COLLIDER_o58            0x19
#define COLLIDER_o89            0x18
#define COLLIDER_o88            0x17
#define COLLIDER_o57            0x16
#define COLLIDER_o87            0x15
#define COLLIDER_o86            0x14
#define COLLIDER_o56            0x13
#define COLLIDER_o85            0x12
#define COLLIDER_o84            0x11
#define COLLIDER_o55            0x10
#define COLLIDER_o83            0xF
#define COLLIDER_o82            0xE
#define COLLIDER_o54            0xD
#define COLLIDER_o81            0xC
#define COLLIDER_o80            0xB
#define COLLIDER_o59            0xA
#define COLLIDER_exite          0x9
#define COLLIDER_tte            0x8
#define COLLIDER_ne             0x7
#define COLLIDER_deilie         0x6
#define COLLIDER_deilite        0x5
#define COLLIDER_exitw          0x4
#define COLLIDER_ttw            0x3
#define COLLIDER_nw             0x2
#define COLLIDER_deiliw         0x1
#define COLLIDER_deilitw        0x0

#define ZONE_Root               0x4
#define ZONE_g16                0x3
#define ZONE_o61                0x2
#define ZONE_o60                0x1
#define ZONE_o59                0x0

