#define COLLIDER_Root           0x25
#define COLLIDER_g22            0x24
#define COLLIDER_o91            0x23
#define COLLIDER_g21            0x22
#define COLLIDER_o88            0x21
#define COLLIDER_iwa            0x20
#define COLLIDER_o54            0x1F
#define COLLIDER_o53            0x1E
#define COLLIDER_o51            0x1D
#define COLLIDER_ki2            0x1C
#define COLLIDER_ki             0x1B
#define COLLIDER_g2             0x1A
#define COLLIDER_o103           0x19
#define COLLIDER_o66            0x18
#define COLLIDER_o101           0x17
#define COLLIDER_o65            0x16
#define COLLIDER_o100           0x15
#define COLLIDER_o99            0x14
#define COLLIDER_o64            0x13
#define COLLIDER_o98            0x12
#define COLLIDER_o97            0x11
#define COLLIDER_o63            0x10
#define COLLIDER_o96            0xF
#define COLLIDER_o95            0xE
#define COLLIDER_o62            0xD
#define COLLIDER_o94            0xC
#define COLLIDER_o93            0xB
#define COLLIDER_o67            0xA
#define COLLIDER_exite          0x9
#define COLLIDER_tte            0x8
#define COLLIDER_ne             0x7
#define COLLIDER_deilie         0x6
#define COLLIDER_deilite        0x5
#define COLLIDER_exitw          0x4
#define COLLIDER_ttw            0x3
#define COLLIDER_nw             0x2
#define COLLIDER_deiliw         0x1
#define COLLIDER_deilitw        0x0

#define ZONE_Root               0x4
#define ZONE_g16                0x3
#define ZONE_o65                0x2
#define ZONE_o64                0x1
#define ZONE_o63                0x0

