#define COLLIDER_Root 0xE
#define COLLIDER_exite 0xD
#define COLLIDER_ne 0xC
#define COLLIDER_tte 0xB
#define COLLIDER_deilie 0xA
#define COLLIDER_deilite 0x9
#define COLLIDER_exitw 0x8
#define COLLIDER_nw 0x7
#define COLLIDER_ttw 0x6
#define COLLIDER_deiliw 0x5
#define COLLIDER_deilitw 0x4
#define COLLIDER_Default 0x3
#define COLLIDER_o44 0x2
#define COLLIDER_kabe 0x1
#define COLLIDER_yuka 0x0
