#define MODEL_Root              0x15
#define MODEL_dai               0x14
#define MODEL_waku1             0x13
#define MODEL_kumo1             0x12
#define MODEL_yuka              0x11
#define MODEL_g49               0x10
#define MODEL_waku2             0xF
#define MODEL_ten4              0xE
#define MODEL_kumo3             0xD
#define MODEL_ten3              0xC
#define MODEL_kumo2             0xB
#define MODEL_hikari            0xA
#define MODEL_ten2              0x9
#define MODEL_hikari2           0x8
#define MODEL_hahen             0x7
#define MODEL_y_hikari          0x6
#define MODEL_hibi              0x5
#define MODEL_kabe              0x4
#define MODEL_kaza              0x3
#define MODEL_ten1              0x2
#define MODEL_yuka2             0x1
#define MODEL_waku              0x0

