#define MODEL_Root              0x11
#define MODEL_dai               0x10
#define MODEL_waku1             0xF
#define MODEL_yuka              0xE
#define MODEL_g49               0xD
#define MODEL_waku2             0xC
#define MODEL_hibi              0xB
#define MODEL_mado3_3           0xA
#define MODEL_mado3             0x9
#define MODEL_mado2_2           0x8
#define MODEL_mado2             0x7
#define MODEL_mado1_1           0x6
#define MODEL_mado              0x5
#define MODEL_kaza              0x4
#define MODEL_kumonosu          0x3
#define MODEL_kabe              0x2
#define MODEL_yuka2             0x1
#define MODEL_waku              0x0

