#define MODEL_Root              0xA4
#define MODEL_mazinai           0xA3
#define MODEL_kemuri            0xA2
#define MODEL_m_hone            0xA1
#define MODEL_m_zyu             0xA0
#define MODEL_m_nuno2           0x9F
#define MODEL_m_nuno1           0x9E
#define MODEL_m_hasi            0x9D
#define MODEL_tubo              0x9C
#define MODEL_o971              0x9B
#define MODEL_o970              0x9A
#define MODEL_o967              0x99
#define MODEL_o965              0x98
#define MODEL_g241              0x97
#define MODEL_o907              0x96
#define MODEL_o906              0x95
#define MODEL_t3                0x94
#define MODEL_o956              0x93
#define MODEL_t2                0x92
#define MODEL_o955              0x91
#define MODEL_t1                0x90
#define MODEL_o958              0x8F
#define MODEL_g222              0x8E
#define MODEL_tubo5             0x8D
#define MODEL_futa5             0x8C
#define MODEL_g221              0x8B
#define MODEL_tubo4             0x8A
#define MODEL_futa4             0x89
#define MODEL_g218              0x88
#define MODEL_futa2             0x87
#define MODEL_tubo2             0x86
#define MODEL_k_i5              0x85
#define MODEL_ie5_naka          0x84
#define MODEL_5n_naisou         0x83
#define MODEL_o966              0x82
#define MODEL_o977              0x81
#define MODEL_g254              0x80
#define MODEL_o975              0x7F
#define MODEL_o974              0x7E
#define MODEL_g253              0x7D
#define MODEL_o973              0x7C
#define MODEL_o972              0x7B
#define MODEL_book2             0x7A
#define MODEL_book1             0x79
#define MODEL_5n_ranpu          0x78
#define MODEL_5n_kanbutu        0x77
#define MODEL_5n_binn           0x76
#define MODEL_5n_tukue          0x75
#define MODEL_r_hako            0x74
#define MODEL_5n_futi           0x73
#define MODEL_5n_zyu            0x72
#define MODEL_5_uka             0x71
#define MODEL_5n_kabe           0x70
#define MODEL_5_doa2            0x6F
#define MODEL_o770              0x6E
#define MODEL_5_doa             0x6D
#define MODEL_o769              0x6C
#define MODEL_g200              0x6B
#define MODEL_6_moyou           0x6A
#define MODEL_6_waku            0x69
#define MODEL_6_kabe            0x68
#define MODEL_ie5               0x67
#define MODEL_yane              0x66
#define MODEL_5_post2           0x65
#define MODEL_5_poster          0x64
#define MODEL_5_yane            0x63
#define MODEL_5_waku            0x62
#define MODEL_5_hasira2         0x61
#define MODEL_5_moyou           0x60
#define MODEL_5_kabe            0x5F
#define MODEL_k_i4              0x5E
#define MODEL_mae               0x5D
#define MODEL_o938              0x5C
#define MODEL_o937              0x5B
#define MODEL_o936              0x5A
#define MODEL_i4_mado           0x59
#define MODEL_4_hasis2          0x58
#define MODEL_ie4_naka          0x57
#define MODEL_4_naisou          0x56
#define MODEL_g255              0x55
#define MODEL_o980              0x54
#define MODEL_o979              0x53
#define MODEL_4_ranpu           0x52
#define MODEL_tukue             0x51
#define MODEL_bed               0x50
#define MODEL_o987              0x4F
#define MODEL_futon             0x4E
#define MODEL_bed__             0x4D
#define MODEL_4n_kannbutu       0x4C
#define MODEL_4n_hari           0x4B
#define MODEL_4n_tana           0x4A
#define MODEL_4n_binn           0x49
#define MODEL_4n_mado           0x48
#define MODEL_4n_moyo           0x47
#define MODEL_4n_kabe           0x46
#define MODEL_4n_waku           0x45
#define MODEL_4n_yane           0x44
#define MODEL_4_yuka            0x43
#define MODEL_g229              0x42
#define MODEL_tubo8             0x41
#define MODEL_futa8             0x40
#define MODEL_i4_doa            0x3F
#define MODEL_4_doa             0x3E
#define MODEL_mobe              0x3D
#define MODEL_4_hasira2         0x3C
#define MODEL_4_kabe2           0x3B
#define MODEL_4_moyou2          0x3A
#define MODEL_4_waku2           0x39
#define MODEL_ie4               0x38
#define MODEL_4_saku            0x37
#define MODEL_4_yane            0x36
#define MODEL_4_waku            0x35
#define MODEL_4_kabe            0x34
#define MODEL_4_moyou           0x33
#define MODEL_i4_bou            0x32
#define MODEL_kanban            0x31
#define MODEL_o852              0x30
#define MODEL_ie3               0x2F
#define MODEL_3_yane            0x2E
#define MODEL_3_rennga          0x2D
#define MODEL_3_kabe            0x2C
#define MODEL_ie2               0x2B
#define MODEL_2_saku            0x2A
#define MODEL_2_yane            0x29
#define MODEL_2_hasira3         0x28
#define MODEL_2_hasira2         0x27
#define MODEL_2_hasira          0x26
#define MODEL_2_moyou           0x25
#define MODEL_2_mado            0x24
#define MODEL_2_kabe            0x23
#define MODEL_ie1               0x22
#define MODEL_1_saku            0x21
#define MODEL_1_yane            0x20
#define MODEL_1_kui             0x1F
#define MODEL_1_nuno            0x1E
#define MODEL_1_waku            0x1D
#define MODEL_1_hasira3         0x1C
#define MODEL_1_hasira2         0x1B
#define MODEL_1_hasira          0x1A
#define MODEL_1_moyou           0x19
#define MODEL_1_mado            0x18
#define MODEL_1_kabe            0x17
#define MODEL_doa               0x16
#define MODEL_1_doa             0x15
#define MODEL_etc               0x14
#define MODEL_saku              0x13
#define MODEL_nuno              0x12
#define MODEL_bou               0x11
#define MODEL_oke               0x10
#define MODEL_hei               0xF
#define MODEL_g_moyou           0xE
#define MODEL_h_kabe            0xD
#define MODEL_hako2             0xC
#define MODEL_hako3             0xB
#define MODEL_hako              0xA
#define MODEL_hako4             0x9
#define MODEL_exitw             0x8
#define MODEL_waku              0x7
#define MODEL_bero              0x6
#define MODEL_g1                0x5
#define MODEL_road              0x4
#define MODEL_frame             0x3
#define MODEL_1_uka             0x2
#define MODEL_stege2            0x1
#define MODEL_stege             0x0

