#define COLLIDER_Root           0x17
#define COLLIDER_g1             0x16
#define COLLIDER_g37            0x15
#define COLLIDER_o110           0x14
#define COLLIDER_o109           0x13
#define COLLIDER_g9             0x12
#define COLLIDER_o13            0x11
#define COLLIDER_o3             0x10
#define COLLIDER_o10            0xF
#define COLLIDER_g10            0xE
#define COLLIDER_o105           0xD
#define COLLIDER_o112           0xC
#define COLLIDER_o111           0xB
#define COLLIDER_o1             0xA
#define COLLIDER_o104           0x9
#define COLLIDER_g2             0x8
#define COLLIDER_g6             0x7
#define COLLIDER_o103           0x6
#define COLLIDER_deilite        0x5
#define COLLIDER_deilie         0x4
#define COLLIDER_g5             0x3
#define COLLIDER_o101           0x2
#define COLLIDER_deilitw        0x1
#define COLLIDER_deiliw         0x0

#define ZONE_Root               0x4
#define ZONE_g1                 0x3
#define ZONE_o2                 0x2
#define ZONE_o4                 0x1
#define ZONE_o5                 0x0

