#define COLLIDER_Root           0x17
#define COLLIDER_g1             0x16
#define COLLIDER_water          0x15
#define COLLIDER_o21            0x14
#define COLLIDER_o19            0x13
#define COLLIDER_g2             0x12
#define COLLIDER_o87            0x11
#define COLLIDER_o86            0x10
#define COLLIDER_o83            0xF
#define COLLIDER_o1             0xE
#define COLLIDER_g4             0xD
#define COLLIDER_o93            0xC
#define COLLIDER_o80            0xB
#define COLLIDER_o91            0xA
#define COLLIDER_o85            0x9
#define COLLIDER_o41            0x8
#define COLLIDER_o79            0x7
#define COLLIDER_o92            0x6
#define COLLIDER_o89            0x5
#define COLLIDER_o6             0x4
#define COLLIDER_g3             0x3
#define COLLIDER_o82            0x2
#define COLLIDER_deilitw        0x1
#define COLLIDER_deiliw         0x0

#define ZONE_Root               0x4
#define ZONE_g1                 0x3
#define ZONE_o3                 0x2
#define ZONE_o2                 0x1
#define ZONE_o1                 0x0

