#define COLLIDER_Root           0x18
#define COLLIDER_g1             0x17
#define COLLIDER_g22            0x16
#define COLLIDER_o69            0x15
#define COLLIDER_o68            0x14
#define COLLIDER_g18            0x13
#define COLLIDER_o74            0x12
#define COLLIDER_o72            0x11
#define COLLIDER_o60            0x10
#define COLLIDER_g2             0xF
#define COLLIDER_o85            0xE
#define COLLIDER_o48            0xD
#define COLLIDER_o65            0xC
#define COLLIDER_o9             0xB
#define COLLIDER_o66            0xA
#define COLLIDER_o1             0x9
#define COLLIDER_g5             0x8
#define COLLIDER_g8             0x7
#define COLLIDER_o47            0x6
#define COLLIDER_deilite        0x5
#define COLLIDER_deilie         0x4
#define COLLIDER_g7             0x3
#define COLLIDER_o45            0x2
#define COLLIDER_deilitw        0x1
#define COLLIDER_deiliw         0x0

#define ZONE_Root               0x4
#define ZONE_g1                 0x3
#define ZONE_o2                 0x2
#define ZONE_o4                 0x1
#define ZONE_o5                 0x0

