#define MODEL_Root              0x13
#define MODEL_r                 0x12
#define MODEL_o269              0x11
#define MODEL_e2                0x10
#define MODEL_o268              0xF
#define MODEL_v                 0xE
#define MODEL_o267              0xD
#define MODEL_o                 0xC
#define MODEL_o266              0xB
#define MODEL_e                 0xA
#define MODEL_o265              0x9
#define MODEL_m                 0x8
#define MODEL_o264              0x7
#define MODEL_a                 0x6
#define MODEL_o262              0x5
#define MODEL_g                 0x4
#define MODEL_o263              0x3
#define MODEL_dai               0x2
#define MODEL_hikari            0x1
#define MODEL_en                0x0

