#define MODEL_Root              0x2B
#define MODEL_mario_g           0x2A
#define MODEL_mario_o           0x29
#define MODEL_Default           0x28
#define MODEL_nagare            0x27
#define MODEL_kumo              0x26
#define MODEL_k13               0x25
#define MODEL_k12               0x24
#define MODEL_k11               0x23
#define MODEL_k10               0x22
#define MODEL_k9                0x21
#define MODEL_k8                0x20
#define MODEL_k7                0x1F
#define MODEL_k6                0x1E
#define MODEL_k5                0x1D
#define MODEL_k4                0x1C
#define MODEL_k3                0x1B
#define MODEL_k2                0x1A
#define MODEL_k1                0x19
#define MODEL_starland          0x18
#define MODEL_stl_2             0x17
#define MODEL_s5                0x16
#define MODEL_s4                0x15
#define MODEL_s3                0x14
#define MODEL_stl_1             0x13
#define MODEL_ls1               0x12
#define MODEL_s2                0x11
#define MODEL_s1                0x10
#define MODEL_castle            0xF
#define MODEL_c8                0xE
#define MODEL_c7                0xD
#define MODEL_c6                0xC
#define MODEL_c5                0xB
#define MODEL_c4                0xA
#define MODEL_c3                0x9
#define MODEL_c2                0x8
#define MODEL_c1                0x7
#define MODEL_g3                0x6
#define MODEL_o3                0x5
#define MODEL_g2                0x4
#define MODEL_o2                0x3
#define MODEL_g1                0x2
#define MODEL_o72               0x1
#define MODEL_o29               0x0

