#define MODEL_Root              0x1F
#define MODEL_dai               0x1E
#define MODEL_waku1             0x1D
#define MODEL_o415              0x1C
#define MODEL_yuka              0x1B
#define MODEL_g49               0x1A
#define MODEL_waku4             0x19
#define MODEL_waku3             0x18
#define MODEL_waku2             0x17
#define MODEL_h3                0x16
#define MODEL_h2                0x15
#define MODEL_h1                0x14
#define MODEL_g102              0x13
#define MODEL_o429              0x12
#define MODEL_o428              0x11
#define MODEL_o427              0x10
#define MODEL_g101              0xF
#define MODEL_o426              0xE
#define MODEL_o425              0xD
#define MODEL_o424              0xC
#define MODEL_m4                0xB
#define MODEL_m3                0xA
#define MODEL_m2                0x9
#define MODEL_m1                0x8
#define MODEL_k4                0x7
#define MODEL_k3                0x6
#define MODEL_k2                0x5
#define MODEL_k1                0x4
#define MODEL_o414              0x3
#define MODEL_waku              0x2
#define MODEL_yuka2             0x1
#define MODEL_o431              0x0

