#define MODEL_Root              0x18
#define MODEL_g1                0x17
#define MODEL_g4                0x16
#define MODEL_g6                0x15
#define MODEL_o19               0x14
#define MODEL_o18               0x13
#define MODEL_o17               0x12
#define MODEL_o16               0x11
#define MODEL_o15               0x10
#define MODEL_g5                0xF
#define MODEL_o12               0xE
#define MODEL_o11               0xD
#define MODEL_o10               0xC
#define MODEL_o8                0xB
#define MODEL_o7                0xA
#define MODEL_g2                0x9
#define MODEL_o23               0x8
#define MODEL_o14               0x7
#define MODEL_o6                0x6
#define MODEL_o3                0x5
#define MODEL_g7                0x4
#define MODEL_g9                0x3
#define MODEL_o22               0x2
#define MODEL_g8                0x1
#define MODEL_o5                0x0

