#define COLLIDER_Root           0x16
#define COLLIDER_g1             0x15
#define COLLIDER_g20            0x14
#define COLLIDER_o68            0x13
#define COLLIDER_o67            0x12
#define COLLIDER_o66            0x11
#define COLLIDER_o65            0x10
#define COLLIDER_o64            0xF
#define COLLIDER_o63            0xE
#define COLLIDER_o62            0xD
#define COLLIDER_o61            0xC
#define COLLIDER_o60            0xB
#define COLLIDER_o59            0xA
#define COLLIDER_o58            0x9
#define COLLIDER_g4             0x8
#define COLLIDER_g17            0x7
#define COLLIDER_o46            0x6
#define COLLIDER_deilite        0x5
#define COLLIDER_deilie         0x4
#define COLLIDER_g16            0x3
#define COLLIDER_o45            0x2
#define COLLIDER_deilitw        0x1
#define COLLIDER_deiliw         0x0

#define ZONE_Root               0xB
#define ZONE_g1                 0xA
#define ZONE_g15                0x9
#define ZONE_o44                0x8
#define ZONE_o45                0x7
#define ZONE_o43                0x6
#define ZONE_g3                 0x5
#define ZONE_o6                 0x4
#define ZONE_g14                0x3
#define ZONE_o40                0x2
#define ZONE_o41                0x1
#define ZONE_o39                0x0

