#define MODEL_Root              0x12
#define MODEL_g1                0x11
#define MODEL_g3                0x10
#define MODEL_g20               0xF
#define MODEL_o49               0xE
#define MODEL_o4                0xD
#define MODEL_o8                0xC
#define MODEL_o6                0xB
#define MODEL_o7                0xA
#define MODEL_g19               0x9
#define MODEL_o52               0x8
#define MODEL_o53               0x7
#define MODEL_g4                0x6
#define MODEL_g17               0x5
#define MODEL_o11               0x4
#define MODEL_o10               0x3
#define MODEL_g16               0x2
#define MODEL_o5                0x1
#define MODEL_o9                0x0

