#define COLLIDER_Root           0x20
#define COLLIDER_g1             0x1F
#define COLLIDER_g35            0x1E
#define COLLIDER_o99            0x1D
#define COLLIDER_o98            0x1C
#define COLLIDER_g31            0x1B
#define COLLIDER_o100           0x1A
#define COLLIDER_g4             0x19
#define COLLIDER_o71            0x18
#define COLLIDER_o70            0x17
#define COLLIDER_o56            0x16
#define COLLIDER_g5             0x15
#define COLLIDER_g30            0x14
#define COLLIDER_o97            0x13
#define COLLIDER_o96            0x12
#define COLLIDER_o12            0x11
#define COLLIDER_o83            0x10
#define COLLIDER_o82            0xF
#define COLLIDER_g2             0xE
#define COLLIDER_o110           0xD
#define COLLIDER_o78            0xC
#define COLLIDER_o48            0xB
#define COLLIDER_o47            0xA
#define COLLIDER_o1             0x9
#define COLLIDER_g20            0x8
#define COLLIDER_g21            0x7
#define COLLIDER_o29            0x6
#define COLLIDER_deilitn        0x5
#define COLLIDER_deilin         0x4
#define COLLIDER_g19            0x3
#define COLLIDER_o27            0x2
#define COLLIDER_deilits        0x1
#define COLLIDER_deilis         0x0

#define ZONE_Root               0x4
#define ZONE_g1                 0x3
#define ZONE_o28                0x2
#define ZONE_o27                0x1
#define ZONE_o26                0x0

