#define MODEL_Root              0x1B
#define MODEL_Default           0x1A
#define MODEL_g77               0x19
#define MODEL_mizu2             0x18
#define MODEL_mizu1             0x17
#define MODEL_bin4              0x16
#define MODEL_bin3              0x15
#define MODEL_bin2              0x14
#define MODEL_bin1              0x13
#define MODEL_hako6             0x12
#define MODEL_hako5             0x11
#define MODEL_hako4             0x10
#define MODEL_hako2             0xF
#define MODEL_hako1             0xE
#define MODEL_hune              0xD
#define MODEL_fune1             0xC
#define MODEL_fune2             0xB
#define MODEL_dai               0xA
#define MODEL_hone              0x9
#define MODEL_o347              0x8
#define MODEL_yuka              0x7
#define MODEL_waku1             0x6
#define MODEL_g49               0x5
#define MODEL_o353              0x4
#define MODEL_hone2             0x3
#define MODEL_waku2             0x2
#define MODEL_waku              0x1
#define MODEL_kabe              0x0

