#define MODEL_Root              0x19
#define MODEL_g5                0x18
#define MODEL_bin4              0x17
#define MODEL_bin3              0x16
#define MODEL_bin2              0x15
#define MODEL_bin1              0x14
#define MODEL_hako6             0x13
#define MODEL_hako5             0x12
#define MODEL_hako4             0x11
#define MODEL_hako3             0x10
#define MODEL_hako2             0xF
#define MODEL_hako1             0xE
#define MODEL_fune              0xD
#define MODEL_fune_u            0xC
#define MODEL_fune_s            0xB
#define MODEL_mizu              0xA
#define MODEL_o30               0x9
#define MODEL_misu1             0x8
#define MODEL_o28               0x7
#define MODEL_g1                0x6
#define MODEL_o31               0x5
#define MODEL_exit              0x4
#define MODEL_sita              0x3
#define MODEL_o21               0x2
#define MODEL_ue                0x1
#define MODEL_hone              0x0

