#define MODEL_Root              0x1C
#define MODEL_dai               0x1B
#define MODEL_g91               0x1A
#define MODEL_hasira            0x19
#define MODEL_hana              0x18
#define MODEL_ha1               0x17
#define MODEL_ha2               0x16
#define MODEL_saku              0x15
#define MODEL_waki1_2           0x14
#define MODEL_hi                0x13
#define MODEL_hkr3              0x12
#define MODEL_o414              0x11
#define MODEL_o406              0x10
#define MODEL_hkr1              0xF
#define MODEL_yuka1             0xE
#define MODEL_yuka2             0xD
#define MODEL_g49               0xC
#define MODEL_waku2             0xB
#define MODEL_syokudai          0xA
#define MODEL_maku              0x9
#define MODEL_daiza2            0x8
#define MODEL_daiz1             0x7
#define MODEL_hasira2           0x6
#define MODEL_hasira1           0x5
#define MODEL_waku_2            0x4
#define MODEL_garasu            0x3
#define MODEL_sann              0x2
#define MODEL_waku              0x1
#define MODEL_kabe1             0x0

