#define COLLIDER_Root           0x22
#define COLLIDER_g1             0x21
#define COLLIDER_g25            0x20
#define COLLIDER_o99            0x1F
#define COLLIDER_o98            0x1E
#define COLLIDER_o97            0x1D
#define COLLIDER_o96            0x1C
#define COLLIDER_o95            0x1B
#define COLLIDER_g22            0x1A
#define COLLIDER_o68            0x19
#define COLLIDER_o66            0x18
#define COLLIDER_o5             0x17
#define COLLIDER_hasira         0x16
#define COLLIDER_o70            0x15
#define COLLIDER_o40            0x14
#define COLLIDER_kabin          0x13
#define COLLIDER_o90            0x12
#define COLLIDER_o77            0x11
#define COLLIDER_isu            0x10
#define COLLIDER_o21            0xF
#define COLLIDER_o19            0xE
#define COLLIDER_desk           0xD
#define COLLIDER_o94            0xC
#define COLLIDER_o75            0xB
#define COLLIDER_o76            0xA
#define COLLIDER_o12            0x9
#define COLLIDER_o100           0x8
#define COLLIDER_g2             0x7
#define COLLIDER_o25            0x6
#define COLLIDER_o1             0x5
#define COLLIDER_g4             0x4
#define COLLIDER_o93            0x3
#define COLLIDER_tte            0x2
#define COLLIDER_deilite        0x1
#define COLLIDER_deilie         0x0

#define ZONE_Root               0x3
#define ZONE_g1                 0x2
#define ZONE_o90                0x1
#define ZONE_o25                0x0

