#define COLLIDER_Root           0x1B
#define COLLIDER_g1             0x1A
#define COLLIDER_g14            0x19
#define COLLIDER_o56            0x18
#define COLLIDER_o55            0x17
#define COLLIDER_g13            0x16
#define COLLIDER_o54            0x15
#define COLLIDER_o53            0x14
#define COLLIDER_g10            0x13
#define COLLIDER_o57            0x12
#define COLLIDER_g15            0x11
#define COLLIDER_o62            0x10
#define COLLIDER_o61            0xF
#define COLLIDER_o59            0xE
#define COLLIDER_o58            0xD
#define COLLIDER_g7             0xC
#define COLLIDER_o40            0xB
#define COLLIDER_o37            0xA
#define COLLIDER_o19            0x9
#define COLLIDER_g4             0x8
#define COLLIDER_o64            0x7
#define COLLIDER_o63            0x6
#define COLLIDER_o5             0x5
#define COLLIDER_g6             0x4
#define COLLIDER_o52            0x3
#define COLLIDER_ttw            0x2
#define COLLIDER_deilitw        0x1
#define COLLIDER_deiliw         0x0

#define ZONE_Root               0x2
#define ZONE_g1                 0x1
#define ZONE_o6                 0x0

