#define COLLIDER_Root           0x1C
#define COLLIDER_g1             0x1B
#define COLLIDER_g9             0x1A
#define COLLIDER_o34            0x19
#define COLLIDER_o33            0x18
#define COLLIDER_o80            0x17
#define COLLIDER_o79            0x16
#define COLLIDER_g7             0x15
#define COLLIDER_o81            0x14
#define COLLIDER_o15            0x13
#define COLLIDER_g10            0x12
#define COLLIDER_o41            0x11
#define COLLIDER_o40            0x10
#define COLLIDER_o39            0xF
#define COLLIDER_o38            0xE
#define COLLIDER_o37            0xD
#define COLLIDER_g13            0xC
#define COLLIDER_o77            0xB
#define COLLIDER_g15            0xA
#define COLLIDER_o76            0x9
#define COLLIDER_o75            0x8
#define COLLIDER_g4             0x7
#define COLLIDER_o78            0x6
#define COLLIDER_o6             0x5
#define COLLIDER_g6             0x4
#define COLLIDER_o74            0x3
#define COLLIDER_ttw            0x2
#define COLLIDER_deilitw        0x1
#define COLLIDER_deiliw         0x0

#define ZONE_Root               0x2
#define ZONE_g1                 0x1
#define ZONE_o6                 0x0

