#define COLLIDER_Root           0x1F
#define COLLIDER_g1             0x1E
#define COLLIDER_tubo           0x1D
#define COLLIDER_o83            0x1C
#define COLLIDER_o92            0x1B
#define COLLIDER_o44            0x1A
#define COLLIDER_g15            0x19
#define COLLIDER_o43            0x18
#define COLLIDER_isu            0x17
#define COLLIDER_o93            0x16
#define COLLIDER_o40            0x15
#define COLLIDER_g13            0x14
#define COLLIDER_o51            0x13
#define COLLIDER_o91            0x12
#define COLLIDER_tana           0x11
#define COLLIDER_o30            0x10
#define COLLIDER_g9             0xF
#define COLLIDER_o97            0xE
#define COLLIDER_o28            0xD
#define COLLIDER_hako           0xC
#define COLLIDER_o90            0xB
#define COLLIDER_o89            0xA
#define COLLIDER_g2             0x9
#define COLLIDER_o99            0x8
#define COLLIDER_o98            0x7
#define COLLIDER_o88            0x6
#define COLLIDER_o8             0x5
#define COLLIDER_g4             0x4
#define COLLIDER_o86            0x3
#define COLLIDER_ttw            0x2
#define COLLIDER_deilitw        0x1
#define COLLIDER_deiliw         0x0

#define ZONE_Root               0x2
#define ZONE_g1                 0x1
#define ZONE_o6                 0x0

