#define MODEL_Root              0x26
#define MODEL_m_n               0x25
#define MODEL_m4                0x24
#define MODEL_m3                0x23
#define MODEL_m2                0x22
#define MODEL_m1                0x21
#define MODEL_n2                0x20
#define MODEL_n1                0x1F
#define MODEL_dai               0x1E
#define MODEL_o287              0x1D
#define MODEL_waku1             0x1C
#define MODEL_yuka              0x1B
#define MODEL_g49               0x1A
#define MODEL_waku2             0x19
#define MODEL_k2_2              0x18
#define MODEL_k2                0x17
#define MODEL_k1_2              0x16
#define MODEL_k1                0x15
#define MODEL_k3_2              0x14
#define MODEL_k3                0x13
#define MODEL_ha2               0x12
#define MODEL_ha1_2             0x11
#define MODEL_ha1               0x10
#define MODEL_saku2             0xF
#define MODEL_miki              0xE
#define MODEL_iwa2              0xD
#define MODEL_iwa               0xC
#define MODEL_k4                0xB
#define MODEL_saku              0xA
#define MODEL_k5_2              0x9
#define MODEL_k5                0x8
#define MODEL_waku              0x7
#define MODEL_yuka2             0x6
#define MODEL_g59               0x5
#define MODEL_g61               0x4
#define MODEL_o265              0x3
#define MODEL_g58               0x2
#define MODEL_g60               0x1
#define MODEL_o263              0x0

