#define COLLIDER_Root           0x2C
#define COLLIDER_g174           0x2B
#define COLLIDER_o486           0x2A
#define COLLIDER_o485           0x29
#define COLLIDER_o484           0x28
#define COLLIDER_o483           0x27
#define COLLIDER_east           0x26
#define COLLIDER_deilitne       0x25
#define COLLIDER_deiline        0x24
#define COLLIDER_ok422          0x23
#define COLLIDER_ok478          0x22
#define COLLIDER_o482           0x21
#define COLLIDER_point          0x20
#define COLLIDER_road2          0x1F
#define COLLIDER_o195           0x1E
#define COLLIDER_o477           0x1D
#define COLLIDER_o476           0x1C
#define COLLIDER_o465           0x1B
#define COLLIDER_west           0x1A
#define COLLIDER_kusa4          0x19
#define COLLIDER_deilitw        0x18
#define COLLIDER_deiliw         0x17
#define COLLIDER_ok479          0x16
#define COLLIDER_o475           0x15
#define COLLIDER_o419           0x14
#define COLLIDER_o405           0x13
#define COLLIDER_o406           0x12
#define COLLIDER_o389           0x11
#define COLLIDER_stage          0x10
#define COLLIDER_o427           0xF
#define COLLIDER_o429           0xE
#define COLLIDER_kusa2          0xD
#define COLLIDER_kusa1          0xC
#define COLLIDER_tree2          0xB
#define COLLIDER_tree1          0xA
#define COLLIDER_bridge         0x9
#define COLLIDER_b1             0x8
#define COLLIDER_kuriking_toride 0x7
#define COLLIDER_o509           0x6
#define COLLIDER_tt             0x5
#define COLLIDER_en2            0x4
#define COLLIDER_en1            0x3
#define COLLIDER_shita          0x2
#define COLLIDER_o488           0x1
#define COLLIDER_o403           0x0

#define ZONE_Root               0x12
#define ZONE_Default            0x11
#define ZONE_o482               0x10
#define ZONE_o479               0xF
#define ZONE_higashi            0xE
#define ZONE_point              0xD
#define ZONE_o438               0xC
#define ZONE_road2              0xB
#define ZONE_nishi              0xA
#define ZONE_west_side          0x9
#define ZONE_event_cam          0x8
#define ZONE_c2_2               0x7
#define ZONE_c2_1               0x6
#define ZONE_c1_2               0x5
#define ZONE_c1_1               0x4
#define ZONE_obj                0x3
#define ZONE_deiline            0x2
#define ZONE_field              0x1
#define ZONE_bridge             0x0

