#define MODEL_Root              0x29
#define MODEL_g79               0x28
#define MODEL_o418              0x27
#define MODEL_g77               0x26
#define MODEL_o416              0x25
#define MODEL_switch            0x24
#define MODEL_1_2               0x23
#define MODEL_1                 0x22
#define MODEL_1_3               0x21
#define MODEL_2_2               0x20
#define MODEL_2                 0x1F
#define MODEL_2_3               0x1E
#define MODEL_3_2               0x1D
#define MODEL_3                 0x1C
#define MODEL_3_3               0x1B
#define MODEL_ami               0x1A
#define MODEL_hasira            0x19
#define MODEL_o383              0x18
#define MODEL_o382              0x17
#define MODEL_o381              0x16
#define MODEL_dai               0x15
#define MODEL_waki1             0x14
#define MODEL_yuka1_2           0x13
#define MODEL_yuka1             0x12
#define MODEL_g72               0x11
#define MODEL_waku2             0x10
#define MODEL_yuka2_2           0xF
#define MODEL_yuka2             0xE
#define MODEL_tai2              0xD
#define MODEL_tai1              0xC
#define MODEL_waku              0xB
#define MODEL_mad5              0xA
#define MODEL_mad4              0x9
#define MODEL_mad3              0x8
#define MODEL_mad1              0x7
#define MODEL_mad1_2            0x6
#define MODEL_mad2              0x5
#define MODEL_mad2_2            0x4
#define MODEL_kab4              0x3
#define MODEL_kab3              0x2
#define MODEL_kab2              0x1
#define MODEL_kab1              0x0

