#define COLLIDER_Root           0x39
#define COLLIDER_g120           0x38
#define COLLIDER_mae            0x37
#define COLLIDER_migi           0x36
#define COLLIDER_oku            0x35
#define COLLIDER_hidari         0x34
#define COLLIDER_g119           0x33
#define COLLIDER_o411           0x32
#define COLLIDER_s_suimen       0x31
#define COLLIDER_o358           0x30
#define COLLIDER_g98            0x2F
#define COLLIDER_anaw           0x2E
#define COLLIDER_naw            0x2D
#define COLLIDER_ttaw           0x2C
#define COLLIDER_deiliaw        0x2B
#define COLLIDER_deilitaw       0x2A
#define COLLIDER_noriba         0x29
#define COLLIDER_ttno           0x28
#define COLLIDER_nno            0x27
#define COLLIDER_deilino        0x26
#define COLLIDER_exite          0x25
#define COLLIDER_ne             0x24
#define COLLIDER_tte            0x23
#define COLLIDER_deilie         0x22
#define COLLIDER_deilite        0x21
#define COLLIDER_exitw          0x20
#define COLLIDER_ttw            0x1F
#define COLLIDER_nw             0x1E
#define COLLIDER_deiliw2        0x1D
#define COLLIDER_deiliw         0x1C
#define COLLIDER_deilitw        0x1B
#define COLLIDER_g117           0x1A
#define COLLIDER_sikake         0x19
#define COLLIDER_g114           0x18
#define COLLIDER_o384           0x17
#define COLLIDER_g112           0x16
#define COLLIDER_o383           0x15
#define COLLIDER_g107           0x14
#define COLLIDER_o378           0x13
#define COLLIDER_g101           0x12
#define COLLIDER_o372           0x11
#define COLLIDER_kakusi         0x10
#define COLLIDER_o369           0xF
#define COLLIDER_o368           0xE
#define COLLIDER_k_yuka         0xD
#define COLLIDER_k_kabe1        0xC
#define COLLIDER_u_hasira       0xB
#define COLLIDER_o403           0xA
#define COLLIDER_o402           0x9
#define COLLIDER_o400           0x8
#define COLLIDER_o401           0x7
#define COLLIDER_o309           0x6
#define COLLIDER_o304           0x5
#define COLLIDER_o298           0x4
#define COLLIDER_u_yuka         0x3
#define COLLIDER_s_saku         0x2
#define COLLIDER_o397           0x1
#define COLLIDER_ue             0x0

#define ZONE_Root               0x4
#define ZONE_g32                0x3
#define ZONE_3                  0x2
#define ZONE_2                  0x1
#define ZONE_1                  0x0

