#define MODEL_Root              0x29
#define MODEL_g15               0x28
#define MODEL_o47               0x27
#define MODEL_o46               0x26
#define MODEL_o44               0x25
#define MODEL_o43               0x24
#define MODEL_o42               0x23
#define MODEL_etc               0x22
#define MODEL_mado              0x21
#define MODEL_doa4              0x20
#define MODEL_o38               0x1F
#define MODEL_doa3              0x1E
#define MODEL_o37               0x1D
#define MODEL_doa2              0x1C
#define MODEL_o34               0x1B
#define MODEL_doa1              0x1A
#define MODEL_o33               0x19
#define MODEL_kumo              0x18
#define MODEL_kumo4             0x17
#define MODEL_kumo3             0x16
#define MODEL_kumo2             0x15
#define MODEL_kumo1             0x14
#define MODEL_dai               0x13
#define MODEL_doa2_3            0x12
#define MODEL_doa2_2            0x11
#define MODEL_dai2              0x10
#define MODEL_dai1_2            0xF
#define MODEL_dai1              0xE
#define MODEL_g1                0xD
#define MODEL_soko              0xC
#define MODEL_hasi1             0xB
#define MODEL_hasi2             0xA
#define MODEL_yuka              0x9
#define MODEL_kabe2             0x8
#define MODEL_kabe1             0x7
#define MODEL_kaidan            0x6
#define MODEL_dan2              0x5
#define MODEL_dan1              0x4
#define MODEL_sokumen           0x3
#define MODEL_tou               0x2
#define MODEL_t_kabe2           0x1
#define MODEL_t_kabe1           0x0

