#define MODEL_Root              0x15
#define MODEL_yougan            0x14
#define MODEL_4                 0x13
#define MODEL_3                 0x12
#define MODEL_1                 0x11
#define MODEL_2                 0x10
#define MODEL_dai               0xF
#define MODEL_soku              0xE
#define MODEL_saku              0xD
#define MODEL_waki1             0xC
#define MODEL_yuka1             0xB
#define MODEL_g1                0xA
#define MODEL_waku2             0x9
#define MODEL_yuka2             0x8
#define MODEL_ami               0x7
#define MODEL_kab2              0x6
#define MODEL_kab1              0x5
#define MODEL_kab2_2            0x4
#define MODEL_kab1_2            0x3
#define MODEL_kabe_k            0x2
#define MODEL_kab_o             0x1
#define MODEL_waku              0x0

