#define MODEL_Root              0x18
#define MODEL_dai               0x17
#define MODEL_o478              0x16
#define MODEL_waku1             0x15
#define MODEL_yuka2             0x14
#define MODEL_g49               0x13
#define MODEL_waku2             0x12
#define MODEL_h3                0x11
#define MODEL_h2                0x10
#define MODEL_waku              0xF
#define MODEL_h1                0xE
#define MODEL_h4                0xD
#define MODEL_futi2             0xC
#define MODEL_kabe4             0xB
#define MODEL_yuka3             0xA
#define MODEL_kabe2             0x9
#define MODEL_futi1             0x8
#define MODEL_kabe1             0x7
#define MODEL_kup1              0x6
#define MODEL_kup2              0x5
#define MODEL_k2_2              0x4
#define MODEL_k2                0x3
#define MODEL_k1_2              0x2
#define MODEL_k1                0x1
#define MODEL_yuka1             0x0

