#define COLLIDER_Root           0x2D
#define COLLIDER_hasi           0x2C
#define COLLIDER_o974           0x2B
#define COLLIDER_o973           0x2A
#define COLLIDER_o972           0x29
#define COLLIDER_o971           0x28
#define COLLIDER_o970           0x27
#define COLLIDER_o969           0x26
#define COLLIDER_exit4          0x25
#define COLLIDER_n4             0x24
#define COLLIDER_tt4            0x23
#define COLLIDER_deili4         0x22
#define COLLIDER_deilit4        0x21
#define COLLIDER_exit3          0x20
#define COLLIDER_n3             0x1F
#define COLLIDER_tt3            0x1E
#define COLLIDER_deili3         0x1D
#define COLLIDER_deilit3        0x1C
#define COLLIDER_exit2          0x1B
#define COLLIDER_ne             0x1A
#define COLLIDER_tte            0x19
#define COLLIDER_deilie         0x18
#define COLLIDER_deilite        0x17
#define COLLIDER_exit           0x16
#define COLLIDER_nw             0x15
#define COLLIDER_deiliw         0x14
#define COLLIDER_deilitw        0x13
#define COLLIDER_F2             0x12
#define COLLIDER_F2_5           0x11
#define COLLIDER_f2_5_yuka      0x10
#define COLLIDER_f2_5_sai       0xF
#define COLLIDER_f2_4           0xE
#define COLLIDER_f2_4_yuka      0xD
#define COLLIDER_f2_4_mado      0xC
#define COLLIDER_F2_3           0xB
#define COLLIDER_f2_3_yuka      0xA
#define COLLIDER_f2_3_sai       0x9
#define COLLIDER_f2_2           0x8
#define COLLIDER_f2_2_yuka      0x7
#define COLLIDER_f2_2_sai       0x6
#define COLLIDER_F2_1           0x5
#define COLLIDER_f2_1_yuka      0x4
#define COLLIDER_f2_1_sai       0x3
#define COLLIDER_naka           0x2
#define COLLIDER_kabe           0x1
#define COLLIDER_kaidan         0x0

#define ZONE_Root               0x3
#define ZONE_naka               0x2
#define ZONE_f1_yuka            0x1
#define ZONE_o970               0x0

