#define MODEL_Root              0x11
#define MODEL_g84               0x10
#define MODEL_waku2             0xF
#define MODEL_waku              0xE
#define MODEL_tai2              0xD
#define MODEL_tai1              0xC
#define MODEL_dai               0xB
#define MODEL_waku1             0xA
#define MODEL_yuka2             0x9
#define MODEL_g49               0x8
#define MODEL_yuka1             0x7
#define MODEL_kup2              0x6
#define MODEL_kup1              0x5
#define MODEL_kab3              0x4
#define MODEL_kab2              0x3
#define MODEL_kab1              0x2
#define MODEL_sai               0x1
#define MODEL_oku               0x0

