#define MODEL_Root              0x1B
#define MODEL_dai               0x1A
#define MODEL_tar1              0x19
#define MODEL_waku1             0x18
#define MODEL_yuka2             0x17
#define MODEL_yuka1             0x16
#define MODEL_fut1              0x15
#define MODEL_g49               0x14
#define MODEL_waku2             0x13
#define MODEL_o5                0x12
#define MODEL_O5_2              0x11
#define MODEL_o4                0x10
#define MODEL_o4_2              0xF
#define MODEL_o3                0xE
#define MODEL_o3_2              0xD
#define MODEL_o2                0xC
#define MODEL_o2_2              0xB
#define MODEL_o1                0xA
#define MODEL_o1_2              0x9
#define MODEL_fut2              0x8
#define MODEL_fut2_2            0x7
#define MODEL_kab               0x6
#define MODEL_kab_k             0x5
#define MODEL_yuka3             0x4
#define MODEL_fut3              0x3
#define MODEL_fut3_2            0x2
#define MODEL_waku              0x1
#define MODEL_tar2              0x0

