#define MODEL_Root              0x1D
#define MODEL_dai               0x1C
#define MODEL_hasira            0x1B
#define MODEL_ue3               0x1A
#define MODEL_sita1             0x19
#define MODEL_iwa3              0x18
#define MODEL_g79               0x17
#define MODEL_yuka2             0x16
#define MODEL_waku1             0x15
#define MODEL_yuka              0x14
#define MODEL_yuka3             0x13
#define MODEL_03                0x12
#define MODEL_o363              0x11
#define MODEL_05                0x10
#define MODEL_ue1               0xF
#define MODEL_ue2               0xE
#define MODEL_iwa2              0xD
#define MODEL_iwa1              0xC
#define MODEL_kabe1             0xB
#define MODEL_kabe2             0xA
#define MODEL_g49               0x9
#define MODEL_yuka4             0x8
#define MODEL_waku              0x7
#define MODEL_waku2             0x6
#define MODEL_o364              0x5
#define MODEL_o365              0x4
#define MODEL_o366              0x3
#define MODEL_o367              0x2
#define MODEL_o368              0x1
#define MODEL_o369              0x0

