#define MODEL_Root              0x22
#define MODEL_dai               0x21
#define MODEL_ue3               0x20
#define MODEL_sita1             0x1F
#define MODEL_iwa3              0x1E
#define MODEL_sima              0x1D
#define MODEL_o368              0x1C
#define MODEL_o367              0x1B
#define MODEL_o366              0x1A
#define MODEL_yougan            0x19
#define MODEL_move              0x18
#define MODEL_o371              0x17
#define MODEL_o370              0x16
#define MODEL_o369              0x15
#define MODEL_awa2              0x14
#define MODEL_awa1              0x13
#define MODEL_g79               0x12
#define MODEL_waku1             0x11
#define MODEL_g97               0x10
#define MODEL_ue1               0xF
#define MODEL_ue2               0xE
#define MODEL_y3_2              0xD
#define MODEL_y3_1              0xC
#define MODEL_iwa4              0xB
#define MODEL_y2_2              0xA
#define MODEL_y2_1              0x9
#define MODEL_iwa2              0x8
#define MODEL_y1_2              0x7
#define MODEL_y1_1              0x6
#define MODEL_g49               0x5
#define MODEL_kabe2             0x4
#define MODEL_kabe1             0x3
#define MODEL_kabe3             0x2
#define MODEL_waku              0x1
#define MODEL_waku2             0x0

