#define COLLIDER_Root           0x1A
#define COLLIDER_nw             0x19
#define COLLIDER_deilitnw       0x18
#define COLLIDER_deilinw        0x17
#define COLLIDER_w              0x16
#define COLLIDER_deilitw        0x15
#define COLLIDER_deiliw         0x14
#define COLLIDER_sw             0x13
#define COLLIDER_deilitsw       0x12
#define COLLIDER_deilisw        0x11
#define COLLIDER_s              0x10
#define COLLIDER_deilits        0xF
#define COLLIDER_deilis         0xE
#define COLLIDER_se             0xD
#define COLLIDER_deilitse       0xC
#define COLLIDER_deilise        0xB
#define COLLIDER_e              0xA
#define COLLIDER_deilite        0x9
#define COLLIDER_deilie         0x8
#define COLLIDER_ne             0x7
#define COLLIDER_deilitne       0x6
#define COLLIDER_deiline        0x5
#define COLLIDER_0              0x4
#define COLLIDER_deilitn        0x3
#define COLLIDER_deilin         0x2
#define COLLIDER_g1             0x1
#define COLLIDER_stage          0x0

#define ZONE_Root               0x4
#define ZONE_Default            0x3
#define ZONE_o174               0x2
#define ZONE_g1                 0x1
#define ZONE_stage              0x0

