#define COLLIDER_Root           0x29
#define COLLIDER_g141           0x28
#define COLLIDER_monw           0x27
#define COLLIDER_g140           0x26
#define COLLIDER_mons           0x25
#define COLLIDER_g139           0x24
#define COLLIDER_mone           0x23
#define COLLIDER_g138           0x22
#define COLLIDER_monn           0x21
#define COLLIDER_g119           0x20
#define COLLIDER_o420           0x1F
#define COLLIDER_o419           0x1E
#define COLLIDER_atari          0x1D
#define COLLIDER_atari_w        0x1C
#define COLLIDER_o418           0x1B
#define COLLIDER_atari_s        0x1A
#define COLLIDER_o417           0x19
#define COLLIDER_atari_e        0x18
#define COLLIDER_o331           0x17
#define COLLIDER_atari_n        0x16
#define COLLIDER_o416           0x15
#define COLLIDER_exit           0x14
#define COLLIDER_exit_w         0x13
#define COLLIDER_ttw            0x12
#define COLLIDER_nw             0x11
#define COLLIDER_deiliw         0x10
#define COLLIDER_deilitw        0xF
#define COLLIDER_exit_s         0xE
#define COLLIDER_tts            0xD
#define COLLIDER_ns             0xC
#define COLLIDER_deilis         0xB
#define COLLIDER_deilits        0xA
#define COLLIDER_exit_e         0x9
#define COLLIDER_tte            0x8
#define COLLIDER_ne             0x7
#define COLLIDER_deilie         0x6
#define COLLIDER_deilite        0x5
#define COLLIDER_exit_n         0x4
#define COLLIDER_ttn            0x3
#define COLLIDER_nn             0x2
#define COLLIDER_deilin         0x1
#define COLLIDER_deilitn        0x0

#define ZONE_Root               0xC
#define ZONE_enter              0xB
#define ZONE_north              0xA
#define ZONE_south              0x9
#define ZONE_west               0x8
#define ZONE_east               0x7
#define ZONE_out                0x6
#define ZONE_kita               0x5
#define ZONE_minami             0x4
#define ZONE_nishi              0x3
#define ZONE_higashi            0x2
#define ZONE_kaiten             0x1
#define ZONE_stage              0x0

