#define COLLIDER_Root           0x27
#define COLLIDER_g145           0x26
#define COLLIDER_monw           0x25
#define COLLIDER_g144           0x24
#define COLLIDER_mons           0x23
#define COLLIDER_g143           0x22
#define COLLIDER_mone           0x21
#define COLLIDER_g142           0x20
#define COLLIDER_monn           0x1F
#define COLLIDER_Default        0x1E
#define COLLIDER_o480           0x1D
#define COLLIDER_o472           0x1C
#define COLLIDER_o471           0x1B
#define COLLIDER_atari          0x1A
#define COLLIDER_o473           0x19
#define COLLIDER_o469           0x18
#define COLLIDER_exit           0x17
#define COLLIDER_exit_w         0x16
#define COLLIDER_ttw            0x15
#define COLLIDER_nw             0x14
#define COLLIDER_deiliw         0x13
#define COLLIDER_deilitw        0x12
#define COLLIDER_exit_s         0x11
#define COLLIDER_tts            0x10
#define COLLIDER_ns             0xF
#define COLLIDER_deilis         0xE
#define COLLIDER_deilits        0xD
#define COLLIDER_exit_e         0xC
#define COLLIDER_tte            0xB
#define COLLIDER_ne             0xA
#define COLLIDER_deilie         0x9
#define COLLIDER_deilite        0x8
#define COLLIDER_exit_n         0x7
#define COLLIDER_ttn            0x6
#define COLLIDER_nn             0x5
#define COLLIDER_deilin         0x4
#define COLLIDER_deilitn        0x3
#define COLLIDER_g1             0x2
#define COLLIDER_o493           0x1
#define COLLIDER_o474           0x0

#define ZONE_Root               0xD
#define ZONE_enter              0xC
#define ZONE_north              0xB
#define ZONE_south              0xA
#define ZONE_west               0x9
#define ZONE_east               0x8
#define ZONE_out                0x7
#define ZONE_o204               0x6
#define ZONE_kita               0x5
#define ZONE_minami             0x4
#define ZONE_nishi              0x3
#define ZONE_higashi            0x2
#define ZONE_kaiten             0x1
#define ZONE_stage              0x0

