#define COLLIDER_Root           0x24
#define COLLIDER_g74            0x23
#define COLLIDER_o210           0x22
#define COLLIDER_o209           0x21
#define COLLIDER_o208           0x20
#define COLLIDER_o207           0x1F
#define COLLIDER_hei            0x1E
#define COLLIDER_o215           0x1D
#define COLLIDER_o206           0x1C
#define COLLIDER_o205           0x1B
#define COLLIDER_h_dai          0x1A
#define COLLIDER_ie             0x19
#define COLLIDER_kabe2          0x18
#define COLLIDER_stage          0x17
#define COLLIDER_iwa            0x16
#define COLLIDER_o153           0x15
#define COLLIDER_kusa           0x14
#define COLLIDER_o148           0x13
#define COLLIDER_o214           0x12
#define COLLIDER_o213           0x11
#define COLLIDER_o212           0x10
#define COLLIDER_road           0xF
#define COLLIDER_exit           0xE
#define COLLIDER_mon            0xD
#define COLLIDER_doa            0xC
#define COLLIDER_nd             0xB
#define COLLIDER_ttd            0xA
#define COLLIDER_deilid         0x9
#define COLLIDER_odeilitd       0x8
#define COLLIDER_exitw          0x7
#define COLLIDER_nw             0x6
#define COLLIDER_deiliw         0x5
#define COLLIDER_deilitw        0x4
#define COLLIDER_exite          0x3
#define COLLIDER_ne             0x2
#define COLLIDER_deilie         0x1
#define COLLIDER_deilite        0x0

#define ZONE_Root               0x6
#define ZONE_Default            0x5
#define ZONE_out2               0x4
#define ZONE_out                0x3
#define ZONE_girden             0x2
#define ZONE_deilie             0x1
#define ZONE_deiliw             0x0

