#define MODEL_Root              0x21
#define MODEL_dai               0x20
#define MODEL_waku1             0x1F
#define MODEL_ha3               0x1E
#define MODEL_hap               0x1D
#define MODEL_kusa3             0x1C
#define MODEL_o306              0x1B
#define MODEL_yuka              0x1A
#define MODEL_hana              0x19
#define MODEL_h8                0x18
#define MODEL_h7                0x17
#define MODEL_h5                0x16
#define MODEL_h3                0x15
#define MODEL_h2                0x14
#define MODEL_h1                0x13
#define MODEL_g49               0x12
#define MODEL_waku2             0x11
#define MODEL_o356              0x10
#define MODEL_saku              0xF
#define MODEL_kusa2             0xE
#define MODEL_nyo               0xD
#define MODEL_o298              0xC
#define MODEL_o299              0xB
#define MODEL_ha1               0xA
#define MODEL_ha1_2             0x9
#define MODEL_miki              0x8
#define MODEL_ha2               0x7
#define MODEL_ha2_2             0x6
#define MODEL_kusa1             0x5
#define MODEL_kusa5             0x4
#define MODEL_waku              0x3
#define MODEL_yuka2             0x2
#define MODEL_futi              0x1
#define MODEL_gake              0x0

