#define MODEL_Root              0x1A
#define MODEL_dai               0x19
#define MODEL_waku1             0x18
#define MODEL_g73               0x17
#define MODEL_o360              0x16
#define MODEL_o359              0x15
#define MODEL_o357              0x14
#define MODEL_futi3             0x13
#define MODEL_yuka1             0x12
#define MODEL_yuka              0x11
#define MODEL_futi2             0x10
#define MODEL_hap               0xF
#define MODEL_ha3               0xE
#define MODEL_g49               0xD
#define MODEL_waku2             0xC
#define MODEL_g76               0xB
#define MODEL_o364              0xA
#define MODEL_o362              0x9
#define MODEL_futi              0x8
#define MODEL_gake              0x7
#define MODEL_kusa2             0x6
#define MODEL_kusa1             0x5
#define MODEL_ha1               0x4
#define MODEL_miki              0x3
#define MODEL_ha2               0x2
#define MODEL_waku              0x1
#define MODEL_yuka2             0x0

