#define MODEL_Root              0x60
#define MODEL_on                0x5F
#define MODEL_moku              0x5E
#define MODEL_m3                0x5D
#define MODEL_m2                0x5C
#define MODEL_g272              0x5B
#define MODEL_kabe_k            0x5A
#define MODEL_o351              0x59
#define MODEL_kaidan            0x58
#define MODEL_o564              0x57
#define MODEL_o640              0x56
#define MODEL_o261              0x55
#define MODEL_o309              0x54
#define MODEL_o260              0x53
#define MODEL_bo3k              0x52
#define MODEL_bo2k              0x51
#define MODEL_bo1k              0x50
#define MODEL_door              0x4F
#define MODEL_hikido            0x4E
#define MODEL_door2             0x4D
#define MODEL_door_1            0x4C
#define MODEL_door1b            0x4B
#define MODEL_hh                0x4A
#define MODEL_hi18              0x49
#define MODEL_hi17              0x48
#define MODEL_hi16              0x47
#define MODEL_hi15              0x46
#define MODEL_hi14              0x45
#define MODEL_hi13              0x44
#define MODEL_hi12              0x43
#define MODEL_hi11              0x42
#define MODEL_hi10              0x41
#define MODEL_hi9               0x40
#define MODEL_hi7               0x3F
#define MODEL_tokei             0x3E
#define MODEL_to                0x3D
#define MODEL_g                 0x3C
#define MODEL_h                 0x3B
#define MODEL_t                 0x3A
#define MODEL_tto               0x39
#define MODEL_furifuri          0x38
#define MODEL_fu                0x37
#define MODEL_miji              0x36
#define MODEL_mi                0x35
#define MODEL_naga              0x34
#define MODEL_na                0x33
#define MODEL_shiyan            0x32
#define MODEL_denki             0x31
#define MODEL_o376              0x30
#define MODEL_a                 0x2F
#define MODEL_r6                0x2E
#define MODEL_r5                0x2D
#define MODEL_r4                0x2C
#define MODEL_r3                0x2B
#define MODEL_r2                0x2A
#define MODEL_r1                0x29
#define MODEL_kusari            0x28
#define MODEL_o405              0x27
#define MODEL_o406              0x26
#define MODEL_bom               0x25
#define MODEL_bom_2             0x24
#define MODEL_bomu_ato          0x23
#define MODEL_bom_1             0x22
#define MODEL_bom_mae           0x21
#define MODEL_off_2             0x20
#define MODEL_kumo_2            0x1F
#define MODEL_hikari_2          0x1E
#define MODEL_rou_2             0x1D
#define MODEL_ten_3             0x1C
#define MODEL_ten_1             0x1B
#define MODEL_ten_2             0x1A
#define MODEL_mado              0x19
#define MODEL_mado_kabe         0x18
#define MODEL_ha3               0x17
#define MODEL_ha2               0x16
#define MODEL_ha1               0x15
#define MODEL_yuka_1f           0x14
#define MODEL_kabe_1f_ue        0x13
#define MODEL_kabe_1f           0x12
#define MODEL_kabe_1f_ki        0x11
#define MODEL_tana1             0x10
#define MODEL_tubo              0xF
#define MODEL_tate_2            0xE
#define MODEL_ushiro            0xD
#define MODEL_off_1             0xC
#define MODEL_kumo_1            0xB
#define MODEL_hikari_1          0xA
#define MODEL_rou_1             0x9
#define MODEL_tukue             0x8
#define MODEL_obk_06_bero       0x7
#define MODEL_yuka_b1           0x6
#define MODEL_kabe_b            0x5
#define MODEL_kabe_b1           0x4
#define MODEL_ki                0x3
#define MODEL_tate              0x2
#define MODEL_hako_l            0x1
#define MODEL_hako_s            0x0

