#define MODEL_Root              0x18
#define MODEL_dai               0x17
#define MODEL_o396              0x16
#define MODEL_o395              0x15
#define MODEL_o394              0x14
#define MODEL_o393              0x13
#define MODEL_waku1             0x12
#define MODEL_futi1             0x11
#define MODEL_kazari2           0x10
#define MODEL_yuka3             0xF
#define MODEL_yuka              0xE
#define MODEL_g49               0xD
#define MODEL_waku2             0xC
#define MODEL_sai3              0xB
#define MODEL_sai2              0xA
#define MODEL_sai1              0x9
#define MODEL_siro              0x8
#define MODEL_ao                0x7
#define MODEL_aka               0x6
#define MODEL_b_ao              0x5
#define MODEL_kabe3             0x4
#define MODEL_kabe2             0x3
#define MODEL_kabe1             0x2
#define MODEL_yuka2             0x1
#define MODEL_waku              0x0

