#define MODEL_Root              0x18
#define MODEL_dai               0x17
#define MODEL_kazari2           0x16
#define MODEL_futi1             0x15
#define MODEL_waku1             0x14
#define MODEL_yuka              0x13
#define MODEL_g97               0x12
#define MODEL_o479              0x11
#define MODEL_o478              0x10
#define MODEL_o477              0xF
#define MODEL_o476              0xE
#define MODEL_3                 0xD
#define MODEL_r_hosi            0xC
#define MODEL_r_uzu             0xB
#define MODEL_r_neko            0xA
#define MODEL_g                 0x9
#define MODEL_hako2             0x8
#define MODEL_hako1             0x7
#define MODEL_sai3              0x6
#define MODEL_sai2              0x5
#define MODEL_sai1              0x4
#define MODEL_waku2             0x3
#define MODEL_yuka2             0x2
#define MODEL_waku              0x1
#define MODEL_kabe              0x0

