#define MODEL_Root              0x2E
#define MODEL_dai2              0x2D
#define MODEL_mae6              0x2C
#define MODEL_mae5              0x2B
#define MODEL_mae4              0x2A
#define MODEL_t_yon             0x29
#define MODEL_t_san             0x28
#define MODEL_itigo             0x27
#define MODEL_kisya             0x26
#define MODEL_yuka6             0x25
#define MODEL_yuka5             0x24
#define MODEL_g2                0x23
#define MODEL_tare              0x22
#define MODEL_kabe2             0x21
#define MODEL_kui3              0x20
#define MODEL_saku3             0x1F
#define MODEL_yuka3             0x1E
#define MODEL_kabe4             0x1D
#define MODEL_dai1              0x1C
#define MODEL_mae2              0x1B
#define MODEL_mae1              0x1A
#define MODEL_yuka              0x19
#define MODEL_g1                0x18
#define MODEL_kui2              0x17
#define MODEL_saku              0x16
#define MODEL_senro             0x15
#define MODEL_kui               0x14
#define MODEL_saku2             0x13
#define MODEL_dan5              0x12
#define MODEL_dan4              0x11
#define MODEL_dan3              0x10
#define MODEL_dan2              0xF
#define MODEL_dan1              0xE
#define MODEL_2_kabe3           0xD
#define MODEL_2_kabe2           0xC
#define MODEL_2_kabe1           0xB
#define MODEL_dai               0xA
#define MODEL_kazari2           0x9
#define MODEL_futi1             0x8
#define MODEL_waku1             0x7
#define MODEL_g                 0x6
#define MODEL_sai3              0x5
#define MODEL_sai2              0x4
#define MODEL_sai1              0x3
#define MODEL_waku2             0x2
#define MODEL_yuka2             0x1
#define MODEL_waku              0x0

