#define MODEL_Root              0x41
#define MODEL_sensya            0x40
#define MODEL_g106              0x3F
#define MODEL_shy               0x3E
#define MODEL_a4                0x3D
#define MODEL_n6                0x3C
#define MODEL_wa4               0x3B
#define MODEL_a3                0x3A
#define MODEL_n5                0x39
#define MODEL_wa3               0x38
#define MODEL_a2                0x37
#define MODEL_n4                0x36
#define MODEL_wa2               0x35
#define MODEL_a1                0x34
#define MODEL_n3                0x33
#define MODEL_wa1               0x32
#define MODEL_futa              0x31
#define MODEL_fyta1             0x30
#define MODEL_nob               0x2F
#define MODEL_nob1              0x2E
#define MODEL_en                0x2D
#define MODEL_en2               0x2C
#define MODEL_en1               0x2B
#define MODEL_kyu               0x2A
#define MODEL_kyu1              0x29
#define MODEL_kyu2              0x28
#define MODEL_kyu3              0x27
#define MODEL_h4                0x26
#define MODEL_n2                0x25
#define MODEL_sya3              0x24
#define MODEL_h3                0x23
#define MODEL_sya2              0x22
#define MODEL_n1                0x21
#define MODEL_h2                0x20
#define MODEL_sya1              0x1F
#define MODEL_h1                0x1E
#define MODEL_tanp              0x1D
#define MODEL_exit              0x1C
#define MODEL_dai               0x1B
#define MODEL_o468              0x1A
#define MODEL_o467              0x19
#define MODEL_kazari2           0x18
#define MODEL_futi1             0x17
#define MODEL_waku1             0x16
#define MODEL_yuka              0x15
#define MODEL_g                 0x14
#define MODEL_hosi              0x13
#define MODEL_kino              0x12
#define MODEL_kuruma            0x11
#define MODEL_15_tu4            0x10
#define MODEL_15_tu3            0xF
#define MODEL_15_tu2            0xE
#define MODEL_15_tu1            0xD
#define MODEL_15_sai3           0xC
#define MODEL_15_sai2           0xB
#define MODEL_15_sai            0xA
#define MODEL_kabe6             0x9
#define MODEL_kabe5             0x8
#define MODEL_kabe4             0x7
#define MODEL_kabe2             0x6
#define MODEL_kabe1             0x5
#define MODEL_kabe3             0x4
#define MODEL_waku2             0x3
#define MODEL_yuka2             0x2
#define MODEL_waku              0x1
#define MODEL_kabe              0x0

