#define COLLIDER_Root           0x11
#define COLLIDER_g97            0x10
#define COLLIDER_o473           0xF
#define COLLIDER_Default        0xE
#define COLLIDER_o494           0xD
#define COLLIDER_o493           0xC
#define COLLIDER_o492           0xB
#define COLLIDER_o486           0xA
#define COLLIDER_o484           0x9
#define COLLIDER_o476           0x8
#define COLLIDER_o485           0x7
#define COLLIDER_deilitn        0x6
#define COLLIDER_o462           0x5
#define COLLIDER_deilin         0x4
#define COLLIDER_deilite        0x3
#define COLLIDER_deilie         0x2
#define COLLIDER_deilits        0x1
#define COLLIDER_deilis         0x0

#define ZONE_Root               0x8
#define ZONE_g32                0x7
#define ZONE_o230               0x6
#define ZONE_o229               0x5
#define ZONE_g1                 0x4
#define ZONE_o35                0x3
#define ZONE_g7                 0x2
#define ZONE_deilis             0x1
#define ZONE_deilin             0x0

