#define COLLIDER_Root           0x2D
#define COLLIDER_hono           0x2C
#define COLLIDER_o554           0x2B
#define COLLIDER_o550           0x2A
#define COLLIDER_yuka           0x29
#define COLLIDER_hi9            0x28
#define COLLIDER_hi7            0x27
#define COLLIDER_hi6            0x26
#define COLLIDER_hi5            0x25
#define COLLIDER_hi4            0x24
#define COLLIDER_hi3            0x23
#define COLLIDER_hi2            0x22
#define COLLIDER_hi1            0x21
#define COLLIDER_kaidan         0x20
#define COLLIDER_o680           0x1F
#define COLLIDER_o710           0x1E
#define COLLIDER_stage          0x1D
#define COLLIDER_saku           0x1C
#define COLLIDER_o658           0x1B
#define COLLIDER_o600           0x1A
#define COLLIDER_ki             0x19
#define COLLIDER_o692           0x18
#define COLLIDER_o558           0x17
#define COLLIDER_o553           0x16
#define COLLIDER_o551           0x15
#define COLLIDER_ue             0x14
#define COLLIDER_bou            0x13
#define COLLIDER_kabe3          0x12
#define COLLIDER_kabe2          0x11
#define COLLIDER_kabe1          0x10
#define COLLIDER_mado           0xF
#define COLLIDER_yane           0xE
#define COLLIDER_o581           0xD
#define COLLIDER_o580           0xC
#define COLLIDER_midoli         0xB
#define COLLIDER_dai            0xA
#define COLLIDER_sikaku         0x9
#define COLLIDER_g149           0x8
#define COLLIDER_o652           0x7
#define COLLIDER_deilit2        0x6
#define COLLIDER_deili2         0x5
#define COLLIDER_o664           0x4
#define COLLIDER_deilit1        0x3
#define COLLIDER_deili1         0x2
#define COLLIDER_tt2            0x1
#define COLLIDER_tt1            0x0

#define ZONE_Root               0x2
#define ZONE_g1                 0x1
#define ZONE_o35                0x0

