#define MODEL_Root              0x1C
#define MODEL_g102              0x1B
#define MODEL_o428              0x1A
#define MODEL_m_fit2            0x19
#define MODEL_m_doa             0x18
#define MODEL_m_kab1            0x17
#define MODEL_m_fut1            0x16
#define MODEL_mo_kab            0x15
#define MODEL_yuka2             0x14
#define MODEL_ms_kab1           0x13
#define MODEL_ms_fut2           0x12
#define MODEL_ms_doa            0x11
#define MODEL_os_fut2           0x10
#define MODEL_os_fut1           0xF
#define MODEL_os_doa1           0xE
#define MODEL_o_fut2            0xD
#define MODEL_o_fut1            0xC
#define MODEL_o_kab1            0xB
#define MODEL_o_doa1            0xA
#define MODEL_waku2             0x9
#define MODEL_ten               0x8
#define MODEL_waku              0x7
#define MODEL_waku2_2           0x6
#define MODEL_dai               0x5
#define MODEL_waku1             0x4
#define MODEL_yuka              0x3
#define MODEL_waku_2            0x2
#define MODEL_kira1             0x1
#define MODEL_kira2             0x0

