#define COLLIDER_Root           0x1D
#define COLLIDER_exite          0x1C
#define COLLIDER_tte            0x1B
#define COLLIDER_ne             0x1A
#define COLLIDER_deilie         0x19
#define COLLIDER_deilite        0x18
#define COLLIDER_exitw          0x17
#define COLLIDER_ttw            0x16
#define COLLIDER_nw             0x15
#define COLLIDER_deiliw         0x14
#define COLLIDER_deilitw        0x13
#define COLLIDER_g7             0x12
#define COLLIDER_o51            0x11
#define COLLIDER_o50            0x10
#define COLLIDER_o47            0xF
#define COLLIDER_o46            0xE
#define COLLIDER_o45            0xD
#define COLLIDER_o44            0xC
#define COLLIDER_o41            0xB
#define COLLIDER_g1             0xA
#define COLLIDER_o55            0x9
#define COLLIDER_o58            0x8
#define COLLIDER_o57            0x7
#define COLLIDER_o54            0x6
#define COLLIDER_o62            0x5
#define COLLIDER_o61            0x4
#define COLLIDER_kabe           0x3
#define COLLIDER_o60            0x2
#define COLLIDER_o59            0x1
#define COLLIDER_ground         0x0

#define ZONE_Root               0x4
#define ZONE_g1                 0x3
#define ZONE_o10                0x2
#define ZONE_o9                 0x1
#define ZONE_ground             0x0

