#define COLLIDER_Root           0x41
#define COLLIDER_g43            0x40
#define COLLIDER_o293           0x3F
#define COLLIDER_o292           0x3E
#define COLLIDER_o291           0x3D
#define COLLIDER_o290           0x3C
#define COLLIDER_o225           0x3B
#define COLLIDER_g2             0x3A
#define COLLIDER_o288           0x39
#define COLLIDER_o262           0x38
#define COLLIDER_o287           0x37
#define COLLIDER_ground         0x36
#define COLLIDER_kabe2          0x35
#define COLLIDER_o268           0x34
#define COLLIDER_o286           0x33
#define COLLIDER_o267           0x32
#define COLLIDER_o266           0x31
#define COLLIDER_o265           0x30
#define COLLIDER_o264           0x2F
#define COLLIDER_o285           0x2E
#define COLLIDER_o263           0x2D
#define COLLIDER_o296           0x2C
#define COLLIDER_kabe           0x2B
#define COLLIDER_hakun          0x2A
#define COLLIDER_h_exit         0x29
#define COLLIDER_h_yuka2        0x28
#define COLLIDER_h_yuka1        0x27
#define COLLIDER_h_doa2         0x26
#define COLLIDER_h_doa1         0x25
#define COLLIDER_h_naiso        0x24
#define COLLIDER_o277           0x23
#define COLLIDER_hn_kabe        0x22
#define COLLIDER_hn_isu1        0x21
#define COLLIDER_hn_yuka1       0x20
#define COLLIDER_h_kabe         0x1F
#define COLLIDER_h_noki         0x1E
#define COLLIDER_k              0x1D
#define COLLIDER_exitk          0x1C
#define COLLIDER_k_yuka2        0x1B
#define COLLIDER_k_yuka1        0x1A
#define COLLIDER_k_d2           0x19
#define COLLIDER_k_d1           0x18
#define COLLIDER_k_naiso        0x17
#define COLLIDER_kn_kabe        0x16
#define COLLIDER_kn_dan         0x15
#define COLLIDER_kn_yuka        0x14
#define COLLIDER_k_kabe         0x13
#define COLLIDER_k_noki         0x12
#define COLLIDER_kinohuse       0x11
#define COLLIDER_kn_noki        0x10
#define COLLIDER_kh_exit        0xF
#define COLLIDER_kh_yuka2       0xE
#define COLLIDER_kh_yuka11      0xD
#define COLLIDER_kh_d2          0xC
#define COLLIDER_kh_d1          0xB
#define COLLIDER_kh_naiso       0xA
#define COLLIDER_o250           0x9
#define COLLIDER_khn_bed1       0x8
#define COLLIDER_khn_isu2       0x7
#define COLLIDER_khn_yuka1      0x6
#define COLLIDER_khn_kabe       0x5
#define COLLIDER_kh_kabe        0x4
#define COLLIDER_exitsw         0x3
#define COLLIDER_nsw            0x2
#define COLLIDER_deilisw        0x1
#define COLLIDER_deilitsw       0x0

#define ZONE_Root               0x8
#define ZONE_k_ie               0x7
#define ZONE_ki_yuka1           0x6
#define ZONE_kino               0x5
#define ZONE_kn_yuka1           0x4
#define ZONE_hakun              0x3
#define ZONE_hn_yuka            0x2
#define ZONE_g2                 0x1
#define ZONE_ground             0x0

