#define COLLIDER_Root           0x3C
#define COLLIDER_exit           0x3B
#define COLLIDER_ne             0x3A
#define COLLIDER_deilite        0x39
#define COLLIDER_deilie         0x38
#define COLLIDER_min            0x37
#define COLLIDER_g91            0x36
#define COLLIDER_o390           0x35
#define COLLIDER_o376           0x34
#define COLLIDER_m_noki         0x33
#define COLLIDER_o385           0x32
#define COLLIDER_exitm          0x31
#define COLLIDER_o355           0x30
#define COLLIDER_ttm            0x2F
#define COLLIDER_m_mae          0x2E
#define COLLIDER_mm_kabe        0x2D
#define COLLIDER_m_naiso        0x2C
#define COLLIDER_o417           0x2B
#define COLLIDER_m_yuka         0x2A
#define COLLIDER_o377           0x29
#define COLLIDER_mn_kabe        0x28
#define COLLIDER_f2             0x27
#define COLLIDER_f_noki         0x26
#define COLLIDER_f_yuka         0x25
#define COLLIDER_exitf2         0x24
#define COLLIDER_o354           0x23
#define COLLIDER_ttf2           0x22
#define COLLIDER_f_sita         0x21
#define COLLIDER_fs_kabe        0x20
#define COLLIDER_f_naiso        0x1F
#define COLLIDER_fn_hako        0x1E
#define COLLIDER_fn_hasi        0x1D
#define COLLIDER_fn_kabe        0x1C
#define COLLIDER_f_kabe         0x1B
#define COLLIDER_son            0x1A
#define COLLIDER_s_yuka         0x19
#define COLLIDER_s_naisou       0x18
#define COLLIDER_yana           0x17
#define COLLIDER_o368           0x16
#define COLLIDER_exitsn         0x15
#define COLLIDER_o353           0x14
#define COLLIDER_ttsn           0x13
#define COLLIDER_sn_tns         0x12
#define COLLIDER_sn_kabe        0x11
#define COLLIDER_exits          0x10
#define COLLIDER_o352           0xF
#define COLLIDER_tts            0xE
#define COLLIDER_s_noki         0xD
#define COLLIDER_s_kabe         0xC
#define COLLIDER_g3             0xB
#define COLLIDER_o414           0xA
#define COLLIDER_o413           0x9
#define COLLIDER_o412           0x8
#define COLLIDER_o401           0x7
#define COLLIDER_o402           0x6
#define COLLIDER_o399           0x5
#define COLLIDER_o398           0x4
#define COLLIDER_saku           0x3
#define COLLIDER_o409           0x2
#define COLLIDER_o408           0x1
#define COLLIDER_o341           0x0

#define ZONE_Root               0xA
#define ZONE_Default            0x9
#define ZONE_min2               0x8
#define ZONE_min                0x7
#define ZONE_f2                 0x6
#define ZONE_son2               0x5
#define ZONE_son                0x4
#define ZONE_g3                 0x3
#define ZONE_s                  0x2
#define ZONE_e                  0x1
#define ZONE_w                  0x0

