#define COLLIDER_Root           0x12
#define COLLIDER_g6             0x11
#define COLLIDER_o23            0x10
#define COLLIDER_g3             0xF
#define COLLIDER_ne             0xE
#define COLLIDER_deili          0xD
#define COLLIDER_deilit         0xC
#define COLLIDER_hasi           0xB
#define COLLIDER_g5             0xA
#define COLLIDER_o22            0x9
#define COLLIDER_o21            0x8
#define COLLIDER_o20            0x7
#define COLLIDER_o17            0x6
#define COLLIDER_o16            0x5
#define COLLIDER_o15            0x4
#define COLLIDER_g2             0x3
#define COLLIDER_dan            0x2
#define COLLIDER_yuka           0x1
#define COLLIDER_kabe           0x0

#define ZONE_Root               0x8
#define ZONE_g5                 0x7
#define ZONE_r3                 0x6
#define ZONE_r2                 0x5
#define ZONE_r1                 0x4
#define ZONE_g4                 0x3
#define ZONE_l3                 0x2
#define ZONE_l2                 0x1
#define ZONE_l1                 0x0

