#define MODEL_Root              0x14
#define MODEL_g4                0x13
#define MODEL_o28               0x12
#define MODEL_o22               0x11
#define MODEL_o10               0x10
#define MODEL_g5                0xF
#define MODEL_o20               0xE
#define MODEL_o19               0xD
#define MODEL_o18               0xC
#define MODEL_o17               0xB
#define MODEL_o16               0xA
#define MODEL_o15               0x9
#define MODEL_o14               0x8
#define MODEL_o13               0x7
#define MODEL_o12               0x6
#define MODEL_o11               0x5
#define MODEL_g1                0x4
#define MODEL_futi              0x3
#define MODEL_exitdai           0x2
#define MODEL_kabe              0x1
#define MODEL_ground            0x0

