#define COLLIDER_Root           0x2F
#define COLLIDER_g28            0x2E
#define COLLIDER_g29            0x2D
#define COLLIDER_o122           0x2C
#define COLLIDER_o121           0x2B
#define COLLIDER_o120           0x2A
#define COLLIDER_o119           0x29
#define COLLIDER_o118           0x28
#define COLLIDER_o106           0x27
#define COLLIDER_o105           0x26
#define COLLIDER_o104           0x25
#define COLLIDER_o103           0x24
#define COLLIDER_yukidaru       0x23
#define COLLIDER_o89            0x22
#define COLLIDER_o88            0x21
#define COLLIDER_o87            0x20
#define COLLIDER_zyumoku        0x1F
#define COLLIDER_miki5          0x1E
#define COLLIDER_miki6          0x1D
#define COLLIDER_miki4          0x1C
#define COLLIDER_miki3          0x1B
#define COLLIDER_miki2          0x1A
#define COLLIDER_miki1          0x19
#define COLLIDER_moue           0x18
#define COLLIDER_o80            0x17
#define COLLIDER_g23            0x16
#define COLLIDER_o79            0x15
#define COLLIDER_g22            0x14
#define COLLIDER_o78            0x13
#define COLLIDER_g2             0x12
#define COLLIDER_kabe           0x11
#define COLLIDER_yama           0x10
#define COLLIDER_ground         0xF
#define COLLIDER_exitn          0xE
#define COLLIDER_nn             0xD
#define COLLIDER_ttn            0xC
#define COLLIDER_deilin         0xB
#define COLLIDER_deilitn        0xA
#define COLLIDER_exite          0x9
#define COLLIDER_tte            0x8
#define COLLIDER_ne             0x7
#define COLLIDER_deilie         0x6
#define COLLIDER_deilite        0x5
#define COLLIDER_exitsw         0x4
#define COLLIDER_ttw            0x3
#define COLLIDER_nsw            0x2
#define COLLIDER_deilisw        0x1
#define COLLIDER_deilitsw       0x0

#define ZONE_Root               0x4
#define ZONE_g11                0x3
#define ZONE_o38                0x2
#define ZONE_o37                0x1
#define ZONE_o36                0x0

