#define COLLIDER_Root           0x1D
#define COLLIDER_g1             0x1C
#define COLLIDER_o47            0x1B
#define COLLIDER_move1          0x1A
#define COLLIDER_m1_kabe        0x19
#define COLLIDER_m1_yuka        0x18
#define COLLIDER_exite          0x17
#define COLLIDER_tte            0x16
#define COLLIDER_ne             0x15
#define COLLIDER_deilie         0x14
#define COLLIDER_deilite        0x13
#define COLLIDER_exitw          0x12
#define COLLIDER_ttw            0x11
#define COLLIDER_nw             0x10
#define COLLIDER_deiliw         0xF
#define COLLIDER_deilitw        0xE
#define COLLIDER_Default        0xD
#define COLLIDER_o49            0xC
#define COLLIDER_iwa2           0xB
#define COLLIDER_iwa1           0xA
#define COLLIDER_kabe1          0x9
#define COLLIDER_o52            0x8
#define COLLIDER_o56            0x7
#define COLLIDER_o51            0x6
#define COLLIDER_o55            0x5
#define COLLIDER_kaidan         0x4
#define COLLIDER_kai_kabe       0x3
#define COLLIDER_o54            0x2
#define COLLIDER_o53            0x1
#define COLLIDER_yuka           0x0

#define ZONE_Root               0x5
#define ZONE_Default            0x4
#define ZONE_o42                0x3
#define ZONE_o38                0x2
#define ZONE_o37                0x1
#define ZONE_yuka               0x0

