#define COLLIDER_Root           0x2F
#define COLLIDER_g21            0x2E
#define COLLIDER_o89            0x2D
#define COLLIDER_g19            0x2C
#define COLLIDER_o61            0x2B
#define COLLIDER_ana            0x2A
#define COLLIDER_na             0x29
#define COLLIDER_tta            0x28
#define COLLIDER_deilia         0x27
#define COLLIDER_deilita        0x26
#define COLLIDER_move2          0x25
#define COLLIDER_o76            0x24
#define COLLIDER_o75            0x23
#define COLLIDER_m2_kabe        0x22
#define COLLIDER_o69            0x21
#define COLLIDER_o68            0x20
#define COLLIDER_o70            0x1F
#define COLLIDER_o67            0x1E
#define COLLIDER_o74            0x1D
#define COLLIDER_o73            0x1C
#define COLLIDER_m2_yuka        0x1B
#define COLLIDER_o72            0x1A
#define COLLIDER_o71            0x19
#define COLLIDER_move1          0x18
#define COLLIDER_m1_kabe        0x17
#define COLLIDER_Default        0x16
#define COLLIDER_iwa2           0x15
#define COLLIDER_o47            0x14
#define COLLIDER_o84            0x13
#define COLLIDER_o81            0x12
#define COLLIDER_o83            0x11
#define COLLIDER_o79            0x10
#define COLLIDER_o88            0xF
#define COLLIDER_o80            0xE
#define COLLIDER_o87            0xD
#define COLLIDER_o86            0xC
#define COLLIDER_kabe1          0xB
#define COLLIDER_yuka           0xA
#define COLLIDER_exite          0x9
#define COLLIDER_tte            0x8
#define COLLIDER_ne             0x7
#define COLLIDER_deilie         0x6
#define COLLIDER_deilite        0x5
#define COLLIDER_exitw          0x4
#define COLLIDER_ttw            0x3
#define COLLIDER_nw             0x2
#define COLLIDER_deiliw         0x1
#define COLLIDER_deilitw        0x0

#define ZONE_Root               0x17
#define ZONE_i                  0x16
#define ZONE_i3                 0x15
#define ZONE_h                  0x14
#define ZONE_h3                 0x13
#define ZONE_g                  0x12
#define ZONE_g3                 0x11
#define ZONE_g2                 0x10
#define ZONE_f                  0xF
#define ZONE_f2                 0xE
#define ZONE_e                  0xD
#define ZONE_e2                 0xC
#define ZONE_e1                 0xB
#define ZONE_d                  0xA
#define ZONE_d2                 0x9
#define ZONE_d1                 0x8
#define ZONE_c                  0x7
#define ZONE_c1                 0x6
#define ZONE_b                  0x5
#define ZONE_b1                 0x4
#define ZONE_a                  0x3
#define ZONE_a3                 0x2
#define ZONE_a2                 0x1
#define ZONE_a1                 0x0

