#define MODEL_Root              0x25
#define MODEL_kori              0x24
#define MODEL_o44               0x23
#define MODEL_Default           0x22
#define MODEL_saku              0x21
#define MODEL_miki8             0x20
#define MODEL_miki14            0x1F
#define MODEL_miki13            0x1E
#define MODEL_miki7             0x1D
#define MODEL_miki6             0x1C
#define MODEL_miki3             0x1B
#define MODEL_miki2             0x1A
#define MODEL_miki1             0x19
#define MODEL_ki14              0x18
#define MODEL_ki13              0x17
#define MODEL_ki12              0x16
#define MODEL_ki11              0x15
#define MODEL_ki10              0x14
#define MODEL_ki9               0x13
#define MODEL_ki8               0x12
#define MODEL_ki7               0x11
#define MODEL_ki6               0x10
#define MODEL_ki5               0xF
#define MODEL_ki4               0xE
#define MODEL_ki3               0xD
#define MODEL_ki2               0xC
#define MODEL_ki1               0xB
#define MODEL_g1                0xA
#define MODEL_tareyuki          0x9
#define MODEL_kabe              0x8
#define MODEL_road              0x7
#define MODEL_yuki              0x6
#define MODEL_exitw             0x5
#define MODEL_o2                0x4
#define MODEL_o26               0x3
#define MODEL_exite             0x2
#define MODEL_o1                0x1
#define MODEL_o25               0x0

