#define COLLIDER_Root           0x50
#define COLLIDER_g280           0x4F
#define COLLIDER_o663           0x4E
#define COLLIDER_o662           0x4D
#define COLLIDER_o661           0x4C
#define COLLIDER_o660           0x4B
#define COLLIDER_o658           0x4A
#define COLLIDER_o657           0x49
#define COLLIDER_monban         0x48
#define COLLIDER_o621           0x47
#define COLLIDER_g189           0x46
#define COLLIDER_o683           0x45
#define COLLIDER_pnori          0x44
#define COLLIDER_deilitp        0x43
#define COLLIDER_o356           0x42
#define COLLIDER_g50            0x41
#define COLLIDER_suimen         0x40
#define COLLIDER_mon            0x3F
#define COLLIDER_o579           0x3E
#define COLLIDER_tumori         0x3D
#define COLLIDER_saku           0x3C
#define COLLIDER_ki             0x3B
#define COLLIDER_miki5          0x3A
#define COLLIDER_miki4          0x39
#define COLLIDER_o653           0x38
#define COLLIDER_sou            0x37
#define COLLIDER_s_tou          0x36
#define COLLIDER_o571           0x35
#define COLLIDER_o570           0x34
#define COLLIDER_s_naiso        0x33
#define COLLIDER_o643           0x32
#define COLLIDER_o626           0x31
#define COLLIDER_sn_isu2        0x30
#define COLLIDER_sn_isu1        0x2F
#define COLLIDER_sn_hako        0x2E
#define COLLIDER_sn_yuka2       0x2D
#define COLLIDER_sn_kabe        0x2C
#define COLLIDER_s_doa          0x2B
#define COLLIDER_o591           0x2A
#define COLLIDER_o540           0x29
#define COLLIDER_s_noki         0x28
#define COLLIDER_s_kabe         0x27
#define COLLIDER_gon            0x26
#define COLLIDER_g_yuka         0x25
#define COLLIDER_g_doa          0x24
#define COLLIDER_o590           0x23
#define COLLIDER_o541           0x22
#define COLLIDER_g_naiso        0x21
#define COLLIDER_isu            0x20
#define COLLIDER_ana            0x1F
#define COLLIDER_g_kai          0x1E
#define COLLIDER_o525           0x1D
#define COLLIDER_gn_dan         0x1C
#define COLLIDER_kagu2          0x1B
#define COLLIDER_kagu1          0x1A
#define COLLIDER_gn_yuka        0x19
#define COLLIDER_gn_hasi        0x18
#define COLLIDER_gn_kabe        0x17
#define COLLIDER_g_noki         0x16
#define COLLIDER_g_yuki1        0x15
#define COLLIDER_g_yuki2        0x14
#define COLLIDER_g_kabe         0x13
#define COLLIDER_g10            0x12
#define COLLIDER_ike            0x11
#define COLLIDER_o681           0x10
#define COLLIDER_o682           0xF
#define COLLIDER_o578           0xE
#define COLLIDER_o634           0xD
#define COLLIDER_o596           0xC
#define COLLIDER_o678           0xB
#define COLLIDER_o664           0xA
#define COLLIDER_o677           0x9
#define COLLIDER_o595           0x8
#define COLLIDER_exite          0x7
#define COLLIDER_ne             0x6
#define COLLIDER_deilie         0x5
#define COLLIDER_deilite        0x4
#define COLLIDER_exitw          0x3
#define COLLIDER_nw             0x2
#define COLLIDER_deiliw         0x1
#define COLLIDER_deilitw        0x0

#define ZONE_Root               0xC
#define ZONE_Default            0xB
#define ZONE_y3                 0xA
#define ZONE_y2                 0x9
#define ZONE_y1                 0x8
#define ZONE_g50                0x7
#define ZONE_sou                0x6
#define ZONE_gon2               0x5
#define ZONE_gon                0x4
#define ZONE_g3                 0x3
#define ZONE_s                  0x2
#define ZONE_e                  0x1
#define ZONE_w                  0x0

