#define MODEL_Root              0x1A
#define MODEL_g1                0x19
#define MODEL_move3             0x18
#define MODEL_m3_kabe           0x17
#define MODEL_move2             0x16
#define MODEL_m2_kabe           0x15
#define MODEL_move1             0x14
#define MODEL_m1_kabe           0x13
#define MODEL_exite             0x12
#define MODEL_o20               0x11
#define MODEL_o19               0x10
#define MODEL_exitw             0xF
#define MODEL_o18               0xE
#define MODEL_o17               0xD
#define MODEL_g2                0xC
#define MODEL_hasira            0xB
#define MODEL_ten3              0xA
#define MODEL_ten2              0x9
#define MODEL_ten               0x8
#define MODEL_Default           0x7
#define MODEL_hako              0x6
#define MODEL_iwa2              0x5
#define MODEL_kabe1             0x4
#define MODEL_futi              0x3
#define MODEL_yuka              0x2
#define MODEL_oku               0x1
#define MODEL_o_kabe            0x0

