#define MODEL_Root              0x1F
#define MODEL_dai               0x1E
#define MODEL_waku1             0x1D
#define MODEL_kouri1            0x1C
#define MODEL_yuka1             0x1B
#define MODEL_yuki              0x1A
#define MODEL_yuki4             0x19
#define MODEL_o285              0x18
#define MODEL_yuki3             0x17
#define MODEL_o284              0x16
#define MODEL_yuki2             0x15
#define MODEL_o283              0x14
#define MODEL_yuki1             0x13
#define MODEL_o253              0x12
#define MODEL_base              0x11
#define MODEL_kouri5            0x10
#define MODEL_kouri4            0xF
#define MODEL_waku2             0xE
#define MODEL_waku              0xD
#define MODEL_p3                0xC
#define MODEL_o278              0xB
#define MODEL_p2                0xA
#define MODEL_o282              0x9
#define MODEL_o281              0x8
#define MODEL_o280              0x7
#define MODEL_o279              0x6
#define MODEL_hsr1              0x5
#define MODEL_hsr2              0x4
#define MODEL_p1                0x3
#define MODEL_kouri3            0x2
#define MODEL_kouri2            0x1
#define MODEL_o274              0x0

