#define MODEL_Root              0x2B
#define MODEL_g22               0x2A
#define MODEL_o84               0x29
#define MODEL_yukidaru          0x28
#define MODEL_mafu              0x27
#define MODEL_baketu            0x26
#define MODEL_body              0x25
#define MODEL_d_me              0x24
#define MODEL_zyumoku           0x23
#define MODEL_g24               0x22
#define MODEL_ki2_1             0x21
#define MODEL_ki2_2             0x20
#define MODEL_ki2_3             0x1F
#define MODEL_miki2             0x1E
#define MODEL_miki6             0x1D
#define MODEL_mili5             0x1C
#define MODEL_miki4             0x1B
#define MODEL_miki3             0x1A
#define MODEL_miki1             0x19
#define MODEL_ki6               0x18
#define MODEL_ki5               0x17
#define MODEL_ki4               0x16
#define MODEL_ki3               0x15
#define MODEL_ki1               0x14
#define MODEL_g2                0x13
#define MODEL_g13               0x12
#define MODEL_o45               0x11
#define MODEL_o44               0x10
#define MODEL_ground            0xF
#define MODEL_road              0xE
#define MODEL_exitdai           0xD
#define MODEL_waku              0xC
#define MODEL_move              0xB
#define MODEL_o66               0xA
#define MODEL_doae              0x9
#define MODEL_o64               0x8
#define MODEL_doaw              0x7
#define MODEL_o65               0x6
#define MODEL_yama              0x5
#define MODEL_o79               0x4
#define MODEL_o78               0x3
#define MODEL_o70               0x2
#define MODEL_yamae             0x1
#define MODEL_yamaw             0x0

