#define MODEL_Root              0x19
#define MODEL_g1                0x18
#define MODEL_exit              0x17
#define MODEL_exitw             0x16
#define MODEL_b_w2              0x15
#define MODEL_b_w               0x14
#define MODEL_exits             0x13
#define MODEL_b_s2              0x12
#define MODEL_b_s               0x11
#define MODEL_exite             0x10
#define MODEL_b_e2              0xF
#define MODEL_b_e               0xE
#define MODEL_exitn             0xD
#define MODEL_b_n2              0xC
#define MODEL_b_n               0xB
#define MODEL_g2                0xA
#define MODEL_g10               0x9
#define MODEL_r1                0x8
#define MODEL_r2                0x7
#define MODEL_r3                0x6
#define MODEL_r4                0x5
#define MODEL_stage             0x4
#define MODEL_g5                0x3
#define MODEL_o3                0x2
#define MODEL_g3                0x1
#define MODEL_o1                0x0

