#define MODEL_Root              0x14
#define MODEL_g1                0x13
#define MODEL_g28               0x12
#define MODEL_g29               0x11
#define MODEL_o56               0x10
#define MODEL_o55               0xF
#define MODEL_exit              0xE
#define MODEL_g7                0xD
#define MODEL_b_w2              0xC
#define MODEL_b_w               0xB
#define MODEL_g8                0xA
#define MODEL_b_e2              0x9
#define MODEL_b_e               0x8
#define MODEL_g12               0x7
#define MODEL_b_n2              0x6
#define MODEL_b_n               0x5
#define MODEL_g2                0x4
#define MODEL_g10               0x3
#define MODEL_stage             0x2
#define MODEL_g5                0x1
#define MODEL_o3                0x0

