#define COLLIDER_Root           0x17
#define COLLIDER_ruin           0x16
#define COLLIDER_r6             0x15
#define COLLIDER_r5             0x14
#define COLLIDER_r4             0x13
#define COLLIDER_r3             0x12
#define COLLIDER_r2             0x11
#define COLLIDER_r1             0x10
#define COLLIDER_pikapika       0xF
#define COLLIDER_point          0xE
#define COLLIDER_iwa            0xD
#define COLLIDER_deili          0xC
#define COLLIDER_o222           0xB
#define COLLIDER_deilit1        0xA
#define COLLIDER_deili1         0x9
#define COLLIDER_deilite        0x8
#define COLLIDER_deilie         0x7
#define COLLIDER_deilits        0x6
#define COLLIDER_deilis         0x5
#define COLLIDER_deilitw        0x4
#define COLLIDER_deiliw         0x3
#define COLLIDER_g6             0x2
#define COLLIDER_o218           0x1
#define COLLIDER_o16            0x0

#define ZONE_Root               0xE
#define ZONE_g1                 0xD
#define ZONE_g6                 0xC
#define ZONE_g7                 0xB
#define ZONE_b_w                0xA
#define ZONE_g11                0x9
#define ZONE_b_s                0x8
#define ZONE_g8                 0x7
#define ZONE_b_e                0x6
#define ZONE_g12                0x5
#define ZONE_b_n                0x4
#define ZONE_g2                 0x3
#define ZONE_g10                0x2
#define ZONE_o22                0x1
#define ZONE_hiru_came          0x0

