#define COLLIDER_Root 0x12
#define COLLIDER_g25 0x11
#define COLLIDER_o141 0x10
#define COLLIDER_o152 0xF
#define COLLIDER_o151 0xE
#define COLLIDER_tuitate 0xD
#define COLLIDER_ttw 0xC
#define COLLIDER_tts 0xB
#define COLLIDER_tte 0xA
#define COLLIDER_dero 0x9
#define COLLIDER_deilitw 0x8
#define COLLIDER_deiliw 0x7
#define COLLIDER_deilits 0x6
#define COLLIDER_deilis 0x5
#define COLLIDER_deilite 0x4
#define COLLIDER_deilie 0x3
#define COLLIDER_g1 0x2
#define COLLIDER_mawari 0x1
#define COLLIDER_stage 0x0
