#define COLLIDER_Root           0x1F
#define COLLIDER_g1             0x1E
#define COLLIDER_g35            0x1D
#define COLLIDER_o73            0x1C
#define COLLIDER_o72            0x1B
#define COLLIDER_o71            0x1A
#define COLLIDER_o70            0x19
#define COLLIDER_o69            0x18
#define COLLIDER_o68            0x17
#define COLLIDER_o67            0x16
#define COLLIDER_y_miki         0x15
#define COLLIDER_yasi           0x14
#define COLLIDER_rim            0x13
#define COLLIDER_remon          0x12
#define COLLIDER_kusa           0x11
#define COLLIDER_exit           0x10
#define COLLIDER_exitw          0xF
#define COLLIDER_nw             0xE
#define COLLIDER_deilitw        0xD
#define COLLIDER_deiliw         0xC
#define COLLIDER_exits          0xB
#define COLLIDER_ns             0xA
#define COLLIDER_deilits        0x9
#define COLLIDER_deilis         0x8
#define COLLIDER_exitn          0x7
#define COLLIDER_nn             0x6
#define COLLIDER_deilitn        0x5
#define COLLIDER_deilin         0x4
#define COLLIDER_g34            0x3
#define COLLIDER_o64            0x2
#define COLLIDER_o65            0x1
#define COLLIDER_o63            0x0

#define ZONE_Root               0xD
#define ZONE_g1                 0xC
#define ZONE_g6                 0xB
#define ZONE_g7                 0xA
#define ZONE_b_w                0x9
#define ZONE_g11                0x8
#define ZONE_b_s                0x7
#define ZONE_g8                 0x6
#define ZONE_b_e                0x5
#define ZONE_g12                0x4
#define ZONE_b_n                0x3
#define ZONE_g2                 0x2
#define ZONE_g10                0x1
#define ZONE_hiru_came          0x0

