#define MODEL_Root              0x1F
#define MODEL_g1                0x1E
#define MODEL_g28               0x1D
#define MODEL_g30               0x1C
#define MODEL_g33               0x1B
#define MODEL_o67               0x1A
#define MODEL_o66               0x19
#define MODEL_g32               0x18
#define MODEL_o65               0x17
#define MODEL_o64               0x16
#define MODEL_o63               0x15
#define MODEL_o62               0x14
#define MODEL_g31               0x13
#define MODEL_o61               0x12
#define MODEL_o60               0x11
#define MODEL_o59               0x10
#define MODEL_o58               0xF
#define MODEL_o57               0xE
#define MODEL_o56               0xD
#define MODEL_o55               0xC
#define MODEL_exit              0xB
#define MODEL_g11               0xA
#define MODEL_b_s2              0x9
#define MODEL_b_s               0x8
#define MODEL_g8                0x7
#define MODEL_b_e2              0x6
#define MODEL_b_e               0x5
#define MODEL_g2                0x4
#define MODEL_g10               0x3
#define MODEL_stage             0x2
#define MODEL_g5                0x1
#define MODEL_o3                0x0

