#define COLLIDER_Root 0x15
#define COLLIDER_g1 0x14
#define COLLIDER_iwa 0x13
#define COLLIDER_o76 0x12
#define COLLIDER_tuitate 0x11
#define COLLIDER_ttn 0x10
#define COLLIDER_tte 0xF
#define COLLIDER_tts 0xE
#define COLLIDER_ttw 0xD
#define COLLIDER_bero 0xC
#define COLLIDER_deiliw 0xB
#define COLLIDER_deilitw 0xA
#define COLLIDER_deilis 0x9
#define COLLIDER_deilits 0x8
#define COLLIDER_deilie 0x7
#define COLLIDER_deilite 0x6
#define COLLIDER_deilin 0x5
#define COLLIDER_deilitn 0x4
#define COLLIDER_g26 0x3
#define COLLIDER_g27 0x2
#define COLLIDER_o57 0x1
#define COLLIDER_o56 0x0
