#define MODEL_Root              0x40
#define MODEL_g1                0x3F
#define MODEL_g38               0x3E
#define MODEL_o64               0x3D
#define MODEL_o63               0x3C
#define MODEL_g37               0x3B
#define MODEL_o62               0x3A
#define MODEL_o61               0x39
#define MODEL_g36               0x38
#define MODEL_o75               0x37
#define MODEL_o74               0x36
#define MODEL_o73               0x35
#define MODEL_o60               0x34
#define MODEL_o59               0x33
#define MODEL_g35               0x32
#define MODEL_o72               0x31
#define MODEL_o58               0x30
#define MODEL_o57               0x2F
#define MODEL_g34               0x2E
#define MODEL_o80               0x2D
#define MODEL_o56               0x2C
#define MODEL_o55               0x2B
#define MODEL_g33               0x2A
#define MODEL_o70               0x29
#define MODEL_o54               0x28
#define MODEL_o53               0x27
#define MODEL_g32               0x26
#define MODEL_o69               0x25
#define MODEL_y_ha              0x24
#define MODEL_o51               0x23
#define MODEL_g31               0x22
#define MODEL_o68               0x21
#define MODEL_o52               0x20
#define MODEL_y_miki            0x1F
#define MODEL_yasi              0x1E
#define MODEL_o78               0x1D
#define MODEL_o76               0x1C
#define MODEL_o50               0x1B
#define MODEL_miki              0x1A
#define MODEL_ki                0x19
#define MODEL_exit              0x18
#define MODEL_g7                0x17
#define MODEL_b_w2              0x16
#define MODEL_b_w               0x15
#define MODEL_g11               0x14
#define MODEL_b_s2              0x13
#define MODEL_b_s               0x12
#define MODEL_g12               0x11
#define MODEL_b_n2              0x10
#define MODEL_b_n               0xF
#define MODEL_g2                0xE
#define MODEL_kasane            0xD
#define MODEL_o66               0xC
#define MODEL_o65               0xB
#define MODEL_k_suna            0xA
#define MODEL_k_kusa            0x9
#define MODEL_stage2            0x8
#define MODEL_stage             0x7
#define MODEL_g10               0x6
#define MODEL_stage3            0x5
#define MODEL_sui               0x4
#define MODEL_o49               0x3
#define MODEL_mizu              0x2
#define MODEL_g5                0x1
#define MODEL_o3                0x0

