#define COLLIDER_Root           0x11
#define COLLIDER_g25            0x10
#define COLLIDER_o140           0xF
#define COLLIDER_o139           0xE
#define COLLIDER_o138           0xD
#define COLLIDER_o130           0xC
#define COLLIDER_o128           0xB
#define COLLIDER_tuitate        0xA
#define COLLIDER_tte            0x9
#define COLLIDER_ttn            0x8
#define COLLIDER_dero           0x7
#define COLLIDER_deilite        0x6
#define COLLIDER_deilie         0x5
#define COLLIDER_deilitn        0x4
#define COLLIDER_deilin         0x3
#define COLLIDER_g1             0x2
#define COLLIDER_mawari         0x1
#define COLLIDER_stage          0x0

#define ZONE_Root               0xD
#define ZONE_g1                 0xC
#define ZONE_g6                 0xB
#define ZONE_g7                 0xA
#define ZONE_b_w                0x9
#define ZONE_g11                0x8
#define ZONE_b_s                0x7
#define ZONE_g8                 0x6
#define ZONE_b_e                0x5
#define ZONE_g12                0x4
#define ZONE_b_n                0x3
#define ZONE_g2                 0x2
#define ZONE_g10                0x1
#define ZONE_hiru_came          0x0

