#define MODEL_Root              0x3B
#define MODEL_g1                0x3A
#define MODEL_ki                0x39
#define MODEL_o84               0x38
#define MODEL_ki_ha             0x37
#define MODEL_ki_miki           0x36
#define MODEL_iwa               0x35
#define MODEL_o82               0x34
#define MODEL_o81               0x33
#define MODEL_o80               0x32
#define MODEL_o78               0x31
#define MODEL_o76               0x30
#define MODEL_o75               0x2F
#define MODEL_iwab              0x2E
#define MODEL_iwaa              0x2D
#define MODEL_g28               0x2C
#define MODEL_o83               0x2B
#define MODEL_g23               0x2A
#define MODEL_o87               0x29
#define MODEL_o85               0x28
#define MODEL_ramp              0x27
#define MODEL_o62               0x26
#define MODEL_o66               0x25
#define MODEL_o65               0x24
#define MODEL_sakji_tent        0x23
#define MODEL_o55               0x22
#define MODEL_o54               0x21
#define MODEL_juutan            0x20
#define MODEL_o51               0x1F
#define MODEL_o50               0x1E
#define MODEL_o49               0x1D
#define MODEL_o48               0x1C
#define MODEL_o46               0x1B
#define MODEL_o42               0x1A
#define MODEL_o40               0x19
#define MODEL_o38               0x18
#define MODEL_g6                0x17
#define MODEL_g7                0x16
#define MODEL_b_w2              0x15
#define MODEL_b_w               0x14
#define MODEL_g11               0x13
#define MODEL_b_s2              0x12
#define MODEL_b_s               0x11
#define MODEL_g8                0x10
#define MODEL_b_e2              0xF
#define MODEL_b_e               0xE
#define MODEL_g12               0xD
#define MODEL_b_n2              0xC
#define MODEL_b_n               0xB
#define MODEL_g2                0xA
#define MODEL_g10               0x9
#define MODEL_r1                0x8
#define MODEL_r2                0x7
#define MODEL_r3                0x6
#define MODEL_r4                0x5
#define MODEL_stage             0x4
#define MODEL_g5                0x3
#define MODEL_o3                0x2
#define MODEL_g3                0x1
#define MODEL_o1                0x0

