#define COLLIDER_Root 0x11
#define COLLIDER_g25 0x10
#define COLLIDER_o196 0xF
#define COLLIDER_o195 0xE
#define COLLIDER_tuitate 0xD
#define COLLIDER_ttw 0xC
#define COLLIDER_tte 0xB
#define COLLIDER_ttn 0xA
#define COLLIDER_dero 0x9
#define COLLIDER_deilitw 0x8
#define COLLIDER_deiliw 0x7
#define COLLIDER_deilite 0x6
#define COLLIDER_deilie 0x5
#define COLLIDER_deilitn 0x4
#define COLLIDER_deilin 0x3
#define COLLIDER_g1 0x2
#define COLLIDER_mawari 0x1
#define COLLIDER_stage 0x0
