#define MODEL_Root              0x12
#define MODEL_dokan             0x11
#define MODEL_dokan3            0x10
#define MODEL_dokan2            0xF
#define MODEL_dokan1            0xE
#define MODEL_exitd             0xD
#define MODEL_o38               0xC
#define MODEL_o37               0xB
#define MODEL_g7                0xA
#define MODEL_sizuku            0x9
#define MODEL_sui               0x8
#define MODEL_mizu              0x7
#define MODEL_Default           0x6
#define MODEL_masuk             0x5
#define MODEL_yuka              0x4
#define MODEL_saku              0x3
#define MODEL_tennzyou          0x2
#define MODEL_futi              0x1
#define MODEL_kabe              0x0

