#define COLLIDER_Root           0x15
#define COLLIDER_exite          0x14
#define COLLIDER_tte            0x13
#define COLLIDER_deilite        0x12
#define COLLIDER_deilie         0x11
#define COLLIDER_ne             0x10
#define COLLIDER_g9             0xF
#define COLLIDER_erb            0xE
#define COLLIDER_4              0xD
#define COLLIDER_3              0xC
#define COLLIDER_2              0xB
#define COLLIDER_1              0xA
#define COLLIDER_g11            0x9
#define COLLIDER_o45            0x8
#define COLLIDER_g8             0x7
#define COLLIDER_o46            0x6
#define COLLIDER_exit_dokan     0x5
#define COLLIDER_Default        0x4
#define COLLIDER_at             0x3
#define COLLIDER_o22            0x2
#define COLLIDER_kabe           0x1
#define COLLIDER_yuka           0x0

#define ZONE_Root               0x4
#define ZONE_g9                 0x3
#define ZONE_3                  0x2
#define ZONE_2                  0x1
#define ZONE_1                  0x0

