#define MODEL_Root              0x1F
#define MODEL_dokan             0x1E
#define MODEL_o42               0x1D
#define MODEL_o41               0x1C
#define MODEL_o40               0x1B
#define MODEL_o44               0x1A
#define MODEL_dokan1            0x19
#define MODEL_dokan4            0x18
#define MODEL_dokan3            0x17
#define MODEL_dokan2            0x16
#define MODEL_g9                0x15
#define MODEL_erb2              0x14
#define MODEL_erb               0x13
#define MODEL_erb1              0x12
#define MODEL_g7                0x11
#define MODEL_sizuku            0x10
#define MODEL_exite             0xF
#define MODEL_o35               0xE
#define MODEL_o34               0xD
#define MODEL_exitw             0xC
#define MODEL_o37               0xB
#define MODEL_o36               0xA
#define MODEL_sui               0x9
#define MODEL_mizu              0x8
#define MODEL_Default           0x7
#define MODEL_masuku            0x6
#define MODEL_kaidan            0x5
#define MODEL_saku              0x4
#define MODEL_tennzyou          0x3
#define MODEL_futi              0x2
#define MODEL_kabe              0x1
#define MODEL_yuka              0x0

