#define COLLIDER_Root           0x1F
#define COLLIDER_exitd          0x1E
#define COLLIDER_ttd            0x1D
#define COLLIDER_nd             0x1C
#define COLLIDER_exite          0x1B
#define COLLIDER_tte            0x1A
#define COLLIDER_deilite        0x19
#define COLLIDER_deilie         0x18
#define COLLIDER_ne             0x17
#define COLLIDER_exitw          0x16
#define COLLIDER_ttw            0x15
#define COLLIDER_nw             0x14
#define COLLIDER_deiliw         0x13
#define COLLIDER_deilitw        0x12
#define COLLIDER_g12            0x11
#define COLLIDER_o118           0x10
#define COLLIDER_o115           0xF
#define COLLIDER_o78            0xE
#define COLLIDER_o77            0xD
#define COLLIDER_o114           0xC
#define COLLIDER_o76            0xB
#define COLLIDER_o75            0xA
#define COLLIDER_Default        0x9
#define COLLIDER_at             0x8
#define COLLIDER_suimen         0x7
#define COLLIDER_tennzyou       0x6
#define COLLIDER_o42            0x5
#define COLLIDER_o120           0x4
#define COLLIDER_o121           0x3
#define COLLIDER_kabe           0x2
#define COLLIDER_o119           0x1
#define COLLIDER_yuka           0x0

#define ZONE_Root               0x4
#define ZONE_g15                0x3
#define ZONE_o73                0x2
#define ZONE_o72                0x1
#define ZONE_o71                0x0

