#define MODEL_Root              0x26
#define MODEL_dokan             0x25
#define MODEL_dokan4            0x24
#define MODEL_dokan3            0x23
#define MODEL_dokan2            0x22
#define MODEL_dokan1            0x21
#define MODEL_exit_d            0x20
#define MODEL_o75               0x1F
#define MODEL_exit              0x1E
#define MODEL_o58               0x1D
#define MODEL_ice               0x1C
#define MODEL_o68               0x1B
#define MODEL_kai_ice2          0x1A
#define MODEL_kai_ice           0x19
#define MODEL_o57               0x18
#define MODEL_kiri              0x17
#define MODEL_d4_ice            0x16
#define MODEL_simo              0x15
#define MODEL_ice_futi          0x14
#define MODEL_o90               0x13
#define MODEL_ice_yuka2         0x12
#define MODEL_o89               0x11
#define MODEL_ice_yuka          0x10
#define MODEL_d2_ice2           0xF
#define MODEL_d2_ice1           0xE
#define MODEL_r_ice             0xD
#define MODEL_l_ice             0xC
#define MODEL_d3_ice2           0xB
#define MODEL_d_ice3            0xA
#define MODEL_d_ice2            0x9
#define MODEL_d_ice1            0x8
#define MODEL_kouri             0x7
#define MODEL_Default           0x6
#define MODEL_kaidan            0x5
#define MODEL_saku              0x4
#define MODEL_tennzyou          0x3
#define MODEL_futi              0x2
#define MODEL_kabe              0x1
#define MODEL_yuka              0x0

