#define MODEL_Root              0x22
#define MODEL_g29               0x21
#define MODEL_kan2              0x20
#define MODEL_o90               0x1F
#define MODEL_kan1              0x1E
#define MODEL_o89               0x1D
#define MODEL_bin               0x1C
#define MODEL_o87               0x1B
#define MODEL_dokan             0x1A
#define MODEL_dokan5            0x19
#define MODEL_dokan4            0x18
#define MODEL_dokan3            0x17
#define MODEL_dokan2            0x16
#define MODEL_dokan1            0x15
#define MODEL_g7                0x14
#define MODEL_sizuku            0x13
#define MODEL_exitd             0x12
#define MODEL_o65               0x11
#define MODEL_exitw             0x10
#define MODEL_o49               0xF
#define MODEL_o80               0xE
#define MODEL_exite             0xD
#define MODEL_o79               0xC
#define MODEL_o20               0xB
#define MODEL_sui               0xA
#define MODEL_nagab             0x9
#define MODEL_nagare            0x8
#define MODEL_Default           0x7
#define MODEL_saku              0x6
#define MODEL_masuk             0x5
#define MODEL_toge              0x4
#define MODEL_tennzyou          0x3
#define MODEL_futi              0x2
#define MODEL_kabe              0x1
#define MODEL_yuka              0x0

