#define COLLIDER_Root           0x1B
#define COLLIDER_g25            0x1A
#define COLLIDER_o89            0x19
#define COLLIDER_o88            0x18
#define COLLIDER_g16            0x17
#define COLLIDER_o57            0x16
#define COLLIDER_exite          0x15
#define COLLIDER_o93            0x14
#define COLLIDER_tte            0x13
#define COLLIDER_deilite        0x12
#define COLLIDER_deilie         0x11
#define COLLIDER_ne             0x10
#define COLLIDER_exitw          0xF
#define COLLIDER_o90            0xE
#define COLLIDER_ttw            0xD
#define COLLIDER_nw             0xC
#define COLLIDER_deiliw         0xB
#define COLLIDER_deilitw        0xA
#define COLLIDER_g12            0x9
#define COLLIDER_o49            0x8
#define COLLIDER_o48            0x7
#define COLLIDER_Default        0x6
#define COLLIDER_at             0x5
#define COLLIDER_o42            0x4
#define COLLIDER_o92            0x3
#define COLLIDER_kabe           0x2
#define COLLIDER_o91            0x1
#define COLLIDER_yuka           0x0

#define ZONE_Root               0x4
#define ZONE_g13                0x3
#define ZONE_3                  0x2
#define ZONE_2                  0x1
#define ZONE_1                  0x0

