#define MODEL_Root              0x17
#define MODEL_dokan             0x16
#define MODEL_doka3             0x15
#define MODEL_doka2             0x14
#define MODEL_g7                0x13
#define MODEL_sizuku            0x12
#define MODEL_exite             0x11
#define MODEL_o21               0x10
#define MODEL_o23               0xF
#define MODEL_exitw             0xE
#define MODEL_o22               0xD
#define MODEL_o20               0xC
#define MODEL_sui               0xB
#define MODEL_mizu2             0xA
#define MODEL_mizu              0x9
#define MODEL_naga1b            0x8
#define MODEL_nagare1           0x7
#define MODEL_Default           0x6
#define MODEL_masuku            0x5
#define MODEL_futi              0x4
#define MODEL_yuka              0x3
#define MODEL_saku              0x2
#define MODEL_tennzyou          0x1
#define MODEL_kabe              0x0

