#define MODEL_Root              0x18
#define MODEL_dokan             0x17
#define MODEL_dokan3            0x16
#define MODEL_dokan2            0x15
#define MODEL_dokan1            0x14
#define MODEL_g7                0x13
#define MODEL_sizuku            0x12
#define MODEL_sui               0x11
#define MODEL_mizu              0x10
#define MODEL_g13               0xF
#define MODEL_doa2              0xE
#define MODEL_o47               0xD
#define MODEL_doa1              0xC
#define MODEL_o46               0xB
#define MODEL_o41               0xA
#define MODEL_o40               0x9
#define MODEL_Default           0x8
#define MODEL_dai2              0x7
#define MODEL_dai1              0x6
#define MODEL_saku              0x5
#define MODEL_nasuk             0x4
#define MODEL_yuka              0x3
#define MODEL_tennzyou          0x2
#define MODEL_futi              0x1
#define MODEL_kabe              0x0

