#define MODEL_Root              0x14
#define MODEL_dokan             0x13
#define MODEL_dokan3            0x12
#define MODEL_dokan2            0x11
#define MODEL_dokan1            0x10
#define MODEL_exit_d            0xF
#define MODEL_o95               0xE
#define MODEL_o75               0xD
#define MODEL_g16               0xC
#define MODEL_takib             0xB
#define MODEL_taki              0xA
#define MODEL_sui               0x9
#define MODEL_nagare            0x8
#define MODEL_nagab             0x7
#define MODEL_Default           0x6
#define MODEL_kaidan            0x5
#define MODEL_saku              0x4
#define MODEL_tennzyou          0x3
#define MODEL_futi              0x2
#define MODEL_kabe              0x1
#define MODEL_yuka              0x0

