#define MODEL_Root              0x1C
#define MODEL_dokan             0x1B
#define MODEL_o54               0x1A
#define MODEL_dokan2            0x19
#define MODEL_dokan1            0x18
#define MODEL_g7                0x17
#define MODEL_sizuku            0x16
#define MODEL_ana               0x15
#define MODEL_oku               0x14
#define MODEL_tyka              0x13
#define MODEL_a_kabe            0x12
#define MODEL_sui               0x11
#define MODEL_mizu              0x10
#define MODEL_Default           0xF
#define MODEL_omasuk            0xE
#define MODEL_kagu              0xD
#define MODEL_bin               0xC
#define MODEL_o45               0xB
#define MODEL_o44               0xA
#define MODEL_hako              0x9
#define MODEL_isu2              0x8
#define MODEL_isu1              0x7
#define MODEL_asi               0x6
#define MODEL_kurosu            0x5
#define MODEL_yuka              0x4
#define MODEL_saku              0x3
#define MODEL_tennzyou          0x2
#define MODEL_futi              0x1
#define MODEL_kabe              0x0

