#define MODEL_Root              0x17
#define MODEL_dokan             0x16
#define MODEL_dokan5            0x15
#define MODEL_dokan4            0x14
#define MODEL_dokan3            0x13
#define MODEL_dokan2            0x12
#define MODEL_dokan1            0x11
#define MODEL_g7                0x10
#define MODEL_sizuku            0xF
#define MODEL_exite             0xE
#define MODEL_o52               0xD
#define MODEL_o51               0xC
#define MODEL_sui               0xB
#define MODEL_o59               0xA
#define MODEL_taki              0x9
#define MODEL_nagab             0x8
#define MODEL_nagare            0x7
#define MODEL_Default           0x6
#define MODEL_masuk             0x5
#define MODEL_futi              0x4
#define MODEL_saku              0x3
#define MODEL_tennzyou          0x2
#define MODEL_kabe              0x1
#define MODEL_yuka              0x0

