#define COLLIDER_Root           0x1C
#define COLLIDER_g14            0x1B
#define COLLIDER_sikake         0x1A
#define COLLIDER_o103           0x19
#define COLLIDER_o82            0x18
#define COLLIDER_yuka           0x17
#define COLLIDER_sotokabe       0x16
#define COLLIDER_utikabe        0x15
#define COLLIDER_ana            0x14
#define COLLIDER_tte            0x13
#define COLLIDER_ne             0x12
#define COLLIDER_deilie         0x11
#define COLLIDER_deilite        0x10
#define COLLIDER_kesukabe       0xF
#define COLLIDER_exit3          0xE
#define COLLIDER_nw2            0xD
#define COLLIDER_ttw2           0xC
#define COLLIDER_deiliw2        0xB
#define COLLIDER_deilitw2       0xA
#define COLLIDER_exit2          0x9
#define COLLIDER_nse            0x8
#define COLLIDER_ttse           0x7
#define COLLIDER_deilise        0x6
#define COLLIDER_deilitse       0x5
#define COLLIDER_exit1          0x4
#define COLLIDER_nw             0x3
#define COLLIDER_ttw            0x2
#define COLLIDER_deiliw         0x1
#define COLLIDER_deilitw        0x0

#define ZONE_Root               0x8
#define ZONE_exit2              0x7
#define ZONE_deilie             0x6
#define ZONE_g26                0x5
#define ZONE_yuka2              0x4
#define ZONE_Default            0x3
#define ZONE_yuka               0x2
#define ZONE_exitw              0x1
#define ZONE_deiliw             0x0

