#define COLLIDER_Root           0x2B
#define COLLIDER_g25            0x2A
#define COLLIDER_o87            0x29
#define COLLIDER_o86            0x28
#define COLLIDER_kaidan         0x27
#define COLLIDER_o101           0x26
#define COLLIDER_k_soku         0x25
#define COLLIDER_g1             0x24
#define COLLIDER_o155           0x23
#define COLLIDER_utiwaku        0x22
#define COLLIDER_kabe           0x21
#define COLLIDER_g2             0x20
#define COLLIDER_yuka1          0x1F
#define COLLIDER_dai            0x1E
#define COLLIDER_exite3         0x1D
#define COLLIDER_ne3            0x1C
#define COLLIDER_tte3           0x1B
#define COLLIDER_deilie3        0x1A
#define COLLIDER_deilite3       0x19
#define COLLIDER_exitw3         0x18
#define COLLIDER_nw3            0x17
#define COLLIDER_ttw3           0x16
#define COLLIDER_deiliw3        0x15
#define COLLIDER_deilitw3       0x14
#define COLLIDER_exite2         0x13
#define COLLIDER_ne2            0x12
#define COLLIDER_tte2           0x11
#define COLLIDER_deilie2        0x10
#define COLLIDER_deilite2       0xF
#define COLLIDER_exitw2         0xE
#define COLLIDER_nw2            0xD
#define COLLIDER_ttw2           0xC
#define COLLIDER_deiliw2        0xB
#define COLLIDER_deilitw2       0xA
#define COLLIDER_exite1         0x9
#define COLLIDER_ne             0x8
#define COLLIDER_tte            0x7
#define COLLIDER_deilie         0x6
#define COLLIDER_deilite        0x5
#define COLLIDER_exitw1         0x4
#define COLLIDER_nw             0x3
#define COLLIDER_ttw            0x2
#define COLLIDER_deiliw         0x1
#define COLLIDER_deilitw        0x0

#define ZONE_Root               0x4
#define ZONE_g24                0x3
#define ZONE_o58                0x2
#define ZONE_o57                0x1
#define ZONE_o56                0x0

