#define MODEL_Root              0x51
#define MODEL_g21               0x50
#define MODEL_o95               0x4F
#define MODEL_o94               0x4E
#define MODEL_ana               0x4D
#define MODEL_hibi              0x4C
#define MODEL_an_kabe           0x4B
#define MODEL_doakabe           0x4A
#define MODEL_o75               0x49
#define MODEL_g14               0x48
#define MODEL_o70               0x47
#define MODEL_g13               0x46
#define MODEL_o69               0x45
#define MODEL_doa2              0x44
#define MODEL_o62               0x43
#define MODEL_doa1              0x42
#define MODEL_doa               0x41
#define MODEL_hasi2             0x40
#define MODEL_h2_waku           0x3F
#define MODEL_h2_ue             0x3E
#define MODEL_h2_kiwa           0x3D
#define MODEL_hasi              0x3C
#define MODEL_h_waku            0x3B
#define MODEL_h_ue              0x3A
#define MODEL_h_kiwa            0x39
#define MODEL_saku              0x38
#define MODEL_kusi              0x37
#define MODEL_dai2              0x36
#define MODEL_dai               0x35
#define MODEL_kisi              0x34
#define MODEL_k_waku            0x33
#define MODEL_k_sita            0x32
#define MODEL_k_kiwa            0x31
#define MODEL_miti              0x30
#define MODEL_k_ue              0x2F
#define MODEL_tou2              0x2E
#define MODEL_o105              0x2D
#define MODEL_o104              0x2C
#define MODEL_o103              0x2B
#define MODEL_o102              0x2A
#define MODEL_o108              0x29
#define MODEL_o107              0x28
#define MODEL_o100              0x27
#define MODEL_tou               0x26
#define MODEL_t_yuka            0x25
#define MODEL_t_hasi            0x24
#define MODEL_t_kusa            0x23
#define MODEL_t_waku2           0x22
#define MODEL_t_waku1           0x21
#define MODEL_t_saku3           0x20
#define MODEL_t_saku2           0x1F
#define MODEL_t_saku            0x1E
#define MODEL_g_ue              0x1D
#define MODEL_g_kiwa2           0x1C
#define MODEL_g_kiwa            0x1B
#define MODEL_trd               0x1A
#define MODEL_o_futa2           0x19
#define MODEL_o_futa            0x18
#define MODEL_o_doa             0x17
#define MODEL_o_waku            0x16
#define MODEL_o_yuka            0x15
#define MODEL_waku2             0x14
#define MODEL_waku              0x13
#define MODEL_sita              0x12
#define MODEL_mado              0x11
#define MODEL_kabe              0x10
#define MODEL_kiwa              0xF
#define MODEL_sima              0xE
#define MODEL_yuka3             0xD
#define MODEL_yuka2             0xC
#define MODEL_yuka              0xB
#define MODEL_frame             0xA
#define MODEL_bero3             0x9
#define MODEL_bero2             0x8
#define MODEL_bero              0x7
#define MODEL_o1                0x6
#define MODEL_g24               0x5
#define MODEL_o125              0x4
#define MODEL_o109              0x3
#define MODEL_ue                0x2
#define MODEL_mizu              0x1
#define MODEL_soko              0x0

