#define MODEL_Root              0x2A
#define MODEL_ori               0x29
#define MODEL_o34               0x28
#define MODEL_doa12             0x27
#define MODEL_o29               0x26
#define MODEL_doa11             0x25
#define MODEL_o28               0x24
#define MODEL_doa8              0x23
#define MODEL_o12               0x22
#define MODEL_doa7              0x21
#define MODEL_o13               0x20
#define MODEL_doa6              0x1F
#define MODEL_o11               0x1E
#define MODEL_doa5              0x1D
#define MODEL_o10               0x1C
#define MODEL_doa4              0x1B
#define MODEL_o9                0x1A
#define MODEL_doa3              0x19
#define MODEL_o8                0x18
#define MODEL_doa2              0x17
#define MODEL_o7                0x16
#define MODEL_doa1              0x15
#define MODEL_o6                0x14
#define MODEL_kaidan            0x13
#define MODEL_k_kusari          0x12
#define MODEL_k_dan             0x11
#define MODEL_k_sokumen         0x10
#define MODEL_g1                0xF
#define MODEL_hikari            0xE
#define MODEL_mado              0xD
#define MODEL_kabe              0xC
#define MODEL_g2                0xB
#define MODEL_saku3             0xA
#define MODEL_saku2             0x9
#define MODEL_saku              0x8
#define MODEL_suimen            0x7
#define MODEL_kiwa              0x6
#define MODEL_suityuu           0x5
#define MODEL_yuka1             0x4
#define MODEL_bero2             0x3
#define MODEL_bero              0x2
#define MODEL_f2_soku           0x1
#define MODEL_dai               0x0

