#define MODEL_Root              0x17
#define MODEL_g25               0x16
#define MODEL_o44               0x15
#define MODEL_o52               0x14
#define MODEL_g24               0x13
#define MODEL_o43               0x12
#define MODEL_o51               0x11
#define MODEL_migi              0x10
#define MODEL_o40               0xF
#define MODEL_o39               0xE
#define MODEL_o38               0xD
#define MODEL_hidari            0xC
#define MODEL_o50               0xB
#define MODEL_o49               0xA
#define MODEL_o48               0x9
#define MODEL_kusari1           0x8
#define MODEL_o31               0x7
#define MODEL_g2                0x6
#define MODEL_suimen2           0x5
#define MODEL_suityuu           0x4
#define MODEL_kusari            0x3
#define MODEL_kiwa              0x2
#define MODEL_yuka1             0x1
#define MODEL_kabe              0x0

