#define MODEL_Root              0x1B
#define MODEL_dai               0x1A
#define MODEL_waku1             0x19
#define MODEL_waku3             0x18
#define MODEL_yuka              0x17
#define MODEL_saku              0x16
#define MODEL_g67               0x15
#define MODEL_g69               0x14
#define MODEL_mizu              0x13
#define MODEL_g68               0x12
#define MODEL_mizu2             0x11
#define MODEL_g70               0x10
#define MODEL_o298              0xF
#define MODEL_g71               0xE
#define MODEL_o297              0xD
#define MODEL_kabe2_2           0xC
#define MODEL_kabe2             0xB
#define MODEL_tyuu              0xA
#define MODEL_kiwa              0x9
#define MODEL_waku4             0x8
#define MODEL_waku              0x7
#define MODEL_g59               0x6
#define MODEL_hikari            0x5
#define MODEL_kusari3           0x4
#define MODEL_kusari2           0x3
#define MODEL_kusari1           0x2
#define MODEL_mado              0x1
#define MODEL_kabe1             0x0

