#define MODEL_Root              0x11
#define MODEL_dai               0x10
#define MODEL_waku1             0xF
#define MODEL_yuka              0xE
#define MODEL_g59               0xD
#define MODEL_waku2             0xC
#define MODEL_kusari3           0xB
#define MODEL_kusari2           0xA
#define MODEL_ksari1            0x9
#define MODEL_saku              0x8
#define MODEL_rou               0x7
#define MODEL_o292              0x6
#define MODEL_kai               0x5
#define MODEL_hikari            0x4
#define MODEL_mado              0x3
#define MODEL_waku              0x2
#define MODEL_oku               0x1
#define MODEL_yuka2             0x0

