#define MODEL_Root              0x1E
#define MODEL_dai               0x1D
#define MODEL_g64               0x1C
#define MODEL_o318              0x1B
#define MODEL_g63               0x1A
#define MODEL_mizu4             0x19
#define MODEL_waku1             0x18
#define MODEL_yuka              0x17
#define MODEL_g59               0x16
#define MODEL_waku2             0x15
#define MODEL_ori               0x14
#define MODEL_saku2             0x13
#define MODEL_saku1             0x12
#define MODEL_kusari1           0x11
#define MODEL_kai               0x10
#define MODEL_hako              0xF
#define MODEL_hikari2           0xE
#define MODEL_hikari            0xD
#define MODEL_mado              0xC
#define MODEL_soto              0xB
#define MODEL_yuka3             0xA
#define MODEL_yuka4             0x9
#define MODEL_yuka2             0x8
#define MODEL_g68               0x7
#define MODEL_mizu3             0x6
#define MODEL_g67               0x5
#define MODEL_mizu2             0x4
#define MODEL_g66               0x3
#define MODEL_mizu1             0x2
#define MODEL_oku               0x1
#define MODEL_waku              0x0

