#define COLLIDER_Root           0x1D
#define COLLIDER_exit4          0x1C
#define COLLIDER_ne3            0x1B
#define COLLIDER_tte3           0x1A
#define COLLIDER_deilie3        0x19
#define COLLIDER_deilite3       0x18
#define COLLIDER_exit3          0x17
#define COLLIDER_ne2            0x16
#define COLLIDER_tte2           0x15
#define COLLIDER_deilie2        0x14
#define COLLIDER_deilite2       0x13
#define COLLIDER_exit2          0x12
#define COLLIDER_ne             0x11
#define COLLIDER_tte            0x10
#define COLLIDER_deilie         0xF
#define COLLIDER_deilite        0xE
#define COLLIDER_exitw          0xD
#define COLLIDER_nw             0xC
#define COLLIDER_ttw            0xB
#define COLLIDER_deiliw         0xA
#define COLLIDER_deilitw        0x9
#define COLLIDER_kaidan         0x8
#define COLLIDER_o158           0x7
#define COLLIDER_o157           0x6
#define COLLIDER_Default        0x5
#define COLLIDER_hako           0x4
#define COLLIDER_g25            0x3
#define COLLIDER_o162           0x2
#define COLLIDER_utikabe        0x1
#define COLLIDER_kabe           0x0

#define ZONE_Root               0x8
#define ZONE_exit2              0x7
#define ZONE_deilie             0x6
#define ZONE_g26                0x5
#define ZONE_yuka2              0x4
#define ZONE_Default            0x3
#define ZONE_yuka               0x2
#define ZONE_exitw              0x1
#define ZONE_deiliw             0x0

