#define MODEL_Root              0x14
#define MODEL_doa8              0x13
#define MODEL_o60               0x12
#define MODEL_doa7              0x11
#define MODEL_o65               0x10
#define MODEL_doa4              0xF
#define MODEL_o63               0xE
#define MODEL_doa3              0xD
#define MODEL_o67               0xC
#define MODEL_g13               0xB
#define MODEL_mado              0xA
#define MODEL_yuka              0x9
#define MODEL_kabe              0x8
#define MODEL_Default           0x7
#define MODEL_saku3             0x6
#define MODEL_saku2             0x5
#define MODEL_sku1              0x4
#define MODEL_okuyuki           0x3
#define MODEL_doa_naka          0x2
#define MODEL_o76               0x1
#define MODEL_o75               0x0

