#define MODEL_Root              0x3A
#define MODEL_exit4             0x39
#define MODEL_o100              0x38
#define MODEL_o99               0x37
#define MODEL_doa8              0x36
#define MODEL_e4_doa2           0x35
#define MODEL_doa7              0x34
#define MODEL_e4_doa            0x33
#define MODEL_exit3             0x32
#define MODEL_o97               0x31
#define MODEL_o96               0x30
#define MODEL_doa6              0x2F
#define MODEL_e3_doa2           0x2E
#define MODEL_doa5              0x2D
#define MODEL_e3_doa            0x2C
#define MODEL_exit2             0x2B
#define MODEL_o88               0x2A
#define MODEL_o87               0x29
#define MODEL_doa4              0x28
#define MODEL_e2_doa2           0x27
#define MODEL_doa3              0x26
#define MODEL_e2_doa            0x25
#define MODEL_exitw             0x24
#define MODEL_deiliw            0x23
#define MODEL_nw                0x22
#define MODEL_doa2              0x21
#define MODEL_ew_doa2           0x20
#define MODEL_doa1              0x1F
#define MODEL_ew_doa            0x1E
#define MODEL_etc               0x1D
#define MODEL_saku3             0x1C
#define MODEL_saku2             0x1B
#define MODEL_kusari            0x1A
#define MODEL_saku              0x19
#define MODEL_g34               0x18
#define MODEL_o145              0x17
#define MODEL_sui               0x16
#define MODEL_sui2              0x15
#define MODEL_sui1              0x14
#define MODEL_suimenn           0x13
#define MODEL_Default           0x12
#define MODEL_m_saku            0x11
#define MODEL_m_soko            0x10
#define MODEL_suityu            0xF
#define MODEL_mado3             0xE
#define MODEL_mado2             0xD
#define MODEL_mado1             0xC
#define MODEL_hako              0xB
#define MODEL_m_kiwa            0xA
#define MODEL_soku              0x9
#define MODEL_yuka              0x8
#define MODEL_kabe              0x7
#define MODEL_move_saku         0x6
#define MODEL_o141              0x5
#define MODEL_o134              0x4
#define MODEL_kaidan            0x3
#define MODEL_k_kusari          0x2
#define MODEL_k_soku            0x1
#define MODEL_dan               0x0

