#define MODEL_Root              0x37
#define MODEL_g42               0x36
#define MODEL_g49               0x35
#define MODEL_kusari2           0x34
#define MODEL_kusari            0x33
#define MODEL_soku              0x32
#define MODEL_saku              0x31
#define MODEL_yuka              0x30
#define MODEL_kabe              0x2F
#define MODEL_exitw             0x2E
#define MODEL_deilitw           0x2D
#define MODEL_deiliw            0x2C
#define MODEL_nw                0x2B
#define MODEL_doa4              0x2A
#define MODEL_o192              0x29
#define MODEL_doa3              0x28
#define MODEL_o191              0x27
#define MODEL_nise_koppa        0x26
#define MODEL_koma2             0x25
#define MODEL_km2               0x24
#define MODEL_koma1             0x23
#define MODEL_km1               0x22
#define MODEL_ashi              0x21
#define MODEL_o165              0x20
#define MODEL_o120              0x1F
#define MODEL_o118              0x1E
#define MODEL_right_arm         0x1D
#define MODEL_o183              0x1C
#define MODEL_o172              0x1B
#define MODEL_o171              0x1A
#define MODEL_dou               0x19
#define MODEL_d3                0x18
#define MODEL_d2                0x17
#define MODEL_d1                0x16
#define MODEL_koura             0x15
#define MODEL_s5                0x14
#define MODEL_s4                0x13
#define MODEL_s3                0x12
#define MODEL_s2                0x11
#define MODEL_s1                0x10
#define MODEL_atama             0xF
#define MODEL_k9                0xE
#define MODEL_k8                0xD
#define MODEL_k7                0xC
#define MODEL_k6                0xB
#define MODEL_k5                0xA
#define MODEL_k4                0x9
#define MODEL_k3                0x8
#define MODEL_k2                0x7
#define MODEL_k1                0x6
#define MODEL_left_arm          0x5
#define MODEL_u3                0x4
#define MODEL_u2                0x3
#define MODEL_u1                0x2
#define MODEL_shippo            0x1
#define MODEL_p1                0x0

