#define COLLIDER_Root           0x1F
#define COLLIDER_g9             0x1E
#define COLLIDER_tou            0x1D
#define COLLIDER_4_2            0x1C
#define COLLIDER_4              0x1B
#define COLLIDER_3              0x1A
#define COLLIDER_2              0x19
#define COLLIDER_o112           0x18
#define COLLIDER_1              0x17
#define COLLIDER_ana            0x16
#define COLLIDER_o83            0x15
#define COLLIDER_tt5            0x14
#define COLLIDER_deili5         0x13
#define COLLIDER_deilit5        0x12
#define COLLIDER_exitt          0x11
#define COLLIDER_nt             0x10
#define COLLIDER_deilit         0xF
#define COLLIDER_deilitt        0xE
#define COLLIDER_exit3          0xD
#define COLLIDER_o92            0xC
#define COLLIDER_tt3            0xB
#define COLLIDER_deili3         0xA
#define COLLIDER_deilit3        0x9
#define COLLIDER_exit2          0x8
#define COLLIDER_o87            0x7
#define COLLIDER_tt2            0x6
#define COLLIDER_deili2         0x5
#define COLLIDER_deilit2        0x4
#define COLLIDER_exit           0x3
#define COLLIDER_o89            0x2
#define COLLIDER_deiliw         0x1
#define COLLIDER_deilitw        0x0

#define ZONE_Root               0x7
#define ZONE_frame              0x6
#define ZONE_tou                0x5
#define ZONE_yuka3              0x4
#define ZONE_yuka2              0x3
#define ZONE_yuka               0x2
#define ZONE_k_ue               0x1
#define ZONE_bero               0x0

