#define MODEL_Root              0x29
#define MODEL_doa8              0x28
#define MODEL_o12               0x27
#define MODEL_doa7              0x26
#define MODEL_o13               0x25
#define MODEL_doa6              0x24
#define MODEL_o11               0x23
#define MODEL_doa5              0x22
#define MODEL_o10               0x21
#define MODEL_doa4              0x20
#define MODEL_o9                0x1F
#define MODEL_doa3              0x1E
#define MODEL_o8                0x1D
#define MODEL_doa2              0x1C
#define MODEL_o7                0x1B
#define MODEL_doa1              0x1A
#define MODEL_o6                0x19
#define MODEL_kaidan            0x18
#define MODEL_kusari            0x17
#define MODEL_dan               0x16
#define MODEL_k_soku            0x15
#define MODEL_ana               0x14
#define MODEL_g14               0x13
#define MODEL_hibi              0x12
#define MODEL_futa              0x11
#define MODEL_oku               0x10
#define MODEL_anaaki            0xF
#define MODEL_g1                0xE
#define MODEL_hikari            0xD
#define MODEL_mado              0xC
#define MODEL_kabe              0xB
#define MODEL_move_saku         0xA
#define MODEL_o32               0x9
#define MODEL_g2                0x8
#define MODEL_saku3             0x7
#define MODEL_saku2             0x6
#define MODEL_saku              0x5
#define MODEL_yuka1             0x4
#define MODEL_bero2             0x3
#define MODEL_bero              0x2
#define MODEL_f2_soku           0x1
#define MODEL_dai               0x0

