#define COLLIDER_Root           0x3D
#define COLLIDER_g1             0x3C
#define COLLIDER_o75            0x3B
#define COLLIDER_o74            0x3A
#define COLLIDER_o73            0x39
#define COLLIDER_ori3           0x38
#define COLLIDER_ori2           0x37
#define COLLIDER_ori1           0x36
#define COLLIDER_4              0x35
#define COLLIDER_3              0x34
#define COLLIDER_2              0x33
#define COLLIDER_1              0x32
#define COLLIDER_g2             0x31
#define COLLIDER_rou3           0x30
#define COLLIDER_rou2           0x2F
#define COLLIDER_rou            0x2E
#define COLLIDER_kabe3          0x2D
#define COLLIDER_kabe2          0x2C
#define COLLIDER_kabe           0x2B
#define COLLIDER_kaidan         0x2A
#define COLLIDER_yuka3          0x29
#define COLLIDER_yuka2          0x28
#define COLLIDER_yuka           0x27
#define COLLIDER_sukim2         0x26
#define COLLIDER_o85            0x25
#define COLLIDER_sukim1         0x24
#define COLLIDER_o84            0x23
#define COLLIDER_ana3           0x22
#define COLLIDER_n3             0x21
#define COLLIDER_tt3            0x20
#define COLLIDER_deili3         0x1F
#define COLLIDER_deilit3        0x1E
#define COLLIDER_ana2           0x1D
#define COLLIDER_n2             0x1C
#define COLLIDER_tt2            0x1B
#define COLLIDER_deili2         0x1A
#define COLLIDER_deilit2        0x19
#define COLLIDER_ana1           0x18
#define COLLIDER_n1             0x17
#define COLLIDER_tt1            0x16
#define COLLIDER_deili1         0x15
#define COLLIDER_deilit1        0x14
#define COLLIDER_exit4          0x13
#define COLLIDER_nwo            0x12
#define COLLIDER_ttwo           0x11
#define COLLIDER_deiliwo        0x10
#define COLLIDER_deilitwo       0xF
#define COLLIDER_exit3          0xE
#define COLLIDER_neo            0xD
#define COLLIDER_tteo           0xC
#define COLLIDER_deilieo        0xB
#define COLLIDER_deiliteo       0xA
#define COLLIDER_exit2          0x9
#define COLLIDER_ne             0x8
#define COLLIDER_tte            0x7
#define COLLIDER_deilie         0x6
#define COLLIDER_deilite        0x5
#define COLLIDER_exit1          0x4
#define COLLIDER_nw             0x3
#define COLLIDER_ttw            0x2
#define COLLIDER_deiliw         0x1
#define COLLIDER_deilitw        0x0

#define ZONE_Root               0x6
#define ZONE_f2                 0x5
#define ZONE_yuka2              0x4
#define ZONE_f1                 0x3
#define ZONE_yuka               0x2
#define ZONE_exite              0x1
#define ZONE_exitw              0x0

