#define MODEL_Root              0x13
#define MODEL_g4                0x12
#define MODEL_o17               0x11
#define MODEL_g1                0x10
#define MODEL_5b                0xF
#define MODEL_4b                0xE
#define MODEL_3b                0xD
#define MODEL_10a               0xC
#define MODEL_9a                0xB
#define MODEL_8a                0xA
#define MODEL_7a                0x9
#define MODEL_6a                0x8
#define MODEL_5a                0x7
#define MODEL_4a                0x6
#define MODEL_3a                0x5
#define MODEL_2                 0x4
#define MODEL_1                 0x3
#define MODEL_g3                0x2
#define MODEL_o10               0x1
#define MODEL_o9                0x0

