#define COLLIDER_Root           0x10
#define COLLIDER_Default        0xF
#define COLLIDER_change         0xE
#define COLLIDER_stage          0xD
#define COLLIDER_7              0xC
#define COLLIDER_deiliw         0xB
#define COLLIDER_o134           0xA
#define COLLIDER_5              0x9
#define COLLIDER_deilis         0x8
#define COLLIDER_o138           0x7
#define COLLIDER_3              0x6
#define COLLIDER_deilie         0x5
#define COLLIDER_o132           0x4
#define COLLIDER_1              0x3
#define COLLIDER_deilitn        0x2
#define COLLIDER_deilin         0x1
#define COLLIDER_o136           0x0

#define ZONE_Root               0x13
#define ZONE_enter_cam          0x12
#define ZONE_south              0x11
#define ZONE_north              0x10
#define ZONE_west               0xF
#define ZONE_east               0xE
#define ZONE_Default            0xD
#define ZONE_higashi            0xC
#define ZONE_nishi              0xB
#define ZONE_kita               0xA
#define ZONE_minami             0x9
#define ZONE_stage              0x8
#define ZONE_7                  0x7
#define ZONE_o135               0x6
#define ZONE_5                  0x5
#define ZONE_o139               0x4
#define ZONE_3                  0x3
#define ZONE_o133               0x2
#define ZONE_1                  0x1
#define ZONE_o137               0x0

