#define COLLIDER_Root           0x15
#define COLLIDER_g7             0x14
#define COLLIDER_o19            0x13
#define COLLIDER_o17            0x12
#define COLLIDER_o16            0x11
#define COLLIDER_o20            0x10
#define COLLIDER_deilite        0xF
#define COLLIDER_deilie         0xE
#define COLLIDER_o21            0xD
#define COLLIDER_deilitw        0xC
#define COLLIDER_deiliw         0xB
#define COLLIDER_g1             0xA
#define COLLIDER_g5             0x9
#define COLLIDER_o5             0x8
#define COLLIDER_g4             0x7
#define COLLIDER_g6             0x6
#define COLLIDER_o3             0x5
#define COLLIDER_o4             0x4
#define COLLIDER_g2             0x3
#define COLLIDER_o18            0x2
#define COLLIDER_o2             0x1
#define COLLIDER_o1             0x0

#define ZONE_Root               0x5
#define ZONE_g7                 0x4
#define ZONE_o17                0x3
#define ZONE_o16                0x2
#define ZONE_deilie             0x1
#define ZONE_deiliw             0x0

