#define MODEL_Root              0x1E
#define MODEL_enter_cam         0x1D
#define MODEL_south             0x1C
#define MODEL_north             0x1B
#define MODEL_west              0x1A
#define MODEL_east              0x19
#define MODEL_g32               0x18
#define MODEL_o166              0x17
#define MODEL_o165              0x16
#define MODEL_Default           0x15
#define MODEL_o167              0x14
#define MODEL_higashi           0x13
#define MODEL_nishi             0x12
#define MODEL_kita              0x11
#define MODEL_minami            0x10
#define MODEL_maru              0xF
#define MODEL_stage             0xE
#define MODEL_7                 0xD
#define MODEL_o135              0xC
#define MODEL_o134              0xB
#define MODEL_5                 0xA
#define MODEL_o139              0x9
#define MODEL_o138              0x8
#define MODEL_3                 0x7
#define MODEL_o133              0x6
#define MODEL_o132              0x5
#define MODEL_1                 0x4
#define MODEL_o137              0x3
#define MODEL_o136              0x2
#define MODEL_g1                0x1
#define MODEL_frame             0x0

