#define COLLIDER_Root           0x20
#define COLLIDER_tukaeruyo      0x1F
#define COLLIDER_o51            0x1E
#define COLLIDER_o34            0x1D
#define COLLIDER_g1             0x1C
#define COLLIDER_deili5b        0x1B
#define COLLIDER_5b             0x1A
#define COLLIDER_deili4b        0x19
#define COLLIDER_4b             0x18
#define COLLIDER_deili3b        0x17
#define COLLIDER_3b             0x16
#define COLLIDER_deili10a       0x15
#define COLLIDER_10a            0x14
#define COLLIDER_deili9a        0x13
#define COLLIDER_9a             0x12
#define COLLIDER_deili8a        0x11
#define COLLIDER_8a             0x10
#define COLLIDER_deili7a        0xF
#define COLLIDER_7a             0xE
#define COLLIDER_deili6a        0xD
#define COLLIDER_6a             0xC
#define COLLIDER_deili5a        0xB
#define COLLIDER_5a             0xA
#define COLLIDER_deili4a        0x9
#define COLLIDER_4a             0x8
#define COLLIDER_deili3a        0x7
#define COLLIDER_3a             0x6
#define COLLIDER_deili2         0x5
#define COLLIDER_2              0x4
#define COLLIDER_deili1         0x3
#define COLLIDER_1              0x2
#define COLLIDER_g3             0x1
#define COLLIDER_o10            0x0

#define ZONE_Root               0x2
#define ZONE_g3                 0x1
#define ZONE_o10                0x0

