#define MODEL_Root              0x13
#define MODEL_g7                0x12
#define MODEL_o17               0x11
#define MODEL_o16               0x10
#define MODEL_o14               0xF
#define MODEL_o11               0xE
#define MODEL_o10               0xD
#define MODEL_o9                0xC
#define MODEL_o8                0xB
#define MODEL_g1                0xA
#define MODEL_g5                0x9
#define MODEL_o5                0x8
#define MODEL_g4                0x7
#define MODEL_g6                0x6
#define MODEL_o3                0x5
#define MODEL_o4                0x4
#define MODEL_g2                0x3
#define MODEL_o18               0x2
#define MODEL_o2                0x1
#define MODEL_o1                0x0

