.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
glabel D_pause_80272380
/* 1671C0 80272380 3FC999999999999A */ .double 0.200000000000000011
/* 1671C8 80272388 00000000 */ .double 0


.section .text
/* Generated by spimdisasm 1.11.1 */

glabel pause_badges_draw_contents
/* 140378 8024B538 27BDFF40 */  addiu      $sp, $sp, -0xC0
/* 14037C 8024B53C 240A0001 */  addiu      $t2, $zero, 0x1
/* 140380 8024B540 3C028027 */  lui        $v0, %hi(gPauseBadgesCurrentPage)
/* 140384 8024B544 8C422650 */  lw         $v0, %lo(gPauseBadgesCurrentPage)($v0)
/* 140388 8024B548 3C038027 */  lui        $v1, %hi(gPauseBadgesPages)
/* 14038C 8024B54C 24632658 */  addiu      $v1, $v1, %lo(gPauseBadgesPages)
/* 140390 8024B550 AFBF00BC */  sw         $ra, 0xBC($sp)
/* 140394 8024B554 AFBE00B8 */  sw         $fp, 0xB8($sp)
/* 140398 8024B558 AFB700B4 */  sw         $s7, 0xB4($sp)
/* 14039C 8024B55C AFB600B0 */  sw         $s6, 0xB0($sp)
/* 1403A0 8024B560 AFB500AC */  sw         $s5, 0xAC($sp)
/* 1403A4 8024B564 AFB400A8 */  sw         $s4, 0xA8($sp)
/* 1403A8 8024B568 AFB300A4 */  sw         $s3, 0xA4($sp)
/* 1403AC 8024B56C AFB200A0 */  sw         $s2, 0xA0($sp)
/* 1403B0 8024B570 AFB1009C */  sw         $s1, 0x9C($sp)
/* 1403B4 8024B574 AFB00098 */  sw         $s0, 0x98($sp)
/* 1403B8 8024B578 AFA500C4 */  sw         $a1, 0xC4($sp)
/* 1403BC 8024B57C AFA600C8 */  sw         $a2, 0xC8($sp)
/* 1403C0 8024B580 AFA700CC */  sw         $a3, 0xCC($sp)
/* 1403C4 8024B584 AFA00070 */  sw         $zero, 0x70($sp)
/* 1403C8 8024B588 AFA00074 */  sw         $zero, 0x74($sp)
/* 1403CC 8024B58C AFAA0064 */  sw         $t2, 0x64($sp)
/* 1403D0 8024B590 01428004 */  sllv       $s0, $v0, $t2
/* 1403D4 8024B594 02028021 */  addu       $s0, $s0, $v0
/* 1403D8 8024B598 00108080 */  sll        $s0, $s0, 2
/* 1403DC 8024B59C 0C0921C1 */  jal        pause_get_total_equipped_bp_cost
/* 1403E0 8024B5A0 02038021 */   addu      $s0, $s0, $v1
/* 1403E4 8024B5A4 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 1403E8 8024B5A8 92090002 */  lbu        $t1, 0x2($s0)
/* 1403EC 8024B5AC 8FAA00CC */  lw         $t2, 0xCC($sp)
/* 1403F0 8024B5B0 25660054 */  addiu      $a2, $t3, 0x54
/* 1403F4 8024B5B4 8FAB00D0 */  lw         $t3, 0xD0($sp)
/* 1403F8 8024B5B8 2543FFAC */  addiu      $v1, $t2, -0x54
/* 1403FC 8024B5BC AFA30014 */  sw         $v1, 0x14($sp)
/* 140400 8024B5C0 240300FF */  addiu      $v1, $zero, 0xFF
/* 140404 8024B5C4 AFA3001C */  sw         $v1, 0x1C($sp)
/* 140408 8024B5C8 24030140 */  addiu      $v1, $zero, 0x140
/* 14040C 8024B5CC AFA30044 */  sw         $v1, 0x44($sp)
/* 140410 8024B5D0 240300F0 */  addiu      $v1, $zero, 0xF0
/* 140414 8024B5D4 AFA30048 */  sw         $v1, 0x48($sp)
/* 140418 8024B5D8 3C038027 */  lui        $v1, %hi(gPauseBadgesSelectedIndex)
/* 14041C 8024B5DC 8C632748 */  lw         $v1, %lo(gPauseBadgesSelectedIndex)($v1)
/* 140420 8024B5E0 AFAB0018 */  sw         $t3, 0x18($sp)
/* 140424 8024B5E4 15200002 */  bnez       $t1, .Lpause_8024B5F0
/* 140428 8024B5E8 0069001A */   div       $zero, $v1, $t1
/* 14042C 8024B5EC 0007000D */  break      7
.Lpause_8024B5F0:
/* 140430 8024B5F0 2401FFFF */  addiu      $at, $zero, -0x1
/* 140434 8024B5F4 15210004 */  bne        $t1, $at, .Lpause_8024B608
/* 140438 8024B5F8 3C018000 */   lui       $at, (0x80000000 >> 16)
/* 14043C 8024B5FC 14610002 */  bne        $v1, $at, .Lpause_8024B608
/* 140440 8024B600 00000000 */   nop
/* 140444 8024B604 0006000D */  break      6
.Lpause_8024B608:
/* 140448 8024B608 00005012 */  mflo       $t2
/* 14044C 8024B60C 00005810 */  mfhi       $t3
/* 140450 8024B610 24040004 */  addiu      $a0, $zero, 0x4
/* 140454 8024B614 8FA700C8 */  lw         $a3, 0xC8($sp)
/* 140458 8024B618 3C088011 */  lui        $t0, %hi(gPlayerData+0x8)
/* 14045C 8024B61C 8108DD98 */  lb         $t0, %lo(gPlayerData+0x8)($t0)
/* 140460 8024B620 3C058027 */  lui        $a1, %hi(gPauseWS_15)
/* 140464 8024B624 24A52018 */  addiu      $a1, $a1, %lo(gPauseWS_15)
/* 140468 8024B628 AFA00010 */  sw         $zero, 0x10($sp)
/* 14046C 8024B62C AFA00020 */  sw         $zero, 0x20($sp)
/* 140470 8024B630 AFA00024 */  sw         $zero, 0x24($sp)
/* 140474 8024B634 AFA00028 */  sw         $zero, 0x28($sp)
/* 140478 8024B638 AFA0002C */  sw         $zero, 0x2C($sp)
/* 14047C 8024B63C AFA00030 */  sw         $zero, 0x30($sp)
/* 140480 8024B640 AFA00034 */  sw         $zero, 0x34($sp)
/* 140484 8024B644 AFA00038 */  sw         $zero, 0x38($sp)
/* 140488 8024B648 AFA0003C */  sw         $zero, 0x3C($sp)
/* 14048C 8024B64C AFA00040 */  sw         $zero, 0x40($sp)
/* 140490 8024B650 AFA0004C */  sw         $zero, 0x4C($sp)
/* 140494 8024B654 01024023 */  subu       $t0, $t0, $v0
/* 140498 8024B658 AFA8006C */  sw         $t0, 0x6C($sp)
/* 14049C 8024B65C AFAA0060 */  sw         $t2, 0x60($sp)
/* 1404A0 8024B660 0C03C5C4 */  jal        draw_box
/* 1404A4 8024B664 AFAB005C */   sw        $t3, 0x5C($sp)
/* 1404A8 8024B668 3C108027 */  lui        $s0, %hi(gPauseBadgesIconIDs)
/* 1404AC 8024B66C 26102778 */  addiu      $s0, $s0, %lo(gPauseBadgesIconIDs)
/* 1404B0 8024B670 8FAA00C4 */  lw         $t2, 0xC4($sp)
/* 1404B4 8024B674 8E040050 */  lw         $a0, 0x50($s0)
/* 1404B8 8024B678 8FAB00C8 */  lw         $t3, 0xC8($sp)
/* 1404BC 8024B67C 254500F1 */  addiu      $a1, $t2, 0xF1
/* 1404C0 8024B680 0C050D4D */  jal        hud_element_set_render_pos
/* 1404C4 8024B684 2566000B */   addiu     $a2, $t3, 0xB
/* 1404C8 8024B688 8E040050 */  lw         $a0, 0x50($s0)
/* 1404CC 8024B68C 240A000A */  addiu      $t2, $zero, 0xA
/* 1404D0 8024B690 0C050CE4 */  jal        hud_element_draw_without_clipping
/* 1404D4 8024B694 AFAA0068 */   sw        $t2, 0x68($sp)
/* 1404D8 8024B698 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 1404DC 8024B69C 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 1404E0 8024B6A0 2546000E */  addiu      $a2, $t2, 0xE
/* 1404E4 8024B6A4 8FAA00CC */  lw         $t2, 0xCC($sp)
/* 1404E8 8024B6A8 25640001 */  addiu      $a0, $t3, 0x1
/* 1404EC 8024B6AC 016A1021 */  addu       $v0, $t3, $t2
/* 1404F0 8024B6B0 8FAB00C8 */  lw         $t3, 0xC8($sp)
/* 1404F4 8024B6B4 8FAA00D0 */  lw         $t2, 0xD0($sp)
/* 1404F8 8024B6B8 2447FFFF */  addiu      $a3, $v0, -0x1
/* 1404FC 8024B6BC 016A1021 */  addu       $v0, $t3, $t2
/* 140500 8024B6C0 1C800002 */  bgtz       $a0, .Lpause_8024B6CC
/* 140504 8024B6C4 2448FFF7 */   addiu     $t0, $v0, -0x9
/* 140508 8024B6C8 24040001 */  addiu      $a0, $zero, 0x1
.Lpause_8024B6CC:
/* 14050C 8024B6CC 58C00001 */  blezl      $a2, .Lpause_8024B6D4
/* 140510 8024B6D0 24060001 */   addiu     $a2, $zero, 0x1
.Lpause_8024B6D4:
/* 140514 8024B6D4 18E005F6 */  blez       $a3, .Lpause_8024CEB0
/* 140518 8024B6D8 00000000 */   nop
/* 14051C 8024B6DC 190005F4 */  blez       $t0, .Lpause_8024CEB0
/* 140520 8024B6E0 2882013F */   slti      $v0, $a0, 0x13F
/* 140524 8024B6E4 104005F2 */  beqz       $v0, .Lpause_8024CEB0
/* 140528 8024B6E8 28C200EF */   slti      $v0, $a2, 0xEF
/* 14052C 8024B6EC 104005F0 */  beqz       $v0, .Lpause_8024CEB0
/* 140530 8024B6F0 28E2013F */   slti      $v0, $a3, 0x13F
/* 140534 8024B6F4 50400001 */  beql       $v0, $zero, .Lpause_8024B6FC
/* 140538 8024B6F8 2407013F */   addiu     $a3, $zero, 0x13F
.Lpause_8024B6FC:
/* 14053C 8024B6FC 290200EF */  slti       $v0, $t0, 0xEF
/* 140540 8024B700 50400001 */  beql       $v0, $zero, .Lpause_8024B708
/* 140544 8024B704 240800EF */   addiu     $t0, $zero, 0xEF
.Lpause_8024B708:
/* 140548 8024B708 3C038009 */  lui        $v1, %hi(gMainGfxPos)
/* 14054C 8024B70C 24636A44 */  addiu      $v1, $v1, %lo(gMainGfxPos)
/* 140550 8024B710 44841000 */  mtc1       $a0, $f2
/* 140554 8024B714 00000000 */  nop
/* 140558 8024B718 468010A0 */  cvt.s.w    $f2, $f2
/* 14055C 8024B71C 44860000 */  mtc1       $a2, $f0
/* 140560 8024B720 00000000 */  nop
/* 140564 8024B724 46800020 */  cvt.s.w    $f0, $f0
/* 140568 8024B728 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 14056C 8024B72C 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 140570 8024B730 3C014080 */  lui        $at, (0x40800000 >> 16)
/* 140574 8024B734 44812000 */  mtc1       $at, $f4
/* 140578 8024B738 3C04ED00 */  lui        $a0, (0xED000000 >> 16)
/* 14057C 8024B73C AFA00058 */  sw         $zero, 0x58($sp)
/* 140580 8024B740 AFA00054 */  sw         $zero, 0x54($sp)
/* 140584 8024B744 256B0077 */  addiu      $t3, $t3, 0x77
/* 140588 8024B748 46041082 */  mul.s      $f2, $f2, $f4
/* 14058C 8024B74C 00000000 */  nop
/* 140590 8024B750 254A0011 */  addiu      $t2, $t2, 0x11
/* 140594 8024B754 AFAB007C */  sw         $t3, 0x7C($sp)
/* 140598 8024B758 AFAA0080 */  sw         $t2, 0x80($sp)
/* 14059C 8024B75C 8C620000 */  lw         $v0, 0x0($v1)
/* 1405A0 8024B760 46040002 */  mul.s      $f0, $f0, $f4
/* 1405A4 8024B764 00000000 */  nop
/* 1405A8 8024B768 0040282D */  daddu      $a1, $v0, $zero
/* 1405AC 8024B76C 24420008 */  addiu      $v0, $v0, 0x8
/* 1405B0 8024B770 AC620000 */  sw         $v0, 0x0($v1)
/* 1405B4 8024B774 4600118D */  trunc.w.s  $f6, $f2
/* 1405B8 8024B778 44023000 */  mfc1       $v0, $f6
/* 1405BC 8024B77C 00000000 */  nop
/* 1405C0 8024B780 30420FFF */  andi       $v0, $v0, 0xFFF
/* 1405C4 8024B784 00021300 */  sll        $v0, $v0, 12
/* 1405C8 8024B788 4600018D */  trunc.w.s  $f6, $f0
/* 1405CC 8024B78C 44033000 */  mfc1       $v1, $f6
/* 1405D0 8024B790 44871000 */  mtc1       $a3, $f2
/* 1405D4 8024B794 00000000 */  nop
/* 1405D8 8024B798 468010A0 */  cvt.s.w    $f2, $f2
/* 1405DC 8024B79C 46041082 */  mul.s      $f2, $f2, $f4
/* 1405E0 8024B7A0 00000000 */  nop
/* 1405E4 8024B7A4 30630FFF */  andi       $v1, $v1, 0xFFF
/* 1405E8 8024B7A8 00641825 */  or         $v1, $v1, $a0
/* 1405EC 8024B7AC 00431025 */  or         $v0, $v0, $v1
/* 1405F0 8024B7B0 44880000 */  mtc1       $t0, $f0
/* 1405F4 8024B7B4 00000000 */  nop
/* 1405F8 8024B7B8 46800020 */  cvt.s.w    $f0, $f0
/* 1405FC 8024B7BC 46040002 */  mul.s      $f0, $f0, $f4
/* 140600 8024B7C0 00000000 */  nop
/* 140604 8024B7C4 ACA20000 */  sw         $v0, 0x0($a1)
/* 140608 8024B7C8 4600118D */  trunc.w.s  $f6, $f2
/* 14060C 8024B7CC 44023000 */  mfc1       $v0, $f6
/* 140610 8024B7D0 00000000 */  nop
/* 140614 8024B7D4 30420FFF */  andi       $v0, $v0, 0xFFF
/* 140618 8024B7D8 00021300 */  sll        $v0, $v0, 12
/* 14061C 8024B7DC 4600018D */  trunc.w.s  $f6, $f0
/* 140620 8024B7E0 44033000 */  mfc1       $v1, $f6
/* 140624 8024B7E4 00000000 */  nop
/* 140628 8024B7E8 30630FFF */  andi       $v1, $v1, 0xFFF
/* 14062C 8024B7EC 00431025 */  or         $v0, $v0, $v1
/* 140630 8024B7F0 ACA20004 */  sw         $v0, 0x4($a1)
.Lpause_8024B7F4:
/* 140634 8024B7F4 AFA00050 */  sw         $zero, 0x50($sp)
.Lpause_8024B7F8:
/* 140638 8024B7F8 8FAB0050 */  lw         $t3, 0x50($sp)
/* 14063C 8024B7FC 3C028027 */  lui        $v0, %hi(gPauseBadgesPages)
/* 140640 8024B800 24422658 */  addiu      $v0, $v0, %lo(gPauseBadgesPages)
/* 140644 8024B804 000B1840 */  sll        $v1, $t3, 1
/* 140648 8024B808 006B1821 */  addu       $v1, $v1, $t3
/* 14064C 8024B80C 00031880 */  sll        $v1, $v1, 2
/* 140650 8024B810 00621821 */  addu       $v1, $v1, $v0
/* 140654 8024B814 AFA30078 */  sw         $v1, 0x78($sp)
/* 140658 8024B818 90620000 */  lbu        $v0, 0x0($v1)
/* 14065C 8024B81C 10400261 */  beqz       $v0, .Lpause_8024C1A4
/* 140660 8024B820 0160202D */   daddu     $a0, $t3, $zero
/* 140664 8024B824 0C092C66 */  jal        pause_badges_get_pos_y
/* 140668 8024B828 0000282D */   daddu     $a1, $zero, $zero
/* 14066C 8024B82C 8FAA0078 */  lw         $t2, 0x78($sp)
/* 140670 8024B830 8D420008 */  lw         $v0, 0x8($t2)
/* 140674 8024B834 18400256 */  blez       $v0, .Lpause_8024C190
/* 140678 8024B838 0000F02D */   daddu     $fp, $zero, $zero
/* 14067C 8024B83C 3C0BE3E3 */  lui        $t3, (0xE3E3E3FF >> 16)
/* 140680 8024B840 356BE3FF */  ori        $t3, $t3, (0xE3E3E3FF & 0xFFFF)
/* 140684 8024B844 AFAB0090 */  sw         $t3, 0x90($sp)
/* 140688 8024B848 3C0A6666 */  lui        $t2, (0x66666667 >> 16)
/* 14068C 8024B84C 354A6667 */  ori        $t2, $t2, (0x66666667 & 0xFFFF)
/* 140690 8024B850 AFAA0094 */  sw         $t2, 0x94($sp)
.Lpause_8024B854:
/* 140694 8024B854 8FAB0078 */  lw         $t3, 0x78($sp)
/* 140698 8024B858 3C128011 */  lui        $s2, %hi(gPlayerData+0x208)
/* 14069C 8024B85C 2652DF98 */  addiu      $s2, $s2, %lo(gPlayerData+0x208)
/* 1406A0 8024B860 AFA00084 */  sw         $zero, 0x84($sp)
/* 1406A4 8024B864 8D620004 */  lw         $v0, 0x4($t3)
/* 1406A8 8024B868 24037FFF */  addiu      $v1, $zero, 0x7FFF
/* 1406AC 8024B86C AFA0008C */  sw         $zero, 0x8C($sp)
/* 1406B0 8024B870 005E1021 */  addu       $v0, $v0, $fp
/* 1406B4 8024B874 00021040 */  sll        $v0, $v0, 1
/* 1406B8 8024B878 3C118027 */  lui        $s1, %hi(gPauseBadgesItemIds)
/* 1406BC 8024B87C 02228821 */  addu       $s1, $s1, $v0
/* 1406C0 8024B880 86312550 */  lh         $s1, %lo(gPauseBadgesItemIds)($s1)
/* 1406C4 8024B884 3C138027 */  lui        $s3, %hi(gPauseBadgesItemIds)
/* 1406C8 8024B888 02629821 */  addu       $s3, $s3, $v0
/* 1406CC 8024B88C 96732550 */  lhu        $s3, %lo(gPauseBadgesItemIds)($s3)
/* 1406D0 8024B890 12230239 */  beq        $s1, $v1, .Lpause_8024C178
/* 1406D4 8024B894 0000A82D */   daddu     $s5, $zero, $zero
/* 1406D8 8024B898 8FA40050 */  lw         $a0, 0x50($sp)
/* 1406DC 8024B89C 0C092C4F */  jal        pause_badges_get_pos_x
/* 1406E0 8024B8A0 03C0282D */   daddu     $a1, $fp, $zero
/* 1406E4 8024B8A4 03C0282D */  daddu      $a1, $fp, $zero
/* 1406E8 8024B8A8 8FA40050 */  lw         $a0, 0x50($sp)
/* 1406EC 8024B8AC 0C092C66 */  jal        pause_badges_get_pos_y
/* 1406F0 8024B8B0 0040B82D */   daddu     $s7, $v0, $zero
/* 1406F4 8024B8B4 0040B02D */  daddu      $s6, $v0, $zero
/* 1406F8 8024B8B8 3A227FFE */  xori       $v0, $s1, 0x7FFE
/* 1406FC 8024B8BC 2C420001 */  sltiu      $v0, $v0, 0x1
/* 140700 8024B8C0 02A0802D */  daddu      $s0, $s5, $zero
/* 140704 8024B8C4 0220182D */  daddu      $v1, $s1, $zero
/* 140708 8024B8C8 AFA20088 */  sw         $v0, 0x88($sp)
.Lpause_8024B8CC:
/* 14070C 8024B8CC 86420000 */  lh         $v0, 0x0($s2)
/* 140710 8024B8D0 1062007D */  beq        $v1, $v0, .Lpause_8024BAC8
/* 140714 8024B8D4 26100001 */   addiu     $s0, $s0, 0x1
/* 140718 8024B8D8 2A020040 */  slti       $v0, $s0, 0x40
/* 14071C 8024B8DC 1440FFFB */  bnez       $v0, .Lpause_8024B8CC
/* 140720 8024B8E0 26520002 */   addiu     $s2, $s2, 0x2
.Lpause_8024B8E4:
/* 140724 8024B8E4 3C038027 */  lui        $v1, %hi(gPauseMenuCurrentTab)
/* 140728 8024B8E8 806324A4 */  lb         $v1, %lo(gPauseMenuCurrentTab)($v1)
/* 14072C 8024B8EC 24020002 */  addiu      $v0, $zero, 0x2
/* 140730 8024B8F0 14620029 */  bne        $v1, $v0, .Lpause_8024B998
/* 140734 8024B8F4 24020001 */   addiu     $v0, $zero, 0x1
/* 140738 8024B8F8 3C038027 */  lui        $v1, %hi(gPauseBadgesLevel)
/* 14073C 8024B8FC 8C632768 */  lw         $v1, %lo(gPauseBadgesLevel)($v1)
/* 140740 8024B900 14620025 */  bne        $v1, $v0, .Lpause_8024B998
/* 140744 8024B904 00000000 */   nop
/* 140748 8024B908 8FA40050 */  lw         $a0, 0x50($sp)
/* 14074C 8024B90C 0C092C82 */  jal        pause_badges_get_column
/* 140750 8024B910 03C0282D */   daddu     $a1, $fp, $zero
/* 140754 8024B914 8FAA005C */  lw         $t2, 0x5C($sp)
/* 140758 8024B918 144A001F */  bne        $v0, $t2, .Lpause_8024B998
/* 14075C 8024B91C 00000000 */   nop
/* 140760 8024B920 8FA40050 */  lw         $a0, 0x50($sp)
/* 140764 8024B924 0C092C94 */  jal        pause_badges_get_row
/* 140768 8024B928 03C0282D */   daddu     $a1, $fp, $zero
/* 14076C 8024B92C 8FAB0060 */  lw         $t3, 0x60($sp)
/* 140770 8024B930 144B0019 */  bne        $v0, $t3, .Lpause_8024B998
/* 140774 8024B934 00131400 */   sll       $v0, $s3, 16
/* 140778 8024B938 24150001 */  addiu      $s5, $zero, 0x1
/* 14077C 8024B93C 8FAA0088 */  lw         $t2, 0x88($sp)
/* 140780 8024B940 1540002A */  bnez       $t2, .Lpause_8024B9EC
/* 140784 8024B944 00021403 */   sra       $v0, $v0, 16
/* 140788 8024B948 00021140 */  sll        $v0, $v0, 5
/* 14078C 8024B94C 3C0B8008 */  lui        $t3, %hi(gItemTable)
/* 140790 8024B950 256B3C80 */  addiu      $t3, $t3, %lo(gItemTable)
/* 140794 8024B954 004B1021 */  addu       $v0, $v0, $t3
/* 140798 8024B958 3C0A8009 */  lui        $t2, %hi(gMoveTable)
/* 14079C 8024B95C 254AB400 */  addiu      $t2, $t2, %lo(gMoveTable)
/* 1407A0 8024B960 9043001A */  lbu        $v1, 0x1A($v0)
/* 1407A4 8024B964 8FAB0084 */  lw         $t3, 0x84($sp)
/* 1407A8 8024B968 00031080 */  sll        $v0, $v1, 2
/* 1407AC 8024B96C 00431021 */  addu       $v0, $v0, $v1
/* 1407B0 8024B970 00021080 */  sll        $v0, $v0, 2
/* 1407B4 8024B974 004A1021 */  addu       $v0, $v0, $t2
/* 1407B8 8024B978 80420012 */  lb         $v0, 0x12($v0)
/* 1407BC 8024B97C 15600006 */  bnez       $t3, .Lpause_8024B998
/* 1407C0 8024B980 AFA20070 */   sw        $v0, 0x70($sp)
/* 1407C4 8024B984 8FAA006C */  lw         $t2, 0x6C($sp)
/* 1407C8 8024B988 0142102A */  slt        $v0, $t2, $v0
/* 1407CC 8024B98C 14400002 */  bnez       $v0, .Lpause_8024B998
/* 1407D0 8024B990 02A0582D */   daddu     $t3, $s5, $zero
/* 1407D4 8024B994 AFAB0074 */  sw         $t3, 0x74($sp)
.Lpause_8024B998:
/* 1407D8 8024B998 8FAA0088 */  lw         $t2, 0x88($sp)
/* 1407DC 8024B99C 15400014 */  bnez       $t2, .Lpause_8024B9F0
/* 1407E0 8024B9A0 0000902D */   daddu     $s2, $zero, $zero
/* 1407E4 8024B9A4 00131400 */  sll        $v0, $s3, 16
/* 1407E8 8024B9A8 000212C3 */  sra        $v0, $v0, 11
/* 1407EC 8024B9AC 3C0B8008 */  lui        $t3, %hi(gItemTable)
/* 1407F0 8024B9B0 256B3C80 */  addiu      $t3, $t3, %lo(gItemTable)
/* 1407F4 8024B9B4 004B1021 */  addu       $v0, $v0, $t3
/* 1407F8 8024B9B8 3C0A8009 */  lui        $t2, %hi(gMoveTable)
/* 1407FC 8024B9BC 254AB400 */  addiu      $t2, $t2, %lo(gMoveTable)
/* 140800 8024B9C0 9043001A */  lbu        $v1, 0x1A($v0)
/* 140804 8024B9C4 8FAB006C */  lw         $t3, 0x6C($sp)
/* 140808 8024B9C8 00031080 */  sll        $v0, $v1, 2
/* 14080C 8024B9CC 00431021 */  addu       $v0, $v0, $v1
/* 140810 8024B9D0 00021080 */  sll        $v0, $v0, 2
/* 140814 8024B9D4 004A1021 */  addu       $v0, $v0, $t2
/* 140818 8024B9D8 80420012 */  lb         $v0, 0x12($v0)
/* 14081C 8024B9DC 0162102A */  slt        $v0, $t3, $v0
/* 140820 8024B9E0 10400003 */  beqz       $v0, .Lpause_8024B9F0
/* 140824 8024B9E4 240A0001 */   addiu     $t2, $zero, 0x1
/* 140828 8024B9E8 AFAA008C */  sw         $t2, 0x8C($sp)
.Lpause_8024B9EC:
/* 14082C 8024B9EC 0000902D */  daddu      $s2, $zero, $zero
.Lpause_8024B9F0:
/* 140830 8024B9F0 12A00003 */  beqz       $s5, .Lpause_8024BA00
/* 140834 8024B9F4 0240A02D */   daddu     $s4, $s2, $zero
/* 140838 8024B9F8 2412FFFF */  addiu      $s2, $zero, -0x1
/* 14083C 8024B9FC 0240A02D */  daddu      $s4, $s2, $zero
.Lpause_8024BA00:
/* 140840 8024BA00 8FAB0054 */  lw         $t3, 0x54($sp)
/* 140844 8024BA04 15600037 */  bnez       $t3, .Lpause_8024BAE4
/* 140848 8024BA08 240A0001 */   addiu     $t2, $zero, 0x1
/* 14084C 8024BA0C 240B000A */  addiu      $t3, $zero, 0xA
/* 140850 8024BA10 AFAA0064 */  sw         $t2, 0x64($sp)
/* 140854 8024BA14 12A00003 */  beqz       $s5, .Lpause_8024BA24
/* 140858 8024BA18 AFAB0068 */   sw        $t3, 0x68($sp)
/* 14085C 8024BA1C 240A0009 */  addiu      $t2, $zero, 0x9
/* 140860 8024BA20 AFAA0064 */  sw         $t2, 0x64($sp)
.Lpause_8024BA24:
/* 140864 8024BA24 8FAB0084 */  lw         $t3, 0x84($sp)
/* 140868 8024BA28 1160002A */  beqz       $t3, .Lpause_8024BAD4
/* 14086C 8024BA2C 00000000 */   nop
/* 140870 8024BA30 0C092CB6 */  jal        pause_badges_scroll_offset_x
/* 140874 8024BA34 02E0202D */   daddu     $a0, $s7, $zero
/* 140878 8024BA38 8FAA007C */  lw         $t2, 0x7C($sp)
/* 14087C 8024BA3C 02C0202D */  daddu      $a0, $s6, $zero
/* 140880 8024BA40 01428021 */  addu       $s0, $t2, $v0
/* 140884 8024BA44 0C092CB2 */  jal        pause_badges_scroll_offset_y
/* 140888 8024BA48 2610FFEC */   addiu     $s0, $s0, -0x14
/* 14088C 8024BA4C 24040004 */  addiu      $a0, $zero, 0x4
/* 140890 8024BA50 3C058027 */  lui        $a1, %hi(gPauseWS_14)
/* 140894 8024BA54 24A51FE0 */  addiu      $a1, $a1, %lo(gPauseWS_14)
/* 140898 8024BA58 8FAB00C8 */  lw         $t3, 0xC8($sp)
/* 14089C 8024BA5C 0200302D */  daddu      $a2, $s0, $zero
/* 1408A0 8024BA60 AFA00010 */  sw         $zero, 0x10($sp)
/* 1408A4 8024BA64 AFA00020 */  sw         $zero, 0x20($sp)
/* 1408A8 8024BA68 AFA00024 */  sw         $zero, 0x24($sp)
/* 1408AC 8024BA6C AFA00028 */  sw         $zero, 0x28($sp)
/* 1408B0 8024BA70 AFA0002C */  sw         $zero, 0x2C($sp)
/* 1408B4 8024BA74 AFA00030 */  sw         $zero, 0x30($sp)
/* 1408B8 8024BA78 AFA00034 */  sw         $zero, 0x34($sp)
/* 1408BC 8024BA7C AFA00038 */  sw         $zero, 0x38($sp)
/* 1408C0 8024BA80 AFA0003C */  sw         $zero, 0x3C($sp)
/* 1408C4 8024BA84 AFA00040 */  sw         $zero, 0x40($sp)
/* 1408C8 8024BA88 AFA0004C */  sw         $zero, 0x4C($sp)
/* 1408CC 8024BA8C 01621021 */  addu       $v0, $t3, $v0
/* 1408D0 8024BA90 24470011 */  addiu      $a3, $v0, 0x11
/* 1408D4 8024BA94 240200C8 */  addiu      $v0, $zero, 0xC8
/* 1408D8 8024BA98 AFA20014 */  sw         $v0, 0x14($sp)
/* 1408DC 8024BA9C 2402000D */  addiu      $v0, $zero, 0xD
/* 1408E0 8024BAA0 AFA20018 */  sw         $v0, 0x18($sp)
/* 1408E4 8024BAA4 240200FF */  addiu      $v0, $zero, 0xFF
/* 1408E8 8024BAA8 AFA2001C */  sw         $v0, 0x1C($sp)
/* 1408EC 8024BAAC 24020140 */  addiu      $v0, $zero, 0x140
/* 1408F0 8024BAB0 AFA20044 */  sw         $v0, 0x44($sp)
/* 1408F4 8024BAB4 240200F0 */  addiu      $v0, $zero, 0xF0
/* 1408F8 8024BAB8 0C03C5C4 */  jal        draw_box
/* 1408FC 8024BABC AFA20048 */   sw        $v0, 0x48($sp)
/* 140900 8024BAC0 08092EB9 */  j          .Lpause_8024BAE4
/* 140904 8024BAC4 00000000 */   nop
.Lpause_8024BAC8:
/* 140908 8024BAC8 240A0001 */  addiu      $t2, $zero, 0x1
/* 14090C 8024BACC 08092E39 */  j          .Lpause_8024B8E4
/* 140910 8024BAD0 AFAA0084 */   sw        $t2, 0x84($sp)
.Lpause_8024BAD4:
/* 140914 8024BAD4 8FAB008C */  lw         $t3, 0x8C($sp)
/* 140918 8024BAD8 11600002 */  beqz       $t3, .Lpause_8024BAE4
/* 14091C 8024BADC 240A000B */   addiu     $t2, $zero, 0xB
/* 140920 8024BAE0 AFAA0068 */  sw         $t2, 0x68($sp)
.Lpause_8024BAE4:
/* 140924 8024BAE4 0C092CA8 */  jal        pause_badges_is_visible
/* 140928 8024BAE8 02C0202D */   daddu     $a0, $s6, $zero
/* 14092C 8024BAEC 104001A2 */  beqz       $v0, .Lpause_8024C178
/* 140930 8024BAF0 00000000 */   nop
/* 140934 8024BAF4 8FAB0054 */  lw         $t3, 0x54($sp)
/* 140938 8024BAF8 15600058 */  bnez       $t3, .Lpause_8024BC5C
/* 14093C 8024BAFC 24020001 */   addiu     $v0, $zero, 0x1
/* 140940 8024BB00 8FAA0088 */  lw         $t2, 0x88($sp)
/* 140944 8024BB04 11400018 */  beqz       $t2, .Lpause_8024BB68
/* 140948 8024BB08 00131400 */   sll       $v0, $s3, 16
/* 14094C 8024BB0C 0C094C60 */  jal        pause_get_menu_msg
/* 140950 8024BB10 2404003F */   addiu     $a0, $zero, 0x3F
/* 140954 8024BB14 02E0202D */  daddu      $a0, $s7, $zero
/* 140958 8024BB18 0C092CB6 */  jal        pause_badges_scroll_offset_x
/* 14095C 8024BB1C 0040882D */   daddu     $s1, $v0, $zero
/* 140960 8024BB20 8FAB007C */  lw         $t3, 0x7C($sp)
/* 140964 8024BB24 02C0202D */  daddu      $a0, $s6, $zero
/* 140968 8024BB28 01628021 */  addu       $s0, $t3, $v0
/* 14096C 8024BB2C 0C092CB2 */  jal        pause_badges_scroll_offset_y
/* 140970 8024BB30 02128021 */   addu      $s0, $s0, $s2
/* 140974 8024BB34 0220202D */  daddu      $a0, $s1, $zero
/* 140978 8024BB38 0200282D */  daddu      $a1, $s0, $zero
/* 14097C 8024BB3C 240700FF */  addiu      $a3, $zero, 0xFF
/* 140980 8024BB40 8FAA0080 */  lw         $t2, 0x80($sp)
/* 140984 8024BB44 8FAB0068 */  lw         $t3, 0x68($sp)
/* 140988 8024BB48 01421021 */  addu       $v0, $t2, $v0
/* 14098C 8024BB4C 8FAA0064 */  lw         $t2, 0x64($sp)
/* 140990 8024BB50 00543021 */  addu       $a2, $v0, $s4
/* 140994 8024BB54 AFAB0010 */  sw         $t3, 0x10($sp)
/* 140998 8024BB58 0C049403 */  jal        draw_msg
/* 14099C 8024BB5C AFAA0014 */   sw        $t2, 0x14($sp)
/* 1409A0 8024BB60 08092F15 */  j          .Lpause_8024BC54
/* 1409A4 8024BB64 00000000 */   nop
.Lpause_8024BB68:
/* 1409A8 8024BB68 000212C3 */  sra        $v0, $v0, 11
/* 1409AC 8024BB6C 3C0B8008 */  lui        $t3, %hi(gItemTable)
/* 1409B0 8024BB70 256B3C80 */  addiu      $t3, $t3, %lo(gItemTable)
/* 1409B4 8024BB74 004B8821 */  addu       $s1, $v0, $t3
/* 1409B8 8024BB78 8E220000 */  lw         $v0, 0x0($s1)
/* 1409BC 8024BB7C 10400015 */  beqz       $v0, .Lpause_8024BBD4
/* 1409C0 8024BB80 00000000 */   nop
/* 1409C4 8024BB84 18400013 */  blez       $v0, .Lpause_8024BBD4
/* 1409C8 8024BB88 00000000 */   nop
/* 1409CC 8024BB8C 0C092CB6 */  jal        pause_badges_scroll_offset_x
/* 1409D0 8024BB90 02E0202D */   daddu     $a0, $s7, $zero
/* 1409D4 8024BB94 8FAA007C */  lw         $t2, 0x7C($sp)
/* 1409D8 8024BB98 02C0202D */  daddu      $a0, $s6, $zero
/* 1409DC 8024BB9C 01428021 */  addu       $s0, $t2, $v0
/* 1409E0 8024BBA0 0C092CB2 */  jal        pause_badges_scroll_offset_y
/* 1409E4 8024BBA4 02128021 */   addu      $s0, $s0, $s2
/* 1409E8 8024BBA8 0200282D */  daddu      $a1, $s0, $zero
/* 1409EC 8024BBAC 8FAB0080 */  lw         $t3, 0x80($sp)
/* 1409F0 8024BBB0 8FAA0068 */  lw         $t2, 0x68($sp)
/* 1409F4 8024BBB4 01621021 */  addu       $v0, $t3, $v0
/* 1409F8 8024BBB8 8FAB0064 */  lw         $t3, 0x64($sp)
/* 1409FC 8024BBBC 240700FF */  addiu      $a3, $zero, 0xFF
/* 140A00 8024BBC0 AFAA0010 */  sw         $t2, 0x10($sp)
/* 140A04 8024BBC4 AFAB0014 */  sw         $t3, 0x14($sp)
/* 140A08 8024BBC8 8E240000 */  lw         $a0, 0x0($s1)
/* 140A0C 8024BBCC 0C049403 */  jal        draw_msg
/* 140A10 8024BBD0 00543021 */   addu      $a2, $v0, $s4
.Lpause_8024BBD4:
/* 140A14 8024BBD4 0C092CB6 */  jal        pause_badges_scroll_offset_x
/* 140A18 8024BBD8 02E0202D */   daddu     $a0, $s7, $zero
/* 140A1C 8024BBDC 02C0202D */  daddu      $a0, $s6, $zero
/* 140A20 8024BBE0 8FAA00C4 */  lw         $t2, 0xC4($sp)
/* 140A24 8024BBE4 245000EB */  addiu      $s0, $v0, 0xEB
/* 140A28 8024BBE8 0C092CB2 */  jal        pause_badges_scroll_offset_y
/* 140A2C 8024BBEC 01508021 */   addu      $s0, $t2, $s0
/* 140A30 8024BBF0 0200282D */  daddu      $a1, $s0, $zero
/* 140A34 8024BBF4 24420011 */  addiu      $v0, $v0, 0x11
/* 140A38 8024BBF8 00131C00 */  sll        $v1, $s3, 16
/* 140A3C 8024BBFC 00031AC3 */  sra        $v1, $v1, 11
/* 140A40 8024BC00 3C0B8008 */  lui        $t3, %hi(gItemTable)
/* 140A44 8024BC04 256B3C80 */  addiu      $t3, $t3, %lo(gItemTable)
/* 140A48 8024BC08 006B1821 */  addu       $v1, $v1, $t3
/* 140A4C 8024BC0C 3C0B8009 */  lui        $t3, %hi(gMoveTable)
/* 140A50 8024BC10 256BB400 */  addiu      $t3, $t3, %lo(gMoveTable)
/* 140A54 8024BC14 24070001 */  addiu      $a3, $zero, 0x1
/* 140A58 8024BC18 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 140A5C 8024BC1C 9063001A */  lbu        $v1, 0x1A($v1)
/* 140A60 8024BC20 01423021 */  addu       $a2, $t2, $v0
/* 140A64 8024BC24 00031080 */  sll        $v0, $v1, 2
/* 140A68 8024BC28 00431021 */  addu       $v0, $v0, $v1
/* 140A6C 8024BC2C 00021080 */  sll        $v0, $v0, 2
/* 140A70 8024BC30 004B1021 */  addu       $v0, $v0, $t3
/* 140A74 8024BC34 80440012 */  lb         $a0, 0x12($v0)
/* 140A78 8024BC38 8FAA0068 */  lw         $t2, 0x68($sp)
/* 140A7C 8024BC3C 240200FF */  addiu      $v0, $zero, 0xFF
/* 140A80 8024BC40 AFA20014 */  sw         $v0, 0x14($sp)
/* 140A84 8024BC44 24020003 */  addiu      $v0, $zero, 0x3
/* 140A88 8024BC48 AFA20018 */  sw         $v0, 0x18($sp)
/* 140A8C 8024BC4C 0C04986F */  jal        draw_number
/* 140A90 8024BC50 AFAA0010 */   sw        $t2, 0x10($sp)
.Lpause_8024BC54:
/* 140A94 8024BC54 8FAB0054 */  lw         $t3, 0x54($sp)
/* 140A98 8024BC58 24020001 */  addiu      $v0, $zero, 0x1
.Lpause_8024BC5C:
/* 140A9C 8024BC5C 15620060 */  bne        $t3, $v0, .Lpause_8024BDE0
/* 140AA0 8024BC60 3C052000 */   lui       $a1, (0x20000000 >> 16)
/* 140AA4 8024BC64 8FAA0058 */  lw         $t2, 0x58($sp)
/* 140AA8 8024BC68 000A1080 */  sll        $v0, $t2, 2
/* 140AAC 8024BC6C 3C0B8027 */  lui        $t3, %hi(gPauseBadgesIconIDs)
/* 140AB0 8024BC70 256B2778 */  addiu      $t3, $t3, %lo(gPauseBadgesIconIDs)
/* 140AB4 8024BC74 004B1021 */  addu       $v0, $v0, $t3
/* 140AB8 8024BC78 8C510000 */  lw         $s1, 0x0($v0)
/* 140ABC 8024BC7C 0C050D77 */  jal        hud_element_clear_flags
/* 140AC0 8024BC80 0220202D */   daddu     $a0, $s1, $zero
/* 140AC4 8024BC84 0220202D */  daddu      $a0, $s1, $zero
/* 140AC8 8024BC88 0C050D6C */  jal        hud_element_set_flags
/* 140ACC 8024BC8C 34058000 */   ori       $a1, $zero, 0x8000
/* 140AD0 8024BC90 8FAA0088 */  lw         $t2, 0x88($sp)
/* 140AD4 8024BC94 11400005 */  beqz       $t2, .Lpause_8024BCAC
/* 140AD8 8024BC98 00000000 */   nop
/* 140ADC 8024BC9C 3C118027 */  lui        $s1, %hi(gPauseBadgesIconIDs+0x54)
/* 140AE0 8024BCA0 8E3127CC */  lw         $s1, %lo(gPauseBadgesIconIDs+0x54)($s1)
/* 140AE4 8024BCA4 08092F5D */  j          .Lpause_8024BD74
/* 140AE8 8024BCA8 00000000 */   nop
.Lpause_8024BCAC:
/* 140AEC 8024BCAC 12A00010 */  beqz       $s5, .Lpause_8024BCF0
/* 140AF0 8024BCB0 0220202D */   daddu     $a0, $s1, $zero
/* 140AF4 8024BCB4 0C050D6C */  jal        hud_element_set_flags
/* 140AF8 8024BCB8 3C052000 */   lui       $a1, (0x20000000 >> 16)
/* 140AFC 8024BCBC 00131400 */  sll        $v0, $s3, 16
/* 140B00 8024BCC0 000212C3 */  sra        $v0, $v0, 11
/* 140B04 8024BCC4 3C0B8008 */  lui        $t3, %hi(gItemTable)
/* 140B08 8024BCC8 256B3C80 */  addiu      $t3, $t3, %lo(gItemTable)
/* 140B0C 8024BCCC 004B1021 */  addu       $v0, $v0, $t3
/* 140B10 8024BCD0 84420004 */  lh         $v0, 0x4($v0)
/* 140B14 8024BCD4 3C0A8008 */  lui        $t2, %hi(gItemHudScripts)
/* 140B18 8024BCD8 254A6A20 */  addiu      $t2, $t2, %lo(gItemHudScripts)
/* 140B1C 8024BCDC 000210C0 */  sll        $v0, $v0, 3
/* 140B20 8024BCE0 004A1021 */  addu       $v0, $v0, $t2
/* 140B24 8024BCE4 8C420000 */  lw         $v0, 0x0($v0)
/* 140B28 8024BCE8 3C018027 */  lui        $at, %hi(gPauseCurrentDescIconScript)
/* 140B2C 8024BCEC AC22249C */  sw         $v0, %lo(gPauseCurrentDescIconScript)($at)
.Lpause_8024BCF0:
/* 140B30 8024BCF0 8FAB0084 */  lw         $t3, 0x84($sp)
/* 140B34 8024BCF4 1560000F */  bnez       $t3, .Lpause_8024BD34
/* 140B38 8024BCF8 00131400 */   sll       $v0, $s3, 16
/* 140B3C 8024BCFC 8FAA008C */  lw         $t2, 0x8C($sp)
/* 140B40 8024BD00 1140000B */  beqz       $t2, .Lpause_8024BD30
/* 140B44 8024BD04 000212C3 */   sra       $v0, $v0, 11
/* 140B48 8024BD08 3C0B8008 */  lui        $t3, %hi(gItemTable)
/* 140B4C 8024BD0C 256B3C80 */  addiu      $t3, $t3, %lo(gItemTable)
/* 140B50 8024BD10 004B1021 */  addu       $v0, $v0, $t3
/* 140B54 8024BD14 84420004 */  lh         $v0, 0x4($v0)
/* 140B58 8024BD18 3C0A8008 */  lui        $t2, %hi(gItemHudScripts)
/* 140B5C 8024BD1C 254A6A20 */  addiu      $t2, $t2, %lo(gItemHudScripts)
/* 140B60 8024BD20 000210C0 */  sll        $v0, $v0, 3
/* 140B64 8024BD24 004A1021 */  addu       $v0, $v0, $t2
/* 140B68 8024BD28 08092F57 */  j          .Lpause_8024BD5C
/* 140B6C 8024BD2C 8C450004 */   lw        $a1, 0x4($v0)
.Lpause_8024BD30:
/* 140B70 8024BD30 00131400 */  sll        $v0, $s3, 16
.Lpause_8024BD34:
/* 140B74 8024BD34 000212C3 */  sra        $v0, $v0, 11
/* 140B78 8024BD38 3C0B8008 */  lui        $t3, %hi(gItemTable)
/* 140B7C 8024BD3C 256B3C80 */  addiu      $t3, $t3, %lo(gItemTable)
/* 140B80 8024BD40 004B1021 */  addu       $v0, $v0, $t3
/* 140B84 8024BD44 84420004 */  lh         $v0, 0x4($v0)
/* 140B88 8024BD48 3C0A8008 */  lui        $t2, %hi(gItemHudScripts)
/* 140B8C 8024BD4C 254A6A20 */  addiu      $t2, $t2, %lo(gItemHudScripts)
/* 140B90 8024BD50 000210C0 */  sll        $v0, $v0, 3
/* 140B94 8024BD54 004A1021 */  addu       $v0, $v0, $t2
/* 140B98 8024BD58 8C450000 */  lw         $a1, 0x0($v0)
.Lpause_8024BD5C:
/* 140B9C 8024BD5C 0C050CEB */  jal        hud_element_set_script
/* 140BA0 8024BD60 0220202D */   daddu     $a0, $s1, $zero
/* 140BA4 8024BD64 3C053F2B */  lui        $a1, (0x3F2BBA99 >> 16)
/* 140BA8 8024BD68 34A5BA99 */  ori        $a1, $a1, (0x3F2BBA99 & 0xFFFF)
/* 140BAC 8024BD6C 0C050DF4 */  jal        hud_element_set_scale
/* 140BB0 8024BD70 0220202D */   daddu     $a0, $s1, $zero
.Lpause_8024BD74:
/* 140BB4 8024BD74 0C092CB6 */  jal        pause_badges_scroll_offset_x
/* 140BB8 8024BD78 02E0202D */   daddu     $a0, $s7, $zero
/* 140BBC 8024BD7C 02C0202D */  daddu      $a0, $s6, $zero
/* 140BC0 8024BD80 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 140BC4 8024BD84 2450006B */  addiu      $s0, $v0, 0x6B
/* 140BC8 8024BD88 01708021 */  addu       $s0, $t3, $s0
/* 140BCC 8024BD8C 0C092CB2 */  jal        pause_badges_scroll_offset_y
/* 140BD0 8024BD90 02128021 */   addu      $s0, $s0, $s2
/* 140BD4 8024BD94 0220202D */  daddu      $a0, $s1, $zero
/* 140BD8 8024BD98 0200282D */  daddu      $a1, $s0, $zero
/* 140BDC 8024BD9C 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 140BE0 8024BDA0 24420017 */  addiu      $v0, $v0, 0x17
/* 140BE4 8024BDA4 01421021 */  addu       $v0, $t2, $v0
/* 140BE8 8024BDA8 0C050D4D */  jal        hud_element_set_render_pos
/* 140BEC 8024BDAC 00543021 */   addu      $a2, $v0, $s4
/* 140BF0 8024BDB0 8FAB0058 */  lw         $t3, 0x58($sp)
/* 140BF4 8024BDB4 15600005 */  bnez       $t3, .Lpause_8024BDCC
/* 140BF8 8024BDB8 00000000 */   nop
/* 140BFC 8024BDBC 0C050CE4 */  jal        hud_element_draw_without_clipping
/* 140C00 8024BDC0 0220202D */   daddu     $a0, $s1, $zero
/* 140C04 8024BDC4 08092F75 */  j          .Lpause_8024BDD4
/* 140C08 8024BDC8 00000000 */   nop
.Lpause_8024BDCC:
/* 140C0C 8024BDCC 0C050CDD */  jal        hud_element_draw_next
/* 140C10 8024BDD0 0220202D */   daddu     $a0, $s1, $zero
.Lpause_8024BDD4:
/* 140C14 8024BDD4 8FAA0058 */  lw         $t2, 0x58($sp)
/* 140C18 8024BDD8 254A0001 */  addiu      $t2, $t2, 0x1
/* 140C1C 8024BDDC AFAA0058 */  sw         $t2, 0x58($sp)
.Lpause_8024BDE0:
/* 140C20 8024BDE0 8FAB0054 */  lw         $t3, 0x54($sp)
/* 140C24 8024BDE4 24020002 */  addiu      $v0, $zero, 0x2
/* 140C28 8024BDE8 156200E3 */  bne        $t3, $v0, .Lpause_8024C178
/* 140C2C 8024BDEC 00000000 */   nop
/* 140C30 8024BDF0 8FAA0088 */  lw         $t2, 0x88($sp)
/* 140C34 8024BDF4 154000E0 */  bnez       $t2, .Lpause_8024C178
/* 140C38 8024BDF8 00131400 */   sll       $v0, $s3, 16
/* 140C3C 8024BDFC 000212C3 */  sra        $v0, $v0, 11
/* 140C40 8024BE00 3C0B8008 */  lui        $t3, %hi(gItemTable)
/* 140C44 8024BE04 256B3C80 */  addiu      $t3, $t3, %lo(gItemTable)
/* 140C48 8024BE08 004B1021 */  addu       $v0, $v0, $t3
/* 140C4C 8024BE0C 9043001A */  lbu        $v1, 0x1A($v0)
/* 140C50 8024BE10 3C0A8009 */  lui        $t2, %hi(gMoveTable)
/* 140C54 8024BE14 254AB400 */  addiu      $t2, $t2, %lo(gMoveTable)
/* 140C58 8024BE18 00031080 */  sll        $v0, $v1, 2
/* 140C5C 8024BE1C 00431021 */  addu       $v0, $v0, $v1
/* 140C60 8024BE20 00021080 */  sll        $v0, $v0, 2
/* 140C64 8024BE24 004A1021 */  addu       $v0, $v0, $t2
/* 140C68 8024BE28 80530012 */  lb         $s3, 0x12($v0)
/* 140C6C 8024BE2C 2A62000B */  slti       $v0, $s3, 0xB
/* 140C70 8024BE30 10400002 */  beqz       $v0, .Lpause_8024BE3C
/* 140C74 8024BE34 24150001 */   addiu     $s5, $zero, 0x1
/* 140C78 8024BE38 24150004 */  addiu      $s5, $zero, 0x4
.Lpause_8024BE3C:
/* 140C7C 8024BE3C 3C04E300 */  lui        $a0, (0xE3001201 >> 16)
/* 140C80 8024BE40 34841201 */  ori        $a0, $a0, (0xE3001201 & 0xFFFF)
/* 140C84 8024BE44 3C058009 */  lui        $a1, %hi(gMainGfxPos)
/* 140C88 8024BE48 8CA56A44 */  lw         $a1, %lo(gMainGfxPos)($a1)
/* 140C8C 8024BE4C 3C02DE00 */  lui        $v0, (0xDE000000 >> 16)
/* 140C90 8024BE50 00A0182D */  daddu      $v1, $a1, $zero
/* 140C94 8024BE54 24A50008 */  addiu      $a1, $a1, 0x8
/* 140C98 8024BE58 AC620000 */  sw         $v0, 0x0($v1)
/* 140C9C 8024BE5C 3C028027 */  lui        $v0, %hi(gPauseDLOrbs)
/* 140CA0 8024BE60 24421818 */  addiu      $v0, $v0, %lo(gPauseDLOrbs)
/* 140CA4 8024BE64 AC620004 */  sw         $v0, 0x4($v1)
/* 140CA8 8024BE68 24A20008 */  addiu      $v0, $a1, 0x8
/* 140CAC 8024BE6C 3C018009 */  lui        $at, %hi(gMainGfxPos)
/* 140CB0 8024BE70 AC256A44 */  sw         $a1, %lo(gMainGfxPos)($at)
/* 140CB4 8024BE74 3C018009 */  lui        $at, %hi(gMainGfxPos)
/* 140CB8 8024BE78 AC226A44 */  sw         $v0, %lo(gMainGfxPos)($at)
/* 140CBC 8024BE7C 24022000 */  addiu      $v0, $zero, 0x2000
/* 140CC0 8024BE80 ACA40000 */  sw         $a0, 0x0($a1)
/* 140CC4 8024BE84 ACA20004 */  sw         $v0, 0x4($a1)
/* 140CC8 8024BE88 8FAB0084 */  lw         $t3, 0x84($sp)
/* 140CCC 8024BE8C 15600081 */  bnez       $t3, .Lpause_8024C094
/* 140CD0 8024BE90 3C0300FF */   lui       $v1, (0xFF64FF >> 16)
/* 140CD4 8024BE94 1A600032 */  blez       $s3, .Lpause_8024BF60
/* 140CD8 8024BE98 0000802D */   daddu     $s0, $zero, $zero
/* 140CDC 8024BE9C 2A740005 */  slti       $s4, $s3, 0x5
.Lpause_8024BEA0:
/* 140CE0 8024BEA0 3C028009 */  lui        $v0, %hi(gMainGfxPos)
/* 140CE4 8024BEA4 8C426A44 */  lw         $v0, %lo(gMainGfxPos)($v0)
/* 140CE8 8024BEA8 02E0202D */  daddu      $a0, $s7, $zero
/* 140CEC 8024BEAC 0040182D */  daddu      $v1, $v0, $zero
/* 140CF0 8024BEB0 3C0AFA00 */  lui        $t2, (0xFA000000 >> 16)
/* 140CF4 8024BEB4 AC6A0000 */  sw         $t2, 0x0($v1)
/* 140CF8 8024BEB8 8FAB0090 */  lw         $t3, 0x90($sp)
/* 140CFC 8024BEBC 24420008 */  addiu      $v0, $v0, 0x8
/* 140D00 8024BEC0 3C018009 */  lui        $at, %hi(gMainGfxPos)
/* 140D04 8024BEC4 AC226A44 */  sw         $v0, %lo(gMainGfxPos)($at)
/* 140D08 8024BEC8 0C092CB6 */  jal        pause_badges_scroll_offset_x
/* 140D0C 8024BECC AC6B0004 */   sw        $t3, 0x4($v1)
/* 140D10 8024BED0 8FAA0094 */  lw         $t2, 0x94($sp)
/* 140D14 8024BED4 02C0202D */  daddu      $a0, $s6, $zero
/* 140D18 8024BED8 020A0018 */  mult       $s0, $t2
/* 140D1C 8024BEDC 244200EB */  addiu      $v0, $v0, 0xEB
/* 140D20 8024BEE0 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 140D24 8024BEE4 00101FC3 */  sra        $v1, $s0, 31
/* 140D28 8024BEE8 01621021 */  addu       $v0, $t3, $v0
/* 140D2C 8024BEEC 00005010 */  mfhi       $t2
/* 140D30 8024BEF0 000A2843 */  sra        $a1, $t2, 1
/* 140D34 8024BEF4 00A38823 */  subu       $s1, $a1, $v1
/* 140D38 8024BEF8 00112880 */  sll        $a1, $s1, 2
/* 140D3C 8024BEFC 00B12821 */  addu       $a1, $a1, $s1
/* 140D40 8024BF00 02052823 */  subu       $a1, $s0, $a1
/* 140D44 8024BF04 00051840 */  sll        $v1, $a1, 1
/* 140D48 8024BF08 00651821 */  addu       $v1, $v1, $a1
/* 140D4C 8024BF0C 00031840 */  sll        $v1, $v1, 1
/* 140D50 8024BF10 24630001 */  addiu      $v1, $v1, 0x1
/* 140D54 8024BF14 0C092CB2 */  jal        pause_badges_scroll_offset_y
/* 140D58 8024BF18 00439021 */   addu      $s2, $v0, $v1
/* 140D5C 8024BF1C 8FAB00C8 */  lw         $t3, 0xC8($sp)
/* 140D60 8024BF20 24420011 */  addiu      $v0, $v0, 0x11
/* 140D64 8024BF24 01621021 */  addu       $v0, $t3, $v0
/* 140D68 8024BF28 16800006 */  bnez       $s4, .Lpause_8024BF44
/* 140D6C 8024BF2C 00553021 */   addu      $a2, $v0, $s5
/* 140D70 8024BF30 24C3FFFD */  addiu      $v1, $a2, -0x3
/* 140D74 8024BF34 00111040 */  sll        $v0, $s1, 1
/* 140D78 8024BF38 00511021 */  addu       $v0, $v0, $s1
/* 140D7C 8024BF3C 00021040 */  sll        $v0, $v0, 1
/* 140D80 8024BF40 00623021 */  addu       $a2, $v1, $v0
.Lpause_8024BF44:
/* 140D84 8024BF44 0000202D */  daddu      $a0, $zero, $zero
/* 140D88 8024BF48 0C092D22 */  jal        pause_badges_draw_bp_orbs
/* 140D8C 8024BF4C 0240282D */   daddu     $a1, $s2, $zero
/* 140D90 8024BF50 26100001 */  addiu      $s0, $s0, 0x1
/* 140D94 8024BF54 0213102A */  slt        $v0, $s0, $s3
/* 140D98 8024BF58 1440FFD1 */  bnez       $v0, .Lpause_8024BEA0
/* 140D9C 8024BF5C 00000000 */   nop
.Lpause_8024BF60:
/* 140DA0 8024BF60 3C06E200 */  lui        $a2, (0xE200001C >> 16)
/* 140DA4 8024BF64 34C6001C */  ori        $a2, $a2, (0xE200001C & 0xFFFF)
/* 140DA8 8024BF68 3C050050 */  lui        $a1, (0x504340 >> 16)
/* 140DAC 8024BF6C 34A54340 */  ori        $a1, $a1, (0x504340 & 0xFFFF)
/* 140DB0 8024BF70 0000802D */  daddu      $s0, $zero, $zero
/* 140DB4 8024BF74 3C02E700 */  lui        $v0, (0xE7000000 >> 16)
/* 140DB8 8024BF78 3C048009 */  lui        $a0, %hi(gMainGfxPos)
/* 140DBC 8024BF7C 8C846A44 */  lw         $a0, %lo(gMainGfxPos)($a0)
/* 140DC0 8024BF80 240B00FF */  addiu      $t3, $zero, 0xFF
/* 140DC4 8024BF84 0080182D */  daddu      $v1, $a0, $zero
/* 140DC8 8024BF88 24840008 */  addiu      $a0, $a0, 0x8
/* 140DCC 8024BF8C AC620000 */  sw         $v0, 0x0($v1)
/* 140DD0 8024BF90 24820008 */  addiu      $v0, $a0, 0x8
/* 140DD4 8024BF94 3C018009 */  lui        $at, %hi(gMainGfxPos)
/* 140DD8 8024BF98 AC246A44 */  sw         $a0, %lo(gMainGfxPos)($at)
/* 140DDC 8024BF9C 3C018009 */  lui        $at, %hi(gMainGfxPos)
/* 140DE0 8024BFA0 AC226A44 */  sw         $v0, %lo(gMainGfxPos)($at)
/* 140DE4 8024BFA4 24820010 */  addiu      $v0, $a0, 0x10
/* 140DE8 8024BFA8 AC600004 */  sw         $zero, 0x4($v1)
/* 140DEC 8024BFAC 3C0AFA00 */  lui        $t2, (0xFA000000 >> 16)
/* 140DF0 8024BFB0 3C018009 */  lui        $at, %hi(gMainGfxPos)
/* 140DF4 8024BFB4 AC226A44 */  sw         $v0, %lo(gMainGfxPos)($at)
/* 140DF8 8024BFB8 000B1400 */  sll        $v0, $t3, 16
/* 140DFC 8024BFBC AC8A0008 */  sw         $t2, 0x8($a0)
/* 140E00 8024BFC0 240A0064 */  addiu      $t2, $zero, 0x64
/* 140E04 8024BFC4 000A1A00 */  sll        $v1, $t2, 8
/* 140E08 8024BFC8 00431025 */  or         $v0, $v0, $v1
/* 140E0C 8024BFCC 34420080 */  ori        $v0, $v0, 0x80
/* 140E10 8024BFD0 AC860000 */  sw         $a2, 0x0($a0)
/* 140E14 8024BFD4 AC850004 */  sw         $a1, 0x4($a0)
/* 140E18 8024BFD8 1A600067 */  blez       $s3, .Lpause_8024C178
/* 140E1C 8024BFDC AC82000C */   sw        $v0, 0xC($a0)
/* 140E20 8024BFE0 2A740005 */  slti       $s4, $s3, 0x5
.Lpause_8024BFE4:
/* 140E24 8024BFE4 8FAB006C */  lw         $t3, 0x6C($sp)
/* 140E28 8024BFE8 020B102A */  slt        $v0, $s0, $t3
/* 140E2C 8024BFEC 50400024 */  beql       $v0, $zero, .Lpause_8024C080
/* 140E30 8024BFF0 26100001 */   addiu     $s0, $s0, 0x1
/* 140E34 8024BFF4 0C092CB6 */  jal        pause_badges_scroll_offset_x
/* 140E38 8024BFF8 02E0202D */   daddu     $a0, $s7, $zero
/* 140E3C 8024BFFC 8FAA0094 */  lw         $t2, 0x94($sp)
/* 140E40 8024C000 02C0202D */  daddu      $a0, $s6, $zero
/* 140E44 8024C004 020A0018 */  mult       $s0, $t2
/* 140E48 8024C008 244200EB */  addiu      $v0, $v0, 0xEB
/* 140E4C 8024C00C 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 140E50 8024C010 00101FC3 */  sra        $v1, $s0, 31
/* 140E54 8024C014 01621021 */  addu       $v0, $t3, $v0
/* 140E58 8024C018 00005010 */  mfhi       $t2
/* 140E5C 8024C01C 000A2843 */  sra        $a1, $t2, 1
/* 140E60 8024C020 00A38823 */  subu       $s1, $a1, $v1
/* 140E64 8024C024 00112880 */  sll        $a1, $s1, 2
/* 140E68 8024C028 00B12821 */  addu       $a1, $a1, $s1
/* 140E6C 8024C02C 02052823 */  subu       $a1, $s0, $a1
/* 140E70 8024C030 00051840 */  sll        $v1, $a1, 1
/* 140E74 8024C034 00651821 */  addu       $v1, $v1, $a1
/* 140E78 8024C038 00031840 */  sll        $v1, $v1, 1
/* 140E7C 8024C03C 24630001 */  addiu      $v1, $v1, 0x1
/* 140E80 8024C040 0C092CB2 */  jal        pause_badges_scroll_offset_y
/* 140E84 8024C044 00439021 */   addu      $s2, $v0, $v1
/* 140E88 8024C048 8FAB00C8 */  lw         $t3, 0xC8($sp)
/* 140E8C 8024C04C 24420011 */  addiu      $v0, $v0, 0x11
/* 140E90 8024C050 01621021 */  addu       $v0, $t3, $v0
/* 140E94 8024C054 16800006 */  bnez       $s4, .Lpause_8024C070
/* 140E98 8024C058 00553021 */   addu      $a2, $v0, $s5
/* 140E9C 8024C05C 24C3FFFD */  addiu      $v1, $a2, -0x3
/* 140EA0 8024C060 00111040 */  sll        $v0, $s1, 1
/* 140EA4 8024C064 00511021 */  addu       $v0, $v0, $s1
/* 140EA8 8024C068 00021040 */  sll        $v0, $v0, 1
/* 140EAC 8024C06C 00623021 */  addu       $a2, $v1, $v0
.Lpause_8024C070:
/* 140EB0 8024C070 24040001 */  addiu      $a0, $zero, 0x1
/* 140EB4 8024C074 0C092D22 */  jal        pause_badges_draw_bp_orbs
/* 140EB8 8024C078 0240282D */   daddu     $a1, $s2, $zero
/* 140EBC 8024C07C 26100001 */  addiu      $s0, $s0, 0x1
.Lpause_8024C080:
/* 140EC0 8024C080 0213102A */  slt        $v0, $s0, $s3
/* 140EC4 8024C084 1440FFD7 */  bnez       $v0, .Lpause_8024BFE4
/* 140EC8 8024C088 00000000 */   nop
/* 140ECC 8024C08C 0809305E */  j          .Lpause_8024C178
/* 140ED0 8024C090 00000000 */   nop
.Lpause_8024C094:
/* 140ED4 8024C094 346364FF */  ori        $v1, $v1, (0xFF64FF & 0xFFFF)
/* 140ED8 8024C098 0000802D */  daddu      $s0, $zero, $zero
/* 140EDC 8024C09C 24A20010 */  addiu      $v0, $a1, 0x10
/* 140EE0 8024C0A0 3C0AFA00 */  lui        $t2, (0xFA000000 >> 16)
/* 140EE4 8024C0A4 3C018009 */  lui        $at, %hi(gMainGfxPos)
/* 140EE8 8024C0A8 AC226A44 */  sw         $v0, %lo(gMainGfxPos)($at)
/* 140EEC 8024C0AC ACAA0008 */  sw         $t2, 0x8($a1)
/* 140EF0 8024C0B0 1A600028 */  blez       $s3, .Lpause_8024C154
/* 140EF4 8024C0B4 ACA3000C */   sw        $v1, 0xC($a1)
/* 140EF8 8024C0B8 2A740005 */  slti       $s4, $s3, 0x5
.Lpause_8024C0BC:
/* 140EFC 8024C0BC 0C092CB6 */  jal        pause_badges_scroll_offset_x
/* 140F00 8024C0C0 02E0202D */   daddu     $a0, $s7, $zero
/* 140F04 8024C0C4 8FAA0094 */  lw         $t2, 0x94($sp)
/* 140F08 8024C0C8 02C0202D */  daddu      $a0, $s6, $zero
/* 140F0C 8024C0CC 020A0018 */  mult       $s0, $t2
/* 140F10 8024C0D0 244200EB */  addiu      $v0, $v0, 0xEB
/* 140F14 8024C0D4 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 140F18 8024C0D8 00101FC3 */  sra        $v1, $s0, 31
/* 140F1C 8024C0DC 01621021 */  addu       $v0, $t3, $v0
/* 140F20 8024C0E0 00005010 */  mfhi       $t2
/* 140F24 8024C0E4 000A2843 */  sra        $a1, $t2, 1
/* 140F28 8024C0E8 00A38823 */  subu       $s1, $a1, $v1
/* 140F2C 8024C0EC 00112880 */  sll        $a1, $s1, 2
/* 140F30 8024C0F0 00B12821 */  addu       $a1, $a1, $s1
/* 140F34 8024C0F4 02052823 */  subu       $a1, $s0, $a1
/* 140F38 8024C0F8 00051840 */  sll        $v1, $a1, 1
/* 140F3C 8024C0FC 00651821 */  addu       $v1, $v1, $a1
/* 140F40 8024C100 00031840 */  sll        $v1, $v1, 1
/* 140F44 8024C104 24630001 */  addiu      $v1, $v1, 0x1
/* 140F48 8024C108 0C092CB2 */  jal        pause_badges_scroll_offset_y
/* 140F4C 8024C10C 00439021 */   addu      $s2, $v0, $v1
/* 140F50 8024C110 8FAB00C8 */  lw         $t3, 0xC8($sp)
/* 140F54 8024C114 24420011 */  addiu      $v0, $v0, 0x11
/* 140F58 8024C118 01621021 */  addu       $v0, $t3, $v0
/* 140F5C 8024C11C 16800006 */  bnez       $s4, .Lpause_8024C138
/* 140F60 8024C120 00553021 */   addu      $a2, $v0, $s5
/* 140F64 8024C124 24C3FFFD */  addiu      $v1, $a2, -0x3
/* 140F68 8024C128 00111040 */  sll        $v0, $s1, 1
/* 140F6C 8024C12C 00511021 */  addu       $v0, $v0, $s1
/* 140F70 8024C130 00021040 */  sll        $v0, $v0, 1
/* 140F74 8024C134 00623021 */  addu       $a2, $v1, $v0
.Lpause_8024C138:
/* 140F78 8024C138 24040002 */  addiu      $a0, $zero, 0x2
/* 140F7C 8024C13C 0C092D22 */  jal        pause_badges_draw_bp_orbs
/* 140F80 8024C140 0240282D */   daddu     $a1, $s2, $zero
/* 140F84 8024C144 26100001 */  addiu      $s0, $s0, 0x1
/* 140F88 8024C148 0213102A */  slt        $v0, $s0, $s3
/* 140F8C 8024C14C 1440FFDB */  bnez       $v0, .Lpause_8024C0BC
/* 140F90 8024C150 00000000 */   nop
.Lpause_8024C154:
/* 140F94 8024C154 3C028009 */  lui        $v0, %hi(gMainGfxPos)
/* 140F98 8024C158 8C426A44 */  lw         $v0, %lo(gMainGfxPos)($v0)
/* 140F9C 8024C15C 0040182D */  daddu      $v1, $v0, $zero
/* 140FA0 8024C160 24420008 */  addiu      $v0, $v0, 0x8
/* 140FA4 8024C164 3C018009 */  lui        $at, %hi(gMainGfxPos)
/* 140FA8 8024C168 AC226A44 */  sw         $v0, %lo(gMainGfxPos)($at)
/* 140FAC 8024C16C 3C02E700 */  lui        $v0, (0xE7000000 >> 16)
/* 140FB0 8024C170 AC620000 */  sw         $v0, 0x0($v1)
/* 140FB4 8024C174 AC600004 */  sw         $zero, 0x4($v1)
.Lpause_8024C178:
/* 140FB8 8024C178 8FAA0078 */  lw         $t2, 0x78($sp)
/* 140FBC 8024C17C 8D420008 */  lw         $v0, 0x8($t2)
/* 140FC0 8024C180 27DE0001 */  addiu      $fp, $fp, 0x1
/* 140FC4 8024C184 03C2102A */  slt        $v0, $fp, $v0
/* 140FC8 8024C188 1440FDB2 */  bnez       $v0, .Lpause_8024B854
/* 140FCC 8024C18C 00000000 */   nop
.Lpause_8024C190:
/* 140FD0 8024C190 8FAB0050 */  lw         $t3, 0x50($sp)
/* 140FD4 8024C194 256B0001 */  addiu      $t3, $t3, 0x1
/* 140FD8 8024C198 29620014 */  slti       $v0, $t3, 0x14
/* 140FDC 8024C19C 1440FD96 */  bnez       $v0, .Lpause_8024B7F8
/* 140FE0 8024C1A0 AFAB0050 */   sw        $t3, 0x50($sp)
.Lpause_8024C1A4:
/* 140FE4 8024C1A4 8FAA0054 */  lw         $t2, 0x54($sp)
/* 140FE8 8024C1A8 254A0001 */  addiu      $t2, $t2, 0x1
/* 140FEC 8024C1AC 29420003 */  slti       $v0, $t2, 0x3
/* 140FF0 8024C1B0 1440FD90 */  bnez       $v0, .Lpause_8024B7F4
/* 140FF4 8024C1B4 AFAA0054 */   sw        $t2, 0x54($sp)
/* 140FF8 8024C1B8 3C098009 */  lui        $t1, %hi(gMainGfxPos)
/* 140FFC 8024C1BC 25296A44 */  addiu      $t1, $t1, %lo(gMainGfxPos)
/* 141000 8024C1C0 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 141004 8024C1C4 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 141008 8024C1C8 8D250000 */  lw         $a1, 0x0($t1)
/* 14100C 8024C1CC 25640001 */  addiu      $a0, $t3, 0x1
/* 141010 8024C1D0 25460001 */  addiu      $a2, $t2, 0x1
/* 141014 8024C1D4 00A0182D */  daddu      $v1, $a1, $zero
/* 141018 8024C1D8 8FAA00CC */  lw         $t2, 0xCC($sp)
/* 14101C 8024C1DC 24A50008 */  addiu      $a1, $a1, 0x8
/* 141020 8024C1E0 016A1021 */  addu       $v0, $t3, $t2
/* 141024 8024C1E4 8FAB00C8 */  lw         $t3, 0xC8($sp)
/* 141028 8024C1E8 8FAA00D0 */  lw         $t2, 0xD0($sp)
/* 14102C 8024C1EC 2447FFFF */  addiu      $a3, $v0, -0x1
/* 141030 8024C1F0 016A1021 */  addu       $v0, $t3, $t2
/* 141034 8024C1F4 2448FFFF */  addiu      $t0, $v0, -0x1
/* 141038 8024C1F8 3C02E700 */  lui        $v0, (0xE7000000 >> 16)
/* 14103C 8024C1FC AD250000 */  sw         $a1, 0x0($t1)
/* 141040 8024C200 AC620000 */  sw         $v0, 0x0($v1)
/* 141044 8024C204 1C800002 */  bgtz       $a0, .Lpause_8024C210
/* 141048 8024C208 AC600004 */   sw        $zero, 0x4($v1)
/* 14104C 8024C20C 24040001 */  addiu      $a0, $zero, 0x1
.Lpause_8024C210:
/* 141050 8024C210 58C00001 */  blezl      $a2, .Lpause_8024C218
/* 141054 8024C214 24060001 */   addiu     $a2, $zero, 0x1
.Lpause_8024C218:
/* 141058 8024C218 18E00325 */  blez       $a3, .Lpause_8024CEB0
/* 14105C 8024C21C 00000000 */   nop
/* 141060 8024C220 19000323 */  blez       $t0, .Lpause_8024CEB0
/* 141064 8024C224 2882013F */   slti      $v0, $a0, 0x13F
/* 141068 8024C228 10400321 */  beqz       $v0, .Lpause_8024CEB0
/* 14106C 8024C22C 28C200EF */   slti      $v0, $a2, 0xEF
/* 141070 8024C230 1040031F */  beqz       $v0, .Lpause_8024CEB0
/* 141074 8024C234 28E2013F */   slti      $v0, $a3, 0x13F
/* 141078 8024C238 50400001 */  beql       $v0, $zero, .Lpause_8024C240
/* 14107C 8024C23C 2407013F */   addiu     $a3, $zero, 0x13F
.Lpause_8024C240:
/* 141080 8024C240 290200EF */  slti       $v0, $t0, 0xEF
/* 141084 8024C244 50400001 */  beql       $v0, $zero, .Lpause_8024C24C
/* 141088 8024C248 240800EF */   addiu     $t0, $zero, 0xEF
.Lpause_8024C24C:
/* 14108C 8024C24C 3C014080 */  lui        $at, (0x40800000 >> 16)
/* 141090 8024C250 44812000 */  mtc1       $at, $f4
/* 141094 8024C254 44840000 */  mtc1       $a0, $f0
/* 141098 8024C258 00000000 */  nop
/* 14109C 8024C25C 46800020 */  cvt.s.w    $f0, $f0
/* 1410A0 8024C260 46040002 */  mul.s      $f0, $f0, $f4
/* 1410A4 8024C264 00000000 */  nop
/* 1410A8 8024C268 24A20008 */  addiu      $v0, $a1, 0x8
/* 1410AC 8024C26C 44861000 */  mtc1       $a2, $f2
/* 1410B0 8024C270 00000000 */  nop
/* 1410B4 8024C274 468010A0 */  cvt.s.w    $f2, $f2
/* 1410B8 8024C278 3C04ED00 */  lui        $a0, (0xED000000 >> 16)
/* 1410BC 8024C27C 46041082 */  mul.s      $f2, $f2, $f4
/* 1410C0 8024C280 00000000 */  nop
/* 1410C4 8024C284 AD220000 */  sw         $v0, 0x0($t1)
/* 1410C8 8024C288 4600018D */  trunc.w.s  $f6, $f0
/* 1410CC 8024C28C 44023000 */  mfc1       $v0, $f6
/* 1410D0 8024C290 00000000 */  nop
/* 1410D4 8024C294 30420FFF */  andi       $v0, $v0, 0xFFF
/* 1410D8 8024C298 00021300 */  sll        $v0, $v0, 12
/* 1410DC 8024C29C 4600118D */  trunc.w.s  $f6, $f2
/* 1410E0 8024C2A0 44033000 */  mfc1       $v1, $f6
/* 1410E4 8024C2A4 44871000 */  mtc1       $a3, $f2
/* 1410E8 8024C2A8 00000000 */  nop
/* 1410EC 8024C2AC 468010A0 */  cvt.s.w    $f2, $f2
/* 1410F0 8024C2B0 46041082 */  mul.s      $f2, $f2, $f4
/* 1410F4 8024C2B4 00000000 */  nop
/* 1410F8 8024C2B8 30630FFF */  andi       $v1, $v1, 0xFFF
/* 1410FC 8024C2BC 00641825 */  or         $v1, $v1, $a0
/* 141100 8024C2C0 00431025 */  or         $v0, $v0, $v1
/* 141104 8024C2C4 44880000 */  mtc1       $t0, $f0
/* 141108 8024C2C8 00000000 */  nop
/* 14110C 8024C2CC 46800020 */  cvt.s.w    $f0, $f0
/* 141110 8024C2D0 46040002 */  mul.s      $f0, $f0, $f4
/* 141114 8024C2D4 00000000 */  nop
/* 141118 8024C2D8 ACA20000 */  sw         $v0, 0x0($a1)
/* 14111C 8024C2DC 4600118D */  trunc.w.s  $f6, $f2
/* 141120 8024C2E0 44023000 */  mfc1       $v0, $f6
/* 141124 8024C2E4 00000000 */  nop
/* 141128 8024C2E8 30420FFF */  andi       $v0, $v0, 0xFFF
/* 14112C 8024C2EC 00021300 */  sll        $v0, $v0, 12
/* 141130 8024C2F0 4600018D */  trunc.w.s  $f6, $f0
/* 141134 8024C2F4 44033000 */  mfc1       $v1, $f6
/* 141138 8024C2F8 00000000 */  nop
/* 14113C 8024C2FC 30630FFF */  andi       $v1, $v1, 0xFFF
/* 141140 8024C300 00431025 */  or         $v0, $v0, $v1
/* 141144 8024C304 3C038027 */  lui        $v1, %hi(gPauseMenuCurrentTab)
/* 141148 8024C308 806324A4 */  lb         $v1, %lo(gPauseMenuCurrentTab)($v1)
/* 14114C 8024C30C ACA20004 */  sw         $v0, 0x4($a1)
/* 141150 8024C310 24020002 */  addiu      $v0, $zero, 0x2
/* 141154 8024C314 1462002A */  bne        $v1, $v0, .Lpause_8024C3C0
/* 141158 8024C318 24020001 */   addiu     $v0, $zero, 0x1
/* 14115C 8024C31C 3C038027 */  lui        $v1, %hi(gPauseBadgesLevel)
/* 141160 8024C320 8C632768 */  lw         $v1, %lo(gPauseBadgesLevel)($v1)
/* 141164 8024C324 14620026 */  bne        $v1, $v0, .Lpause_8024C3C0
/* 141168 8024C328 00000000 */   nop
/* 14116C 8024C32C 3C118027 */  lui        $s1, %hi(gPauseBadgesCurrentPage)
/* 141170 8024C330 26312650 */  addiu      $s1, $s1, %lo(gPauseBadgesCurrentPage)
/* 141174 8024C334 8E220000 */  lw         $v0, 0x0($s1)
/* 141178 8024C338 1840000E */  blez       $v0, .Lpause_8024C374
/* 14117C 8024C33C 24420001 */   addiu     $v0, $v0, 0x1
/* 141180 8024C340 3C108027 */  lui        $s0, %hi(gPauseBadgesIconIDs)
/* 141184 8024C344 26102778 */  addiu      $s0, $s0, %lo(gPauseBadgesIconIDs)
/* 141188 8024C348 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 14118C 8024C34C 8E040044 */  lw         $a0, 0x44($s0)
/* 141190 8024C350 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 141194 8024C354 25650116 */  addiu      $a1, $t3, 0x116
/* 141198 8024C358 0C050D4D */  jal        hud_element_set_render_pos
/* 14119C 8024C35C 2546000E */   addiu     $a2, $t2, 0xE
/* 1411A0 8024C360 8E040044 */  lw         $a0, 0x44($s0)
/* 1411A4 8024C364 0C050CE4 */  jal        hud_element_draw_without_clipping
/* 1411A8 8024C368 00000000 */   nop
/* 1411AC 8024C36C 8E220000 */  lw         $v0, 0x0($s1)
/* 1411B0 8024C370 24420001 */  addiu      $v0, $v0, 0x1
.Lpause_8024C374:
/* 1411B4 8024C374 00021840 */  sll        $v1, $v0, 1
/* 1411B8 8024C378 00621821 */  addu       $v1, $v1, $v0
/* 1411BC 8024C37C 00031880 */  sll        $v1, $v1, 2
/* 1411C0 8024C380 3C028027 */  lui        $v0, %hi(gPauseBadgesPages)
/* 1411C4 8024C384 00431021 */  addu       $v0, $v0, $v1
/* 1411C8 8024C388 90422658 */  lbu        $v0, %lo(gPauseBadgesPages)($v0)
/* 1411CC 8024C38C 1040000C */  beqz       $v0, .Lpause_8024C3C0
/* 1411D0 8024C390 00000000 */   nop
/* 1411D4 8024C394 3C108027 */  lui        $s0, %hi(gPauseBadgesIconIDs)
/* 1411D8 8024C398 26102778 */  addiu      $s0, $s0, %lo(gPauseBadgesIconIDs)
/* 1411DC 8024C39C 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 1411E0 8024C3A0 8E040048 */  lw         $a0, 0x48($s0)
/* 1411E4 8024C3A4 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 1411E8 8024C3A8 25650116 */  addiu      $a1, $t3, 0x116
/* 1411EC 8024C3AC 0C050D4D */  jal        hud_element_set_render_pos
/* 1411F0 8024C3B0 25460092 */   addiu     $a2, $t2, 0x92
/* 1411F4 8024C3B4 8E040048 */  lw         $a0, 0x48($s0)
/* 1411F8 8024C3B8 0C050CE4 */  jal        hud_element_draw_without_clipping
/* 1411FC 8024C3BC 00000000 */   nop
.Lpause_8024C3C0:
/* 141200 8024C3C0 3C108027 */  lui        $s0, %hi(gPauseBadgesIconIDs)
/* 141204 8024C3C4 26102778 */  addiu      $s0, $s0, %lo(gPauseBadgesIconIDs)
/* 141208 8024C3C8 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 14120C 8024C3CC 8E040040 */  lw         $a0, 0x40($s0)
/* 141210 8024C3D0 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 141214 8024C3D4 2565002B */  addiu      $a1, $t3, 0x2B
/* 141218 8024C3D8 0C050D4D */  jal        hud_element_set_render_pos
/* 14121C 8024C3DC 25460051 */   addiu     $a2, $t2, 0x51
/* 141220 8024C3E0 8E040040 */  lw         $a0, 0x40($s0)
/* 141224 8024C3E4 0C050CE4 */  jal        hud_element_draw_without_clipping
/* 141228 8024C3E8 2414000A */   addiu     $s4, $zero, 0xA
/* 14122C 8024C3EC 0C094C60 */  jal        pause_get_menu_msg
/* 141230 8024C3F0 24040040 */   addiu     $a0, $zero, 0x40
/* 141234 8024C3F4 0040202D */  daddu      $a0, $v0, $zero
/* 141238 8024C3F8 240700FF */  addiu      $a3, $zero, 0xFF
/* 14123C 8024C3FC 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 141240 8024C400 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 141244 8024C404 24020001 */  addiu      $v0, $zero, 0x1
/* 141248 8024C408 AFB40010 */  sw         $s4, 0x10($sp)
/* 14124C 8024C40C AFA20014 */  sw         $v0, 0x14($sp)
/* 141250 8024C410 25650010 */  addiu      $a1, $t3, 0x10
/* 141254 8024C414 2550004A */  addiu      $s0, $t2, 0x4A
/* 141258 8024C418 0C049403 */  jal        draw_msg
/* 14125C 8024C41C 0200302D */   daddu     $a2, $s0, $zero
/* 141260 8024C420 0200302D */  daddu      $a2, $s0, $zero
/* 141264 8024C424 24070001 */  addiu      $a3, $zero, 0x1
/* 141268 8024C428 241500FF */  addiu      $s5, $zero, 0xFF
/* 14126C 8024C42C 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 141270 8024C430 3C048011 */  lui        $a0, %hi(gPlayerData+0x8)
/* 141274 8024C434 8084DD98 */  lb         $a0, %lo(gPlayerData+0x8)($a0)
/* 141278 8024C438 24130003 */  addiu      $s3, $zero, 0x3
/* 14127C 8024C43C AFB40010 */  sw         $s4, 0x10($sp)
/* 141280 8024C440 AFB50014 */  sw         $s5, 0x14($sp)
/* 141284 8024C444 AFB30018 */  sw         $s3, 0x18($sp)
/* 141288 8024C448 0C04986F */  jal        draw_number
/* 14128C 8024C44C 25650045 */   addiu     $a1, $t3, 0x45
/* 141290 8024C450 0C0921C1 */  jal        pause_get_total_equipped_bp_cost
/* 141294 8024C454 0000882D */   daddu     $s1, $zero, $zero
/* 141298 8024C458 3C056666 */  lui        $a1, (0x66666667 >> 16)
/* 14129C 8024C45C 3C048011 */  lui        $a0, %hi(gPlayerData+0x8)
/* 1412A0 8024C460 8084DD98 */  lb         $a0, %lo(gPlayerData+0x8)($a0)
/* 1412A4 8024C464 34A56667 */  ori        $a1, $a1, (0x66666667 & 0xFFFF)
/* 1412A8 8024C468 2483FFFF */  addiu      $v1, $a0, -0x1
/* 1412AC 8024C46C 00650018 */  mult       $v1, $a1
/* 1412B0 8024C470 00829023 */  subu       $s2, $a0, $v0
/* 1412B4 8024C474 00031FC3 */  sra        $v1, $v1, 31
/* 1412B8 8024C478 00005010 */  mfhi       $t2
/* 1412BC 8024C47C 000A1083 */  sra        $v0, $t2, 2
/* 1412C0 8024C480 00431023 */  subu       $v0, $v0, $v1
/* 1412C4 8024C484 02621804 */  sllv       $v1, $v0, $s3
/* 1412C8 8024C488 0254102A */  slt        $v0, $s2, $s4
/* 1412CC 8024C48C 54400001 */  bnel       $v0, $zero, .Lpause_8024C494
/* 1412D0 8024C490 2411FFFC */   addiu     $s1, $zero, -0x4
.Lpause_8024C494:
/* 1412D4 8024C494 24040007 */  addiu      $a0, $zero, 0x7
/* 1412D8 8024C498 24620064 */  addiu      $v0, $v1, 0x64
/* 1412DC 8024C49C 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 1412E0 8024C4A0 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 1412E4 8024C4A4 2565000C */  addiu      $a1, $t3, 0xC
/* 1412E8 8024C4A8 01428021 */  addu       $s0, $t2, $v0
/* 1412EC 8024C4AC 0C094C65 */  jal        pause_draw_menu_label
/* 1412F0 8024C4B0 0200302D */   daddu     $a2, $s0, $zero
/* 1412F4 8024C4B4 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 1412F8 8024C4B8 3C038015 */  lui        $v1, %hi(gCurrentLanguage)
/* 1412FC 8024C4BC 8C63AE4C */  lw         $v1, %lo(gCurrentLanguage)($v1)
/* 141300 8024C4C0 25620049 */  addiu      $v0, $t3, 0x49
/* 141304 8024C4C4 14730002 */  bne        $v1, $s3, .Lpause_8024C4D0
/* 141308 8024C4C8 00512821 */   addu      $a1, $v0, $s1
/* 14130C 8024C4CC 24A50008 */  addiu      $a1, $a1, 0x8
.Lpause_8024C4D0:
/* 141310 8024C4D0 0240202D */  daddu      $a0, $s2, $zero
/* 141314 8024C4D4 0200302D */  daddu      $a2, $s0, $zero
/* 141318 8024C4D8 24070001 */  addiu      $a3, $zero, 0x1
/* 14131C 8024C4DC AFB40010 */  sw         $s4, 0x10($sp)
/* 141320 8024C4E0 AFB50014 */  sw         $s5, 0x14($sp)
/* 141324 8024C4E4 0C04986F */  jal        draw_number
/* 141328 8024C4E8 AFB30018 */   sw        $s3, 0x18($sp)
/* 14132C 8024C4EC 3C05E300 */  lui        $a1, (0xE3001201 >> 16)
/* 141330 8024C4F0 34A51201 */  ori        $a1, $a1, (0xE3001201 & 0xFFFF)
/* 141334 8024C4F4 3C068009 */  lui        $a2, %hi(gMainGfxPos)
/* 141338 8024C4F8 24C66A44 */  addiu      $a2, $a2, %lo(gMainGfxPos)
/* 14133C 8024C4FC 0000882D */  daddu      $s1, $zero, $zero
/* 141340 8024C500 3C02DE00 */  lui        $v0, (0xDE000000 >> 16)
/* 141344 8024C504 0220B02D */  daddu      $s6, $s1, $zero
/* 141348 8024C508 8CC30000 */  lw         $v1, 0x0($a2)
/* 14134C 8024C50C 241700FF */  addiu      $s7, $zero, 0xFF
/* 141350 8024C510 0060202D */  daddu      $a0, $v1, $zero
/* 141354 8024C514 24630008 */  addiu      $v1, $v1, 0x8
/* 141358 8024C518 ACC30000 */  sw         $v1, 0x0($a2)
/* 14135C 8024C51C 3C108011 */  lui        $s0, %hi(gPlayerData+0x8)
/* 141360 8024C520 8210DD98 */  lb         $s0, %lo(gPlayerData+0x8)($s0)
/* 141364 8024C524 241E0064 */  addiu      $fp, $zero, 0x64
/* 141368 8024C528 AC820000 */  sw         $v0, 0x0($a0)
/* 14136C 8024C52C 3C028027 */  lui        $v0, %hi(gPauseDLOrbs)
/* 141370 8024C530 24421818 */  addiu      $v0, $v0, %lo(gPauseDLOrbs)
/* 141374 8024C534 AC820004 */  sw         $v0, 0x4($a0)
/* 141378 8024C538 24620008 */  addiu      $v0, $v1, 0x8
/* 14137C 8024C53C ACC20000 */  sw         $v0, 0x0($a2)
/* 141380 8024C540 24022000 */  addiu      $v0, $zero, 0x2000
/* 141384 8024C544 AC650000 */  sw         $a1, 0x0($v1)
/* 141388 8024C548 1A000026 */  blez       $s0, .Lpause_8024C5E4
/* 14138C 8024C54C AC620004 */   sw        $v0, 0x4($v1)
/* 141390 8024C550 00C0902D */  daddu      $s2, $a2, $zero
/* 141394 8024C554 3C15FA00 */  lui        $s5, (0xFA000000 >> 16)
/* 141398 8024C558 3C14E3E3 */  lui        $s4, (0xE3E3E3FF >> 16)
/* 14139C 8024C55C 3694E3FF */  ori        $s4, $s4, (0xE3E3E3FF & 0xFFFF)
/* 1413A0 8024C560 3C136666 */  lui        $s3, (0x66666667 >> 16)
/* 1413A4 8024C564 36736667 */  ori        $s3, $s3, (0x66666667 & 0xFFFF)
/* 1413A8 8024C568 0000202D */  daddu      $a0, $zero, $zero
.Lpause_8024C56C:
/* 1413AC 8024C56C 8E420000 */  lw         $v0, 0x0($s2)
/* 1413B0 8024C570 02330018 */  mult       $s1, $s3
/* 1413B4 8024C574 0040182D */  daddu      $v1, $v0, $zero
/* 1413B8 8024C578 24420008 */  addiu      $v0, $v0, 0x8
/* 1413BC 8024C57C AE420000 */  sw         $v0, 0x0($s2)
/* 1413C0 8024C580 001117C3 */  sra        $v0, $s1, 31
/* 1413C4 8024C584 AC750000 */  sw         $s5, 0x0($v1)
/* 1413C8 8024C588 AC740004 */  sw         $s4, 0x4($v1)
/* 1413CC 8024C58C 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 1413D0 8024C590 00005010 */  mfhi       $t2
/* 1413D4 8024C594 000A3083 */  sra        $a2, $t2, 2
/* 1413D8 8024C598 00C23023 */  subu       $a2, $a2, $v0
/* 1413DC 8024C59C 00061080 */  sll        $v0, $a2, 2
/* 1413E0 8024C5A0 00461021 */  addu       $v0, $v0, $a2
/* 1413E4 8024C5A4 00021040 */  sll        $v0, $v0, 1
/* 1413E8 8024C5A8 02221023 */  subu       $v0, $s1, $v0
/* 1413EC 8024C5AC 00022840 */  sll        $a1, $v0, 1
/* 1413F0 8024C5B0 00A22821 */  addu       $a1, $a1, $v0
/* 1413F4 8024C5B4 00052840 */  sll        $a1, $a1, 1
/* 1413F8 8024C5B8 24A5000B */  addiu      $a1, $a1, 0xB
/* 1413FC 8024C5BC 01652821 */  addu       $a1, $t3, $a1
/* 141400 8024C5C0 000630C0 */  sll        $a2, $a2, 3
/* 141404 8024C5C4 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 141408 8024C5C8 24C6005C */  addiu      $a2, $a2, 0x5C
/* 14140C 8024C5CC 0C092D22 */  jal        pause_badges_draw_bp_orbs
/* 141410 8024C5D0 01463021 */   addu      $a2, $t2, $a2
/* 141414 8024C5D4 26310001 */  addiu      $s1, $s1, 0x1
/* 141418 8024C5D8 0230102A */  slt        $v0, $s1, $s0
/* 14141C 8024C5DC 1440FFE3 */  bnez       $v0, .Lpause_8024C56C
/* 141420 8024C5E0 0000202D */   daddu     $a0, $zero, $zero
.Lpause_8024C5E4:
/* 141424 8024C5E4 3C058009 */  lui        $a1, %hi(gMainGfxPos)
/* 141428 8024C5E8 24A56A44 */  addiu      $a1, $a1, %lo(gMainGfxPos)
/* 14142C 8024C5EC 8CA40000 */  lw         $a0, 0x0($a1)
/* 141430 8024C5F0 3C02E700 */  lui        $v0, (0xE7000000 >> 16)
/* 141434 8024C5F4 0080182D */  daddu      $v1, $a0, $zero
/* 141438 8024C5F8 24840008 */  addiu      $a0, $a0, 0x8
/* 14143C 8024C5FC ACA40000 */  sw         $a0, 0x0($a1)
/* 141440 8024C600 AC620000 */  sw         $v0, 0x0($v1)
/* 141444 8024C604 AC600004 */  sw         $zero, 0x4($v1)
/* 141448 8024C608 8FAB0074 */  lw         $t3, 0x74($sp)
/* 14144C 8024C60C 11600089 */  beqz       $t3, .Lpause_8024C834
/* 141450 8024C610 24820008 */   addiu     $v0, $a0, 0x8
/* 141454 8024C614 ACA20000 */  sw         $v0, 0x0($a1)
/* 141458 8024C618 3C02FA00 */  lui        $v0, (0xFA000000 >> 16)
/* 14145C 8024C61C AC820000 */  sw         $v0, 0x0($a0)
/* 141460 8024C620 00171400 */  sll        $v0, $s7, 16
/* 141464 8024C624 001E1A00 */  sll        $v1, $fp, 8
/* 141468 8024C628 00431025 */  or         $v0, $v0, $v1
/* 14146C 8024C62C 344200FF */  ori        $v0, $v0, 0xFF
/* 141470 8024C630 AC820004 */  sw         $v0, 0x4($a0)
/* 141474 8024C634 8FAA006C */  lw         $t2, 0x6C($sp)
/* 141478 8024C638 8FAB0070 */  lw         $t3, 0x70($sp)
/* 14147C 8024C63C 014B1023 */  subu       $v0, $t2, $t3
/* 141480 8024C640 1840001D */  blez       $v0, .Lpause_8024C6B8
/* 141484 8024C644 0000882D */   daddu     $s1, $zero, $zero
/* 141488 8024C648 3C126666 */  lui        $s2, (0x66666667 >> 16)
/* 14148C 8024C64C 36526667 */  ori        $s2, $s2, (0x66666667 & 0xFFFF)
/* 141490 8024C650 0040802D */  daddu      $s0, $v0, $zero
/* 141494 8024C654 02320018 */  mult       $s1, $s2
.Lpause_8024C658:
/* 141498 8024C658 24040002 */  addiu      $a0, $zero, 0x2
/* 14149C 8024C65C 001117C3 */  sra        $v0, $s1, 31
/* 1414A0 8024C660 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 1414A4 8024C664 00005010 */  mfhi       $t2
/* 1414A8 8024C668 008A3007 */  srav       $a2, $t2, $a0
/* 1414AC 8024C66C 00C23023 */  subu       $a2, $a2, $v0
/* 1414B0 8024C670 00861004 */  sllv       $v0, $a2, $a0
/* 1414B4 8024C674 00461021 */  addu       $v0, $v0, $a2
/* 1414B8 8024C678 00021040 */  sll        $v0, $v0, 1
/* 1414BC 8024C67C 02221023 */  subu       $v0, $s1, $v0
/* 1414C0 8024C680 00022840 */  sll        $a1, $v0, 1
/* 1414C4 8024C684 00A22821 */  addu       $a1, $a1, $v0
/* 1414C8 8024C688 00052840 */  sll        $a1, $a1, 1
/* 1414CC 8024C68C 24A5000B */  addiu      $a1, $a1, 0xB
/* 1414D0 8024C690 01652821 */  addu       $a1, $t3, $a1
/* 1414D4 8024C694 000630C0 */  sll        $a2, $a2, 3
/* 1414D8 8024C698 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 1414DC 8024C69C 24C6005C */  addiu      $a2, $a2, 0x5C
/* 1414E0 8024C6A0 0C092D22 */  jal        pause_badges_draw_bp_orbs
/* 1414E4 8024C6A4 01463021 */   addu      $a2, $t2, $a2
/* 1414E8 8024C6A8 26310001 */  addiu      $s1, $s1, 0x1
/* 1414EC 8024C6AC 0230102A */  slt        $v0, $s1, $s0
/* 1414F0 8024C6B0 1440FFE9 */  bnez       $v0, .Lpause_8024C658
/* 1414F4 8024C6B4 02320018 */   mult      $s1, $s2
.Lpause_8024C6B8:
/* 1414F8 8024C6B8 3C108009 */  lui        $s0, %hi(gMainGfxPos)
/* 1414FC 8024C6BC 26106A44 */  addiu      $s0, $s0, %lo(gMainGfxPos)
/* 141500 8024C6C0 3C02E700 */  lui        $v0, (0xE7000000 >> 16)
/* 141504 8024C6C4 8E030000 */  lw         $v1, 0x0($s0)
/* 141508 8024C6C8 8FAB006C */  lw         $t3, 0x6C($sp)
/* 14150C 8024C6CC 8FAA0070 */  lw         $t2, 0x70($sp)
/* 141510 8024C6D0 3C058007 */  lui        $a1, %hi(gGameStatusPtr)
/* 141514 8024C6D4 8CA514AC */  lw         $a1, %lo(gGameStatusPtr)($a1)
/* 141518 8024C6D8 016A8823 */  subu       $s1, $t3, $t2
/* 14151C 8024C6DC 0060202D */  daddu      $a0, $v1, $zero
/* 141520 8024C6E0 AC820000 */  sw         $v0, 0x0($a0)
/* 141524 8024C6E4 AC800004 */  sw         $zero, 0x4($a0)
/* 141528 8024C6E8 94A40134 */  lhu        $a0, 0x134($a1)
/* 14152C 8024C6EC 24630008 */  addiu      $v1, $v1, 0x8
/* 141530 8024C6F0 00041100 */  sll        $v0, $a0, 4
/* 141534 8024C6F4 00441023 */  subu       $v0, $v0, $a0
/* 141538 8024C6F8 44826000 */  mtc1       $v0, $f12
/* 14153C 8024C6FC 00000000 */  nop
/* 141540 8024C700 46806320 */  cvt.s.w    $f12, $f12
/* 141544 8024C704 0C00A89B */  jal        sin_deg
/* 141548 8024C708 AE030000 */   sw        $v1, 0x0($s0)
/* 14154C 8024C70C 3C04E200 */  lui        $a0, (0xE200001C >> 16)
/* 141550 8024C710 3484001C */  ori        $a0, $a0, (0xE200001C & 0xFFFF)
/* 141554 8024C714 3C030050 */  lui        $v1, (0x504340 >> 16)
/* 141558 8024C718 34634340 */  ori        $v1, $v1, (0x504340 & 0xFFFF)
/* 14155C 8024C71C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
/* 141560 8024C720 44811000 */  mtc1       $at, $f2
/* 141564 8024C724 8E050000 */  lw         $a1, 0x0($s0)
/* 141568 8024C728 46020000 */  add.s      $f0, $f0, $f2
/* 14156C 8024C72C 00A0102D */  daddu      $v0, $a1, $zero
/* 141570 8024C730 3C018027 */  lui        $at, %hi(D_pause_80272380)
/* 141574 8024C734 D4222380 */  ldc1       $f2, %lo(D_pause_80272380)($at)
/* 141578 8024C738 46000021 */  cvt.d.s    $f0, $f0
/* 14157C 8024C73C 46220002 */  mul.d      $f0, $f0, $f2
/* 141580 8024C740 00000000 */  nop
/* 141584 8024C744 24A50008 */  addiu      $a1, $a1, 0x8
/* 141588 8024C748 AE050000 */  sw         $a1, 0x0($s0)
/* 14158C 8024C74C AC440000 */  sw         $a0, 0x0($v0)
/* 141590 8024C750 AC430004 */  sw         $v1, 0x4($v0)
/* 141594 8024C754 3C013FE0 */  lui        $at, (0x3FE00000 >> 16)
/* 141598 8024C758 44811800 */  mtc1       $at, $f3
/* 14159C 8024C75C 44801000 */  mtc1       $zero, $f2
/* 1415A0 8024C760 24A20008 */  addiu      $v0, $a1, 0x8
/* 1415A4 8024C764 AE020000 */  sw         $v0, 0x0($s0)
/* 1415A8 8024C768 46220000 */  add.d      $f0, $f0, $f2
/* 1415AC 8024C76C 3C02FA00 */  lui        $v0, (0xFA000000 >> 16)
/* 1415B0 8024C770 3C01437F */  lui        $at, (0x437F0000 >> 16)
/* 1415B4 8024C774 44811000 */  mtc1       $at, $f2
/* 1415B8 8024C778 46200020 */  cvt.s.d    $f0, $f0
/* 1415BC 8024C77C 46020002 */  mul.s      $f0, $f0, $f2
/* 1415C0 8024C780 00000000 */  nop
/* 1415C4 8024C784 ACA20000 */  sw         $v0, 0x0($a1)
/* 1415C8 8024C788 00171400 */  sll        $v0, $s7, 16
/* 1415CC 8024C78C 001E1A00 */  sll        $v1, $fp, 8
/* 1415D0 8024C790 00431025 */  or         $v0, $v0, $v1
/* 1415D4 8024C794 4600018D */  trunc.w.s  $f6, $f0
/* 1415D8 8024C798 44043000 */  mfc1       $a0, $f6
/* 1415DC 8024C79C 00000000 */  nop
/* 1415E0 8024C7A0 308400FF */  andi       $a0, $a0, 0xFF
/* 1415E4 8024C7A4 00441025 */  or         $v0, $v0, $a0
/* 1415E8 8024C7A8 ACA20004 */  sw         $v0, 0x4($a1)
/* 1415EC 8024C7AC 8FAB006C */  lw         $t3, 0x6C($sp)
/* 1415F0 8024C7B0 022B102A */  slt        $v0, $s1, $t3
/* 1415F4 8024C7B4 10400046 */  beqz       $v0, .Lpause_8024C8D0
/* 1415F8 8024C7B8 00000000 */   nop
/* 1415FC 8024C7BC 3C106666 */  lui        $s0, (0x66666667 >> 16)
/* 141600 8024C7C0 36106667 */  ori        $s0, $s0, (0x66666667 & 0xFFFF)
/* 141604 8024C7C4 02300018 */  mult       $s1, $s0
.Lpause_8024C7C8:
/* 141608 8024C7C8 24040002 */  addiu      $a0, $zero, 0x2
/* 14160C 8024C7CC 001117C3 */  sra        $v0, $s1, 31
/* 141610 8024C7D0 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 141614 8024C7D4 00005010 */  mfhi       $t2
/* 141618 8024C7D8 008A3007 */  srav       $a2, $t2, $a0
/* 14161C 8024C7DC 00C23023 */  subu       $a2, $a2, $v0
/* 141620 8024C7E0 00861004 */  sllv       $v0, $a2, $a0
/* 141624 8024C7E4 00461021 */  addu       $v0, $v0, $a2
/* 141628 8024C7E8 00021040 */  sll        $v0, $v0, 1
/* 14162C 8024C7EC 02221023 */  subu       $v0, $s1, $v0
/* 141630 8024C7F0 00022840 */  sll        $a1, $v0, 1
/* 141634 8024C7F4 00A22821 */  addu       $a1, $a1, $v0
/* 141638 8024C7F8 00052840 */  sll        $a1, $a1, 1
/* 14163C 8024C7FC 24A5000B */  addiu      $a1, $a1, 0xB
/* 141640 8024C800 01652821 */  addu       $a1, $t3, $a1
/* 141644 8024C804 000630C0 */  sll        $a2, $a2, 3
/* 141648 8024C808 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 14164C 8024C80C 24C6005C */  addiu      $a2, $a2, 0x5C
/* 141650 8024C810 0C092D22 */  jal        pause_badges_draw_bp_orbs
/* 141654 8024C814 01463021 */   addu      $a2, $t2, $a2
/* 141658 8024C818 8FAB006C */  lw         $t3, 0x6C($sp)
/* 14165C 8024C81C 26310001 */  addiu      $s1, $s1, 0x1
/* 141660 8024C820 022B102A */  slt        $v0, $s1, $t3
/* 141664 8024C824 1440FFE8 */  bnez       $v0, .Lpause_8024C7C8
/* 141668 8024C828 02300018 */   mult      $s1, $s0
/* 14166C 8024C82C 08093234 */  j          .Lpause_8024C8D0
/* 141670 8024C830 00000000 */   nop
.Lpause_8024C834:
/* 141674 8024C834 ACA20000 */  sw         $v0, 0x0($a1)
/* 141678 8024C838 3C02FA00 */  lui        $v0, (0xFA000000 >> 16)
/* 14167C 8024C83C AC820000 */  sw         $v0, 0x0($a0)
/* 141680 8024C840 00171400 */  sll        $v0, $s7, 16
/* 141684 8024C844 001E1A00 */  sll        $v1, $fp, 8
/* 141688 8024C848 00431025 */  or         $v0, $v0, $v1
/* 14168C 8024C84C 344200FF */  ori        $v0, $v0, 0xFF
/* 141690 8024C850 AC820004 */  sw         $v0, 0x4($a0)
/* 141694 8024C854 8FAA006C */  lw         $t2, 0x6C($sp)
/* 141698 8024C858 1940001D */  blez       $t2, .Lpause_8024C8D0
/* 14169C 8024C85C 0000882D */   daddu     $s1, $zero, $zero
/* 1416A0 8024C860 3C106666 */  lui        $s0, (0x66666667 >> 16)
/* 1416A4 8024C864 36106667 */  ori        $s0, $s0, (0x66666667 & 0xFFFF)
/* 1416A8 8024C868 02300018 */  mult       $s1, $s0
.Lpause_8024C86C:
/* 1416AC 8024C86C 24040002 */  addiu      $a0, $zero, 0x2
/* 1416B0 8024C870 001117C3 */  sra        $v0, $s1, 31
/* 1416B4 8024C874 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 1416B8 8024C878 00005010 */  mfhi       $t2
/* 1416BC 8024C87C 008A3007 */  srav       $a2, $t2, $a0
/* 1416C0 8024C880 00C23023 */  subu       $a2, $a2, $v0
/* 1416C4 8024C884 00861004 */  sllv       $v0, $a2, $a0
/* 1416C8 8024C888 00461021 */  addu       $v0, $v0, $a2
/* 1416CC 8024C88C 00021040 */  sll        $v0, $v0, 1
/* 1416D0 8024C890 02221023 */  subu       $v0, $s1, $v0
/* 1416D4 8024C894 00022840 */  sll        $a1, $v0, 1
/* 1416D8 8024C898 00A22821 */  addu       $a1, $a1, $v0
/* 1416DC 8024C89C 00052840 */  sll        $a1, $a1, 1
/* 1416E0 8024C8A0 24A5000B */  addiu      $a1, $a1, 0xB
/* 1416E4 8024C8A4 01652821 */  addu       $a1, $t3, $a1
/* 1416E8 8024C8A8 000630C0 */  sll        $a2, $a2, 3
/* 1416EC 8024C8AC 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 1416F0 8024C8B0 24C6005C */  addiu      $a2, $a2, 0x5C
/* 1416F4 8024C8B4 0C092D22 */  jal        pause_badges_draw_bp_orbs
/* 1416F8 8024C8B8 01463021 */   addu      $a2, $t2, $a2
/* 1416FC 8024C8BC 8FAB006C */  lw         $t3, 0x6C($sp)
/* 141700 8024C8C0 26310001 */  addiu      $s1, $s1, 0x1
/* 141704 8024C8C4 022B102A */  slt        $v0, $s1, $t3
/* 141708 8024C8C8 1440FFE8 */  bnez       $v0, .Lpause_8024C86C
/* 14170C 8024C8CC 02300018 */   mult      $s1, $s0
.Lpause_8024C8D0:
/* 141710 8024C8D0 3C038009 */  lui        $v1, %hi(gMainGfxPos)
/* 141714 8024C8D4 24636A44 */  addiu      $v1, $v1, %lo(gMainGfxPos)
/* 141718 8024C8D8 8C620000 */  lw         $v0, 0x0($v1)
/* 14171C 8024C8DC 0040202D */  daddu      $a0, $v0, $zero
/* 141720 8024C8E0 24420008 */  addiu      $v0, $v0, 0x8
/* 141724 8024C8E4 AC620000 */  sw         $v0, 0x0($v1)
/* 141728 8024C8E8 3C02E700 */  lui        $v0, (0xE7000000 >> 16)
/* 14172C 8024C8EC AC820000 */  sw         $v0, 0x0($a0)
/* 141730 8024C8F0 AC800004 */  sw         $zero, 0x4($a0)
/* 141734 8024C8F4 3C038027 */  lui        $v1, %hi(gPauseBadgesCurrentTab)
/* 141738 8024C8F8 8C63276C */  lw         $v1, %lo(gPauseBadgesCurrentTab)($v1)
/* 14173C 8024C8FC 8FA600C4 */  lw         $a2, 0xC4($sp)
/* 141740 8024C900 50600001 */  beql       $v1, $zero, .Lpause_8024C908
/* 141744 8024C904 24C60009 */   addiu     $a2, $a2, 0x9
.Lpause_8024C908:
/* 141748 8024C908 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 14174C 8024C90C 2402005B */  addiu      $v0, $zero, 0x5B
/* 141750 8024C910 AFA20014 */  sw         $v0, 0x14($sp)
/* 141754 8024C914 24020022 */  addiu      $v0, $zero, 0x22
/* 141758 8024C918 AFA20018 */  sw         $v0, 0x18($sp)
/* 14175C 8024C91C 240200FF */  addiu      $v0, $zero, 0xFF
/* 141760 8024C920 AFA2001C */  sw         $v0, 0x1C($sp)
/* 141764 8024C924 24020001 */  addiu      $v0, $zero, 0x1
/* 141768 8024C928 AFA00010 */  sw         $zero, 0x10($sp)
/* 14176C 8024C92C 14620004 */  bne        $v1, $v0, .Lpause_8024C940
/* 141770 8024C930 25470007 */   addiu     $a3, $t2, 0x7
/* 141774 8024C934 24020080 */  addiu      $v0, $zero, 0x80
/* 141778 8024C938 08093251 */  j          .Lpause_8024C944
/* 14177C 8024C93C AFA20020 */   sw        $v0, 0x20($sp)
.Lpause_8024C940:
/* 141780 8024C940 AFA00020 */  sw         $zero, 0x20($sp)
.Lpause_8024C944:
/* 141784 8024C944 24040004 */  addiu      $a0, $zero, 0x4
/* 141788 8024C948 3C058027 */  lui        $a1, %hi(gPauseWS_13)
/* 14178C 8024C94C 24A51FA8 */  addiu      $a1, $a1, %lo(gPauseWS_13)
/* 141790 8024C950 24020140 */  addiu      $v0, $zero, 0x140
/* 141794 8024C954 AFA20044 */  sw         $v0, 0x44($sp)
/* 141798 8024C958 240200F0 */  addiu      $v0, $zero, 0xF0
/* 14179C 8024C95C AFA00024 */  sw         $zero, 0x24($sp)
/* 1417A0 8024C960 AFA00028 */  sw         $zero, 0x28($sp)
/* 1417A4 8024C964 AFA0002C */  sw         $zero, 0x2C($sp)
/* 1417A8 8024C968 AFA00030 */  sw         $zero, 0x30($sp)
/* 1417AC 8024C96C AFA00034 */  sw         $zero, 0x34($sp)
/* 1417B0 8024C970 AFA00038 */  sw         $zero, 0x38($sp)
/* 1417B4 8024C974 AFA0003C */  sw         $zero, 0x3C($sp)
/* 1417B8 8024C978 AFA00040 */  sw         $zero, 0x40($sp)
/* 1417BC 8024C97C AFA20048 */  sw         $v0, 0x48($sp)
/* 1417C0 8024C980 0C03C5C4 */  jal        draw_box
/* 1417C4 8024C984 AFA0004C */   sw        $zero, 0x4C($sp)
/* 1417C8 8024C988 3C128015 */  lui        $s2, %hi(gCurrentLanguage)
/* 1417CC 8024C98C 2652AE4C */  addiu      $s2, $s2, %lo(gCurrentLanguage)
/* 1417D0 8024C990 8E420000 */  lw         $v0, 0x0($s2)
/* 1417D4 8024C994 28420002 */  slti       $v0, $v0, 0x2
/* 1417D8 8024C998 10400013 */  beqz       $v0, .Lpause_8024C9E8
/* 1417DC 8024C99C 00000000 */   nop
/* 1417E0 8024C9A0 0C094C60 */  jal        pause_get_menu_msg
/* 1417E4 8024C9A4 24040041 */   addiu     $a0, $zero, 0x41
/* 1417E8 8024C9A8 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 1417EC 8024C9AC 3C038027 */  lui        $v1, %hi(gPauseBadgesCurrentTab)
/* 1417F0 8024C9B0 8C63276C */  lw         $v1, %lo(gPauseBadgesCurrentTab)($v1)
/* 1417F4 8024C9B4 14600002 */  bnez       $v1, .Lpause_8024C9C0
/* 1417F8 8024C9B8 2565000A */   addiu     $a1, $t3, 0xA
/* 1417FC 8024C9BC 25650013 */  addiu      $a1, $t3, 0x13
.Lpause_8024C9C0:
/* 141800 8024C9C0 240700FF */  addiu      $a3, $zero, 0xFF
/* 141804 8024C9C4 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 141808 8024C9C8 24080001 */  addiu      $t0, $zero, 0x1
/* 14180C 8024C9CC 14680002 */  bne        $v1, $t0, .Lpause_8024C9D8
/* 141810 8024C9D0 25460011 */   addiu     $a2, $t2, 0x11
/* 141814 8024C9D4 240700BF */  addiu      $a3, $zero, 0xBF
.Lpause_8024C9D8:
/* 141818 8024C9D8 0040202D */  daddu      $a0, $v0, $zero
/* 14181C 8024C9DC AFA00010 */  sw         $zero, 0x10($sp)
/* 141820 8024C9E0 080932A0 */  j          .Lpause_8024CA80
/* 141824 8024C9E4 AFA80014 */   sw        $t0, 0x14($sp)
.Lpause_8024C9E8:
/* 141828 8024C9E8 0C094C60 */  jal        pause_get_menu_msg
/* 14182C 8024C9EC 24040041 */   addiu     $a0, $zero, 0x41
/* 141830 8024C9F0 3C118027 */  lui        $s1, %hi(gPauseBadgesCurrentTab)
/* 141834 8024C9F4 2631276C */  addiu      $s1, $s1, %lo(gPauseBadgesCurrentTab)
/* 141838 8024C9F8 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 14183C 8024C9FC 8E230000 */  lw         $v1, 0x0($s1)
/* 141840 8024CA00 14600002 */  bnez       $v1, .Lpause_8024CA0C
/* 141844 8024CA04 2565000C */   addiu     $a1, $t3, 0xC
/* 141848 8024CA08 25650015 */  addiu      $a1, $t3, 0x15
.Lpause_8024CA0C:
/* 14184C 8024CA0C 240700FF */  addiu      $a3, $zero, 0xFF
/* 141850 8024CA10 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 141854 8024CA14 24100001 */  addiu      $s0, $zero, 0x1
/* 141858 8024CA18 14700002 */  bne        $v1, $s0, .Lpause_8024CA24
/* 14185C 8024CA1C 2546000C */   addiu     $a2, $t2, 0xC
/* 141860 8024CA20 240700BF */  addiu      $a3, $zero, 0xBF
.Lpause_8024CA24:
/* 141864 8024CA24 0040202D */  daddu      $a0, $v0, $zero
/* 141868 8024CA28 AFA00010 */  sw         $zero, 0x10($sp)
/* 14186C 8024CA2C 0C049403 */  jal        draw_msg
/* 141870 8024CA30 AFB00014 */   sw        $s0, 0x14($sp)
/* 141874 8024CA34 0C094C60 */  jal        pause_get_menu_msg
/* 141878 8024CA38 24040042 */   addiu     $a0, $zero, 0x42
/* 14187C 8024CA3C 0040202D */  daddu      $a0, $v0, $zero
/* 141880 8024CA40 24020002 */  addiu      $v0, $zero, 0x2
/* 141884 8024CA44 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 141888 8024CA48 8E430000 */  lw         $v1, 0x0($s2)
/* 14188C 8024CA4C 14620002 */  bne        $v1, $v0, .Lpause_8024CA58
/* 141890 8024CA50 25650018 */   addiu     $a1, $t3, 0x18
/* 141894 8024CA54 2565001A */  addiu      $a1, $t3, 0x1A
.Lpause_8024CA58:
/* 141898 8024CA58 8E220000 */  lw         $v0, 0x0($s1)
/* 14189C 8024CA5C 50400001 */  beql       $v0, $zero, .Lpause_8024CA64
/* 1418A0 8024CA60 24A50009 */   addiu     $a1, $a1, 0x9
.Lpause_8024CA64:
/* 1418A4 8024CA64 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 1418A8 8024CA68 240700FF */  addiu      $a3, $zero, 0xFF
/* 1418AC 8024CA6C 14500002 */  bne        $v0, $s0, .Lpause_8024CA78
/* 1418B0 8024CA70 25460016 */   addiu     $a2, $t2, 0x16
/* 1418B4 8024CA74 240700BF */  addiu      $a3, $zero, 0xBF
.Lpause_8024CA78:
/* 1418B8 8024CA78 AFA00010 */  sw         $zero, 0x10($sp)
/* 1418BC 8024CA7C AFB00014 */  sw         $s0, 0x14($sp)
.Lpause_8024CA80:
/* 1418C0 8024CA80 0C049403 */  jal        draw_msg
/* 1418C4 8024CA84 00000000 */   nop
/* 1418C8 8024CA88 24020001 */  addiu      $v0, $zero, 0x1
/* 1418CC 8024CA8C 3C038027 */  lui        $v1, %hi(gPauseBadgesCurrentTab)
/* 1418D0 8024CA90 8C63276C */  lw         $v1, %lo(gPauseBadgesCurrentTab)($v1)
/* 1418D4 8024CA94 8FA600C4 */  lw         $a2, 0xC4($sp)
/* 1418D8 8024CA98 50620001 */  beql       $v1, $v0, .Lpause_8024CAA0
/* 1418DC 8024CA9C 24C60009 */   addiu     $a2, $a2, 0x9
.Lpause_8024CAA0:
/* 1418E0 8024CAA0 8FAB00C8 */  lw         $t3, 0xC8($sp)
/* 1418E4 8024CAA4 2402005B */  addiu      $v0, $zero, 0x5B
/* 1418E8 8024CAA8 AFA20014 */  sw         $v0, 0x14($sp)
/* 1418EC 8024CAAC 24020022 */  addiu      $v0, $zero, 0x22
/* 1418F0 8024CAB0 AFA20018 */  sw         $v0, 0x18($sp)
/* 1418F4 8024CAB4 240200FF */  addiu      $v0, $zero, 0xFF
/* 1418F8 8024CAB8 AFA00010 */  sw         $zero, 0x10($sp)
/* 1418FC 8024CABC AFA2001C */  sw         $v0, 0x1C($sp)
/* 141900 8024CAC0 14600004 */  bnez       $v1, .Lpause_8024CAD4
/* 141904 8024CAC4 25670025 */   addiu     $a3, $t3, 0x25
/* 141908 8024CAC8 24020080 */  addiu      $v0, $zero, 0x80
/* 14190C 8024CACC 080932B6 */  j          .Lpause_8024CAD8
/* 141910 8024CAD0 AFA20020 */   sw        $v0, 0x20($sp)
.Lpause_8024CAD4:
/* 141914 8024CAD4 AFA00020 */  sw         $zero, 0x20($sp)
.Lpause_8024CAD8:
/* 141918 8024CAD8 24040004 */  addiu      $a0, $zero, 0x4
/* 14191C 8024CADC 3C058027 */  lui        $a1, %hi(gPauseWS_13)
/* 141920 8024CAE0 24A51FA8 */  addiu      $a1, $a1, %lo(gPauseWS_13)
/* 141924 8024CAE4 24020140 */  addiu      $v0, $zero, 0x140
/* 141928 8024CAE8 AFA20044 */  sw         $v0, 0x44($sp)
/* 14192C 8024CAEC 240200F0 */  addiu      $v0, $zero, 0xF0
/* 141930 8024CAF0 AFA00024 */  sw         $zero, 0x24($sp)
/* 141934 8024CAF4 AFA00028 */  sw         $zero, 0x28($sp)
/* 141938 8024CAF8 AFA0002C */  sw         $zero, 0x2C($sp)
/* 14193C 8024CAFC AFA00030 */  sw         $zero, 0x30($sp)
/* 141940 8024CB00 AFA00034 */  sw         $zero, 0x34($sp)
/* 141944 8024CB04 AFA00038 */  sw         $zero, 0x38($sp)
/* 141948 8024CB08 AFA0003C */  sw         $zero, 0x3C($sp)
/* 14194C 8024CB0C AFA00040 */  sw         $zero, 0x40($sp)
/* 141950 8024CB10 AFA20048 */  sw         $v0, 0x48($sp)
/* 141954 8024CB14 0C03C5C4 */  jal        draw_box
/* 141958 8024CB18 AFA0004C */   sw        $zero, 0x4C($sp)
/* 14195C 8024CB1C 0C094C60 */  jal        pause_get_menu_msg
/* 141960 8024CB20 24040043 */   addiu     $a0, $zero, 0x43
/* 141964 8024CB24 3C118027 */  lui        $s1, %hi(gPauseBadgesCurrentTab)
/* 141968 8024CB28 2631276C */  addiu      $s1, $s1, %lo(gPauseBadgesCurrentTab)
/* 14196C 8024CB2C 24100001 */  addiu      $s0, $zero, 0x1
/* 141970 8024CB30 8FAA00C4 */  lw         $t2, 0xC4($sp)
/* 141974 8024CB34 8E230000 */  lw         $v1, 0x0($s1)
/* 141978 8024CB38 14700002 */  bne        $v1, $s0, .Lpause_8024CB44
/* 14197C 8024CB3C 2545000C */   addiu     $a1, $t2, 0xC
/* 141980 8024CB40 25450015 */  addiu      $a1, $t2, 0x15
.Lpause_8024CB44:
/* 141984 8024CB44 8FAB00C8 */  lw         $t3, 0xC8($sp)
/* 141988 8024CB48 240700FF */  addiu      $a3, $zero, 0xFF
/* 14198C 8024CB4C 14600002 */  bnez       $v1, .Lpause_8024CB58
/* 141990 8024CB50 2566002A */   addiu     $a2, $t3, 0x2A
/* 141994 8024CB54 240700BF */  addiu      $a3, $zero, 0xBF
.Lpause_8024CB58:
/* 141998 8024CB58 0040202D */  daddu      $a0, $v0, $zero
/* 14199C 8024CB5C AFA00010 */  sw         $zero, 0x10($sp)
/* 1419A0 8024CB60 0C049403 */  jal        draw_msg
/* 1419A4 8024CB64 AFB00014 */   sw        $s0, 0x14($sp)
/* 1419A8 8024CB68 0C094C60 */  jal        pause_get_menu_msg
/* 1419AC 8024CB6C 24040044 */   addiu     $a0, $zero, 0x44
/* 1419B0 8024CB70 3C038015 */  lui        $v1, %hi(gCurrentLanguage)
/* 1419B4 8024CB74 8C63AE4C */  lw         $v1, %lo(gCurrentLanguage)($v1)
/* 1419B8 8024CB78 8FAA00C4 */  lw         $t2, 0xC4($sp)
/* 1419BC 8024CB7C 3C018027 */  lui        $at, %hi(D_PAL_80271B2C)
/* 1419C0 8024CB80 00230821 */  addu       $at, $at, $v1
/* 1419C4 8024CB84 90231B2C */  lbu        $v1, %lo(D_PAL_80271B2C)($at)
/* 1419C8 8024CB88 01432821 */  addu       $a1, $t2, $v1
/* 1419CC 8024CB8C 8E230000 */  lw         $v1, 0x0($s1)
/* 1419D0 8024CB90 50700001 */  beql       $v1, $s0, .Lpause_8024CB98
/* 1419D4 8024CB94 24A50009 */   addiu     $a1, $a1, 0x9
.Lpause_8024CB98:
/* 1419D8 8024CB98 8FAB00C8 */  lw         $t3, 0xC8($sp)
/* 1419DC 8024CB9C 240700FF */  addiu      $a3, $zero, 0xFF
/* 1419E0 8024CBA0 14600002 */  bnez       $v1, .Lpause_8024CBAC
/* 1419E4 8024CBA4 25660034 */   addiu     $a2, $t3, 0x34
/* 1419E8 8024CBA8 240700BF */  addiu      $a3, $zero, 0xBF
.Lpause_8024CBAC:
/* 1419EC 8024CBAC 0040202D */  daddu      $a0, $v0, $zero
/* 1419F0 8024CBB0 AFA00010 */  sw         $zero, 0x10($sp)
/* 1419F4 8024CBB4 0C049403 */  jal        draw_msg
/* 1419F8 8024CBB8 AFB00014 */   sw        $s0, 0x14($sp)
/* 1419FC 8024CBBC 3C038027 */  lui        $v1, %hi(gPauseMenuCurrentTab)
/* 141A00 8024CBC0 806324A4 */  lb         $v1, %lo(gPauseMenuCurrentTab)($v1)
/* 141A04 8024CBC4 24020002 */  addiu      $v0, $zero, 0x2
/* 141A08 8024CBC8 14620050 */  bne        $v1, $v0, .Lpause_8024CD0C
/* 141A0C 8024CBCC 00000000 */   nop
/* 141A10 8024CBD0 3C028027 */  lui        $v0, %hi(gPauseBadgesLevel)
/* 141A14 8024CBD4 8C422768 */  lw         $v0, %lo(gPauseBadgesLevel)($v0)
/* 141A18 8024CBD8 14400009 */  bnez       $v0, .Lpause_8024CC00
/* 141A1C 8024CBDC 24040020 */   addiu     $a0, $zero, 0x20
/* 141A20 8024CBE0 8E260000 */  lw         $a2, 0x0($s1)
/* 141A24 8024CBE4 8FAA00C4 */  lw         $t2, 0xC4($sp)
/* 141A28 8024CBE8 8FAB00C8 */  lw         $t3, 0xC8($sp)
/* 141A2C 8024CBEC 2545000A */  addiu      $a1, $t2, 0xA
/* 141A30 8024CBF0 00063140 */  sll        $a2, $a2, 5
/* 141A34 8024CBF4 24C6001A */  addiu      $a2, $a2, 0x1A
/* 141A38 8024CBF8 08093341 */  j          .Lpause_8024CD04
/* 141A3C 8024CBFC 01663021 */   addu      $a2, $t3, $a2
.Lpause_8024CC00:
/* 141A40 8024CC00 3C118027 */  lui        $s1, %hi(gPauseBadgesCurrentPage)
/* 141A44 8024CC04 26312650 */  addiu      $s1, $s1, %lo(gPauseBadgesCurrentPage)
/* 141A48 8024CC08 8E240000 */  lw         $a0, 0x0($s1)
/* 141A4C 8024CC0C 3C128027 */  lui        $s2, %hi(gPauseBadgesPages)
/* 141A50 8024CC10 26522658 */  addiu      $s2, $s2, %lo(gPauseBadgesPages)
/* 141A54 8024CC14 00041040 */  sll        $v0, $a0, 1
/* 141A58 8024CC18 00441021 */  addu       $v0, $v0, $a0
/* 141A5C 8024CC1C 00021080 */  sll        $v0, $v0, 2
/* 141A60 8024CC20 00521021 */  addu       $v0, $v0, $s2
/* 141A64 8024CC24 90430001 */  lbu        $v1, 0x1($v0)
/* 141A68 8024CC28 90420002 */  lbu        $v0, 0x2($v0)
/* 141A6C 8024CC2C 00620018 */  mult       $v1, $v0
/* 141A70 8024CC30 3C108027 */  lui        $s0, %hi(gPauseBadgesSelectedIndex)
/* 141A74 8024CC34 26102748 */  addiu      $s0, $s0, %lo(gPauseBadgesSelectedIndex)
/* 141A78 8024CC38 8E050000 */  lw         $a1, 0x0($s0)
/* 141A7C 8024CC3C 00005012 */  mflo       $t2
/* 141A80 8024CC40 0C092C4F */  jal        pause_badges_get_pos_x
/* 141A84 8024CC44 00AA2823 */   subu      $a1, $a1, $t2
/* 141A88 8024CC48 8E240000 */  lw         $a0, 0x0($s1)
/* 141A8C 8024CC4C 00041840 */  sll        $v1, $a0, 1
/* 141A90 8024CC50 00641821 */  addu       $v1, $v1, $a0
/* 141A94 8024CC54 00031880 */  sll        $v1, $v1, 2
/* 141A98 8024CC58 00721821 */  addu       $v1, $v1, $s2
/* 141A9C 8024CC5C 90650001 */  lbu        $a1, 0x1($v1)
/* 141AA0 8024CC60 90630002 */  lbu        $v1, 0x2($v1)
/* 141AA4 8024CC64 00A30018 */  mult       $a1, $v1
/* 141AA8 8024CC68 8E050000 */  lw         $a1, 0x0($s0)
/* 141AAC 8024CC6C 0040802D */  daddu      $s0, $v0, $zero
/* 141AB0 8024CC70 00005012 */  mflo       $t2
/* 141AB4 8024CC74 0C092C66 */  jal        pause_badges_get_pos_y
/* 141AB8 8024CC78 00AA2823 */   subu      $a1, $a1, $t2
/* 141ABC 8024CC7C 0200202D */  daddu      $a0, $s0, $zero
/* 141AC0 8024CC80 0C092CB6 */  jal        pause_badges_scroll_offset_x
/* 141AC4 8024CC84 0040802D */   daddu     $s0, $v0, $zero
/* 141AC8 8024CC88 0200202D */  daddu      $a0, $s0, $zero
/* 141ACC 8024CC8C 0C092CB2 */  jal        pause_badges_scroll_offset_y
/* 141AD0 8024CC90 0040802D */   daddu     $s0, $v0, $zero
/* 141AD4 8024CC94 0040302D */  daddu      $a2, $v0, $zero
/* 141AD8 8024CC98 04C10003 */  bgez       $a2, .Lpause_8024CCA8
/* 141ADC 8024CC9C 28C20071 */   slti      $v0, $a2, 0x71
/* 141AE0 8024CCA0 0809332C */  j          .Lpause_8024CCB0
/* 141AE4 8024CCA4 0000302D */   daddu     $a2, $zero, $zero
.Lpause_8024CCA8:
/* 141AE8 8024CCA8 50400001 */  beql       $v0, $zero, .Lpause_8024CCB0
/* 141AEC 8024CCAC 24060070 */   addiu     $a2, $zero, 0x70
.Lpause_8024CCB0:
/* 141AF0 8024CCB0 3C038027 */  lui        $v1, %hi(gPauseBadgesCurrentScrollPos)
/* 141AF4 8024CCB4 8C63275C */  lw         $v1, %lo(gPauseBadgesCurrentScrollPos)($v1)
/* 141AF8 8024CCB8 3C028027 */  lui        $v0, %hi(gPauseBadgesTargetScrollPos)
/* 141AFC 8024CCBC 8C422760 */  lw         $v0, %lo(gPauseBadgesTargetScrollPos)($v0)
/* 141B00 8024CCC0 1062000A */  beq        $v1, $v0, .Lpause_8024CCEC
/* 141B04 8024CCC4 24040020 */   addiu     $a0, $zero, 0x20
/* 141B08 8024CCC8 2605005D */  addiu      $a1, $s0, 0x5D
/* 141B0C 8024CCCC 24C60017 */  addiu      $a2, $a2, 0x17
/* 141B10 8024CCD0 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 141B14 8024CCD4 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 141B18 8024CCD8 01652821 */  addu       $a1, $t3, $a1
/* 141B1C 8024CCDC 0C091AAF */  jal        pause_set_cursor_pos_immediate
/* 141B20 8024CCE0 01463021 */   addu      $a2, $t2, $a2
/* 141B24 8024CCE4 08093343 */  j          .Lpause_8024CD0C
/* 141B28 8024CCE8 00000000 */   nop
.Lpause_8024CCEC:
/* 141B2C 8024CCEC 2605005D */  addiu      $a1, $s0, 0x5D
/* 141B30 8024CCF0 24C60017 */  addiu      $a2, $a2, 0x17
/* 141B34 8024CCF4 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 141B38 8024CCF8 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 141B3C 8024CCFC 01652821 */  addu       $a1, $t3, $a1
/* 141B40 8024CD00 01463021 */  addu       $a2, $t2, $a2
.Lpause_8024CD04:
/* 141B44 8024CD04 0C091B05 */  jal        pause_set_cursor_pos
/* 141B48 8024CD08 00000000 */   nop
.Lpause_8024CD0C:
/* 141B4C 8024CD0C 3C108027 */  lui        $s0, %hi(gPauseBadgesShowNotEnoughBP)
/* 141B50 8024CD10 26102770 */  addiu      $s0, $s0, %lo(gPauseBadgesShowNotEnoughBP)
/* 141B54 8024CD14 8E020000 */  lw         $v0, 0x0($s0)
/* 141B58 8024CD18 10400065 */  beqz       $v0, .Lpause_8024CEB0
/* 141B5C 8024CD1C 00000000 */   nop
/* 141B60 8024CD20 0C091AAC */  jal        pause_set_cursor_opacity
/* 141B64 8024CD24 0000202D */   daddu     $a0, $zero, $zero
/* 141B68 8024CD28 8E020000 */  lw         $v0, 0x0($s0)
/* 141B6C 8024CD2C 24110001 */  addiu      $s1, $zero, 0x1
/* 141B70 8024CD30 54510038 */  bnel       $v0, $s1, .Lpause_8024CE14
/* 141B74 8024CD34 24040004 */   addiu     $a0, $zero, 0x4
/* 141B78 8024CD38 0C094C60 */  jal        pause_get_menu_msg
/* 141B7C 8024CD3C 24040045 */   addiu     $a0, $zero, 0x45
/* 141B80 8024CD40 0040202D */  daddu      $a0, $v0, $zero
/* 141B84 8024CD44 0C0493E5 */  jal        get_msg_width
/* 141B88 8024CD48 0000282D */   daddu     $a1, $zero, $zero
/* 141B8C 8024CD4C 24040004 */  addiu      $a0, $zero, 0x4
/* 141B90 8024CD50 3C058027 */  lui        $a1, %hi(gPauseWS_13)
/* 141B94 8024CD54 24A51FA8 */  addiu      $a1, $a1, %lo(gPauseWS_13)
/* 141B98 8024CD58 0040802D */  daddu      $s0, $v0, $zero
/* 141B9C 8024CD5C 24060100 */  addiu      $a2, $zero, 0x100
/* 141BA0 8024CD60 00D03023 */  subu       $a2, $a2, $s0
/* 141BA4 8024CD64 000617C2 */  srl        $v0, $a2, 31
/* 141BA8 8024CD68 00C23021 */  addu       $a2, $a2, $v0
/* 141BAC 8024CD6C 02263007 */  srav       $a2, $a2, $s1
/* 141BB0 8024CD70 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 141BB4 8024CD74 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 141BB8 8024CD78 26020024 */  addiu      $v0, $s0, 0x24
/* 141BBC 8024CD7C AFA20014 */  sw         $v0, 0x14($sp)
/* 141BC0 8024CD80 2402001A */  addiu      $v0, $zero, 0x1A
/* 141BC4 8024CD84 AFA20018 */  sw         $v0, 0x18($sp)
/* 141BC8 8024CD88 240200FF */  addiu      $v0, $zero, 0xFF
/* 141BCC 8024CD8C AFA2001C */  sw         $v0, 0x1C($sp)
/* 141BD0 8024CD90 24020140 */  addiu      $v0, $zero, 0x140
/* 141BD4 8024CD94 AFA20044 */  sw         $v0, 0x44($sp)
/* 141BD8 8024CD98 240200F0 */  addiu      $v0, $zero, 0xF0
/* 141BDC 8024CD9C AFA00010 */  sw         $zero, 0x10($sp)
/* 141BE0 8024CDA0 AFA00020 */  sw         $zero, 0x20($sp)
/* 141BE4 8024CDA4 AFA00024 */  sw         $zero, 0x24($sp)
/* 141BE8 8024CDA8 AFA00028 */  sw         $zero, 0x28($sp)
/* 141BEC 8024CDAC AFA0002C */  sw         $zero, 0x2C($sp)
/* 141BF0 8024CDB0 AFA00030 */  sw         $zero, 0x30($sp)
/* 141BF4 8024CDB4 AFA00034 */  sw         $zero, 0x34($sp)
/* 141BF8 8024CDB8 AFA00038 */  sw         $zero, 0x38($sp)
/* 141BFC 8024CDBC AFA0003C */  sw         $zero, 0x3C($sp)
/* 141C00 8024CDC0 AFA00040 */  sw         $zero, 0x40($sp)
/* 141C04 8024CDC4 AFA20048 */  sw         $v0, 0x48($sp)
/* 141C08 8024CDC8 AFA0004C */  sw         $zero, 0x4C($sp)
/* 141C0C 8024CDCC 01663021 */  addu       $a2, $t3, $a2
/* 141C10 8024CDD0 0C03C5C4 */  jal        draw_box
/* 141C14 8024CDD4 2547003C */   addiu     $a3, $t2, 0x3C
/* 141C18 8024CDD8 0C094C60 */  jal        pause_get_menu_msg
/* 141C1C 8024CDDC 24040045 */   addiu     $a0, $zero, 0x45
/* 141C20 8024CDE0 0040202D */  daddu      $a0, $v0, $zero
/* 141C24 8024CDE4 24050124 */  addiu      $a1, $zero, 0x124
/* 141C28 8024CDE8 00B02823 */  subu       $a1, $a1, $s0
/* 141C2C 8024CDEC 000517C2 */  srl        $v0, $a1, 31
/* 141C30 8024CDF0 00A22821 */  addu       $a1, $a1, $v0
/* 141C34 8024CDF4 02252807 */  srav       $a1, $a1, $s1
/* 141C38 8024CDF8 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 141C3C 8024CDFC 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 141C40 8024CE00 240700FF */  addiu      $a3, $zero, 0xFF
/* 141C44 8024CE04 AFA00010 */  sw         $zero, 0x10($sp)
/* 141C48 8024CE08 AFB10014 */  sw         $s1, 0x14($sp)
/* 141C4C 8024CE0C 080933AA */  j          .Lpause_8024CEA8
/* 141C50 8024CE10 01652821 */   addu      $a1, $t3, $a1
.Lpause_8024CE14:
/* 141C54 8024CE14 3C058027 */  lui        $a1, %hi(gPauseWS_13)
/* 141C58 8024CE18 24A51FA8 */  addiu      $a1, $a1, %lo(gPauseWS_13)
/* 141C5C 8024CE1C 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 141C60 8024CE20 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 141C64 8024CE24 240200AD */  addiu      $v0, $zero, 0xAD
/* 141C68 8024CE28 AFA20014 */  sw         $v0, 0x14($sp)
/* 141C6C 8024CE2C 2402001A */  addiu      $v0, $zero, 0x1A
/* 141C70 8024CE30 AFA20018 */  sw         $v0, 0x18($sp)
/* 141C74 8024CE34 240200FF */  addiu      $v0, $zero, 0xFF
/* 141C78 8024CE38 AFA2001C */  sw         $v0, 0x1C($sp)
/* 141C7C 8024CE3C 24020140 */  addiu      $v0, $zero, 0x140
/* 141C80 8024CE40 AFA20044 */  sw         $v0, 0x44($sp)
/* 141C84 8024CE44 240200F0 */  addiu      $v0, $zero, 0xF0
/* 141C88 8024CE48 AFA00010 */  sw         $zero, 0x10($sp)
/* 141C8C 8024CE4C AFA00020 */  sw         $zero, 0x20($sp)
/* 141C90 8024CE50 AFA00024 */  sw         $zero, 0x24($sp)
/* 141C94 8024CE54 AFA00028 */  sw         $zero, 0x28($sp)
/* 141C98 8024CE58 AFA0002C */  sw         $zero, 0x2C($sp)
/* 141C9C 8024CE5C AFA00030 */  sw         $zero, 0x30($sp)
/* 141CA0 8024CE60 AFA00034 */  sw         $zero, 0x34($sp)
/* 141CA4 8024CE64 AFA00038 */  sw         $zero, 0x38($sp)
/* 141CA8 8024CE68 AFA0003C */  sw         $zero, 0x3C($sp)
/* 141CAC 8024CE6C AFA00040 */  sw         $zero, 0x40($sp)
/* 141CB0 8024CE70 AFA20048 */  sw         $v0, 0x48($sp)
/* 141CB4 8024CE74 AFA0004C */  sw         $zero, 0x4C($sp)
/* 141CB8 8024CE78 25660043 */  addiu      $a2, $t3, 0x43
/* 141CBC 8024CE7C 0C03C5C4 */  jal        draw_box
/* 141CC0 8024CE80 2547003C */   addiu     $a3, $t2, 0x3C
/* 141CC4 8024CE84 0C094C60 */  jal        pause_get_menu_msg
/* 141CC8 8024CE88 24040046 */   addiu     $a0, $zero, 0x46
/* 141CCC 8024CE8C 0040202D */  daddu      $a0, $v0, $zero
/* 141CD0 8024CE90 8FAB00C4 */  lw         $t3, 0xC4($sp)
/* 141CD4 8024CE94 8FAA00C8 */  lw         $t2, 0xC8($sp)
/* 141CD8 8024CE98 240700FF */  addiu      $a3, $zero, 0xFF
/* 141CDC 8024CE9C AFA00010 */  sw         $zero, 0x10($sp)
/* 141CE0 8024CEA0 AFB10014 */  sw         $s1, 0x14($sp)
/* 141CE4 8024CEA4 2565005A */  addiu      $a1, $t3, 0x5A
.Lpause_8024CEA8:
/* 141CE8 8024CEA8 0C049403 */  jal        draw_msg
/* 141CEC 8024CEAC 25460042 */   addiu     $a2, $t2, 0x42
.Lpause_8024CEB0:
/* 141CF0 8024CEB0 8FBF00BC */  lw         $ra, 0xBC($sp)
/* 141CF4 8024CEB4 8FBE00B8 */  lw         $fp, 0xB8($sp)
/* 141CF8 8024CEB8 8FB700B4 */  lw         $s7, 0xB4($sp)
/* 141CFC 8024CEBC 8FB600B0 */  lw         $s6, 0xB0($sp)
/* 141D00 8024CEC0 8FB500AC */  lw         $s5, 0xAC($sp)
/* 141D04 8024CEC4 8FB400A8 */  lw         $s4, 0xA8($sp)
/* 141D08 8024CEC8 8FB300A4 */  lw         $s3, 0xA4($sp)
/* 141D0C 8024CECC 8FB200A0 */  lw         $s2, 0xA0($sp)
/* 141D10 8024CED0 8FB1009C */  lw         $s1, 0x9C($sp)
/* 141D14 8024CED4 8FB00098 */  lw         $s0, 0x98($sp)
/* 141D18 8024CED8 03E00008 */  jr         $ra
/* 141D1C 8024CEDC 27BD00C0 */   addiu     $sp, $sp, 0xC0
