.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel hos_05_AnimBowser_FlyOff
/* A9A8B4 80244774 27BDFFD0 */  addiu      $sp, $sp, -0x30
/* A9A8B8 80244778 AFB00018 */  sw         $s0, 0x18($sp)
/* A9A8BC 8024477C 0080802D */  daddu      $s0, $a0, $zero
/* A9A8C0 80244780 AFB1001C */  sw         $s1, 0x1C($sp)
/* A9A8C4 80244784 00A0882D */  daddu      $s1, $a1, $zero
/* A9A8C8 80244788 24050007 */  addiu      $a1, $zero, 0x7
/* A9A8CC 8024478C AFBF0028 */  sw         $ra, 0x28($sp)
/* A9A8D0 80244790 AFB30024 */  sw         $s3, 0x24($sp)
/* A9A8D4 80244794 0C0B42B0 */  jal        resolve_npc
/* A9A8D8 80244798 AFB20020 */   sw        $s2, 0x20($sp)
/* A9A8DC 8024479C 0200202D */  daddu      $a0, $s0, $zero
/* A9A8E0 802447A0 24050008 */  addiu      $a1, $zero, 0x8
/* A9A8E4 802447A4 0C0B42B0 */  jal        resolve_npc
/* A9A8E8 802447A8 0040902D */   daddu     $s2, $v0, $zero
/* A9A8EC 802447AC 12200004 */  beqz       $s1, .LPAL_802447C0
/* A9A8F0 802447B0 0040982D */   daddu     $s3, $v0, $zero
/* A9A8F4 802447B4 C640003C */  lwc1       $f0, 0x3C($s2)
/* A9A8F8 802447B8 3C018025 */  lui        $at, %hi(hos_05_AnimBowser_FlyOff_InitialY)
/* A9A8FC 802447BC E420F314 */  swc1       $f0, %lo(hos_05_AnimBowser_FlyOff_InitialY)($at)
.LPAL_802447C0:
/* A9A900 802447C0 3C018025 */  lui        $at, %hi(hos_05_AnimBowser_FlyOff_InitialY)
/* A9A904 802447C4 C420F314 */  lwc1       $f0, %lo(hos_05_AnimBowser_FlyOff_InitialY)($at)
/* A9A908 802447C8 24040003 */  addiu      $a0, $zero, 0x3
/* A9A90C 802447CC 44050000 */  mfc1       $a1, $f0
/* A9A910 802447D0 3C0143FA */  lui        $at, (0x43FA0000 >> 16)
/* A9A914 802447D4 44810000 */  mtc1       $at, $f0
/* A9A918 802447D8 44853000 */  mtc1       $a1, $f6
/* A9A91C 802447DC 3C108025 */  lui        $s0, %hi(hos_05_AnimBowser_FlyOff_Time)
/* A9A920 802447E0 2610AE70 */  addiu      $s0, $s0, %lo(hos_05_AnimBowser_FlyOff_Time)
/* A9A924 802447E4 46003180 */  add.s      $f6, $f6, $f0
/* A9A928 802447E8 3C014220 */  lui        $at, (0x42200000 >> 16)
/* A9A92C 802447EC 44811000 */  mtc1       $at, $f2
/* A9A930 802447F0 8E070000 */  lw         $a3, 0x0($s0)
/* A9A934 802447F4 44063000 */  mfc1       $a2, $f6
/* A9A938 802447F8 2642003C */  addiu      $v0, $s2, 0x3C
/* A9A93C 802447FC AFA20014 */  sw         $v0, 0x14($sp)
/* A9A940 80244800 0C090439 */  jal        interp_value_with_easing
/* A9A944 80244804 E7A20010 */   swc1      $f2, 0x10($sp)
/* A9A948 80244808 C640003C */  lwc1       $f0, 0x3C($s2)
/* A9A94C 8024480C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
/* A9A950 80244810 44811000 */  mtc1       $at, $f2
/* A9A954 80244814 E660003C */  swc1       $f0, 0x3C($s3)
/* A9A958 80244818 C6000000 */  lwc1       $f0, 0x0($s0)
/* A9A95C 8024481C C644003C */  lwc1       $f4, 0x3C($s2)
/* A9A960 80244820 46020000 */  add.s      $f0, $f0, $f2
/* A9A964 80244824 E6440070 */  swc1       $f4, 0x70($s2)
/* A9A968 80244828 C662003C */  lwc1       $f2, 0x3C($s3)
/* A9A96C 8024482C 3C014204 */  lui        $at, (0x42040000 >> 16)
/* A9A970 80244830 44812000 */  mtc1       $at, $f4
/* A9A974 80244834 24020001 */  addiu      $v0, $zero, 0x1
/* A9A978 80244838 E6620070 */  swc1       $f2, 0x70($s3)
/* A9A97C 8024483C 4600203C */  c.lt.s     $f4, $f0
/* A9A980 80244840 00000000 */  nop
/* A9A984 80244844 45010002 */  bc1t       .LPAL_80244850
/* A9A988 80244848 E6000000 */   swc1      $f0, 0x0($s0)
/* A9A98C 8024484C 0000102D */  daddu      $v0, $zero, $zero
.LPAL_80244850:
/* A9A990 80244850 8FBF0028 */  lw         $ra, 0x28($sp)
/* A9A994 80244854 8FB30024 */  lw         $s3, 0x24($sp)
/* A9A998 80244858 8FB20020 */  lw         $s2, 0x20($sp)
/* A9A99C 8024485C 8FB1001C */  lw         $s1, 0x1C($sp)
/* A9A9A0 80244860 8FB00018 */  lw         $s0, 0x18($sp)
/* A9A9A4 80244864 03E00008 */  jr         $ra
/* A9A9A8 80244868 27BD0030 */   addiu     $sp, $sp, 0x30
