.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel filemenu_init
/* 1713C8 802489A8 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 1713CC 802489AC AFB3001C */  sw         $s3, 0x1C($sp)
/* 1713D0 802489B0 0080982D */  daddu      $s3, $a0, $zero
/* 1713D4 802489B4 3C040013 */  lui        $a0, %hi(ui_images_ROM_START)
/* 1713D8 802489B8 24842E40 */  addiu      $a0, $a0, %lo(ui_images_ROM_START)
/* 1713DC 802489BC 3C050014 */  lui        $a1, %hi(ui_images_ROM_END)
/* 1713E0 802489C0 24A5B8F0 */  addiu      $a1, $a1, %lo(ui_images_ROM_END)
/* 1713E4 802489C4 3C068024 */  lui        $a2, %hi(ui_images_VRAM)
/* 1713E8 802489C8 24C6E000 */  addiu      $a2, $a2, %lo(ui_images_VRAM)
/* 1713EC 802489CC AFBF0020 */  sw         $ra, 0x20($sp)
/* 1713F0 802489D0 AFB20018 */  sw         $s2, 0x18($sp)
/* 1713F4 802489D4 AFB10014 */  sw         $s1, 0x14($sp)
/* 1713F8 802489D8 0C00A5AF */  jal        dma_copy
/* 1713FC 802489DC AFB00010 */   sw        $s0, 0x10($sp)
/* 171400 802489E0 0000802D */  daddu      $s0, $zero, $zero
/* 171404 802489E4 3C128025 */  lui        $s2, %hi(filemenu_cursorHudElemID)
/* 171408 802489E8 26521760 */  addiu      $s2, $s2, %lo(filemenu_cursorHudElemID)
/* 17140C 802489EC 3C118025 */  lui        $s1, %hi(filemenu_cursor_hudElemScripts)
/* 171410 802489F0 2631E980 */  addiu      $s1, $s1, %lo(filemenu_cursor_hudElemScripts)
.Lfilemenu_802489F4:
/* 171414 802489F4 8E240000 */  lw         $a0, 0x0($s1)
/* 171418 802489F8 26310004 */  addiu      $s1, $s1, 0x4
/* 17141C 802489FC 0C050015 */  jal        hud_element_create
/* 171420 80248A00 26100001 */   addiu     $s0, $s0, 0x1
/* 171424 80248A04 0040202D */  daddu      $a0, $v0, $zero
/* 171428 80248A08 3C052000 */  lui        $a1, (0x20000080 >> 16)
/* 17142C 80248A0C 34A50080 */  ori        $a1, $a1, (0x20000080 & 0xFFFF)
/* 171430 80248A10 0C050D6C */  jal        hud_element_set_flags
/* 171434 80248A14 AE440000 */   sw        $a0, 0x0($s2)
/* 171438 80248A18 1A00FFF6 */  blez       $s0, .Lfilemenu_802489F4
/* 17143C 80248A1C 26520004 */   addiu     $s2, $s2, 0x4
/* 171440 80248A20 3C028025 */  lui        $v0, %hi(filemenu_cursorHudElemID)
/* 171444 80248A24 8C421760 */  lw         $v0, %lo(filemenu_cursorHudElemID)($v0)
/* 171448 80248A28 3C018025 */  lui        $at, %hi(filemenu_cursorHudElem)
/* 17144C 80248A2C AC221748 */  sw         $v0, %lo(filemenu_cursorHudElem)($at)
/* 171450 80248A30 16600004 */  bnez       $s3, .Lfilemenu_80248A44
/* 171454 80248A34 00000000 */   nop
/* 171458 80248A38 3C028025 */  lui        $v0, %hi(filemenu_common_windowBPs+0x20)
/* 17145C 80248A3C 8C42EC14 */  lw         $v0, %lo(filemenu_common_windowBPs+0x20)($v0)
/* 171460 80248A40 AC400000 */  sw         $zero, 0x0($v0)
.Lfilemenu_80248A44:
/* 171464 80248A44 3C048025 */  lui        $a0, %hi(filemenu_common_windowBPs)
/* 171468 80248A48 2484EBF4 */  addiu      $a0, $a0, %lo(filemenu_common_windowBPs)
/* 17146C 80248A4C 0C051AB8 */  jal        setup_pause_menu_tab
/* 171470 80248A50 24050003 */   addiu     $a1, $zero, 0x3
/* 171474 80248A54 24020002 */  addiu      $v0, $zero, 0x2
/* 171478 80248A58 1262002C */  beq        $s3, $v0, .Lfilemenu_80248B0C
/* 17147C 80248A5C 0000282D */   daddu     $a1, $zero, $zero
/* 171480 80248A60 3C108025 */  lui        $s0, %hi(filemenu_menus)
/* 171484 80248A64 8E10E984 */  lw         $s0, %lo(filemenu_menus)($s0)
/* 171488 80248A68 3C018025 */  lui        $at, %hi(filemenu_currentMenu)
/* 17148C 80248A6C A0201758 */  sb         $zero, %lo(filemenu_currentMenu)($at)
/* 171490 80248A70 0C00AD5D */  jal        func_PAL_8002B574
/* 171494 80248A74 A2000004 */   sb        $zero, 0x4($s0)
/* 171498 80248A78 82020004 */  lb         $v0, 0x4($s0)
/* 17149C 80248A7C 1440000E */  bnez       $v0, .Lfilemenu_80248AB8
/* 1714A0 80248A80 0200202D */   daddu     $a0, $s0, $zero
/* 1714A4 80248A84 0C00ABF8 */  jal        fio_has_valid_backup
/* 1714A8 80248A88 00000000 */   nop
/* 1714AC 80248A8C 3C04800D */  lui        $a0, %hi(D_800D5D58)
/* 1714B0 80248A90 24845D58 */  addiu      $a0, $a0, %lo(D_800D5D58)
/* 1714B4 80248A94 8C82003C */  lw         $v0, 0x3C($a0)
/* 1714B8 80248A98 2C420004 */  sltiu      $v0, $v0, 0x4
/* 1714BC 80248A9C 50400001 */  beql       $v0, $zero, .Lfilemenu_80248AA4
/* 1714C0 80248AA0 AC80003C */   sw        $zero, 0x3C($a0)
.Lfilemenu_80248AA4:
/* 1714C4 80248AA4 3C038007 */  lui        $v1, %hi(gGameStatusPtr)
/* 1714C8 80248AA8 8C6314AC */  lw         $v1, %lo(gGameStatusPtr)($v1)
/* 1714CC 80248AAC 9082003F */  lbu        $v0, 0x3F($a0)
/* 1714D0 80248AB0 A0620166 */  sb         $v0, 0x166($v1)
/* 1714D4 80248AB4 0200202D */  daddu      $a0, $s0, $zero
.Lfilemenu_80248AB8:
/* 1714D8 80248AB8 3C028007 */  lui        $v0, %hi(gGameStatusPtr)
/* 1714DC 80248ABC 8C4214AC */  lw         $v0, %lo(gGameStatusPtr)($v0)
/* 1714E0 80248AC0 3C118025 */  lui        $s1, %hi(filemenu_menus)
/* 1714E4 80248AC4 2631E984 */  addiu      $s1, $s1, %lo(filemenu_menus)
/* 1714E8 80248AC8 90460166 */  lbu        $a2, 0x166($v0)
/* 1714EC 80248ACC 0000802D */  daddu      $s0, $zero, $zero
/* 1714F0 80248AD0 30C50001 */  andi       $a1, $a2, 0x1
/* 1714F4 80248AD4 00052840 */  sll        $a1, $a1, 1
/* 1714F8 80248AD8 0C091B29 */  jal        filemenu_set_selected
/* 1714FC 80248ADC 00063042 */   srl       $a2, $a2, 1
.Lfilemenu_80248AE0:
/* 171500 80248AE0 8E240000 */  lw         $a0, 0x0($s1)
/* 171504 80248AE4 8C82000C */  lw         $v0, 0xC($a0)
/* 171508 80248AE8 10400003 */  beqz       $v0, .Lfilemenu_80248AF8
/* 17150C 80248AEC 26100001 */   addiu     $s0, $s0, 0x1
/* 171510 80248AF0 0040F809 */  jalr       $v0
/* 171514 80248AF4 00000000 */   nop
.Lfilemenu_80248AF8:
/* 171518 80248AF8 2A020004 */  slti       $v0, $s0, 0x4
/* 17151C 80248AFC 1440FFF8 */  bnez       $v0, .Lfilemenu_80248AE0
/* 171520 80248B00 26310004 */   addiu     $s1, $s1, 0x4
/* 171524 80248B04 080922DB */  j          .Lfilemenu_80248B6C
/* 171528 80248B08 24040017 */   addiu     $a0, $zero, 0x17
.Lfilemenu_80248B0C:
/* 17152C 80248B0C 3C028025 */  lui        $v0, %hi(filemenu_menus)
/* 171530 80248B10 2442E984 */  addiu      $v0, $v0, %lo(filemenu_menus)
/* 171534 80248B14 0040882D */  daddu      $s1, $v0, $zero
/* 171538 80248B18 24120004 */  addiu      $s2, $zero, 0x4
/* 17153C 80248B1C 8E240010 */  lw         $a0, 0x10($s1)
/* 171540 80248B20 3C068015 */  lui        $a2, %hi(gCurrentLanguage)
/* 171544 80248B24 8CC6AE4C */  lw         $a2, %lo(gCurrentLanguage)($a2)
/* 171548 80248B28 0240102D */  daddu      $v0, $s2, $zero
/* 17154C 80248B2C 3C018025 */  lui        $at, %hi(filemenu_currentMenu)
/* 171550 80248B30 A0221758 */  sb         $v0, %lo(filemenu_currentMenu)($at)
/* 171554 80248B34 0C091B29 */  jal        filemenu_set_selected
/* 171558 80248B38 00A0802D */   daddu     $s0, $a1, $zero
.Lfilemenu_80248B3C:
/* 17155C 80248B3C 16120007 */  bne        $s0, $s2, .Lfilemenu_80248B5C
/* 171560 80248B40 26100001 */   addiu     $s0, $s0, 0x1
/* 171564 80248B44 8E240000 */  lw         $a0, 0x0($s1)
/* 171568 80248B48 8C82000C */  lw         $v0, 0xC($a0)
/* 17156C 80248B4C 10400003 */  beqz       $v0, .Lfilemenu_80248B5C
/* 171570 80248B50 00000000 */   nop
/* 171574 80248B54 0040F809 */  jalr       $v0
/* 171578 80248B58 00000000 */   nop
.Lfilemenu_80248B5C:
/* 17157C 80248B5C 2A020005 */  slti       $v0, $s0, 0x5
/* 171580 80248B60 1440FFF6 */  bnez       $v0, .Lfilemenu_80248B3C
/* 171584 80248B64 26310004 */   addiu     $s1, $s1, 0x4
/* 171588 80248B68 24040017 */  addiu      $a0, $zero, 0x17
.Lfilemenu_80248B6C:
/* 17158C 80248B6C 0C051A48 */  jal        update_window_hierarchy
/* 171590 80248B70 24050040 */   addiu     $a1, $zero, 0x40
/* 171594 80248B74 8FBF0020 */  lw         $ra, 0x20($sp)
/* 171598 80248B78 8FB3001C */  lw         $s3, 0x1C($sp)
/* 17159C 80248B7C 8FB20018 */  lw         $s2, 0x18($sp)
/* 1715A0 80248B80 8FB10014 */  lw         $s1, 0x14($sp)
/* 1715A4 80248B84 8FB00010 */  lw         $s0, 0x10($sp)
/* 1715A8 80248B88 03E00008 */  jr         $ra
/* 1715AC 80248B8C 27BD0028 */   addiu     $sp, $sp, 0x28
