.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel fio_fetch_saved_file_info
/* 655C 8002B15C 27BDFFC8 */  addiu      $sp, $sp, -0x38
/* 6560 8002B160 AFB60028 */  sw         $s6, 0x28($sp)
/* 6564 8002B164 3C168009 */  lui        $s6, %hi(D_80097E10)
/* 6568 8002B168 26D67E10 */  addiu      $s6, $s6, %lo(D_80097E10)
/* 656C 8002B16C AFB40020 */  sw         $s4, 0x20($sp)
/* 6570 8002B170 3C148009 */  lui        $s4, %hi(D_80096A90)
/* 6574 8002B174 26946A90 */  addiu      $s4, $s4, %lo(D_80096A90)
/* 6578 8002B178 AFB3001C */  sw         $s3, 0x1C($sp)
/* 657C 8002B17C 0280982D */  daddu      $s3, $s4, $zero
/* 6580 8002B180 AFB00010 */  sw         $s0, 0x10($sp)
/* 6584 8002B184 0000802D */  daddu      $s0, $zero, $zero
/* 6588 8002B188 2404FFFF */  addiu      $a0, $zero, -0x1
/* 658C 8002B18C 3C03800A */  lui        $v1, %hi(D_80099190)
/* 6590 8002B190 24639190 */  addiu      $v1, $v1, %lo(D_80099190)
/* 6594 8002B194 AFBF0034 */  sw         $ra, 0x34($sp)
/* 6598 8002B198 AFBE0030 */  sw         $fp, 0x30($sp)
/* 659C 8002B19C AFB7002C */  sw         $s7, 0x2C($sp)
/* 65A0 8002B1A0 AFB50024 */  sw         $s5, 0x24($sp)
/* 65A4 8002B1A4 AFB20018 */  sw         $s2, 0x18($sp)
/* 65A8 8002B1A8 AFB10014 */  sw         $s1, 0x14($sp)
.L8002B1AC:
/* 65AC 8002B1AC AC640000 */  sw         $a0, 0x0($v1)
/* 65B0 8002B1B0 AC640004 */  sw         $a0, 0x4($v1)
/* 65B4 8002B1B4 26100001 */  addiu      $s0, $s0, 0x1
/* 65B8 8002B1B8 2A020004 */  slti       $v0, $s0, 0x4
/* 65BC 8002B1BC 1440FFFB */  bnez       $v0, .L8002B1AC
/* 65C0 8002B1C0 24630008 */   addiu     $v1, $v1, 0x8
/* 65C4 8002B1C4 0000802D */  daddu      $s0, $zero, $zero
/* 65C8 8002B1C8 241E0004 */  addiu      $fp, $zero, 0x4
/* 65CC 8002B1CC 3C15800A */  lui        $s5, %hi(D_80099190)
/* 65D0 8002B1D0 26B59190 */  addiu      $s5, $s5, %lo(D_80099190)
/* 65D4 8002B1D4 24170063 */  addiu      $s7, $zero, 0x63
/* 65D8 8002B1D8 3C12800A */  lui        $s2, %hi(physicalSaveInfo)
/* 65DC 8002B1DC 265291B0 */  addiu      $s2, $s2, %lo(physicalSaveInfo)
.L8002B1E0:
/* 65E0 8002B1E0 0000882D */  daddu      $s1, $zero, $zero
/* 65E4 8002B1E4 0200202D */  daddu      $a0, $s0, $zero
.L8002B1E8:
/* 65E8 8002B1E8 0280282D */  daddu      $a1, $s4, $zero
/* 65EC 8002B1EC 0C00AEA7 */  jal        fio_read_flash
/* 65F0 8002B1F0 24061380 */   addiu     $a2, $zero, 0x1380
/* 65F4 8002B1F4 0200202D */  daddu      $a0, $s0, $zero
/* 65F8 8002B1F8 02C0282D */  daddu      $a1, $s6, $zero
/* 65FC 8002B1FC 0C00AEA7 */  jal        fio_read_flash
/* 6600 8002B200 24061380 */   addiu     $a2, $zero, 0x1380
/* 6604 8002B204 0C00AB81 */  jal        func_8002AE04
/* 6608 8002B208 00000000 */   nop
/* 660C 8002B20C 10400005 */  beqz       $v0, .L8002B224
/* 6610 8002B210 00000000 */   nop
/* 6614 8002B214 26310001 */  addiu      $s1, $s1, 0x1
/* 6618 8002B218 2A220004 */  slti       $v0, $s1, 0x4
/* 661C 8002B21C 1440FFF2 */  bnez       $v0, .L8002B1E8
/* 6620 8002B220 0200202D */   daddu     $a0, $s0, $zero
.L8002B224:
/* 6624 8002B224 0C00AC40 */  jal        fio_validate_file_checksum
/* 6628 8002B228 0280202D */   daddu     $a0, $s4, $zero
/* 662C 8002B22C 50400016 */  beql       $v0, $zero, .L8002B288
/* 6630 8002B230 AE400004 */   sw        $zero, 0x4($s2)
/* 6634 8002B234 523E0014 */  beql       $s1, $fp, .L8002B288
/* 6638 8002B238 AE400004 */   sw        $zero, 0x4($s2)
/* 663C 8002B23C 8E620038 */  lw         $v0, 0x38($s3)
/* 6640 8002B240 AE420000 */  sw         $v0, 0x0($s2)
/* 6644 8002B244 8E62003C */  lw         $v0, 0x3C($s3)
/* 6648 8002B248 AE420004 */  sw         $v0, 0x4($s2)
/* 664C 8002B24C 8E620038 */  lw         $v0, 0x38($s3)
/* 6650 8002B250 8E63003C */  lw         $v1, 0x3C($s3)
/* 6654 8002B254 000210C0 */  sll        $v0, $v0, 3
/* 6658 8002B258 00552021 */  addu       $a0, $v0, $s5
/* 665C 8002B25C 8C820004 */  lw         $v0, 0x4($a0)
/* 6660 8002B260 0043102A */  slt        $v0, $v0, $v1
/* 6664 8002B264 5040000A */  beql       $v0, $zero, .L8002B290
/* 6668 8002B268 26100001 */   addiu     $s0, $s0, 0x1
/* 666C 8002B26C AC900000 */  sw         $s0, 0x0($a0)
/* 6670 8002B270 8E620038 */  lw         $v0, 0x38($s3)
/* 6674 8002B274 8E63003C */  lw         $v1, 0x3C($s3)
/* 6678 8002B278 000210C0 */  sll        $v0, $v0, 3
/* 667C 8002B27C 00551021 */  addu       $v0, $v0, $s5
/* 6680 8002B280 0800ACA3 */  j          .L8002B28C
/* 6684 8002B284 AC430004 */   sw        $v1, 0x4($v0)
.L8002B288:
/* 6688 8002B288 AE570000 */  sw         $s7, 0x0($s2)
.L8002B28C:
/* 668C 8002B28C 26100001 */  addiu      $s0, $s0, 0x1
.L8002B290:
/* 6690 8002B290 2A020006 */  slti       $v0, $s0, 0x6
/* 6694 8002B294 1440FFD2 */  bnez       $v0, .L8002B1E0
/* 6698 8002B298 26520008 */   addiu     $s2, $s2, 0x8
/* 669C 8002B29C 3C057FFF */  lui        $a1, (0x7FFFFFFF >> 16)
/* 66A0 8002B2A0 34A5FFFF */  ori        $a1, $a1, (0x7FFFFFFF & 0xFFFF)
/* 66A4 8002B2A4 0000882D */  daddu      $s1, $zero, $zero
/* 66A8 8002B2A8 3C08800A */  lui        $t0, %hi(D_80099190)
/* 66AC 8002B2AC 25089190 */  addiu      $t0, $t0, %lo(D_80099190)
/* 66B0 8002B2B0 24070004 */  addiu      $a3, $zero, 0x4
/* 66B4 8002B2B4 3C06800A */  lui        $a2, %hi(nextAvailableSavePage)
/* 66B8 8002B2B8 24C691E0 */  addiu      $a2, $a2, %lo(nextAvailableSavePage)
/* 66BC 8002B2BC 3C04800A */  lui        $a0, %hi(physicalSaveInfo)
/* 66C0 8002B2C0 248491B0 */  addiu      $a0, $a0, %lo(physicalSaveInfo)
.L8002B2C4:
/* 66C4 8002B2C4 0000802D */  daddu      $s0, $zero, $zero
/* 66C8 8002B2C8 0100182D */  daddu      $v1, $t0, $zero
.L8002B2CC:
/* 66CC 8002B2CC 8C620000 */  lw         $v0, 0x0($v1)
/* 66D0 8002B2D0 12220005 */  beq        $s1, $v0, .L8002B2E8
/* 66D4 8002B2D4 00000000 */   nop
/* 66D8 8002B2D8 26100001 */  addiu      $s0, $s0, 0x1
/* 66DC 8002B2DC 2A020004 */  slti       $v0, $s0, 0x4
/* 66E0 8002B2E0 1440FFFA */  bnez       $v0, .L8002B2CC
/* 66E4 8002B2E4 24630008 */   addiu     $v1, $v1, 0x8
.L8002B2E8:
/* 66E8 8002B2E8 56070008 */  bnel       $s0, $a3, .L8002B30C
/* 66EC 8002B2EC 26310001 */   addiu     $s1, $s1, 0x1
/* 66F0 8002B2F0 8C830004 */  lw         $v1, 0x4($a0)
/* 66F4 8002B2F4 0065102A */  slt        $v0, $v1, $a1
/* 66F8 8002B2F8 50400004 */  beql       $v0, $zero, .L8002B30C
/* 66FC 8002B2FC 26310001 */   addiu     $s1, $s1, 0x1
/* 6700 8002B300 0060282D */  daddu      $a1, $v1, $zero
/* 6704 8002B304 ACD10000 */  sw         $s1, 0x0($a2)
/* 6708 8002B308 26310001 */  addiu      $s1, $s1, 0x1
.L8002B30C:
/* 670C 8002B30C 2A220006 */  slti       $v0, $s1, 0x6
/* 6710 8002B310 1440FFEC */  bnez       $v0, .L8002B2C4
/* 6714 8002B314 24840008 */   addiu     $a0, $a0, 0x8
/* 6718 8002B318 8FBF0034 */  lw         $ra, 0x34($sp)
/* 671C 8002B31C 8FBE0030 */  lw         $fp, 0x30($sp)
/* 6720 8002B320 8FB7002C */  lw         $s7, 0x2C($sp)
/* 6724 8002B324 8FB60028 */  lw         $s6, 0x28($sp)
/* 6728 8002B328 8FB50024 */  lw         $s5, 0x24($sp)
/* 672C 8002B32C 8FB40020 */  lw         $s4, 0x20($sp)
/* 6730 8002B330 8FB3001C */  lw         $s3, 0x1C($sp)
/* 6734 8002B334 8FB20018 */  lw         $s2, 0x18($sp)
/* 6738 8002B338 8FB10014 */  lw         $s1, 0x14($sp)
/* 673C 8002B33C 8FB00010 */  lw         $s0, 0x10($sp)
/* 6740 8002B340 24020001 */  addiu      $v0, $zero, 0x1
/* 6744 8002B344 03E00008 */  jr         $ra
/* 6748 8002B348 27BD0038 */   addiu     $sp, $sp, 0x38
