.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
glabel jtbl_filemenu_80251720
/* 17A140 80251720 8024D130 */ .word .Lfilemenu_8024D130
/* 17A144 80251724 8024D160 */ .word .Lfilemenu_8024D160
/* 17A148 80251728 8024D18C */ .word .Lfilemenu_8024D18C
/* 17A14C 8025172C 8024D344 */ .word .Lfilemenu_8024D344
/* 17A150 80251730 8024D1D0 */ .word .Lfilemenu_8024D1D0


.section .text
/* Generated by spimdisasm 1.11.1 */

glabel filemenu_choose_name_handle_input
/* 1758D0 8024CEB0 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 1758D4 8024CEB4 AFB00010 */  sw         $s0, 0x10($sp)
/* 1758D8 8024CEB8 0080802D */  daddu      $s0, $a0, $zero
/* 1758DC 8024CEBC 3C048016 */  lui        $a0, %hi(gWindows)
/* 1758E0 8024CEC0 24848910 */  addiu      $a0, $a0, %lo(gWindows)
/* 1758E4 8024CEC4 3C028015 */  lui        $v0, %hi(gCurrentLanguage)
/* 1758E8 8024CEC8 8C42AE4C */  lw         $v0, %lo(gCurrentLanguage)($v0)
/* 1758EC 8024CECC AFBF0018 */  sw         $ra, 0x18($sp)
/* 1758F0 8024CED0 AFB10014 */  sw         $s1, 0x14($sp)
/* 1758F4 8024CED4 92070003 */  lbu        $a3, 0x3($s0)
/* 1758F8 8024CED8 3C018025 */  lui        $at, %hi(D_filemenu_80250958)
/* 1758FC 8024CEDC 00220821 */  addu       $at, $at, $v0
/* 175900 8024CEE0 90220958 */  lbu        $v0, %lo(D_filemenu_80250958)($at)
/* 175904 8024CEE4 80830603 */  lb         $v1, 0x603($a0)
/* 175908 8024CEE8 00022842 */  srl        $a1, $v0, 1
/* 17590C 8024CEEC A4820610 */  sh         $v0, 0x610($a0)
/* 175910 8024CEF0 2402FFFF */  addiu      $v0, $zero, -0x1
/* 175914 8024CEF4 1062000B */  beq        $v1, $v0, .Lfilemenu_8024CF24
/* 175918 8024CEF8 2486060C */   addiu     $a2, $a0, 0x60C
/* 17591C 8024CEFC 00031140 */  sll        $v0, $v1, 5
/* 175920 8024CF00 00441021 */  addu       $v0, $v0, $a0
/* 175924 8024CF04 94420010 */  lhu        $v0, 0x10($v0)
/* 175928 8024CF08 00021400 */  sll        $v0, $v0, 16
/* 17592C 8024CF0C 00021C03 */  sra        $v1, $v0, 16
/* 175930 8024CF10 000217C2 */  srl        $v0, $v0, 31
/* 175934 8024CF14 00621821 */  addu       $v1, $v1, $v0
/* 175938 8024CF18 00031843 */  sra        $v1, $v1, 1
/* 17593C 8024CF1C 080933CB */  j          .Lfilemenu_8024CF2C
/* 175940 8024CF20 00651023 */   subu      $v0, $v1, $a1
.Lfilemenu_8024CF24:
/* 175944 8024CF24 240200A0 */  addiu      $v0, $zero, 0xA0
/* 175948 8024CF28 00451023 */  subu       $v0, $v0, $a1
.Lfilemenu_8024CF2C:
/* 17594C 8024CF2C 3C038025 */  lui        $v1, %hi(filemenu_heldButtons)
/* 175950 8024CF30 8C63174C */  lw         $v1, %lo(filemenu_heldButtons)($v1)
/* 175954 8024CF34 A4C20000 */  sh         $v0, 0x0($a2)
/* 175958 8024CF38 3C020004 */  lui        $v0, (0x40000 >> 16)
/* 17595C 8024CF3C 00621024 */  and        $v0, $v1, $v0
/* 175960 8024CF40 1040000A */  beqz       $v0, .Lfilemenu_8024CF6C
/* 175964 8024CF44 3C020008 */   lui       $v0, (0x80000 >> 16)
/* 175968 8024CF48 92020001 */  lbu        $v0, 0x1($s0)
/* 17596C 8024CF4C 2442FFFF */  addiu      $v0, $v0, -0x1
/* 175970 8024CF50 A2020001 */  sb         $v0, 0x1($s0)
/* 175974 8024CF54 00021600 */  sll        $v0, $v0, 24
/* 175978 8024CF58 04410021 */  bgez       $v0, .Lfilemenu_8024CFE0
/* 17597C 8024CF5C 00000000 */   nop
/* 175980 8024CF60 92020005 */  lbu        $v0, 0x5($s0)
/* 175984 8024CF64 080933F7 */  j          .Lfilemenu_8024CFDC
/* 175988 8024CF68 2442FFFF */   addiu     $v0, $v0, -0x1
.Lfilemenu_8024CF6C:
/* 17598C 8024CF6C 00621024 */  and        $v0, $v1, $v0
/* 175990 8024CF70 1040001B */  beqz       $v0, .Lfilemenu_8024CFE0
/* 175994 8024CF74 00000000 */   nop
/* 175998 8024CF78 92020001 */  lbu        $v0, 0x1($s0)
/* 17599C 8024CF7C 82030005 */  lb         $v1, 0x5($s0)
/* 1759A0 8024CF80 24420001 */  addiu      $v0, $v0, 0x1
/* 1759A4 8024CF84 A2020001 */  sb         $v0, 0x1($s0)
/* 1759A8 8024CF88 00021600 */  sll        $v0, $v0, 24
/* 1759AC 8024CF8C 00021603 */  sra        $v0, $v0, 24
/* 1759B0 8024CF90 0043102A */  slt        $v0, $v0, $v1
/* 1759B4 8024CF94 50400001 */  beql       $v0, $zero, .Lfilemenu_8024CF9C
/* 1759B8 8024CF98 A2000001 */   sb        $zero, 0x1($s0)
.Lfilemenu_8024CF9C:
/* 1759BC 8024CF9C 82020006 */  lb         $v0, 0x6($s0)
/* 1759C0 8024CFA0 82030002 */  lb         $v1, 0x2($s0)
/* 1759C4 8024CFA4 2442FFFF */  addiu      $v0, $v0, -0x1
/* 1759C8 8024CFA8 1462000D */  bne        $v1, $v0, .Lfilemenu_8024CFE0
/* 1759CC 8024CFAC 00000000 */   nop
/* 1759D0 8024CFB0 82020001 */  lb         $v0, 0x1($s0)
/* 1759D4 8024CFB4 92030001 */  lbu        $v1, 0x1($s0)
/* 1759D8 8024CFB8 2842000B */  slti       $v0, $v0, 0xB
/* 1759DC 8024CFBC 14400003 */  bnez       $v0, .Lfilemenu_8024CFCC
/* 1759E0 8024CFC0 2462FFF8 */   addiu     $v0, $v1, -0x8
/* 1759E4 8024CFC4 080933F8 */  j          .Lfilemenu_8024CFE0
/* 1759E8 8024CFC8 A2000001 */   sb        $zero, 0x1($s0)
.Lfilemenu_8024CFCC:
/* 1759EC 8024CFCC 304200FF */  andi       $v0, $v0, 0xFF
/* 1759F0 8024CFD0 2C420002 */  sltiu      $v0, $v0, 0x2
/* 1759F4 8024CFD4 10400002 */  beqz       $v0, .Lfilemenu_8024CFE0
/* 1759F8 8024CFD8 2402000A */   addiu     $v0, $zero, 0xA
.Lfilemenu_8024CFDC:
/* 1759FC 8024CFDC A2020001 */  sb         $v0, 0x1($s0)
.Lfilemenu_8024CFE0:
/* 175A00 8024CFE0 3C038025 */  lui        $v1, %hi(filemenu_heldButtons)
/* 175A04 8024CFE4 8C63174C */  lw         $v1, %lo(filemenu_heldButtons)($v1)
/* 175A08 8024CFE8 3C020001 */  lui        $v0, (0x10000 >> 16)
/* 175A0C 8024CFEC 00621024 */  and        $v0, $v1, $v0
/* 175A10 8024CFF0 1040000B */  beqz       $v0, .Lfilemenu_8024D020
/* 175A14 8024CFF4 3C020002 */   lui       $v0, (0x20000 >> 16)
/* 175A18 8024CFF8 92020002 */  lbu        $v0, 0x2($s0)
/* 175A1C 8024CFFC 2442FFFF */  addiu      $v0, $v0, -0x1
/* 175A20 8024D000 A2020002 */  sb         $v0, 0x2($s0)
/* 175A24 8024D004 00021600 */  sll        $v0, $v0, 24
/* 175A28 8024D008 04410011 */  bgez       $v0, .Lfilemenu_8024D050
/* 175A2C 8024D00C 00000000 */   nop
/* 175A30 8024D010 92020006 */  lbu        $v0, 0x6($s0)
/* 175A34 8024D014 2442FFFF */  addiu      $v0, $v0, -0x1
/* 175A38 8024D018 08093414 */  j          .Lfilemenu_8024D050
/* 175A3C 8024D01C A2020002 */   sb        $v0, 0x2($s0)
.Lfilemenu_8024D020:
/* 175A40 8024D020 00621024 */  and        $v0, $v1, $v0
/* 175A44 8024D024 1040000A */  beqz       $v0, .Lfilemenu_8024D050
/* 175A48 8024D028 00000000 */   nop
/* 175A4C 8024D02C 92020002 */  lbu        $v0, 0x2($s0)
/* 175A50 8024D030 82030006 */  lb         $v1, 0x6($s0)
/* 175A54 8024D034 24420001 */  addiu      $v0, $v0, 0x1
/* 175A58 8024D038 A2020002 */  sb         $v0, 0x2($s0)
/* 175A5C 8024D03C 00021600 */  sll        $v0, $v0, 24
/* 175A60 8024D040 00021603 */  sra        $v0, $v0, 24
/* 175A64 8024D044 0043102A */  slt        $v0, $v0, $v1
/* 175A68 8024D048 50400001 */  beql       $v0, $zero, .Lfilemenu_8024D050
/* 175A6C 8024D04C A2000002 */   sb        $zero, 0x2($s0)
.Lfilemenu_8024D050:
/* 175A70 8024D050 82020006 */  lb         $v0, 0x6($s0)
/* 175A74 8024D054 82030002 */  lb         $v1, 0x2($s0)
/* 175A78 8024D058 2442FFFF */  addiu      $v0, $v0, -0x1
/* 175A7C 8024D05C 1462000D */  bne        $v1, $v0, .Lfilemenu_8024D094
/* 175A80 8024D060 00000000 */   nop
/* 175A84 8024D064 82020001 */  lb         $v0, 0x1($s0)
/* 175A88 8024D068 92030001 */  lbu        $v1, 0x1($s0)
/* 175A8C 8024D06C 2842000B */  slti       $v0, $v0, 0xB
/* 175A90 8024D070 14400003 */  bnez       $v0, .Lfilemenu_8024D080
/* 175A94 8024D074 2462FFF8 */   addiu     $v0, $v1, -0x8
/* 175A98 8024D078 08093424 */  j          .Lfilemenu_8024D090
/* 175A9C 8024D07C 2402000A */   addiu     $v0, $zero, 0xA
.Lfilemenu_8024D080:
/* 175AA0 8024D080 304200FF */  andi       $v0, $v0, 0xFF
/* 175AA4 8024D084 2C420002 */  sltiu      $v0, $v0, 0x2
/* 175AA8 8024D088 10400002 */  beqz       $v0, .Lfilemenu_8024D094
/* 175AAC 8024D08C 24020007 */   addiu     $v0, $zero, 0x7
.Lfilemenu_8024D090:
/* 175AB0 8024D090 A2020001 */  sb         $v0, 0x1($s0)
.Lfilemenu_8024D094:
/* 175AB4 8024D094 82020004 */  lb         $v0, 0x4($s0)
/* 175AB8 8024D098 82030005 */  lb         $v1, 0x5($s0)
/* 175ABC 8024D09C 00430018 */  mult       $v0, $v1
/* 175AC0 8024D0A0 00004812 */  mflo       $t1
/* 175AC4 8024D0A4 82020006 */  lb         $v0, 0x6($s0)
/* 175AC8 8024D0A8 00000000 */  nop
/* 175ACC 8024D0AC 01220018 */  mult       $t1, $v0
/* 175AD0 8024D0B0 00002012 */  mflo       $a0
/* 175AD4 8024D0B4 82020002 */  lb         $v0, 0x2($s0)
/* 175AD8 8024D0B8 00000000 */  nop
/* 175ADC 8024D0BC 00620018 */  mult       $v1, $v0
/* 175AE0 8024D0C0 00001012 */  mflo       $v0
/* 175AE4 8024D0C4 00821821 */  addu       $v1, $a0, $v0
/* 175AE8 8024D0C8 82040001 */  lb         $a0, 0x1($s0)
/* 175AEC 8024D0CC 8E020008 */  lw         $v0, 0x8($s0)
/* 175AF0 8024D0D0 00641821 */  addu       $v1, $v1, $a0
/* 175AF4 8024D0D4 00431021 */  addu       $v0, $v0, $v1
/* 175AF8 8024D0D8 90420000 */  lbu        $v0, 0x0($v0)
/* 175AFC 8024D0DC A2020003 */  sb         $v0, 0x3($s0)
/* 175B00 8024D0E0 304200FF */  andi       $v0, $v0, 0xFF
/* 175B04 8024D0E4 10E20003 */  beq        $a3, $v0, .Lfilemenu_8024D0F4
/* 175B08 8024D0E8 00000000 */   nop
/* 175B0C 8024D0EC 0C052219 */  jal        sfx_play_sound
/* 175B10 8024D0F0 24042102 */   addiu     $a0, $zero, 0x2102
.Lfilemenu_8024D0F4:
/* 175B14 8024D0F4 3C028025 */  lui        $v0, %hi(filemenu_pressedButtons)
/* 175B18 8024D0F8 8C421744 */  lw         $v0, %lo(filemenu_pressedButtons)($v0)
/* 175B1C 8024D0FC 30428000 */  andi       $v0, $v0, 0x8000
/* 175B20 8024D100 1040009F */  beqz       $v0, .Lfilemenu_8024D380
/* 175B24 8024D104 00000000 */   nop
/* 175B28 8024D108 92020003 */  lbu        $v0, 0x3($s0)
/* 175B2C 8024D10C 2443FF3A */  addiu      $v1, $v0, -0xC6
/* 175B30 8024D110 2C620005 */  sltiu      $v0, $v1, 0x5
/* 175B34 8024D114 10400072 */  beqz       $v0, .Lfilemenu_8024D2E0
/* 175B38 8024D118 00031080 */   sll       $v0, $v1, 2
/* 175B3C 8024D11C 3C018025 */  lui        $at, %hi(jtbl_filemenu_80251720)
/* 175B40 8024D120 00220821 */  addu       $at, $at, $v0
/* 175B44 8024D124 8C221720 */  lw         $v0, %lo(jtbl_filemenu_80251720)($at)
/* 175B48 8024D128 00400008 */  jr         $v0
/* 175B4C 8024D12C 00000000 */   nop
.Lfilemenu_8024D130:
/* 175B50 8024D130 0C052219 */  jal        sfx_play_sound
/* 175B54 8024D134 24042103 */   addiu     $a0, $zero, 0x2103
/* 175B58 8024D138 3C048025 */  lui        $a0, %hi(filemenu_filename_pos)
/* 175B5C 8024D13C 24841750 */  addiu      $a0, $a0, %lo(filemenu_filename_pos)
/* 175B60 8024D140 80820000 */  lb         $v0, 0x0($a0)
/* 175B64 8024D144 24050008 */  addiu      $a1, $zero, 0x8
/* 175B68 8024D148 14450002 */  bne        $v0, $a1, .Lfilemenu_8024D154
/* 175B6C 8024D14C 24020007 */   addiu     $v0, $zero, 0x7
/* 175B70 8024D150 A0820000 */  sb         $v0, 0x0($a0)
.Lfilemenu_8024D154:
/* 175B74 8024D154 80830000 */  lb         $v1, 0x0($a0)
/* 175B78 8024D158 080934C6 */  j          .Lfilemenu_8024D318
/* 175B7C 8024D15C 240200F7 */   addiu     $v0, $zero, 0xF7
.Lfilemenu_8024D160:
/* 175B80 8024D160 82020004 */  lb         $v0, 0x4($s0)
/* 175B84 8024D164 24110001 */  addiu      $s1, $zero, 0x1
/* 175B88 8024D168 10510076 */  beq        $v0, $s1, .Lfilemenu_8024D344
/* 175B8C 8024D16C 00000000 */   nop
/* 175B90 8024D170 0C052219 */  jal        sfx_play_sound
/* 175B94 8024D174 24042105 */   addiu     $a0, $zero, 0x2105
/* 175B98 8024D178 82050001 */  lb         $a1, 0x1($s0)
/* 175B9C 8024D17C 82060002 */  lb         $a2, 0x2($s0)
/* 175BA0 8024D180 0200202D */  daddu      $a0, $s0, $zero
/* 175BA4 8024D184 0809346C */  j          .Lfilemenu_8024D1B0
/* 175BA8 8024D188 A2110004 */   sb        $s1, 0x4($s0)
.Lfilemenu_8024D18C:
/* 175BAC 8024D18C 82020004 */  lb         $v0, 0x4($s0)
/* 175BB0 8024D190 1040006C */  beqz       $v0, .Lfilemenu_8024D344
/* 175BB4 8024D194 00000000 */   nop
/* 175BB8 8024D198 0C052219 */  jal        sfx_play_sound
/* 175BBC 8024D19C 24042105 */   addiu     $a0, $zero, 0x2105
/* 175BC0 8024D1A0 82050001 */  lb         $a1, 0x1($s0)
/* 175BC4 8024D1A4 82060002 */  lb         $a2, 0x2($s0)
/* 175BC8 8024D1A8 0200202D */  daddu      $a0, $s0, $zero
/* 175BCC 8024D1AC A2000004 */  sb         $zero, 0x4($s0)
.Lfilemenu_8024D1B0:
/* 175BD0 8024D1B0 0C091B29 */  jal        filemenu_set_selected
/* 175BD4 8024D1B4 00000000 */   nop
/* 175BD8 8024D1B8 3C058025 */  lui        $a1, %hi(filemenu_update_change_layout)
/* 175BDC 8024D1BC 24A5C330 */  addiu      $a1, $a1, %lo(filemenu_update_change_layout)
/* 175BE0 8024D1C0 0C051A8B */  jal        set_window_update
/* 175BE4 8024D1C4 24040031 */   addiu     $a0, $zero, 0x31
/* 175BE8 8024D1C8 080934D1 */  j          .Lfilemenu_8024D344
/* 175BEC 8024D1CC 00000000 */   nop
.Lfilemenu_8024D1D0:
/* 175BF0 8024D1D0 0000182D */  daddu      $v1, $zero, $zero
/* 175BF4 8024D1D4 3C058025 */  lui        $a1, %hi(filemenu_filename)
/* 175BF8 8024D1D8 24A527E0 */  addiu      $a1, $a1, %lo(filemenu_filename)
/* 175BFC 8024D1DC 240400F7 */  addiu      $a0, $zero, 0xF7
/* 175C00 8024D1E0 00651021 */  addu       $v0, $v1, $a1
.Lfilemenu_8024D1E4:
/* 175C04 8024D1E4 90420000 */  lbu        $v0, 0x0($v0)
/* 175C08 8024D1E8 14440006 */  bne        $v0, $a0, .Lfilemenu_8024D204
/* 175C0C 8024D1EC 24020008 */   addiu     $v0, $zero, 0x8
/* 175C10 8024D1F0 24630001 */  addiu      $v1, $v1, 0x1
/* 175C14 8024D1F4 28620008 */  slti       $v0, $v1, 0x8
/* 175C18 8024D1F8 1440FFFA */  bnez       $v0, .Lfilemenu_8024D1E4
/* 175C1C 8024D1FC 00651021 */   addu      $v0, $v1, $a1
/* 175C20 8024D200 24020008 */  addiu      $v0, $zero, 0x8
.Lfilemenu_8024D204:
/* 175C24 8024D204 14620005 */  bne        $v1, $v0, .Lfilemenu_8024D21C
/* 175C28 8024D208 00000000 */   nop
/* 175C2C 8024D20C 0C052219 */  jal        sfx_play_sound
/* 175C30 8024D210 2404021D */   addiu     $a0, $zero, 0x21D
/* 175C34 8024D214 080934D1 */  j          .Lfilemenu_8024D344
/* 175C38 8024D218 00000000 */   nop
.Lfilemenu_8024D21C:
/* 175C3C 8024D21C 0C052219 */  jal        sfx_play_sound
/* 175C40 8024D220 240400C9 */   addiu     $a0, $zero, 0xC9
/* 175C44 8024D224 3C058024 */  lui        $a1, %hi(filemenu_update_show_name_confirm)
/* 175C48 8024D228 24A57BDC */  addiu      $a1, $a1, %lo(filemenu_update_show_name_confirm)
/* 175C4C 8024D22C 0C051A8B */  jal        set_window_update
/* 175C50 8024D230 24040032 */   addiu     $a0, $zero, 0x32
/* 175C54 8024D234 3C048016 */  lui        $a0, %hi(gWindows)
/* 175C58 8024D238 24848910 */  addiu      $a0, $a0, %lo(gWindows)
/* 175C5C 8024D23C 24020079 */  addiu      $v0, $zero, 0x79
/* 175C60 8024D240 A482064E */  sh         $v0, 0x64E($a0)
/* 175C64 8024D244 24020045 */  addiu      $v0, $zero, 0x45
/* 175C68 8024D248 A4820650 */  sh         $v0, 0x650($a0)
/* 175C6C 8024D24C 2402002C */  addiu      $v0, $zero, 0x2C
/* 175C70 8024D250 80830643 */  lb         $v1, 0x643($a0)
/* 175C74 8024D254 A4820652 */  sh         $v0, 0x652($a0)
/* 175C78 8024D258 2402FFFF */  addiu      $v0, $zero, -0x1
/* 175C7C 8024D25C 1062000B */  beq        $v1, $v0, .Lfilemenu_8024D28C
/* 175C80 8024D260 2485064C */   addiu     $a1, $a0, 0x64C
/* 175C84 8024D264 00031140 */  sll        $v0, $v1, 5
/* 175C88 8024D268 00441021 */  addu       $v0, $v0, $a0
/* 175C8C 8024D26C 94420010 */  lhu        $v0, 0x10($v0)
/* 175C90 8024D270 00021400 */  sll        $v0, $v0, 16
/* 175C94 8024D274 00021C03 */  sra        $v1, $v0, 16
/* 175C98 8024D278 000217C2 */  srl        $v0, $v0, 31
/* 175C9C 8024D27C 00621821 */  addu       $v1, $v1, $v0
/* 175CA0 8024D280 00031843 */  sra        $v1, $v1, 1
/* 175CA4 8024D284 080934A6 */  j          .Lfilemenu_8024D298
/* 175CA8 8024D288 2463FFDE */   addiu     $v1, $v1, -0x22
.Lfilemenu_8024D28C:
/* 175CAC 8024D28C 2403007E */  addiu      $v1, $zero, 0x7E
/* 175CB0 8024D290 3C048016 */  lui        $a0, %hi(gWindows)
/* 175CB4 8024D294 24848910 */  addiu      $a0, $a0, %lo(gWindows)
.Lfilemenu_8024D298:
/* 175CB8 8024D298 A4A30000 */  sh         $v1, 0x0($a1)
/* 175CBC 8024D29C 3C038015 */  lui        $v1, %hi(gCurrentLanguage)
/* 175CC0 8024D2A0 8C63AE4C */  lw         $v1, %lo(gCurrentLanguage)($v1)
/* 175CC4 8024D2A4 2402FFBA */  addiu      $v0, $zero, -0x46
/* 175CC8 8024D2A8 A48205CE */  sh         $v0, 0x5CE($a0)
/* 175CCC 8024D2AC 2402003E */  addiu      $v0, $zero, 0x3E
/* 175CD0 8024D2B0 3C018025 */  lui        $at, %hi(D_filemenu_80250960)
/* 175CD4 8024D2B4 00230821 */  addu       $at, $at, $v1
/* 175CD8 8024D2B8 90230960 */  lbu        $v1, %lo(D_filemenu_80250960)($at)
/* 175CDC 8024D2BC A48205D2 */  sh         $v0, 0x5D2($a0)
/* 175CE0 8024D2C0 00032842 */  srl        $a1, $v1, 1
/* 175CE4 8024D2C4 A48305D0 */  sh         $v1, 0x5D0($a0)
/* 175CE8 8024D2C8 808305C3 */  lb         $v1, 0x5C3($a0)
/* 175CEC 8024D2CC 2402FFFF */  addiu      $v0, $zero, -0x1
/* 175CF0 8024D2D0 146200C2 */  bne        $v1, $v0, .Lfilemenu_8024D5DC
/* 175CF4 8024D2D4 248705CC */   addiu     $a3, $a0, 0x5CC
/* 175CF8 8024D2D8 08093582 */  j          .Lfilemenu_8024D608
/* 175CFC 8024D2DC 240200A0 */   addiu     $v0, $zero, 0xA0
.Lfilemenu_8024D2E0:
/* 175D00 8024D2E0 0C052219 */  jal        sfx_play_sound
/* 175D04 8024D2E4 24042103 */   addiu     $a0, $zero, 0x2103
/* 175D08 8024D2E8 3C048025 */  lui        $a0, %hi(filemenu_filename_pos)
/* 175D0C 8024D2EC 24841750 */  addiu      $a0, $a0, %lo(filemenu_filename_pos)
/* 175D10 8024D2F0 80830000 */  lb         $v1, 0x0($a0)
/* 175D14 8024D2F4 24050008 */  addiu      $a1, $zero, 0x8
/* 175D18 8024D2F8 14650006 */  bne        $v1, $a1, .Lfilemenu_8024D314
/* 175D1C 8024D2FC 00000000 */   nop
/* 175D20 8024D300 92020003 */  lbu        $v0, 0x3($s0)
/* 175D24 8024D304 3C018025 */  lui        $at, %hi(filemenu_filename+0x7)
/* 175D28 8024D308 A02227E7 */  sb         $v0, %lo(filemenu_filename+0x7)($at)
/* 175D2C 8024D30C 080934D1 */  j          .Lfilemenu_8024D344
/* 175D30 8024D310 00000000 */   nop
.Lfilemenu_8024D314:
/* 175D34 8024D314 92020003 */  lbu        $v0, 0x3($s0)
.Lfilemenu_8024D318:
/* 175D38 8024D318 3C018025 */  lui        $at, %hi(filemenu_filename)
/* 175D3C 8024D31C 00230821 */  addu       $at, $at, $v1
/* 175D40 8024D320 A02227E0 */  sb         $v0, %lo(filemenu_filename)($at)
/* 175D44 8024D324 90820000 */  lbu        $v0, 0x0($a0)
/* 175D48 8024D328 24420001 */  addiu      $v0, $v0, 0x1
/* 175D4C 8024D32C A0820000 */  sb         $v0, 0x0($a0)
/* 175D50 8024D330 00021600 */  sll        $v0, $v0, 24
/* 175D54 8024D334 00021603 */  sra        $v0, $v0, 24
/* 175D58 8024D338 28420009 */  slti       $v0, $v0, 0x9
/* 175D5C 8024D33C 50400001 */  beql       $v0, $zero, .Lfilemenu_8024D344
/* 175D60 8024D340 A0850000 */   sb        $a1, 0x0($a0)
.Lfilemenu_8024D344:
/* 175D64 8024D344 92020003 */  lbu        $v0, 0x3($s0)
/* 175D68 8024D348 24420039 */  addiu      $v0, $v0, 0x39
/* 175D6C 8024D34C 304200FF */  andi       $v0, $v0, 0xFF
/* 175D70 8024D350 2C420003 */  sltiu      $v0, $v0, 0x3
/* 175D74 8024D354 1440000A */  bnez       $v0, .Lfilemenu_8024D380
/* 175D78 8024D358 24020008 */   addiu     $v0, $zero, 0x8
/* 175D7C 8024D35C 3C038025 */  lui        $v1, %hi(filemenu_filename_pos)
/* 175D80 8024D360 80631750 */  lb         $v1, %lo(filemenu_filename_pos)($v1)
/* 175D84 8024D364 14620006 */  bne        $v1, $v0, .Lfilemenu_8024D380
/* 175D88 8024D368 0200202D */   daddu     $a0, $s0, $zero
/* 175D8C 8024D36C 82050005 */  lb         $a1, 0x5($s0)
/* 175D90 8024D370 82060006 */  lb         $a2, 0x6($s0)
/* 175D94 8024D374 24A5FFFD */  addiu      $a1, $a1, -0x3
/* 175D98 8024D378 0C091B29 */  jal        filemenu_set_selected
/* 175D9C 8024D37C 24C6FFFF */   addiu     $a2, $a2, -0x1
.Lfilemenu_8024D380:
/* 175DA0 8024D380 3C038025 */  lui        $v1, %hi(filemenu_pressedButtons)
/* 175DA4 8024D384 8C631744 */  lw         $v1, %lo(filemenu_pressedButtons)($v1)
/* 175DA8 8024D388 30624000 */  andi       $v0, $v1, 0x4000
/* 175DAC 8024D38C 14400006 */  bnez       $v0, .Lfilemenu_8024D3A8
/* 175DB0 8024D390 30628000 */   andi      $v0, $v1, 0x8000
/* 175DB4 8024D394 1040004B */  beqz       $v0, .Lfilemenu_8024D4C4
/* 175DB8 8024D398 240200C9 */   addiu     $v0, $zero, 0xC9
/* 175DBC 8024D39C 92030003 */  lbu        $v1, 0x3($s0)
/* 175DC0 8024D3A0 14620048 */  bne        $v1, $v0, .Lfilemenu_8024D4C4
/* 175DC4 8024D3A4 00000000 */   nop
.Lfilemenu_8024D3A8:
/* 175DC8 8024D3A8 0C052219 */  jal        sfx_play_sound
/* 175DCC 8024D3AC 24042104 */   addiu     $a0, $zero, 0x2104
/* 175DD0 8024D3B0 3C038025 */  lui        $v1, %hi(filemenu_filename_pos)
/* 175DD4 8024D3B4 24631750 */  addiu      $v1, $v1, %lo(filemenu_filename_pos)
/* 175DD8 8024D3B8 90620000 */  lbu        $v0, 0x0($v1)
/* 175DDC 8024D3BC 2442FFFF */  addiu      $v0, $v0, -0x1
/* 175DE0 8024D3C0 A0620000 */  sb         $v0, 0x0($v1)
/* 175DE4 8024D3C4 00021600 */  sll        $v0, $v0, 24
/* 175DE8 8024D3C8 00021603 */  sra        $v0, $v0, 24
/* 175DEC 8024D3CC 04430031 */  bgezl      $v0, .Lfilemenu_8024D494
/* 175DF0 8024D3D0 0040182D */   daddu     $v1, $v0, $zero
/* 175DF4 8024D3D4 24040030 */  addiu      $a0, $zero, 0x30
/* 175DF8 8024D3D8 3C108024 */  lui        $s0, %hi(filemenu_update_hidden_name_input)
/* 175DFC 8024D3DC 26107538 */  addiu      $s0, $s0, %lo(filemenu_update_hidden_name_input)
/* 175E00 8024D3E0 0200282D */  daddu      $a1, $s0, $zero
/* 175E04 8024D3E4 0C051A8B */  jal        set_window_update
/* 175E08 8024D3E8 A0600000 */   sb        $zero, 0x0($v1)
/* 175E0C 8024D3EC 24040031 */  addiu      $a0, $zero, 0x31
/* 175E10 8024D3F0 0C051A8B */  jal        set_window_update
/* 175E14 8024D3F4 0200282D */   daddu     $a1, $s0, $zero
/* 175E18 8024D3F8 2404002D */  addiu      $a0, $zero, 0x2D
/* 175E1C 8024D3FC 3C108024 */  lui        $s0, %hi(filemenu_update_show_with_rotation)
/* 175E20 8024D400 2610772C */  addiu      $s0, $s0, %lo(filemenu_update_show_with_rotation)
/* 175E24 8024D404 0C051A8B */  jal        set_window_update
/* 175E28 8024D408 0200282D */   daddu     $a1, $s0, $zero
/* 175E2C 8024D40C 24040033 */  addiu      $a0, $zero, 0x33
/* 175E30 8024D410 0C051A8B */  jal        set_window_update
/* 175E34 8024D414 0200282D */   daddu     $a1, $s0, $zero
/* 175E38 8024D418 24040034 */  addiu      $a0, $zero, 0x34
/* 175E3C 8024D41C 0C051A8B */  jal        set_window_update
/* 175E40 8024D420 0200282D */   daddu     $a1, $s0, $zero
/* 175E44 8024D424 24040035 */  addiu      $a0, $zero, 0x35
/* 175E48 8024D428 0C051A8B */  jal        set_window_update
/* 175E4C 8024D42C 0200282D */   daddu     $a1, $s0, $zero
/* 175E50 8024D430 24040036 */  addiu      $a0, $zero, 0x36
/* 175E54 8024D434 0C051A8B */  jal        set_window_update
/* 175E58 8024D438 0200282D */   daddu     $a1, $s0, $zero
/* 175E5C 8024D43C 24040037 */  addiu      $a0, $zero, 0x37
/* 175E60 8024D440 0C051A8B */  jal        set_window_update
/* 175E64 8024D444 0200282D */   daddu     $a1, $s0, $zero
/* 175E68 8024D448 24040035 */  addiu      $a0, $zero, 0x35
/* 175E6C 8024D44C 0C051A8B */  jal        set_window_update
/* 175E70 8024D450 0200282D */   daddu     $a1, $s0, $zero
/* 175E74 8024D454 24040038 */  addiu      $a0, $zero, 0x38
/* 175E78 8024D458 0C051A8B */  jal        set_window_update
/* 175E7C 8024D45C 0200282D */   daddu     $a1, $s0, $zero
/* 175E80 8024D460 24040039 */  addiu      $a0, $zero, 0x39
/* 175E84 8024D464 0C051A8B */  jal        set_window_update
/* 175E88 8024D468 0200282D */   daddu     $a1, $s0, $zero
/* 175E8C 8024D46C 2404003A */  addiu      $a0, $zero, 0x3A
/* 175E90 8024D470 0C051A8B */  jal        set_window_update
/* 175E94 8024D474 0200282D */   daddu     $a1, $s0, $zero
/* 175E98 8024D478 2404003B */  addiu      $a0, $zero, 0x3B
/* 175E9C 8024D47C 0C051A8B */  jal        set_window_update
/* 175EA0 8024D480 0200282D */   daddu     $a1, $s0, $zero
/* 175EA4 8024D484 3C018025 */  lui        $at, %hi(filemenu_currentMenu)
/* 175EA8 8024D488 A0201758 */  sb         $zero, %lo(filemenu_currentMenu)($at)
/* 175EAC 8024D48C 0809358E */  j          .Lfilemenu_8024D638
/* 175EB0 8024D490 00000000 */   nop
.Lfilemenu_8024D494:
/* 175EB4 8024D494 28620008 */  slti       $v0, $v1, 0x8
/* 175EB8 8024D498 1040000A */  beqz       $v0, .Lfilemenu_8024D4C4
/* 175EBC 8024D49C 00000000 */   nop
/* 175EC0 8024D4A0 3C058025 */  lui        $a1, %hi(filemenu_filename)
/* 175EC4 8024D4A4 24A527E0 */  addiu      $a1, $a1, %lo(filemenu_filename)
/* 175EC8 8024D4A8 240400F7 */  addiu      $a0, $zero, 0xF7
/* 175ECC 8024D4AC 00651021 */  addu       $v0, $v1, $a1
.Lfilemenu_8024D4B0:
/* 175ED0 8024D4B0 A0440000 */  sb         $a0, 0x0($v0)
/* 175ED4 8024D4B4 24630001 */  addiu      $v1, $v1, 0x1
/* 175ED8 8024D4B8 28620008 */  slti       $v0, $v1, 0x8
/* 175EDC 8024D4BC 1440FFFC */  bnez       $v0, .Lfilemenu_8024D4B0
/* 175EE0 8024D4C0 00651021 */   addu      $v0, $v1, $a1
.Lfilemenu_8024D4C4:
/* 175EE4 8024D4C4 3C028025 */  lui        $v0, %hi(filemenu_pressedButtons)
/* 175EE8 8024D4C8 8C421744 */  lw         $v0, %lo(filemenu_pressedButtons)($v0)
/* 175EEC 8024D4CC 30421000 */  andi       $v0, $v0, 0x1000
/* 175EF0 8024D4D0 10400059 */  beqz       $v0, .Lfilemenu_8024D638
/* 175EF4 8024D4D4 0000182D */   daddu     $v1, $zero, $zero
/* 175EF8 8024D4D8 3C058025 */  lui        $a1, %hi(filemenu_filename)
/* 175EFC 8024D4DC 24A527E0 */  addiu      $a1, $a1, %lo(filemenu_filename)
/* 175F00 8024D4E0 240400F7 */  addiu      $a0, $zero, 0xF7
/* 175F04 8024D4E4 00651021 */  addu       $v0, $v1, $a1
.Lfilemenu_8024D4E8:
/* 175F08 8024D4E8 90420000 */  lbu        $v0, 0x0($v0)
/* 175F0C 8024D4EC 14440006 */  bne        $v0, $a0, .Lfilemenu_8024D508
/* 175F10 8024D4F0 24020008 */   addiu     $v0, $zero, 0x8
/* 175F14 8024D4F4 24630001 */  addiu      $v1, $v1, 0x1
/* 175F18 8024D4F8 28620008 */  slti       $v0, $v1, 0x8
/* 175F1C 8024D4FC 1440FFFA */  bnez       $v0, .Lfilemenu_8024D4E8
/* 175F20 8024D500 00651021 */   addu      $v0, $v1, $a1
/* 175F24 8024D504 24020008 */  addiu      $v0, $zero, 0x8
.Lfilemenu_8024D508:
/* 175F28 8024D508 14620005 */  bne        $v1, $v0, .Lfilemenu_8024D520
/* 175F2C 8024D50C 00000000 */   nop
/* 175F30 8024D510 0C052219 */  jal        sfx_play_sound
/* 175F34 8024D514 2404021D */   addiu     $a0, $zero, 0x21D
/* 175F38 8024D518 0809358E */  j          .Lfilemenu_8024D638
/* 175F3C 8024D51C 00000000 */   nop
.Lfilemenu_8024D520:
/* 175F40 8024D520 0C052219 */  jal        sfx_play_sound
/* 175F44 8024D524 240400C9 */   addiu     $a0, $zero, 0xC9
/* 175F48 8024D528 3C058024 */  lui        $a1, %hi(filemenu_update_show_name_confirm)
/* 175F4C 8024D52C 24A57BDC */  addiu      $a1, $a1, %lo(filemenu_update_show_name_confirm)
/* 175F50 8024D530 0C051A8B */  jal        set_window_update
/* 175F54 8024D534 24040032 */   addiu     $a0, $zero, 0x32
/* 175F58 8024D538 3C048016 */  lui        $a0, %hi(gWindows)
/* 175F5C 8024D53C 24848910 */  addiu      $a0, $a0, %lo(gWindows)
/* 175F60 8024D540 24020079 */  addiu      $v0, $zero, 0x79
/* 175F64 8024D544 A482064E */  sh         $v0, 0x64E($a0)
/* 175F68 8024D548 24020045 */  addiu      $v0, $zero, 0x45
/* 175F6C 8024D54C A4820650 */  sh         $v0, 0x650($a0)
/* 175F70 8024D550 2402002C */  addiu      $v0, $zero, 0x2C
/* 175F74 8024D554 80830643 */  lb         $v1, 0x643($a0)
/* 175F78 8024D558 A4820652 */  sh         $v0, 0x652($a0)
/* 175F7C 8024D55C 2402FFFF */  addiu      $v0, $zero, -0x1
/* 175F80 8024D560 1062000B */  beq        $v1, $v0, .Lfilemenu_8024D590
/* 175F84 8024D564 2485064C */   addiu     $a1, $a0, 0x64C
/* 175F88 8024D568 00031140 */  sll        $v0, $v1, 5
/* 175F8C 8024D56C 00441021 */  addu       $v0, $v0, $a0
/* 175F90 8024D570 94420010 */  lhu        $v0, 0x10($v0)
/* 175F94 8024D574 00021400 */  sll        $v0, $v0, 16
/* 175F98 8024D578 00021C03 */  sra        $v1, $v0, 16
/* 175F9C 8024D57C 000217C2 */  srl        $v0, $v0, 31
/* 175FA0 8024D580 00621821 */  addu       $v1, $v1, $v0
/* 175FA4 8024D584 00031843 */  sra        $v1, $v1, 1
/* 175FA8 8024D588 08093567 */  j          .Lfilemenu_8024D59C
/* 175FAC 8024D58C 2463FFDE */   addiu     $v1, $v1, -0x22
.Lfilemenu_8024D590:
/* 175FB0 8024D590 2403007E */  addiu      $v1, $zero, 0x7E
/* 175FB4 8024D594 3C048016 */  lui        $a0, %hi(gWindows)
/* 175FB8 8024D598 24848910 */  addiu      $a0, $a0, %lo(gWindows)
.Lfilemenu_8024D59C:
/* 175FBC 8024D59C A4A30000 */  sh         $v1, 0x0($a1)
/* 175FC0 8024D5A0 3C038015 */  lui        $v1, %hi(gCurrentLanguage)
/* 175FC4 8024D5A4 8C63AE4C */  lw         $v1, %lo(gCurrentLanguage)($v1)
/* 175FC8 8024D5A8 2402FFBA */  addiu      $v0, $zero, -0x46
/* 175FCC 8024D5AC A48205CE */  sh         $v0, 0x5CE($a0)
/* 175FD0 8024D5B0 2402003E */  addiu      $v0, $zero, 0x3E
/* 175FD4 8024D5B4 3C018025 */  lui        $at, %hi(D_filemenu_80250960)
/* 175FD8 8024D5B8 00230821 */  addu       $at, $at, $v1
/* 175FDC 8024D5BC 90230960 */  lbu        $v1, %lo(D_filemenu_80250960)($at)
/* 175FE0 8024D5C0 A48205D2 */  sh         $v0, 0x5D2($a0)
/* 175FE4 8024D5C4 00032842 */  srl        $a1, $v1, 1
/* 175FE8 8024D5C8 A48305D0 */  sh         $v1, 0x5D0($a0)
/* 175FEC 8024D5CC 808305C3 */  lb         $v1, 0x5C3($a0)
/* 175FF0 8024D5D0 2402FFFF */  addiu      $v0, $zero, -0x1
/* 175FF4 8024D5D4 1062000B */  beq        $v1, $v0, .Lfilemenu_8024D604
/* 175FF8 8024D5D8 248705CC */   addiu     $a3, $a0, 0x5CC
.Lfilemenu_8024D5DC:
/* 175FFC 8024D5DC 00031140 */  sll        $v0, $v1, 5
/* 176000 8024D5E0 00441021 */  addu       $v0, $v0, $a0
/* 176004 8024D5E4 94420010 */  lhu        $v0, 0x10($v0)
/* 176008 8024D5E8 00021400 */  sll        $v0, $v0, 16
/* 17600C 8024D5EC 00021C03 */  sra        $v1, $v0, 16
/* 176010 8024D5F0 000217C2 */  srl        $v0, $v0, 31
/* 176014 8024D5F4 00621821 */  addu       $v1, $v1, $v0
/* 176018 8024D5F8 00031843 */  sra        $v1, $v1, 1
/* 17601C 8024D5FC 08093583 */  j          .Lfilemenu_8024D60C
/* 176020 8024D600 00651023 */   subu      $v0, $v1, $a1
.Lfilemenu_8024D604:
/* 176024 8024D604 240200A0 */  addiu      $v0, $zero, 0xA0
.Lfilemenu_8024D608:
/* 176028 8024D608 00451023 */  subu       $v0, $v0, $a1
.Lfilemenu_8024D60C:
/* 17602C 8024D60C 0000282D */  daddu      $a1, $zero, $zero
/* 176030 8024D610 00A0302D */  daddu      $a2, $a1, $zero
/* 176034 8024D614 A4E20000 */  sh         $v0, 0x0($a3)
/* 176038 8024D618 3C048025 */  lui        $a0, %hi(filemenu_menus+0x4)
/* 17603C 8024D61C 8C84E988 */  lw         $a0, %lo(filemenu_menus+0x4)($a0)
/* 176040 8024D620 24020001 */  addiu      $v0, $zero, 0x1
/* 176044 8024D624 3C018025 */  lui        $at, %hi(filemenu_currentMenu)
/* 176048 8024D628 A0221758 */  sb         $v0, %lo(filemenu_currentMenu)($at)
/* 17604C 8024D62C 24020001 */  addiu      $v0, $zero, 0x1
/* 176050 8024D630 0C091B29 */  jal        filemenu_set_selected
/* 176054 8024D634 A0820004 */   sb        $v0, 0x4($a0)
.Lfilemenu_8024D638:
/* 176058 8024D638 8FBF0018 */  lw         $ra, 0x18($sp)
/* 17605C 8024D63C 8FB10014 */  lw         $s1, 0x14($sp)
/* 176060 8024D640 8FB00010 */  lw         $s0, 0x10($sp)
/* 176064 8024D644 03E00008 */  jr         $ra
/* 176068 8024D648 27BD0020 */   addiu     $sp, $sp, 0x20
