.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.11.5 */

# Handwritten function
glabel __osSetWatchLo
/* 48A50 8006D650 40849000 */  mtc0      $a0, $18 # handwritten instruction
/* 48A54 8006D654 00000000 */  nop
/* 48A58 8006D658 03E00008 */  jr        $ra
/* 48A5C 8006D65C 00000000 */   nop
