.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.11.5 */

glabel bzero
/* 40BE0 800657E0 00041823 */  negu      $v1, $a0
/* 40BE4 800657E4 28A1000C */  slti      $at, $a1, 0xC
/* 40BE8 800657E8 1420001D */  bnez      $at, .LPAL_80065860
/* 40BEC 800657EC 00000000 */   nop
/* 40BF0 800657F0 30630003 */  andi      $v1, $v1, 0x3
/* 40BF4 800657F4 10600003 */  beqz      $v1, .LPAL_80065804
/* 40BF8 800657F8 00A32823 */   subu     $a1, $a1, $v1
/* 40BFC 800657FC A8800000 */  swl       $zero, 0x0($a0)
/* 40C00 80065800 00832021 */  addu      $a0, $a0, $v1
.LPAL_80065804:
/* 40C04 80065804 2401FFE0 */  addiu     $at, $zero, -0x20
/* 40C08 80065808 00A13824 */  and       $a3, $a1, $at
/* 40C0C 8006580C 10E0000C */  beqz      $a3, .LPAL_80065840
/* 40C10 80065810 00A72823 */   subu     $a1, $a1, $a3
/* 40C14 80065814 00E43821 */  addu      $a3, $a3, $a0
.LPAL_80065818:
/* 40C18 80065818 AC800000 */  sw        $zero, 0x0($a0)
/* 40C1C 8006581C AC800004 */  sw        $zero, 0x4($a0)
/* 40C20 80065820 AC800008 */  sw        $zero, 0x8($a0)
/* 40C24 80065824 AC80000C */  sw        $zero, 0xC($a0)
/* 40C28 80065828 24840020 */  addiu     $a0, $a0, 0x20
/* 40C2C 8006582C AC80FFF0 */  sw        $zero, -0x10($a0)
/* 40C30 80065830 AC80FFF4 */  sw        $zero, -0xC($a0)
/* 40C34 80065834 AC80FFF8 */  sw        $zero, -0x8($a0)
/* 40C38 80065838 1487FFF7 */  bne       $a0, $a3, .LPAL_80065818
/* 40C3C 8006583C AC80FFFC */   sw       $zero, -0x4($a0)
.LPAL_80065840:
/* 40C40 80065840 2401FFFC */  addiu     $at, $zero, -0x4
/* 40C44 80065844 00A13824 */  and       $a3, $a1, $at
/* 40C48 80065848 10E00005 */  beqz      $a3, .LPAL_80065860
/* 40C4C 8006584C 00A72823 */   subu     $a1, $a1, $a3
/* 40C50 80065850 00E43821 */  addu      $a3, $a3, $a0
.LPAL_80065854:
/* 40C54 80065854 24840004 */  addiu     $a0, $a0, 0x4
/* 40C58 80065858 1487FFFE */  bne       $a0, $a3, .LPAL_80065854
/* 40C5C 8006585C AC80FFFC */   sw       $zero, -0x4($a0)
.LPAL_80065860:
/* 40C60 80065860 18A00005 */  blez      $a1, .LPAL_80065878
/* 40C64 80065864 00000000 */   nop
/* 40C68 80065868 00A42821 */  addu      $a1, $a1, $a0
.LPAL_8006586C:
/* 40C6C 8006586C 24840001 */  addiu     $a0, $a0, 0x1
/* 40C70 80065870 1485FFFE */  bne       $a0, $a1, .LPAL_8006586C
/* 40C74 80065874 A080FFFF */   sb       $zero, -0x1($a0)
.LPAL_80065878:
/* 40C78 80065878 03E00008 */  jr        $ra
/* 40C7C 8006587C 00000000 */   nop
