.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.11.5 */

glabel func_PAL_8006C6F0
/* 47AF0 8006C6F0 27BDFFD8 */  addiu     $sp, $sp, -0x28
/* 47AF4 8006C6F4 AFB20020 */  sw        $s2, 0x20($sp)
/* 47AF8 8006C6F8 00809021 */  addu      $s2, $a0, $zero
/* 47AFC 8006C6FC AFB00018 */  sw        $s0, 0x18($sp)
/* 47B00 8006C700 3C10800D */  lui       $s0, %hi(D_800D58B0)
/* 47B04 8006C704 261058B0 */  addiu     $s0, $s0, %lo(D_800D58B0)
/* 47B08 8006C708 3C05800D */  lui       $a1, %hi(D_800D58BC)
/* 47B0C 8006C70C 8CA558BC */  lw        $a1, %lo(D_800D58BC)($a1)
/* 47B10 8006C710 02002021 */  addu      $a0, $s0, $zero
/* 47B14 8006C714 3C06D200 */  lui       $a2, (0xD2000000 >> 16)
/* 47B18 8006C718 AFB1001C */  sw        $s1, 0x1C($sp)
/* 47B1C 8006C71C 3C110001 */  lui       $s1, (0x10000 >> 16)
/* 47B20 8006C720 AFBF0024 */  sw        $ra, 0x24($sp)
/* 47B24 8006C724 0C018534 */  jal       osEPiWriteIo
/* 47B28 8006C728 00B12825 */   or       $a1, $a1, $s1
/* 47B2C 8006C72C 3C05800D */  lui       $a1, %hi(D_800D58BC)
/* 47B30 8006C730 8CA558BC */  lw        $a1, %lo(D_800D58BC)($a1)
/* 47B34 8006C734 02002021 */  addu      $a0, $s0, $zero
/* 47B38 8006C738 0C01854C */  jal       osEPiReadIo
/* 47B3C 8006C73C 27A60010 */   addiu    $a2, $sp, 0x10
/* 47B40 8006C740 3C05800D */  lui       $a1, %hi(D_800D58BC)
/* 47B44 8006C744 8CA558BC */  lw        $a1, %lo(D_800D58BC)($a1)
/* 47B48 8006C748 02002021 */  addu      $a0, $s0, $zero
/* 47B4C 8006C74C 3C06D200 */  lui       $a2, (0xD2000000 >> 16)
/* 47B50 8006C750 0C018534 */  jal       osEPiWriteIo
/* 47B54 8006C754 00B12825 */   or       $a1, $a1, $s1
/* 47B58 8006C758 3C05800D */  lui       $a1, %hi(D_800D58BC)
/* 47B5C 8006C75C 8CA558BC */  lw        $a1, %lo(D_800D58BC)($a1)
/* 47B60 8006C760 02002021 */  addu      $a0, $s0, $zero
/* 47B64 8006C764 0C01854C */  jal       osEPiReadIo
/* 47B68 8006C768 27A60010 */   addiu    $a2, $sp, 0x10
/* 47B6C 8006C76C 8FA20010 */  lw        $v0, 0x10($sp)
/* 47B70 8006C770 A2420000 */  sb        $v0, 0x0($s2)
/* 47B74 8006C774 8FBF0024 */  lw        $ra, 0x24($sp)
/* 47B78 8006C778 8FB20020 */  lw        $s2, 0x20($sp)
/* 47B7C 8006C77C 8FB1001C */  lw        $s1, 0x1C($sp)
/* 47B80 8006C780 8FB00018 */  lw        $s0, 0x18($sp)
/* 47B84 8006C784 03E00008 */  jr        $ra
/* 47B88 8006C788 27BD0028 */   addiu    $sp, $sp, 0x28
/* 47B8C 8006C78C 00000000 */  nop
