.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.11.5 */

glabel __osSetFpcCsr
/* 48A30 8006D630 4442F800 */  cfc1      $v0, $31
/* 48A34 8006D634 44C4F800 */  ctc1      $a0, $31
/* 48A38 8006D638 03E00008 */  jr        $ra
/* 48A3C 8006D63C 00000000 */   nop
