# %s disassembly and split file
# generated by n64split v%s - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64     # allow use of 64-bit general purpose registers

.include "globals.inc"


.section .text80200000, "ax"

func_80200000:
/* 3169F0 80200000 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 3169F4 80200004 3C05AC29 */  lui   $a1, 0xac29
/* 3169F8 80200008 34A5007B */  ori   $a1, $a1, 0x7b
/* 3169FC 8020000C 3C06B000 */  lui   $a2, 0xb000
/* 316A00 80200010 34C606A8 */  ori   $a2, $a2, 0x6a8
/* 316A04 80200014 3C02A460 */  lui   $v0, 0xa460
/* 316A08 80200018 34420010 */  ori   $v0, $v0, 0x10
/* 316A0C 8020001C AFBF0010 */  sw    $ra, 0x10($sp)
/* 316A10 80200020 8C420000 */  lw    $v0, ($v0)
/* 316A14 80200024 3C048005 */  lui   $a0, 0x8005
/* 316A18 80200028 2484AA85 */  addiu $a0, $a0, -0x557b
/* 316A1C 8020002C 30420003 */  andi  $v0, $v0, 3
/* 316A20 80200030 10400006 */  beqz  $v0, .L8020004C
/* 316A24 80200034 3C03A460 */   lui   $v1, 0xa460
/* 316A28 80200038 34630010 */  ori   $v1, $v1, 0x10
.L8020003C:
/* 316A2C 8020003C 8C620000 */  lw    $v0, ($v1)
/* 316A30 80200040 30420003 */  andi  $v0, $v0, 3
/* 316A34 80200044 1440FFFD */  bnez  $v0, .L8020003C
/* 316A38 80200048 00000000 */   nop   
.L8020004C:
/* 316A3C 8020004C 24C2FE38 */  addiu $v0, $a2, -0x1c8
/* 316A40 80200050 3C03A000 */  lui   $v1, 0xa000
/* 316A44 80200054 00431025 */  or    $v0, $v0, $v1
/* 316A48 80200058 8C420000 */  lw    $v0, ($v0)
/* 316A4C 8020005C 00A22823 */  subu  $a1, $a1, $v0
/* 316A50 80200060 00852021 */  addu  $a0, $a0, $a1
/* 316A54 80200064 0080F809 */  jalr  $a0
/* 316A58 80200068 00000000 */  nop   
/* 316A5C 8020006C 8FBF0010 */  lw    $ra, 0x10($sp)
/* 316A60 80200070 03E00008 */  jr    $ra
/* 316A64 80200074 27BD0018 */   addiu $sp, $sp, 0x18

/* 316A68 80200078 00000000 */  nop   
/* 316A6C 8020007C 00000000 */  nop   
