# %s disassembly and split file
# generated by n64split v%s - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64     # allow use of 64-bit general purpose registers

.include "globals.inc"


.section .text80067380, "ax"

osViBlack:
/* 042780 80067380 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 042784 80067384 AFB00010 */  sw    $s0, 0x10($sp)
/* 042788 80067388 AFBF0014 */  sw    $ra, 0x14($sp)
/* 04278C 8006738C 0C01ACD8 */  jal   osDisableInt
/* 042790 80067390 00808021 */   addu  $s0, $a0, $zero
/* 042794 80067394 321000FF */  andi  $s0, $s0, 0xff
/* 042798 80067398 12000006 */  beqz  $s0, .L800673B4
/* 04279C 8006739C 00402021 */   addu  $a0, $v0, $zero
/* 0427A0 800673A0 3C038009 */  lui   $v1, 0x8009
/* 0427A4 800673A4 8C6359D4 */  lw    $v1, 0x59d4($v1)
/* 0427A8 800673A8 94620000 */  lhu   $v0, ($v1)
/* 0427AC 800673AC 08019CF1 */  j     .L800673C4
/* 0427B0 800673B0 34420020 */   ori   $v0, $v0, 0x20

.L800673B4:
/* 0427B4 800673B4 3C038009 */  lui   $v1, 0x8009
/* 0427B8 800673B8 8C6359D4 */  lw    $v1, 0x59d4($v1)
/* 0427BC 800673BC 94620000 */  lhu   $v0, ($v1)
/* 0427C0 800673C0 3042FFDF */  andi  $v0, $v0, 0xffdf
.L800673C4:
/* 0427C4 800673C4 0C01ACF4 */  jal   osRestoreInt
/* 0427C8 800673C8 A4620000 */   sh    $v0, ($v1)
/* 0427CC 800673CC 8FBF0014 */  lw    $ra, 0x14($sp)
/* 0427D0 800673D0 8FB00010 */  lw    $s0, 0x10($sp)
/* 0427D4 800673D4 03E00008 */  jr    $ra
/* 0427D8 800673D8 27BD0018 */   addiu $sp, $sp, 0x18

/* 0427DC 800673DC 00000000 */  nop   
osViRepeatLine:
/* 0427E0 800673E0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 0427E4 800673E4 AFB00010 */  sw    $s0, 0x10($sp)
/* 0427E8 800673E8 AFBF0014 */  sw    $ra, 0x14($sp)
/* 0427EC 800673EC 0C01ACD8 */  jal   osDisableInt
/* 0427F0 800673F0 00808021 */   addu  $s0, $a0, $zero
/* 0427F4 800673F4 321000FF */  andi  $s0, $s0, 0xff
/* 0427F8 800673F8 12000006 */  beqz  $s0, .L80067414
/* 0427FC 800673FC 00402021 */   addu  $a0, $v0, $zero
/* 042800 80067400 3C038009 */  lui   $v1, 0x8009
/* 042804 80067404 8C6359D4 */  lw    $v1, 0x59d4($v1)
/* 042808 80067408 94620000 */  lhu   $v0, ($v1)
/* 04280C 8006740C 08019D09 */  j     .L80067424
/* 042810 80067410 34420040 */   ori   $v0, $v0, 0x40

.L80067414:
/* 042814 80067414 3C038009 */  lui   $v1, 0x8009
/* 042818 80067418 8C6359D4 */  lw    $v1, 0x59d4($v1)
/* 04281C 8006741C 94620000 */  lhu   $v0, ($v1)
/* 042820 80067420 3042FFBF */  andi  $v0, $v0, 0xffbf
.L80067424:
/* 042824 80067424 0C01ACF4 */  jal   osRestoreInt
/* 042828 80067428 A4620000 */   sh    $v0, ($v1)
/* 04282C 8006742C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 042830 80067430 8FB00010 */  lw    $s0, 0x10($sp)
/* 042834 80067434 03E00008 */  jr    $ra
/* 042838 80067438 27BD0018 */   addiu $sp, $sp, 0x18

/* 04283C 8006743C 00000000 */  nop   
guMtxIdent:
/* 042840 80067440 20080001 */  addi  $t0, $zero, 1
/* 042844 80067444 00084C00 */  sll   $t1, $t0, 0x10
/* 042848 80067448 AC890000 */  sw    $t1, ($a0)
/* 04284C 8006744C AC800004 */  sw    $zero, 4($a0)
/* 042850 80067450 AC880008 */  sw    $t0, 8($a0)
/* 042854 80067454 AC80000C */  sw    $zero, 0xc($a0)
/* 042858 80067458 AC800010 */  sw    $zero, 0x10($a0)
/* 04285C 8006745C AC890014 */  sw    $t1, 0x14($a0)
/* 042860 80067460 AC800018 */  sw    $zero, 0x18($a0)
/* 042864 80067464 AC88001C */  sw    $t0, 0x1c($a0)
/* 042868 80067468 AC800020 */  sw    $zero, 0x20($a0)
/* 04286C 8006746C AC800024 */  sw    $zero, 0x24($a0)
/* 042870 80067470 AC800028 */  sw    $zero, 0x28($a0)
/* 042874 80067474 AC80002C */  sw    $zero, 0x2c($a0)
/* 042878 80067478 AC800030 */  sw    $zero, 0x30($a0)
/* 04287C 8006747C AC800034 */  sw    $zero, 0x34($a0)
/* 042880 80067480 AC800038 */  sw    $zero, 0x38($a0)
/* 042884 80067484 03E00008 */  jr    $ra
/* 042888 80067488 AC80003C */   sw    $zero, 0x3c($a0)

/* 04288C 8006748C 00000000 */  nop   
/* 042890 80067490 00000000 */  nop   
/* 042894 80067494 00000000 */  nop   
/* 042898 80067498 00000000 */  nop   
/* 04289C 8006749C 00000000 */  nop   

.set reorder
