#include "../common/Credits.h"

CreditsEntry N(Credits_Jobs)[] = {
    {
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 195,
    },
    {
        .msgID = MSG_Credits_0009,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_000A,
        .posX = STANDARD_POS_X,
        .posY = 175,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_000B,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 455,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 513,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_000C,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 50,
    },
    {
        .msgID = MSG_Credits_000D,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_000E,
        .posX = STANDARD_POS_X,
        .posY = 175,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_000F,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 1095,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 1153,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 50,
    },
    {
        .msgID = MSG_Credits_0010,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0011,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0023,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0012,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 615,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 673,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 50,
    },
    {
        .msgID = MSG_Credits_0013,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0014,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0015,
        .posX = STANDARD_POS_X,
        .posY = 175,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0016,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0017,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0018,
        .posX = STANDARD_POS_X,
        .posY = 175,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 50,
    },
    {
        .msgID = MSG_Credits_001F,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
{
        .msgID = MSG_PAL_Credits_002E,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 295,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 353,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_PAL_Credits_002F,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_PAL_Credits_0030,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_PAL_Credits_0031,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_PAL_Credits_0032,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_PAL_Credits_0033,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_PAL_Credits_002D,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0024,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 135,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 193,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0022,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 295,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = STANDARD_VANISH_TIME,
        .perCharDelayOut = 0,
        .next = 353,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = -1,
    },
};
