#include "../common/Credits.h"

CreditsEntry N(Credits_Jobs)[] = {
    {
        .next = 235,
    },
    {
        .msgID = MSG_Credits_0009,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_000A,
        .posX = STANDARD_POS_X,
        .posY = 175,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 280,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_000B,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 690,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 760,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_000C,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 280,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = 60,
    },
    {
        .msgID = MSG_Credits_000D,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_000E,
        .posX = STANDARD_POS_X,
        .posY = 175,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 280,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_000F,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 1650,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 1720,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = 60,
    },
    {
        .msgID = MSG_Credits_0010,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 280,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0011,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 280,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0023,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 224,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 1,
        .next = 280,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0012,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 890,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 960,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = 60,
    },
    {
        .msgID = MSG_Credits_0013,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 280,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0014,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0015,
        .posX = STANDARD_POS_X,
        .posY = 175,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 280,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0016,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 280,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0017,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0018,
        .posX = STANDARD_POS_X,
        .posY = 175,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 280,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = 60,
    },
    {
        .msgID = MSG_Credits_001F,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 280,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0020,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 280,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0021,
        .posX = STANDARD_POS_X,
        .posY = 164,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 280,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0022,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 450,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 520,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = -1,
    },
};
