#include "../common/Credits.h"

CreditsEntry N(Credits_Jobs)[] = {
    {
        .next = 235,
    },
    {
        .msgID = MSG_Credits_0009,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_000A,
        .posX = STANDARD_POS_X,
        .posY = 175,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 246,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_000B,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 588,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 658,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_000C,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 246,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = 60,
    },
    {
        .msgID = MSG_Credits_000D,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_000E,
        .posX = STANDARD_POS_X,
        .posY = 175,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 246,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_000F,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 1412,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 1482,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = 60,
    },
    {
        .msgID = MSG_Credits_0010,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 246,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0011,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 246,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0023,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 190,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 1,
        .next = 246,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0012,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 754,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 824,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = 60,
    },
    {
        .msgID = MSG_Credits_0013,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 246,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0014,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0015,
        .posX = STANDARD_POS_X,
        .posY = 175,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 246,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0016,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 246,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0017,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0018,
        .posX = STANDARD_POS_X,
        .posY = 175,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 246,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = 60,
    },
    {
        .msgID = MSG_Credits_001F,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 246,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0029,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 246,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_002A,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 246,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_002B,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 382,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 452,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_002C,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 382,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 452,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0024,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 176,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 246,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0022,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 382,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 452,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = -1,
    },
};
