.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.11.1 */

glabel osPfsChecker
/* 47580 8006C180 27BDFB70 */  addiu     $sp, $sp, -0x490
/* 47584 8006C184 240D00FE */  addiu     $t5, $zero, 0xFE
/* 47588 8006C188 AFB40478 */  sw        $s4, 0x478($sp)
/* 4758C 8006C18C 0080A021 */  addu      $s4, $a0, $zero
/* 47590 8006C190 AFBF048C */  sw        $ra, 0x48C($sp)
/* 47594 8006C194 AFBE0488 */  sw        $fp, 0x488($sp)
/* 47598 8006C198 AFB70484 */  sw        $s7, 0x484($sp)
/* 4759C 8006C19C AFB60480 */  sw        $s6, 0x480($sp)
/* 475A0 8006C1A0 AFB5047C */  sw        $s5, 0x47C($sp)
/* 475A4 8006C1A4 AFB30474 */  sw        $s3, 0x474($sp)
/* 475A8 8006C1A8 AFB20470 */  sw        $s2, 0x470($sp)
/* 475AC 8006C1AC AFB1046C */  sw        $s1, 0x46C($sp)
/* 475B0 8006C1B0 AFB00468 */  sw        $s0, 0x468($sp)
/* 475B4 8006C1B4 AFA00460 */  sw        $zero, 0x460($sp)
/* 475B8 8006C1B8 0C01A701 */  jal       __osCheckId
/* 475BC 8006C1BC AFAD0464 */   sw       $t5, 0x464($sp)
/* 475C0 8006C1C0 00408021 */  addu      $s0, $v0, $zero
/* 475C4 8006C1C4 24030002 */  addiu     $v1, $zero, 0x2
/* 475C8 8006C1C8 16030004 */  bne       $s0, $v1, .LIQUE_8006C1DC
/* 475CC 8006C1CC 00000000 */   nop
/* 475D0 8006C1D0 0C01A6A2 */  jal       __osGetId
/* 475D4 8006C1D4 02802021 */   addu     $a0, $s4, $zero
/* 475D8 8006C1D8 00408021 */  addu      $s0, $v0, $zero
.LIQUE_8006C1DC:
/* 475DC 8006C1DC 12000003 */  beqz      $s0, .LIQUE_8006C1EC
/* 475E0 8006C1E0 02802021 */   addu     $a0, $s4, $zero
.LIQUE_8006C1E4:
/* 475E4 8006C1E4 0801B16D */  j         .LIQUE_8006C5B4
/* 475E8 8006C1E8 02001021 */   addu     $v0, $s0, $zero
.LIQUE_8006C1EC:
/* 475EC 8006C1EC 0C01B179 */  jal       corrupted_init
/* 475F0 8006C1F0 27A50258 */   addiu    $a1, $sp, 0x258
/* 475F4 8006C1F4 00408021 */  addu      $s0, $v0, $zero
/* 475F8 8006C1F8 160000EF */  bnez      $s0, .LIQUE_8006C5B8
/* 475FC 8006C1FC 8FBF048C */   lw       $ra, 0x48C($sp)
/* 47600 8006C200 8E830050 */  lw        $v1, 0x50($s4)
/* 47604 8006C204 18600071 */  blez      $v1, .LIQUE_8006C3CC
/* 47608 8006C208 00008821 */   addu     $s1, $zero, $zero
/* 4760C 8006C20C 27A70218 */  addiu     $a3, $sp, 0x218
.LIQUE_8006C210:
/* 47610 8006C210 8E840004 */  lw        $a0, 0x4($s4)
/* 47614 8006C214 9686005E */  lhu       $a2, 0x5E($s4)
/* 47618 8006C218 8E850008 */  lw        $a1, 0x8($s4)
/* 4761C 8006C21C 00D13021 */  addu      $a2, $a2, $s1
/* 47620 8006C220 0C01A7D8 */  jal       __osContRamRead
/* 47624 8006C224 30C6FFFF */   andi     $a2, $a2, 0xFFFF
/* 47628 8006C228 00408021 */  addu      $s0, $v0, $zero
/* 4762C 8006C22C 1600FFED */  bnez      $s0, .LIQUE_8006C1E4
/* 47630 8006C230 97A2021C */   lhu      $v0, 0x21C($sp)
/* 47634 8006C234 14400005 */  bnez      $v0, .LIQUE_8006C24C
/* 47638 8006C238 8FA20218 */   lw       $v0, 0x218($sp)
/* 4763C 8006C23C 5040005F */  beql      $v0, $zero, .LIQUE_8006C3BC
/* 47640 8006C240 8E830050 */   lw       $v1, 0x50($s4)
/* 47644 8006C244 0801B0D0 */  j         .LIQUE_8006C340
/* 47648 8006C248 2405FFFF */   addiu    $a1, $zero, -0x1
.LIQUE_8006C24C:
/* 4764C 8006C24C 14400003 */  bnez      $v0, .LIQUE_8006C25C
/* 47650 8006C250 00002821 */   addu     $a1, $zero, $zero
/* 47654 8006C254 0801B0D0 */  j         .LIQUE_8006C340
/* 47658 8006C258 2405FFFF */   addiu    $a1, $zero, -0x1
.LIQUE_8006C25C:
/* 4765C 8006C25C 0000B021 */  addu      $s6, $zero, $zero
/* 47660 8006C260 97B5021E */  lhu       $s5, 0x21E($sp)
/* 47664 8006C264 8E820060 */  lw        $v0, 0x60($s4)
/* 47668 8006C268 32A4FFFF */  andi      $a0, $s5, 0xFFFF
/* 4766C 8006C26C 0082102A */  slt       $v0, $a0, $v0
/* 47670 8006C270 14400033 */  bnez      $v0, .LIQUE_8006C340
/* 47674 8006C274 241200FF */   addiu    $s2, $zero, 0xFF
/* 47678 8006C278 92830064 */  lbu       $v1, 0x64($s4)
/* 4767C 8006C27C 00041202 */  srl       $v0, $a0, 8
/* 47680 8006C280 0043102B */  sltu      $v0, $v0, $v1
/* 47684 8006C284 1040002E */  beqz      $v0, .LIQUE_8006C340
/* 47688 8006C288 00000000 */   nop
/* 4768C 8006C28C 32B300FF */  andi      $s3, $s5, 0xFF
/* 47690 8006C290 1260002B */  beqz      $s3, .LIQUE_8006C340
/* 47694 8006C294 00000000 */   nop
/* 47698 8006C298 241E0003 */  addiu     $fp, $zero, 0x3
/* 4769C 8006C29C 27B70118 */  addiu     $s7, $sp, 0x118
.LIQUE_8006C2A0:
/* 476A0 8006C2A0 00151600 */  sll       $v0, $s5, 24
/* 476A4 8006C2A4 04400026 */  bltz      $v0, .LIQUE_8006C340
/* 476A8 8006C2A8 00041202 */   srl      $v0, $a0, 8
/* 476AC 8006C2AC 1242000E */  beq       $s2, $v0, .LIQUE_8006C2E8
/* 476B0 8006C2B0 8FAD0464 */   lw       $t5, 0x464($sp)
/* 476B4 8006C2B4 00409021 */  addu      $s2, $v0, $zero
/* 476B8 8006C2B8 11B20007 */  beq       $t5, $s2, .LIQUE_8006C2D8
/* 476BC 8006C2BC 02802021 */   addu     $a0, $s4, $zero
/* 476C0 8006C2C0 27A50118 */  addiu     $a1, $sp, 0x118
/* 476C4 8006C2C4 00003021 */  addu      $a2, $zero, $zero
/* 476C8 8006C2C8 0C01A731 */  jal       __osPfsRWInode
/* 476CC 8006C2CC 02403821 */   addu     $a3, $s2, $zero
/* 476D0 8006C2D0 00408021 */  addu      $s0, $v0, $zero
/* 476D4 8006C2D4 AFB20464 */  sw        $s2, 0x464($sp)
.LIQUE_8006C2D8:
/* 476D8 8006C2D8 12000004 */  beqz      $s0, .LIQUE_8006C2EC
/* 476DC 8006C2DC 02802021 */   addu     $a0, $s4, $zero
/* 476E0 8006C2E0 161E00B4 */  bne       $s0, $fp, .LIQUE_8006C5B4
/* 476E4 8006C2E4 02001021 */   addu     $v0, $s0, $zero
.LIQUE_8006C2E8:
/* 476E8 8006C2E8 02802021 */  addu      $a0, $s4, $zero
.LIQUE_8006C2EC:
/* 476EC 8006C2EC 02A02821 */  addu      $a1, $s5, $zero
/* 476F0 8006C2F0 27A60258 */  addiu     $a2, $sp, 0x258
/* 476F4 8006C2F4 0C01B1CE */  jal       corrupted
/* 476F8 8006C2F8 00052C00 */   sll      $a1, $a1, 16
/* 476FC 8006C2FC 00562823 */  subu      $a1, $v0, $s6
/* 47700 8006C300 14A00015 */  bnez      $a1, .LIQUE_8006C358
/* 47704 8006C304 00131040 */   sll      $v0, $s3, 1
/* 47708 8006C308 02E21021 */  addu      $v0, $s7, $v0
/* 4770C 8006C30C 94550000 */  lhu       $s5, 0x0($v0)
/* 47710 8006C310 8E830060 */  lw        $v1, 0x60($s4)
/* 47714 8006C314 32A4FFFF */  andi      $a0, $s5, 0xFFFF
/* 47718 8006C318 0083182A */  slt       $v1, $a0, $v1
/* 4771C 8006C31C 14600008 */  bnez      $v1, .LIQUE_8006C340
/* 47720 8006C320 24160001 */   addiu    $s6, $zero, 0x1
/* 47724 8006C324 92830064 */  lbu       $v1, 0x64($s4)
/* 47728 8006C328 00041202 */  srl       $v0, $a0, 8
/* 4772C 8006C32C 0043102B */  sltu      $v0, $v0, $v1
/* 47730 8006C330 10400003 */  beqz      $v0, .LIQUE_8006C340
/* 47734 8006C334 32A200FF */   andi     $v0, $s5, 0xFF
/* 47738 8006C338 1440FFD9 */  bnez      $v0, .LIQUE_8006C2A0
/* 4773C 8006C33C 00409821 */   addu     $s3, $v0, $zero
.LIQUE_8006C340:
/* 47740 8006C340 54A00006 */  bnel      $a1, $zero, .LIQUE_8006C35C
/* 47744 8006C344 27A40218 */   addiu    $a0, $sp, 0x218
/* 47748 8006C348 32A3FFFF */  andi      $v1, $s5, 0xFFFF
/* 4774C 8006C34C 24020001 */  addiu     $v0, $zero, 0x1
/* 47750 8006C350 5062001A */  beql      $v1, $v0, .LIQUE_8006C3BC
/* 47754 8006C354 8E830050 */   lw       $v1, 0x50($s4)
.LIQUE_8006C358:
/* 47758 8006C358 27A40218 */  addiu     $a0, $sp, 0x218
.LIQUE_8006C35C:
/* 4775C 8006C35C 0C018ACC */  jal       bzero
/* 47760 8006C360 24050020 */   addiu    $a1, $zero, 0x20
/* 47764 8006C364 92820065 */  lbu       $v0, 0x65($s4)
/* 47768 8006C368 10400006 */  beqz      $v0, .LIQUE_8006C384
/* 4776C 8006C36C 02802021 */   addu     $a0, $s4, $zero
/* 47770 8006C370 0C01A568 */  jal       __osPfsSelectBank
/* 47774 8006C374 00002821 */   addu     $a1, $zero, $zero
/* 47778 8006C378 00408021 */  addu      $s0, $v0, $zero
/* 4777C 8006C37C 1600008D */  bnez      $s0, .LIQUE_8006C5B4
/* 47780 8006C380 02001021 */   addu     $v0, $s0, $zero
.LIQUE_8006C384:
/* 47784 8006C384 8E840004 */  lw        $a0, 0x4($s4)
/* 47788 8006C388 8E850008 */  lw        $a1, 0x8($s4)
/* 4778C 8006C38C 9686005E */  lhu       $a2, 0x5E($s4)
/* 47790 8006C390 27A70218 */  addiu     $a3, $sp, 0x218
/* 47794 8006C394 AFA00010 */  sw        $zero, 0x10($sp)
/* 47798 8006C398 00D13021 */  addu      $a2, $a2, $s1
/* 4779C 8006C39C 0C01A808 */  jal       __osContRamWrite
/* 477A0 8006C3A0 30C6FFFF */   andi     $a2, $a2, 0xFFFF
/* 477A4 8006C3A4 00408021 */  addu      $s0, $v0, $zero
/* 477A8 8006C3A8 1600FF8E */  bnez      $s0, .LIQUE_8006C1E4
/* 477AC 8006C3AC 8FAD0460 */   lw       $t5, 0x460($sp)
/* 477B0 8006C3B0 25AD0001 */  addiu     $t5, $t5, 0x1
/* 477B4 8006C3B4 AFAD0460 */  sw        $t5, 0x460($sp)
/* 477B8 8006C3B8 8E830050 */  lw        $v1, 0x50($s4)
.LIQUE_8006C3BC:
/* 477BC 8006C3BC 26310001 */  addiu     $s1, $s1, 0x1
/* 477C0 8006C3C0 0223102A */  slt       $v0, $s1, $v1
/* 477C4 8006C3C4 1440FF92 */  bnez      $v0, .LIQUE_8006C210
/* 477C8 8006C3C8 27A70218 */   addiu    $a3, $sp, 0x218
.LIQUE_8006C3CC:
/* 477CC 8006C3CC 1860001C */  blez      $v1, .LIQUE_8006C440
/* 477D0 8006C3D0 00008821 */   addu     $s1, $zero, $zero
/* 477D4 8006C3D4 27B20238 */  addiu     $s2, $sp, 0x238
.LIQUE_8006C3D8:
/* 477D8 8006C3D8 27A70218 */  addiu     $a3, $sp, 0x218
/* 477DC 8006C3DC 8E840004 */  lw        $a0, 0x4($s4)
/* 477E0 8006C3E0 9686005E */  lhu       $a2, 0x5E($s4)
/* 477E4 8006C3E4 8E850008 */  lw        $a1, 0x8($s4)
/* 477E8 8006C3E8 00D13021 */  addu      $a2, $a2, $s1
/* 477EC 8006C3EC 0C01A7D8 */  jal       __osContRamRead
/* 477F0 8006C3F0 30C6FFFF */   andi     $a2, $a2, 0xFFFF
/* 477F4 8006C3F4 00408021 */  addu      $s0, $v0, $zero
/* 477F8 8006C3F8 1600FF7A */  bnez      $s0, .LIQUE_8006C1E4
/* 477FC 8006C3FC 97A2021C */   lhu      $v0, 0x21C($sp)
/* 47800 8006C400 10400009 */  beqz      $v0, .LIQUE_8006C428
/* 47804 8006C404 8FA20218 */   lw       $v0, 0x218($sp)
/* 47808 8006C408 10400007 */  beqz      $v0, .LIQUE_8006C428
/* 4780C 8006C40C 97A3021E */   lhu      $v1, 0x21E($sp)
/* 47810 8006C410 96820062 */  lhu       $v0, 0x62($s4)
/* 47814 8006C414 0062102B */  sltu      $v0, $v1, $v0
/* 47818 8006C418 54400004 */  bnel      $v0, $zero, .LIQUE_8006C42C
/* 4781C 8006C41C A6400000 */   sh       $zero, 0x0($s2)
/* 47820 8006C420 0801B10B */  j         .LIQUE_8006C42C
/* 47824 8006C424 A6430000 */   sh       $v1, 0x0($s2)
.LIQUE_8006C428:
/* 47828 8006C428 A6400000 */  sh        $zero, 0x0($s2)
.LIQUE_8006C42C:
/* 4782C 8006C42C 8E820050 */  lw        $v0, 0x50($s4)
/* 47830 8006C430 26310001 */  addiu     $s1, $s1, 0x1
/* 47834 8006C434 0222102A */  slt       $v0, $s1, $v0
/* 47838 8006C438 1440FFE7 */  bnez      $v0, .LIQUE_8006C3D8
/* 4783C 8006C43C 26520002 */   addiu    $s2, $s2, 0x2
.LIQUE_8006C440:
/* 47840 8006C440 92820064 */  lbu       $v0, 0x64($s4)
/* 47844 8006C444 10400052 */  beqz      $v0, .LIQUE_8006C590
/* 47848 8006C448 00009021 */   addu     $s2, $zero, $zero
/* 4784C 8006C44C 27B30018 */  addiu     $s3, $sp, 0x18
/* 47850 8006C450 02802021 */  addu      $a0, $s4, $zero
.LIQUE_8006C454:
/* 47854 8006C454 27A50118 */  addiu     $a1, $sp, 0x118
/* 47858 8006C458 00003021 */  addu      $a2, $zero, $zero
/* 4785C 8006C45C 0C01A731 */  jal       __osPfsRWInode
/* 47860 8006C460 02403821 */   addu     $a3, $s2, $zero
/* 47864 8006C464 00408021 */  addu      $s0, $v0, $zero
/* 47868 8006C468 12000003 */  beqz      $s0, .LIQUE_8006C478
/* 4786C 8006C46C 24020003 */   addiu    $v0, $zero, 0x3
/* 47870 8006C470 16020050 */  bne       $s0, $v0, .LIQUE_8006C5B4
/* 47874 8006C474 02001021 */   addu     $v0, $s0, $zero
.LIQUE_8006C478:
/* 47878 8006C478 16400002 */  bnez      $s2, .LIQUE_8006C484
/* 4787C 8006C47C 24060001 */   addiu    $a2, $zero, 0x1
/* 47880 8006C480 8E860060 */  lw        $a2, 0x60($s4)
.LIQUE_8006C484:
/* 47884 8006C484 18C0000A */  blez      $a2, .LIQUE_8006C4B0
/* 47888 8006C488 00008821 */   addu     $s1, $zero, $zero
/* 4788C 8006C48C 27A50018 */  addiu     $a1, $sp, 0x18
/* 47890 8006C490 27A40118 */  addiu     $a0, $sp, 0x118
.LIQUE_8006C494:
/* 47894 8006C494 94830000 */  lhu       $v1, 0x0($a0)
/* 47898 8006C498 24840002 */  addiu     $a0, $a0, 0x2
/* 4789C 8006C49C 26310001 */  addiu     $s1, $s1, 0x1
/* 478A0 8006C4A0 0226102A */  slt       $v0, $s1, $a2
/* 478A4 8006C4A4 A4A30000 */  sh        $v1, 0x0($a1)
/* 478A8 8006C4A8 1440FFFA */  bnez      $v0, .LIQUE_8006C494
/* 478AC 8006C4AC 24A50002 */   addiu    $a1, $a1, 0x2
.LIQUE_8006C4B0:
/* 478B0 8006C4B0 2A220080 */  slti      $v0, $s1, 0x80
/* 478B4 8006C4B4 10400008 */  beqz      $v0, .LIQUE_8006C4D8
/* 478B8 8006C4B8 00111040 */   sll      $v0, $s1, 1
/* 478BC 8006C4BC 24040003 */  addiu     $a0, $zero, 0x3
/* 478C0 8006C4C0 00531821 */  addu      $v1, $v0, $s3
.LIQUE_8006C4C4:
/* 478C4 8006C4C4 A4640000 */  sh        $a0, 0x0($v1)
/* 478C8 8006C4C8 26310001 */  addiu     $s1, $s1, 0x1
/* 478CC 8006C4CC 2A220080 */  slti      $v0, $s1, 0x80
/* 478D0 8006C4D0 1440FFFC */  bnez      $v0, .LIQUE_8006C4C4
/* 478D4 8006C4D4 24630002 */   addiu    $v1, $v1, 0x2
.LIQUE_8006C4D8:
/* 478D8 8006C4D8 8E820050 */  lw        $v0, 0x50($s4)
/* 478DC 8006C4DC 1840001F */  blez      $v0, .LIQUE_8006C55C
/* 478E0 8006C4E0 00008821 */   addu     $s1, $zero, $zero
/* 478E4 8006C4E4 00003821 */  addu      $a3, $zero, $zero
/* 478E8 8006C4E8 27A60238 */  addiu     $a2, $sp, 0x238
/* 478EC 8006C4EC 00C06021 */  addu      $t4, $a2, $zero
/* 478F0 8006C4F0 00405821 */  addu      $t3, $v0, $zero
.LIQUE_8006C4F4:
/* 478F4 8006C4F4 90C20000 */  lbu       $v0, 0x0($a2)
/* 478F8 8006C4F8 54520014 */  bnel      $v0, $s2, .LIQUE_8006C54C
/* 478FC 8006C4FC 24E70002 */   addiu    $a3, $a3, 0x2
/* 47900 8006C500 27AA0018 */  addiu     $t2, $sp, 0x18
/* 47904 8006C504 27A90118 */  addiu     $t1, $sp, 0x118
/* 47908 8006C508 01872821 */  addu      $a1, $t4, $a3
/* 4790C 8006C50C 96880062 */  lhu       $t0, 0x62($s4)
/* 47910 8006C510 94A20000 */  lhu       $v0, 0x0($a1)
.LIQUE_8006C514:
/* 47914 8006C514 0048102B */  sltu      $v0, $v0, $t0
/* 47918 8006C518 5440000C */  bnel      $v0, $zero, .LIQUE_8006C54C
/* 4791C 8006C51C 24E70002 */   addiu    $a3, $a3, 0x2
/* 47920 8006C520 90A30001 */  lbu       $v1, 0x1($a1)
/* 47924 8006C524 00031840 */  sll       $v1, $v1, 1
/* 47928 8006C528 01231021 */  addu      $v0, $t1, $v1
/* 4792C 8006C52C 94440000 */  lhu       $a0, 0x0($v0)
/* 47930 8006C530 01431821 */  addu      $v1, $t2, $v1
/* 47934 8006C534 A4640000 */  sh        $a0, 0x0($v1)
/* 47938 8006C538 A4A40000 */  sh        $a0, 0x0($a1)
/* 4793C 8006C53C 90A20000 */  lbu       $v0, 0x0($a1)
/* 47940 8006C540 5052FFF4 */  beql      $v0, $s2, .LIQUE_8006C514
/* 47944 8006C544 94A20000 */   lhu      $v0, 0x0($a1)
/* 47948 8006C548 24E70002 */  addiu     $a3, $a3, 0x2
.LIQUE_8006C54C:
/* 4794C 8006C54C 26310001 */  addiu     $s1, $s1, 0x1
/* 47950 8006C550 022B102A */  slt       $v0, $s1, $t3
/* 47954 8006C554 1440FFE7 */  bnez      $v0, .LIQUE_8006C4F4
/* 47958 8006C558 24C60002 */   addiu    $a2, $a2, 0x2
.LIQUE_8006C55C:
/* 4795C 8006C55C 02802021 */  addu      $a0, $s4, $zero
/* 47960 8006C560 27A50018 */  addiu     $a1, $sp, 0x18
/* 47964 8006C564 24060001 */  addiu     $a2, $zero, 0x1
/* 47968 8006C568 0C01A731 */  jal       __osPfsRWInode
/* 4796C 8006C56C 02403821 */   addu     $a3, $s2, $zero
/* 47970 8006C570 00408021 */  addu      $s0, $v0, $zero
/* 47974 8006C574 1600FF1B */  bnez      $s0, .LIQUE_8006C1E4
/* 47978 8006C578 26430001 */   addiu    $v1, $s2, 0x1
/* 4797C 8006C57C 92820064 */  lbu       $v0, 0x64($s4)
/* 47980 8006C580 307200FF */  andi      $s2, $v1, 0xFF
/* 47984 8006C584 0242102B */  sltu      $v0, $s2, $v0
/* 47988 8006C588 1440FFB2 */  bnez      $v0, .LIQUE_8006C454
/* 4798C 8006C58C 02802021 */   addu     $a0, $s4, $zero
.LIQUE_8006C590:
/* 47990 8006C590 8FAD0460 */  lw        $t5, 0x460($sp)
/* 47994 8006C594 11A00003 */  beqz      $t5, .LIQUE_8006C5A4
/* 47998 8006C598 8E820000 */   lw       $v0, 0x0($s4)
/* 4799C 8006C59C 0801B16B */  j         .LIQUE_8006C5AC
/* 479A0 8006C5A0 34420002 */   ori      $v0, $v0, 0x2
.LIQUE_8006C5A4:
/* 479A4 8006C5A4 2403FFFD */  addiu     $v1, $zero, -0x3
/* 479A8 8006C5A8 00431024 */  and       $v0, $v0, $v1
.LIQUE_8006C5AC:
/* 479AC 8006C5AC AE820000 */  sw        $v0, 0x0($s4)
/* 479B0 8006C5B0 00001021 */  addu      $v0, $zero, $zero
.LIQUE_8006C5B4:
/* 479B4 8006C5B4 8FBF048C */  lw        $ra, 0x48C($sp)
.LIQUE_8006C5B8:
/* 479B8 8006C5B8 8FBE0488 */  lw        $fp, 0x488($sp)
/* 479BC 8006C5BC 8FB70484 */  lw        $s7, 0x484($sp)
/* 479C0 8006C5C0 8FB60480 */  lw        $s6, 0x480($sp)
/* 479C4 8006C5C4 8FB5047C */  lw        $s5, 0x47C($sp)
/* 479C8 8006C5C8 8FB40478 */  lw        $s4, 0x478($sp)
/* 479CC 8006C5CC 8FB30474 */  lw        $s3, 0x474($sp)
/* 479D0 8006C5D0 8FB20470 */  lw        $s2, 0x470($sp)
/* 479D4 8006C5D4 8FB1046C */  lw        $s1, 0x46C($sp)
/* 479D8 8006C5D8 8FB00468 */  lw        $s0, 0x468($sp)
/* 479DC 8006C5DC 03E00008 */  jr        $ra
/* 479E0 8006C5E0 27BD0490 */   addiu    $sp, $sp, 0x490

glabel corrupted_init
/* 479E4 8006C5E4 27BDFED0 */  addiu     $sp, $sp, -0x130
/* 479E8 8006C5E8 AFB20118 */  sw        $s2, 0x118($sp)
/* 479EC 8006C5EC 00809021 */  addu      $s2, $a0, $zero
/* 479F0 8006C5F0 00003021 */  addu      $a2, $zero, $zero
/* 479F4 8006C5F4 AFB3011C */  sw        $s3, 0x11C($sp)
/* 479F8 8006C5F8 24B30101 */  addiu     $s3, $a1, 0x101
/* 479FC 8006C5FC 02602021 */  addu      $a0, $s3, $zero
/* 47A00 8006C600 AFBF012C */  sw        $ra, 0x12C($sp)
/* 47A04 8006C604 AFB60128 */  sw        $s6, 0x128($sp)
/* 47A08 8006C608 AFB50124 */  sw        $s5, 0x124($sp)
/* 47A0C 8006C60C AFB40120 */  sw        $s4, 0x120($sp)
/* 47A10 8006C610 AFB10114 */  sw        $s1, 0x114($sp)
/* 47A14 8006C614 AFB00110 */  sw        $s0, 0x110($sp)
.LIQUE_8006C618:
/* 47A18 8006C618 00861021 */  addu      $v0, $a0, $a2
/* 47A1C 8006C61C 24C60001 */  addiu     $a2, $a2, 0x1
/* 47A20 8006C620 28C30100 */  slti      $v1, $a2, 0x100
/* 47A24 8006C624 1460FFFC */  bnez      $v1, .LIQUE_8006C618
/* 47A28 8006C628 A0400000 */   sb       $zero, 0x0($v0)
/* 47A2C 8006C62C 240200FF */  addiu     $v0, $zero, 0xFF
/* 47A30 8006C630 A0A20100 */  sb        $v0, 0x100($a1)
/* 47A34 8006C634 92430064 */  lbu       $v1, 0x64($s2)
/* 47A38 8006C638 10600034 */  beqz      $v1, .LIQUE_8006C70C
/* 47A3C 8006C63C 00008021 */   addu     $s0, $zero, $zero
/* 47A40 8006C640 24160003 */  addiu     $s6, $zero, 0x3
/* 47A44 8006C644 27B40010 */  addiu     $s4, $sp, 0x10
/* 47A48 8006C648 24150001 */  addiu     $s5, $zero, 0x1
.LIQUE_8006C64C:
/* 47A4C 8006C64C 16000002 */  bnez      $s0, .LIQUE_8006C658
/* 47A50 8006C650 24110001 */   addiu    $s1, $zero, 0x1
/* 47A54 8006C654 8E510060 */  lw        $s1, 0x60($s2)
.LIQUE_8006C658:
/* 47A58 8006C658 02402021 */  addu      $a0, $s2, $zero
/* 47A5C 8006C65C 27A50010 */  addiu     $a1, $sp, 0x10
/* 47A60 8006C660 00003021 */  addu      $a2, $zero, $zero
/* 47A64 8006C664 0C01A731 */  jal       __osPfsRWInode
/* 47A68 8006C668 02003821 */   addu     $a3, $s0, $zero
/* 47A6C 8006C66C 10400004 */  beqz      $v0, .LIQUE_8006C680
/* 47A70 8006C670 02203021 */   addu     $a2, $s1, $zero
/* 47A74 8006C674 14560027 */  bne       $v0, $s6, .LIQUE_8006C714
/* 47A78 8006C678 8FBF012C */   lw       $ra, 0x12C($sp)
/* 47A7C 8006C67C 02203021 */  addu      $a2, $s1, $zero
.LIQUE_8006C680:
/* 47A80 8006C680 28C20080 */  slti      $v0, $a2, 0x80
/* 47A84 8006C684 1040001C */  beqz      $v0, .LIQUE_8006C6F8
/* 47A88 8006C688 26030001 */   addiu    $v1, $s0, 0x1
/* 47A8C 8006C68C 02604021 */  addu      $t0, $s3, $zero
/* 47A90 8006C690 32020007 */  andi      $v0, $s0, 0x7
/* 47A94 8006C694 00553804 */  sllv      $a3, $s5, $v0
/* 47A98 8006C698 00061840 */  sll       $v1, $a2, 1
/* 47A9C 8006C69C 00742821 */  addu      $a1, $v1, $s4
.LIQUE_8006C6A0:
/* 47AA0 8006C6A0 94A40000 */  lhu       $a0, 0x0($a1)
/* 47AA4 8006C6A4 8E420060 */  lw        $v0, 0x60($s2)
/* 47AA8 8006C6A8 3083FFFF */  andi      $v1, $a0, 0xFFFF
/* 47AAC 8006C6AC 0062102A */  slt       $v0, $v1, $v0
/* 47AB0 8006C6B0 1440000D */  bnez      $v0, .LIQUE_8006C6E8
/* 47AB4 8006C6B4 24C60001 */   addiu    $a2, $a2, 0x1
/* 47AB8 8006C6B8 00031A02 */  srl       $v1, $v1, 8
/* 47ABC 8006C6BC 1070000A */  beq       $v1, $s0, .LIQUE_8006C6E8
/* 47AC0 8006C6C0 00000000 */   nop
/* 47AC4 8006C6C4 3082007F */  andi      $v0, $a0, 0x7F
/* 47AC8 8006C6C8 00021082 */  srl       $v0, $v0, 2
/* 47ACC 8006C6CC 30630007 */  andi      $v1, $v1, 0x7
/* 47AD0 8006C6D0 00031940 */  sll       $v1, $v1, 5
/* 47AD4 8006C6D4 00431021 */  addu      $v0, $v0, $v1
/* 47AD8 8006C6D8 01021021 */  addu      $v0, $t0, $v0
/* 47ADC 8006C6DC 90440000 */  lbu       $a0, 0x0($v0)
/* 47AE0 8006C6E0 00872025 */  or        $a0, $a0, $a3
/* 47AE4 8006C6E4 A0440000 */  sb        $a0, 0x0($v0)
.LIQUE_8006C6E8:
/* 47AE8 8006C6E8 28C20080 */  slti      $v0, $a2, 0x80
/* 47AEC 8006C6EC 1440FFEC */  bnez      $v0, .LIQUE_8006C6A0
/* 47AF0 8006C6F0 24A50002 */   addiu    $a1, $a1, 0x2
/* 47AF4 8006C6F4 26030001 */  addiu     $v1, $s0, 0x1
.LIQUE_8006C6F8:
/* 47AF8 8006C6F8 92420064 */  lbu       $v0, 0x64($s2)
/* 47AFC 8006C6FC 307000FF */  andi      $s0, $v1, 0xFF
/* 47B00 8006C700 0202102B */  sltu      $v0, $s0, $v0
/* 47B04 8006C704 1440FFD1 */  bnez      $v0, .LIQUE_8006C64C
/* 47B08 8006C708 00000000 */   nop
.LIQUE_8006C70C:
/* 47B0C 8006C70C 00001021 */  addu      $v0, $zero, $zero
/* 47B10 8006C710 8FBF012C */  lw        $ra, 0x12C($sp)
.LIQUE_8006C714:
/* 47B14 8006C714 8FB60128 */  lw        $s6, 0x128($sp)
/* 47B18 8006C718 8FB50124 */  lw        $s5, 0x124($sp)
/* 47B1C 8006C71C 8FB40120 */  lw        $s4, 0x120($sp)
/* 47B20 8006C720 8FB3011C */  lw        $s3, 0x11C($sp)
/* 47B24 8006C724 8FB20118 */  lw        $s2, 0x118($sp)
/* 47B28 8006C728 8FB10114 */  lw        $s1, 0x114($sp)
/* 47B2C 8006C72C 8FB00110 */  lw        $s0, 0x110($sp)
/* 47B30 8006C730 03E00008 */  jr        $ra
/* 47B34 8006C734 27BD0130 */   addiu    $sp, $sp, 0x130

glabel corrupted
/* 47B38 8006C738 00052C03 */  sra       $a1, $a1, 16
/* 47B3C 8006C73C 27BDFFC8 */  addiu     $sp, $sp, -0x38
/* 47B40 8006C740 AFB00010 */  sw        $s0, 0x10($sp)
/* 47B44 8006C744 00008021 */  addu      $s0, $zero, $zero
/* 47B48 8006C748 AFB10014 */  sw        $s1, 0x14($sp)
/* 47B4C 8006C74C 00008821 */  addu      $s1, $zero, $zero
/* 47B50 8006C750 AFB40020 */  sw        $s4, 0x20($sp)
/* 47B54 8006C754 0080A021 */  addu      $s4, $a0, $zero
/* 47B58 8006C758 AFB3001C */  sw        $s3, 0x1C($sp)
/* 47B5C 8006C75C 00C09821 */  addu      $s3, $a2, $zero
/* 47B60 8006C760 30A300FF */  andi      $v1, $a1, 0xFF
/* 47B64 8006C764 00031882 */  srl       $v1, $v1, 2
/* 47B68 8006C768 AFB50024 */  sw        $s5, 0x24($sp)
/* 47B6C 8006C76C 30B5FFFF */  andi      $s5, $a1, 0xFFFF
/* 47B70 8006C770 00152A02 */  srl       $a1, $s5, 8
/* 47B74 8006C774 30A20007 */  andi      $v0, $a1, 0x7
/* 47B78 8006C778 00021140 */  sll       $v0, $v0, 5
/* 47B7C 8006C77C AFBF0030 */  sw        $ra, 0x30($sp)
/* 47B80 8006C780 AFB7002C */  sw        $s7, 0x2C($sp)
/* 47B84 8006C784 AFB60028 */  sw        $s6, 0x28($sp)
/* 47B88 8006C788 AFB20018 */  sw        $s2, 0x18($sp)
/* 47B8C 8006C78C 92840064 */  lbu       $a0, 0x64($s4)
/* 47B90 8006C790 10800034 */  beqz      $a0, .LIQUE_8006C864
/* 47B94 8006C794 00621821 */   addu     $v1, $v1, $v0
/* 47B98 8006C798 26620101 */  addiu     $v0, $s3, 0x101
/* 47B9C 8006C79C 0043B821 */  addu      $s7, $v0, $v1
/* 47BA0 8006C7A0 30B600FF */  andi      $s6, $a1, 0xFF
.LIQUE_8006C7A4:
/* 47BA4 8006C7A4 16000002 */  bnez      $s0, .LIQUE_8006C7B0
/* 47BA8 8006C7A8 24120001 */   addiu    $s2, $zero, 0x1
/* 47BAC 8006C7AC 8E920060 */  lw        $s2, 0x60($s4)
.LIQUE_8006C7B0:
/* 47BB0 8006C7B0 12160006 */  beq       $s0, $s6, .LIQUE_8006C7CC
/* 47BB4 8006C7B4 32030007 */   andi     $v1, $s0, 0x7
/* 47BB8 8006C7B8 92E20000 */  lbu       $v0, 0x0($s7)
/* 47BBC 8006C7BC 00621007 */  srav      $v0, $v0, $v1
/* 47BC0 8006C7C0 30420001 */  andi      $v0, $v0, 0x1
/* 47BC4 8006C7C4 10400022 */  beqz      $v0, .LIQUE_8006C850
/* 47BC8 8006C7C8 26030001 */   addiu    $v1, $s0, 0x1
.LIQUE_8006C7CC:
/* 47BCC 8006C7CC 92620100 */  lbu       $v0, 0x100($s3)
/* 47BD0 8006C7D0 1202000B */  beq       $s0, $v0, .LIQUE_8006C800
/* 47BD4 8006C7D4 02802021 */   addu     $a0, $s4, $zero
/* 47BD8 8006C7D8 02602821 */  addu      $a1, $s3, $zero
/* 47BDC 8006C7DC 00003021 */  addu      $a2, $zero, $zero
/* 47BE0 8006C7E0 0C01A731 */  jal       __osPfsRWInode
/* 47BE4 8006C7E4 02003821 */   addu     $a3, $s0, $zero
/* 47BE8 8006C7E8 00401821 */  addu      $v1, $v0, $zero
/* 47BEC 8006C7EC 10600003 */  beqz      $v1, .LIQUE_8006C7FC
/* 47BF0 8006C7F0 24020003 */   addiu    $v0, $zero, 0x3
/* 47BF4 8006C7F4 1462001C */  bne       $v1, $v0, .LIQUE_8006C868
/* 47BF8 8006C7F8 00601021 */   addu     $v0, $v1, $zero
.LIQUE_8006C7FC:
/* 47BFC 8006C7FC A2700100 */  sb        $s0, 0x100($s3)
.LIQUE_8006C800:
/* 47C00 8006C800 2A250002 */  slti      $a1, $s1, 0x2
/* 47C04 8006C804 10A00010 */  beqz      $a1, .LIQUE_8006C848
/* 47C08 8006C808 02402021 */   addu     $a0, $s2, $zero
/* 47C0C 8006C80C 02A03021 */  addu      $a2, $s5, $zero
/* 47C10 8006C810 00041040 */  sll       $v0, $a0, 1
/* 47C14 8006C814 00531821 */  addu      $v1, $v0, $s3
.LIQUE_8006C818:
/* 47C18 8006C818 28820080 */  slti      $v0, $a0, 0x80
/* 47C1C 8006C81C 10400008 */  beqz      $v0, .LIQUE_8006C840
/* 47C20 8006C820 00000000 */   nop
/* 47C24 8006C824 94620000 */  lhu       $v0, 0x0($v1)
/* 47C28 8006C828 14460003 */  bne       $v0, $a2, .LIQUE_8006C838
/* 47C2C 8006C82C 24630002 */   addiu    $v1, $v1, 0x2
/* 47C30 8006C830 26310001 */  addiu     $s1, $s1, 0x1
/* 47C34 8006C834 2A250002 */  slti      $a1, $s1, 0x2
.LIQUE_8006C838:
/* 47C38 8006C838 14A0FFF7 */  bnez      $a1, .LIQUE_8006C818
/* 47C3C 8006C83C 24840001 */   addiu    $a0, $a0, 0x1
.LIQUE_8006C840:
/* 47C40 8006C840 14A00003 */  bnez      $a1, .LIQUE_8006C850
/* 47C44 8006C844 26030001 */   addiu    $v1, $s0, 0x1
.LIQUE_8006C848:
/* 47C48 8006C848 0801B21A */  j         .LIQUE_8006C868
/* 47C4C 8006C84C 24020002 */   addiu    $v0, $zero, 0x2
.LIQUE_8006C850:
/* 47C50 8006C850 92820064 */  lbu       $v0, 0x64($s4)
/* 47C54 8006C854 307000FF */  andi      $s0, $v1, 0xFF
/* 47C58 8006C858 0202102B */  sltu      $v0, $s0, $v0
/* 47C5C 8006C85C 1440FFD1 */  bnez      $v0, .LIQUE_8006C7A4
/* 47C60 8006C860 00000000 */   nop
.LIQUE_8006C864:
/* 47C64 8006C864 02201021 */  addu      $v0, $s1, $zero
.LIQUE_8006C868:
/* 47C68 8006C868 8FBF0030 */  lw        $ra, 0x30($sp)
/* 47C6C 8006C86C 8FB7002C */  lw        $s7, 0x2C($sp)
/* 47C70 8006C870 8FB60028 */  lw        $s6, 0x28($sp)
/* 47C74 8006C874 8FB50024 */  lw        $s5, 0x24($sp)
/* 47C78 8006C878 8FB40020 */  lw        $s4, 0x20($sp)
/* 47C7C 8006C87C 8FB3001C */  lw        $s3, 0x1C($sp)
/* 47C80 8006C880 8FB20018 */  lw        $s2, 0x18($sp)
/* 47C84 8006C884 8FB10014 */  lw        $s1, 0x14($sp)
/* 47C88 8006C888 8FB00010 */  lw        $s0, 0x10($sp)
/* 47C8C 8006C88C 03E00008 */  jr        $ra
/* 47C90 8006C890 27BD0038 */   addiu    $sp, $sp, 0x38
/* 47C94 8006C894 00000000 */  nop
/* 47C98 8006C898 00000000 */  nop
/* 47C9C 8006C89C 00000000 */  nop
