.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel filemenu_main_handle_input
/* 1725D4 80249BB4 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 1725D8 80249BB8 AFB3001C */  sw         $s3, 0x1C($sp)
/* 1725DC 80249BBC 0080982D */  daddu      $s3, $a0, $zero
/* 1725E0 80249BC0 3C028025 */  lui        $v0, %hi(filemenu_heldButtons)
/* 1725E4 80249BC4 8C42174C */  lw         $v0, %lo(filemenu_heldButtons)($v0)
/* 1725E8 80249BC8 3C030004 */  lui        $v1, (0x40000 >> 16)
/* 1725EC 80249BCC AFBF0020 */  sw         $ra, 0x20($sp)
/* 1725F0 80249BD0 AFB20018 */  sw         $s2, 0x18($sp)
/* 1725F4 80249BD4 AFB10014 */  sw         $s1, 0x14($sp)
/* 1725F8 80249BD8 AFB00010 */  sw         $s0, 0x10($sp)
/* 1725FC 80249BDC 92670003 */  lbu        $a3, 0x3($s3)
/* 172600 80249BE0 00431024 */  and        $v0, $v0, $v1
/* 172604 80249BE4 1040001C */  beqz       $v0, .Lfilemenu_80249C58
/* 172608 80249BE8 00000000 */   nop
.Lfilemenu_80249BEC:
/* 17260C 80249BEC 92620001 */  lbu        $v0, 0x1($s3)
/* 172610 80249BF0 2442FFFF */  addiu      $v0, $v0, -0x1
/* 172614 80249BF4 A2620001 */  sb         $v0, 0x1($s3)
/* 172618 80249BF8 00021600 */  sll        $v0, $v0, 24
/* 17261C 80249BFC 00022E03 */  sra        $a1, $v0, 24
/* 172620 80249C00 04A20015 */  bltzl      $a1, .Lfilemenu_80249C58
/* 172624 80249C04 A2600001 */   sb        $zero, 0x1($s3)
/* 172628 80249C08 82620004 */  lb         $v0, 0x4($s3)
/* 17262C 80249C0C 82630005 */  lb         $v1, 0x5($s3)
/* 172630 80249C10 00430018 */  mult       $v0, $v1
/* 172634 80249C14 00006012 */  mflo       $t4
/* 172638 80249C18 82620006 */  lb         $v0, 0x6($s3)
/* 17263C 80249C1C 00000000 */  nop
/* 172640 80249C20 01820018 */  mult       $t4, $v0
/* 172644 80249C24 00002012 */  mflo       $a0
/* 172648 80249C28 82620002 */  lb         $v0, 0x2($s3)
/* 17264C 80249C2C 00000000 */  nop
/* 172650 80249C30 00620018 */  mult       $v1, $v0
/* 172654 80249C34 00001812 */  mflo       $v1
/* 172658 80249C38 00831021 */  addu       $v0, $a0, $v1
/* 17265C 80249C3C 00451021 */  addu       $v0, $v0, $a1
/* 172660 80249C40 8E630008 */  lw         $v1, 0x8($s3)
/* 172664 80249C44 92640003 */  lbu        $a0, 0x3($s3)
/* 172668 80249C48 00621821 */  addu       $v1, $v1, $v0
/* 17266C 80249C4C 90620000 */  lbu        $v0, 0x0($v1)
/* 172670 80249C50 1082FFE6 */  beq        $a0, $v0, .Lfilemenu_80249BEC
/* 172674 80249C54 00000000 */   nop
.Lfilemenu_80249C58:
/* 172678 80249C58 3C028025 */  lui        $v0, %hi(filemenu_heldButtons)
/* 17267C 80249C5C 8C42174C */  lw         $v0, %lo(filemenu_heldButtons)($v0)
/* 172680 80249C60 3C030008 */  lui        $v1, (0x80000 >> 16)
/* 172684 80249C64 00431024 */  and        $v0, $v0, $v1
/* 172688 80249C68 1040001E */  beqz       $v0, .Lfilemenu_80249CE4
/* 17268C 80249C6C 00000000 */   nop
/* 172690 80249C70 92660005 */  lbu        $a2, 0x5($s3)
/* 172694 80249C74 82650005 */  lb         $a1, 0x5($s3)
.Lfilemenu_80249C78:
/* 172698 80249C78 92620001 */  lbu        $v0, 0x1($s3)
/* 17269C 80249C7C 24420001 */  addiu      $v0, $v0, 0x1
/* 1726A0 80249C80 A2620001 */  sb         $v0, 0x1($s3)
/* 1726A4 80249C84 00021600 */  sll        $v0, $v0, 24
/* 1726A8 80249C88 00022603 */  sra        $a0, $v0, 24
/* 1726AC 80249C8C 0085102A */  slt        $v0, $a0, $a1
/* 1726B0 80249C90 1040003E */  beqz       $v0, .Lfilemenu_80249D8C
/* 1726B4 80249C94 24C2FFFF */   addiu     $v0, $a2, -0x1
/* 1726B8 80249C98 82620004 */  lb         $v0, 0x4($s3)
/* 1726BC 80249C9C 00450018 */  mult       $v0, $a1
/* 1726C0 80249CA0 00001812 */  mflo       $v1
/* 1726C4 80249CA4 82620006 */  lb         $v0, 0x6($s3)
/* 1726C8 80249CA8 00000000 */  nop
/* 1726CC 80249CAC 00620018 */  mult       $v1, $v0
/* 1726D0 80249CB0 00001812 */  mflo       $v1
/* 1726D4 80249CB4 82620002 */  lb         $v0, 0x2($s3)
/* 1726D8 80249CB8 00000000 */  nop
/* 1726DC 80249CBC 00A20018 */  mult       $a1, $v0
/* 1726E0 80249CC0 00006012 */  mflo       $t4
/* 1726E4 80249CC4 006C1021 */  addu       $v0, $v1, $t4
/* 1726E8 80249CC8 00441021 */  addu       $v0, $v0, $a0
/* 1726EC 80249CCC 8E630008 */  lw         $v1, 0x8($s3)
/* 1726F0 80249CD0 92640003 */  lbu        $a0, 0x3($s3)
/* 1726F4 80249CD4 00621821 */  addu       $v1, $v1, $v0
/* 1726F8 80249CD8 90620000 */  lbu        $v0, 0x0($v1)
/* 1726FC 80249CDC 1082FFE6 */  beq        $a0, $v0, .Lfilemenu_80249C78
/* 172700 80249CE0 00000000 */   nop
.Lfilemenu_80249CE4:
/* 172704 80249CE4 3C028025 */  lui        $v0, %hi(filemenu_heldButtons)
/* 172708 80249CE8 8C42174C */  lw         $v0, %lo(filemenu_heldButtons)($v0)
/* 17270C 80249CEC 3C030001 */  lui        $v1, (0x10000 >> 16)
/* 172710 80249CF0 00431024 */  and        $v0, $v0, $v1
/* 172714 80249CF4 10400007 */  beqz       $v0, .Lfilemenu_80249D14
/* 172718 80249CF8 00000000 */   nop
/* 17271C 80249CFC 92620002 */  lbu        $v0, 0x2($s3)
/* 172720 80249D00 2442FFFF */  addiu      $v0, $v0, -0x1
/* 172724 80249D04 A2620002 */  sb         $v0, 0x2($s3)
/* 172728 80249D08 00021600 */  sll        $v0, $v0, 24
/* 17272C 80249D0C 04420001 */  bltzl      $v0, .Lfilemenu_80249D14
/* 172730 80249D10 A2600002 */   sb        $zero, 0x2($s3)
.Lfilemenu_80249D14:
/* 172734 80249D14 3C028025 */  lui        $v0, %hi(filemenu_heldButtons)
/* 172738 80249D18 8C42174C */  lw         $v0, %lo(filemenu_heldButtons)($v0)
/* 17273C 80249D1C 3C030002 */  lui        $v1, (0x20000 >> 16)
/* 172740 80249D20 00431024 */  and        $v0, $v0, $v1
/* 172744 80249D24 1040000C */  beqz       $v0, .Lfilemenu_80249D58
/* 172748 80249D28 00000000 */   nop
/* 17274C 80249D2C 92620002 */  lbu        $v0, 0x2($s3)
/* 172750 80249D30 82630006 */  lb         $v1, 0x6($s3)
/* 172754 80249D34 24420001 */  addiu      $v0, $v0, 0x1
/* 172758 80249D38 A2620002 */  sb         $v0, 0x2($s3)
/* 17275C 80249D3C 00021600 */  sll        $v0, $v0, 24
/* 172760 80249D40 00021603 */  sra        $v0, $v0, 24
/* 172764 80249D44 0043102A */  slt        $v0, $v0, $v1
/* 172768 80249D48 92630006 */  lbu        $v1, 0x6($s3)
/* 17276C 80249D4C 14400002 */  bnez       $v0, .Lfilemenu_80249D58
/* 172770 80249D50 2462FFFF */   addiu     $v0, $v1, -0x1
/* 172774 80249D54 A2620002 */  sb         $v0, 0x2($s3)
.Lfilemenu_80249D58:
/* 172778 80249D58 82620004 */  lb         $v0, 0x4($s3)
/* 17277C 80249D5C 1440000D */  bnez       $v0, .Lfilemenu_80249D94
/* 172780 80249D60 00000000 */   nop
/* 172784 80249D64 82630001 */  lb         $v1, 0x1($s3)
/* 172788 80249D68 24020001 */  addiu      $v0, $zero, 0x1
/* 17278C 80249D6C 14620019 */  bne        $v1, $v0, .Lfilemenu_80249DD4
/* 172790 80249D70 00000000 */   nop
/* 172794 80249D74 92620002 */  lbu        $v0, 0x2($s3)
/* 172798 80249D78 2C420002 */  sltiu      $v0, $v0, 0x2
/* 17279C 80249D7C 54400015 */  bnel       $v0, $zero, .Lfilemenu_80249DD4
/* 1727A0 80249D80 A2600001 */   sb        $zero, 0x1($s3)
/* 1727A4 80249D84 08092775 */  j          .Lfilemenu_80249DD4
/* 1727A8 80249D88 00000000 */   nop
.Lfilemenu_80249D8C:
/* 1727AC 80249D8C 08092739 */  j          .Lfilemenu_80249CE4
/* 1727B0 80249D90 A2620001 */   sb        $v0, 0x1($s3)
.Lfilemenu_80249D94:
/* 1727B4 80249D94 0440000F */  bltz       $v0, .Lfilemenu_80249DD4
/* 1727B8 80249D98 28420004 */   slti      $v0, $v0, 0x4
/* 1727BC 80249D9C 1040000D */  beqz       $v0, .Lfilemenu_80249DD4
/* 1727C0 80249DA0 24020001 */   addiu     $v0, $zero, 0x1
/* 1727C4 80249DA4 82630001 */  lb         $v1, 0x1($s3)
/* 1727C8 80249DA8 14620005 */  bne        $v1, $v0, .Lfilemenu_80249DC0
/* 1727CC 80249DAC 00000000 */   nop
/* 1727D0 80249DB0 92620002 */  lbu        $v0, 0x2($s3)
/* 1727D4 80249DB4 2C420002 */  sltiu      $v0, $v0, 0x2
/* 1727D8 80249DB8 54400001 */  bnel       $v0, $zero, .Lfilemenu_80249DC0
/* 1727DC 80249DBC A2600001 */   sb        $zero, 0x1($s3)
.Lfilemenu_80249DC0:
/* 1727E0 80249DC0 82630002 */  lb         $v1, 0x2($s3)
/* 1727E4 80249DC4 24020002 */  addiu      $v0, $zero, 0x2
/* 1727E8 80249DC8 14620002 */  bne        $v1, $v0, .Lfilemenu_80249DD4
/* 1727EC 80249DCC 24020001 */   addiu     $v0, $zero, 0x1
/* 1727F0 80249DD0 A2620001 */  sb         $v0, 0x1($s3)
.Lfilemenu_80249DD4:
/* 1727F4 80249DD4 82620004 */  lb         $v0, 0x4($s3)
/* 1727F8 80249DD8 82630005 */  lb         $v1, 0x5($s3)
/* 1727FC 80249DDC 00430018 */  mult       $v0, $v1
/* 172800 80249DE0 00006012 */  mflo       $t4
/* 172804 80249DE4 82620006 */  lb         $v0, 0x6($s3)
/* 172808 80249DE8 00000000 */  nop
/* 17280C 80249DEC 01820018 */  mult       $t4, $v0
/* 172810 80249DF0 00002012 */  mflo       $a0
/* 172814 80249DF4 82620002 */  lb         $v0, 0x2($s3)
/* 172818 80249DF8 00000000 */  nop
/* 17281C 80249DFC 00620018 */  mult       $v1, $v0
/* 172820 80249E00 00001812 */  mflo       $v1
/* 172824 80249E04 00831821 */  addu       $v1, $a0, $v1
/* 172828 80249E08 82640001 */  lb         $a0, 0x1($s3)
/* 17282C 80249E0C 8E620008 */  lw         $v0, 0x8($s3)
/* 172830 80249E10 00641821 */  addu       $v1, $v1, $a0
/* 172834 80249E14 00431021 */  addu       $v0, $v0, $v1
/* 172838 80249E18 90420000 */  lbu        $v0, 0x0($v0)
/* 17283C 80249E1C A2620003 */  sb         $v0, 0x3($s3)
/* 172840 80249E20 304200FF */  andi       $v0, $v0, 0xFF
/* 172844 80249E24 10E20003 */  beq        $a3, $v0, .Lfilemenu_80249E34
/* 172848 80249E28 00000000 */   nop
/* 17284C 80249E2C 0C052219 */  jal        sfx_play_sound
/* 172850 80249E30 24042101 */   addiu     $a0, $zero, 0x2101
.Lfilemenu_80249E34:
/* 172854 80249E34 82620004 */  lb         $v0, 0x4($s3)
/* 172858 80249E38 14400022 */  bnez       $v0, .Lfilemenu_80249EC4
/* 17285C 80249E3C 00000000 */   nop
/* 172860 80249E40 3C108007 */  lui        $s0, %hi(gGameStatusPtr)
/* 172864 80249E44 261014AC */  addiu      $s0, $s0, %lo(gGameStatusPtr)
/* 172868 80249E48 3C058025 */  lui        $a1, %hi(filemenu_pressedButtons)
/* 17286C 80249E4C 24A51744 */  addiu      $a1, $a1, %lo(filemenu_pressedButtons)
/* 172870 80249E50 8CA20000 */  lw         $v0, 0x0($a1)
/* 172874 80249E54 8E030000 */  lw         $v1, 0x0($s0)
/* 172878 80249E58 30422000 */  andi       $v0, $v0, 0x2000
/* 17287C 80249E5C 906400AB */  lbu        $a0, 0xAB($v1)
/* 172880 80249E60 10400002 */  beqz       $v0, .Lfilemenu_80249E6C
/* 172884 80249E64 24020001 */   addiu     $v0, $zero, 0x1
/* 172888 80249E68 A06200AB */  sb         $v0, 0xAB($v1)
.Lfilemenu_80249E6C:
/* 17288C 80249E6C 8CA20000 */  lw         $v0, 0x0($a1)
/* 172890 80249E70 30420010 */  andi       $v0, $v0, 0x10
/* 172894 80249E74 10400003 */  beqz       $v0, .Lfilemenu_80249E84
/* 172898 80249E78 00000000 */   nop
/* 17289C 80249E7C 8E020000 */  lw         $v0, 0x0($s0)
/* 1728A0 80249E80 A04000AB */  sb         $zero, 0xAB($v0)
.Lfilemenu_80249E84:
/* 1728A4 80249E84 8E020000 */  lw         $v0, 0x0($s0)
/* 1728A8 80249E88 904200AB */  lbu        $v0, 0xAB($v0)
/* 1728AC 80249E8C 1082000D */  beq        $a0, $v0, .Lfilemenu_80249EC4
/* 1728B0 80249E90 00000000 */   nop
/* 1728B4 80249E94 0C052219 */  jal        sfx_play_sound
/* 1728B8 80249E98 240400C8 */   addiu     $a0, $zero, 0xC8
/* 1728BC 80249E9C 8E020000 */  lw         $v0, 0x0($s0)
/* 1728C0 80249EA0 904200AB */  lbu        $v0, 0xAB($v0)
/* 1728C4 80249EA4 10400005 */  beqz       $v0, .Lfilemenu_80249EBC
/* 1728C8 80249EA8 00000000 */   nop
/* 1728CC 80249EAC 0C0159CF */  jal        audio_set_stereo
/* 1728D0 80249EB0 00000000 */   nop
/* 1728D4 80249EB4 080927B1 */  j          .Lfilemenu_80249EC4
/* 1728D8 80249EB8 00000000 */   nop
.Lfilemenu_80249EBC:
/* 1728DC 80249EBC 0C0159D8 */  jal        audio_set_mono
/* 1728E0 80249EC0 00000000 */   nop
.Lfilemenu_80249EC4:
/* 1728E4 80249EC4 3C038025 */  lui        $v1, %hi(filemenu_pressedButtons)
/* 1728E8 80249EC8 24631744 */  addiu      $v1, $v1, %lo(filemenu_pressedButtons)
/* 1728EC 80249ECC 8C620000 */  lw         $v0, 0x0($v1)
/* 1728F0 80249ED0 30421000 */  andi       $v0, $v0, 0x1000
/* 1728F4 80249ED4 10400009 */  beqz       $v0, .Lfilemenu_80249EFC
/* 1728F8 80249ED8 00000000 */   nop
/* 1728FC 80249EDC 82620004 */  lb         $v0, 0x4($s3)
/* 172900 80249EE0 14400006 */  bnez       $v0, .Lfilemenu_80249EFC
/* 172904 80249EE4 00000000 */   nop
/* 172908 80249EE8 92620003 */  lbu        $v0, 0x3($s3)
/* 17290C 80249EEC 2C420004 */  sltiu      $v0, $v0, 0x4
/* 172910 80249EF0 10400002 */  beqz       $v0, .Lfilemenu_80249EFC
/* 172914 80249EF4 34028000 */   ori       $v0, $zero, 0x8000
/* 172918 80249EF8 AC620000 */  sw         $v0, 0x0($v1)
.Lfilemenu_80249EFC:
/* 17291C 80249EFC 3C028025 */  lui        $v0, %hi(filemenu_pressedButtons)
/* 172920 80249F00 8C421744 */  lw         $v0, %lo(filemenu_pressedButtons)($v0)
/* 172924 80249F04 30428000 */  andi       $v0, $v0, 0x8000
/* 172928 80249F08 1040028C */  beqz       $v0, .Lfilemenu_8024A93C
/* 17292C 80249F0C 24110001 */   addiu     $s1, $zero, 0x1
/* 172930 80249F10 82630004 */  lb         $v1, 0x4($s3)
/* 172934 80249F14 1071011F */  beq        $v1, $s1, .Lfilemenu_8024A394
/* 172938 80249F18 0000202D */   daddu     $a0, $zero, $zero
/* 17293C 80249F1C 28620002 */  slti       $v0, $v1, 0x2
/* 172940 80249F20 10400005 */  beqz       $v0, .Lfilemenu_80249F38
/* 172944 80249F24 24100002 */   addiu     $s0, $zero, 0x2
/* 172948 80249F28 10600009 */  beqz       $v1, .Lfilemenu_80249F50
/* 17294C 80249F2C 00000000 */   nop
/* 172950 80249F30 08092A4F */  j          .Lfilemenu_8024A93C
/* 172954 80249F34 00000000 */   nop
.Lfilemenu_80249F38:
/* 172958 80249F38 10700180 */  beq        $v1, $s0, .Lfilemenu_8024A53C
/* 17295C 80249F3C 24020003 */   addiu     $v0, $zero, 0x3
/* 172960 80249F40 106201AA */  beq        $v1, $v0, .Lfilemenu_8024A5EC
/* 172964 80249F44 24020006 */   addiu     $v0, $zero, 0x6
/* 172968 80249F48 08092A4F */  j          .Lfilemenu_8024A93C
/* 17296C 80249F4C 00000000 */   nop
.Lfilemenu_80249F50:
/* 172970 80249F50 92620003 */  lbu        $v0, 0x3($s3)
/* 172974 80249F54 2C420004 */  sltiu      $v0, $v0, 0x4
/* 172978 80249F58 10400007 */  beqz       $v0, .Lfilemenu_80249F78
/* 17297C 80249F5C 00000000 */   nop
/* 172980 80249F60 92620003 */  lbu        $v0, 0x3($s3)
/* 172984 80249F64 3C018007 */  lui        $at, %hi(gSaveSlotHasData)
/* 172988 80249F68 00220821 */  addu       $at, $at, $v0
/* 17298C 80249F6C 90223D74 */  lbu        $v0, %lo(gSaveSlotHasData)($at)
/* 172990 80249F70 50400001 */  beql       $v0, $zero, .Lfilemenu_80249F78
/* 172994 80249F74 24040001 */   addiu     $a0, $zero, 0x1
.Lfilemenu_80249F78:
/* 172998 80249F78 10800040 */  beqz       $a0, .Lfilemenu_8024A07C
/* 17299C 80249F7C 240400F7 */   addiu     $a0, $zero, 0xF7
/* 1729A0 80249F80 24030007 */  addiu      $v1, $zero, 0x7
/* 1729A4 80249F84 3C028025 */  lui        $v0, %hi(filemenu_filename+0x7)
/* 1729A8 80249F88 244227E7 */  addiu      $v0, $v0, %lo(filemenu_filename+0x7)
.Lfilemenu_80249F8C:
/* 1729AC 80249F8C A0440000 */  sb         $a0, 0x0($v0)
/* 1729B0 80249F90 2463FFFF */  addiu      $v1, $v1, -0x1
/* 1729B4 80249F94 0461FFFD */  bgez       $v1, .Lfilemenu_80249F8C
/* 1729B8 80249F98 2442FFFF */   addiu     $v0, $v0, -0x1
/* 1729BC 80249F9C 24040030 */  addiu      $a0, $zero, 0x30
/* 1729C0 80249FA0 3C108024 */  lui        $s0, %hi(filemenu_update_show_name_input)
/* 1729C4 80249FA4 26107290 */  addiu      $s0, $s0, %lo(filemenu_update_show_name_input)
/* 1729C8 80249FA8 3C018025 */  lui        $at, %hi(filemenu_filename_pos)
/* 1729CC 80249FAC A0201750 */  sb         $zero, %lo(filemenu_filename_pos)($at)
/* 1729D0 80249FB0 0C051A8B */  jal        set_window_update
/* 1729D4 80249FB4 0200282D */   daddu     $a1, $s0, $zero
/* 1729D8 80249FB8 24040031 */  addiu      $a0, $zero, 0x31
/* 1729DC 80249FBC 0C051A8B */  jal        set_window_update
/* 1729E0 80249FC0 0200282D */   daddu     $a1, $s0, $zero
/* 1729E4 80249FC4 2404002D */  addiu      $a0, $zero, 0x2D
/* 1729E8 80249FC8 3C108024 */  lui        $s0, %hi(filemenu_update_hidden_with_rotation)
/* 1729EC 80249FCC 261077A8 */  addiu      $s0, $s0, %lo(filemenu_update_hidden_with_rotation)
/* 1729F0 80249FD0 0C051A8B */  jal        set_window_update
/* 1729F4 80249FD4 0200282D */   daddu     $a1, $s0, $zero
/* 1729F8 80249FD8 24040033 */  addiu      $a0, $zero, 0x33
/* 1729FC 80249FDC 0C051A8B */  jal        set_window_update
/* 172A00 80249FE0 0200282D */   daddu     $a1, $s0, $zero
/* 172A04 80249FE4 24040034 */  addiu      $a0, $zero, 0x34
/* 172A08 80249FE8 0C051A8B */  jal        set_window_update
/* 172A0C 80249FEC 0200282D */   daddu     $a1, $s0, $zero
/* 172A10 80249FF0 24040035 */  addiu      $a0, $zero, 0x35
/* 172A14 80249FF4 0C051A8B */  jal        set_window_update
/* 172A18 80249FF8 0200282D */   daddu     $a1, $s0, $zero
/* 172A1C 80249FFC 24040036 */  addiu      $a0, $zero, 0x36
/* 172A20 8024A000 0C051A8B */  jal        set_window_update
/* 172A24 8024A004 0200282D */   daddu     $a1, $s0, $zero
/* 172A28 8024A008 24040037 */  addiu      $a0, $zero, 0x37
/* 172A2C 8024A00C 0C051A8B */  jal        set_window_update
/* 172A30 8024A010 0200282D */   daddu     $a1, $s0, $zero
/* 172A34 8024A014 24040035 */  addiu      $a0, $zero, 0x35
/* 172A38 8024A018 0C051A8B */  jal        set_window_update
/* 172A3C 8024A01C 0200282D */   daddu     $a1, $s0, $zero
/* 172A40 8024A020 24040038 */  addiu      $a0, $zero, 0x38
/* 172A44 8024A024 0C051A8B */  jal        set_window_update
/* 172A48 8024A028 0200282D */   daddu     $a1, $s0, $zero
/* 172A4C 8024A02C 24040039 */  addiu      $a0, $zero, 0x39
/* 172A50 8024A030 0C051A8B */  jal        set_window_update
/* 172A54 8024A034 0200282D */   daddu     $a1, $s0, $zero
/* 172A58 8024A038 2404003A */  addiu      $a0, $zero, 0x3A
/* 172A5C 8024A03C 0C051A8B */  jal        set_window_update
/* 172A60 8024A040 0200282D */   daddu     $a1, $s0, $zero
/* 172A64 8024A044 2404003B */  addiu      $a0, $zero, 0x3B
/* 172A68 8024A048 0C051A8B */  jal        set_window_update
/* 172A6C 8024A04C 0200282D */   daddu     $a1, $s0, $zero
/* 172A70 8024A050 0C052219 */  jal        sfx_play_sound
/* 172A74 8024A054 240400C9 */   addiu     $a0, $zero, 0xC9
/* 172A78 8024A058 0000282D */  daddu      $a1, $zero, $zero
/* 172A7C 8024A05C 00A0302D */  daddu      $a2, $a1, $zero
/* 172A80 8024A060 3C048025 */  lui        $a0, %hi(filemenu_menus+0xC)
/* 172A84 8024A064 8C84E990 */  lw         $a0, %lo(filemenu_menus+0xC)($a0)
/* 172A88 8024A068 24020003 */  addiu      $v0, $zero, 0x3
/* 172A8C 8024A06C 3C018025 */  lui        $at, %hi(filemenu_currentMenu)
/* 172A90 8024A070 A0221758 */  sb         $v0, %lo(filemenu_currentMenu)($at)
/* 172A94 8024A074 08092A4D */  j          .Lfilemenu_8024A934
/* 172A98 8024A078 A0800004 */   sb        $zero, 0x4($a0)
.Lfilemenu_8024A07C:
/* 172A9C 8024A07C 92630003 */  lbu        $v1, 0x3($s3)
/* 172AA0 8024A080 24020006 */  addiu      $v0, $zero, 0x6
/* 172AA4 8024A084 1462002C */  bne        $v1, $v0, .Lfilemenu_8024A138
/* 172AA8 8024A088 24020004 */   addiu     $v0, $zero, 0x4
/* 172AAC 8024A08C 24040033 */  addiu      $a0, $zero, 0x33
/* 172AB0 8024A090 3C128024 */  lui        $s2, %hi(filemenu_update_hidden_options_left)
/* 172AB4 8024A094 2652759C */  addiu      $s2, $s2, %lo(filemenu_update_hidden_options_left)
/* 172AB8 8024A098 0C051A8B */  jal        set_window_update
/* 172ABC 8024A09C 0240282D */   daddu     $a1, $s2, $zero
/* 172AC0 8024A0A0 24040034 */  addiu      $a0, $zero, 0x34
/* 172AC4 8024A0A4 3C118024 */  lui        $s1, %hi(filemenu_update_hidden_options_right)
/* 172AC8 8024A0A8 26317600 */  addiu      $s1, $s1, %lo(filemenu_update_hidden_options_right)
/* 172ACC 8024A0AC 0C051A8B */  jal        set_window_update
/* 172AD0 8024A0B0 0220282D */   daddu     $a1, $s1, $zero
/* 172AD4 8024A0B4 24040035 */  addiu      $a0, $zero, 0x35
/* 172AD8 8024A0B8 3C108024 */  lui        $s0, %hi(filemenu_update_hidden_options_bottom)
/* 172ADC 8024A0BC 261076C8 */  addiu      $s0, $s0, %lo(filemenu_update_hidden_options_bottom)
/* 172AE0 8024A0C0 0C051A8B */  jal        set_window_update
/* 172AE4 8024A0C4 0200282D */   daddu     $a1, $s0, $zero
/* 172AE8 8024A0C8 24040036 */  addiu      $a0, $zero, 0x36
/* 172AEC 8024A0CC 0C051A8B */  jal        set_window_update
/* 172AF0 8024A0D0 0200282D */   daddu     $a1, $s0, $zero
/* 172AF4 8024A0D4 24040037 */  addiu      $a0, $zero, 0x37
/* 172AF8 8024A0D8 0C051A8B */  jal        set_window_update
/* 172AFC 8024A0DC 0200282D */   daddu     $a1, $s0, $zero
/* 172B00 8024A0E0 24040038 */  addiu      $a0, $zero, 0x38
/* 172B04 8024A0E4 0C051A8B */  jal        set_window_update
/* 172B08 8024A0E8 0240282D */   daddu     $a1, $s2, $zero
/* 172B0C 8024A0EC 24040039 */  addiu      $a0, $zero, 0x39
/* 172B10 8024A0F0 0C051A8B */  jal        set_window_update
/* 172B14 8024A0F4 0220282D */   daddu     $a1, $s1, $zero
/* 172B18 8024A0F8 2404003A */  addiu      $a0, $zero, 0x3A
/* 172B1C 8024A0FC 0C051A8B */  jal        set_window_update
/* 172B20 8024A100 0240282D */   daddu     $a1, $s2, $zero
/* 172B24 8024A104 2404003B */  addiu      $a0, $zero, 0x3B
/* 172B28 8024A108 0C051A8B */  jal        set_window_update
/* 172B2C 8024A10C 0220282D */   daddu     $a1, $s1, $zero
/* 172B30 8024A110 3C058024 */  lui        $a1, %hi(filemenu_update_hidden_title)
/* 172B34 8024A114 24A57664 */  addiu      $a1, $a1, %lo(filemenu_update_hidden_title)
/* 172B38 8024A118 0C051A8B */  jal        set_window_update
/* 172B3C 8024A11C 2404002D */   addiu     $a0, $zero, 0x2D
/* 172B40 8024A120 0C052219 */  jal        sfx_play_sound
/* 172B44 8024A124 240400D6 */   addiu     $a0, $zero, 0xD6
/* 172B48 8024A128 0C00CE04 */  jal        set_game_mode
/* 172B4C 8024A12C 2404000F */   addiu     $a0, $zero, 0xF
/* 172B50 8024A130 08092A4F */  j          .Lfilemenu_8024A93C
/* 172B54 8024A134 00000000 */   nop
.Lfilemenu_8024A138:
/* 172B58 8024A138 14620005 */  bne        $v1, $v0, .Lfilemenu_8024A150
/* 172B5C 8024A13C 24020005 */   addiu     $v0, $zero, 0x5
/* 172B60 8024A140 0C052219 */  jal        sfx_play_sound
/* 172B64 8024A144 240400C9 */   addiu     $a0, $zero, 0xC9
/* 172B68 8024A148 08092859 */  j          .Lfilemenu_8024A164
/* 172B6C 8024A14C 24020001 */   addiu     $v0, $zero, 0x1
.Lfilemenu_8024A150:
/* 172B70 8024A150 1462001B */  bne        $v1, $v0, .Lfilemenu_8024A1C0
/* 172B74 8024A154 2C620004 */   sltiu     $v0, $v1, 0x4
/* 172B78 8024A158 0C052219 */  jal        sfx_play_sound
/* 172B7C 8024A15C 240400C9 */   addiu     $a0, $zero, 0xC9
/* 172B80 8024A160 24020002 */  addiu      $v0, $zero, 0x2
.Lfilemenu_8024A164:
/* 172B84 8024A164 A2620004 */  sb         $v0, 0x4($s3)
/* 172B88 8024A168 0260202D */  daddu      $a0, $s3, $zero
/* 172B8C 8024A16C 24050001 */  addiu      $a1, $zero, 0x1
/* 172B90 8024A170 0C091B29 */  jal        filemenu_set_selected
/* 172B94 8024A174 24060002 */   addiu     $a2, $zero, 0x2
/* 172B98 8024A178 3C058024 */  lui        $a1, %hi(filemenu_update_hidden_options_left)
/* 172B9C 8024A17C 24A5759C */  addiu      $a1, $a1, %lo(filemenu_update_hidden_options_left)
/* 172BA0 8024A180 0C051A8B */  jal        set_window_update
/* 172BA4 8024A184 24040033 */   addiu     $a0, $zero, 0x33
/* 172BA8 8024A188 3C058024 */  lui        $a1, %hi(filemenu_update_hidden_options_right)
/* 172BAC 8024A18C 24A57600 */  addiu      $a1, $a1, %lo(filemenu_update_hidden_options_right)
/* 172BB0 8024A190 0C051A8B */  jal        set_window_update
/* 172BB4 8024A194 24040034 */   addiu     $a0, $zero, 0x34
/* 172BB8 8024A198 24040035 */  addiu      $a0, $zero, 0x35
/* 172BBC 8024A19C 3C108024 */  lui        $s0, %hi(filemenu_update_hidden_options_bottom)
/* 172BC0 8024A1A0 261076C8 */  addiu      $s0, $s0, %lo(filemenu_update_hidden_options_bottom)
/* 172BC4 8024A1A4 0C051A8B */  jal        set_window_update
/* 172BC8 8024A1A8 0200282D */   daddu     $a1, $s0, $zero
/* 172BCC 8024A1AC 24040037 */  addiu      $a0, $zero, 0x37
/* 172BD0 8024A1B0 0C051A8B */  jal        set_window_update
/* 172BD4 8024A1B4 0200282D */   daddu     $a1, $s0, $zero
/* 172BD8 8024A1B8 08092A4F */  j          .Lfilemenu_8024A93C
/* 172BDC 8024A1BC 00000000 */   nop
.Lfilemenu_8024A1C0:
/* 172BE0 8024A1C0 104001DE */  beqz       $v0, .Lfilemenu_8024A93C
/* 172BE4 8024A1C4 00000000 */   nop
/* 172BE8 8024A1C8 0C052219 */  jal        sfx_play_sound
/* 172BEC 8024A1CC 240400C9 */   addiu     $a0, $zero, 0xC9
/* 172BF0 8024A1D0 2404002D */  addiu      $a0, $zero, 0x2D
/* 172BF4 8024A1D4 3C108024 */  lui        $s0, %hi(filemenu_update_hidden_with_rotation)
/* 172BF8 8024A1D8 261077A8 */  addiu      $s0, $s0, %lo(filemenu_update_hidden_with_rotation)
/* 172BFC 8024A1DC 0C051A8B */  jal        set_window_update
/* 172C00 8024A1E0 0200282D */   daddu     $a1, $s0, $zero
/* 172C04 8024A1E4 24040033 */  addiu      $a0, $zero, 0x33
/* 172C08 8024A1E8 0C051A8B */  jal        set_window_update
/* 172C0C 8024A1EC 0200282D */   daddu     $a1, $s0, $zero
/* 172C10 8024A1F0 24040034 */  addiu      $a0, $zero, 0x34
/* 172C14 8024A1F4 0C051A8B */  jal        set_window_update
/* 172C18 8024A1F8 0200282D */   daddu     $a1, $s0, $zero
/* 172C1C 8024A1FC 24040035 */  addiu      $a0, $zero, 0x35
/* 172C20 8024A200 0C051A8B */  jal        set_window_update
/* 172C24 8024A204 0200282D */   daddu     $a1, $s0, $zero
/* 172C28 8024A208 24040036 */  addiu      $a0, $zero, 0x36
/* 172C2C 8024A20C 0C051A8B */  jal        set_window_update
/* 172C30 8024A210 0200282D */   daddu     $a1, $s0, $zero
/* 172C34 8024A214 24040037 */  addiu      $a0, $zero, 0x37
/* 172C38 8024A218 0C051A8B */  jal        set_window_update
/* 172C3C 8024A21C 0200282D */   daddu     $a1, $s0, $zero
/* 172C40 8024A220 24040035 */  addiu      $a0, $zero, 0x35
/* 172C44 8024A224 0C051A8B */  jal        set_window_update
/* 172C48 8024A228 0200282D */   daddu     $a1, $s0, $zero
/* 172C4C 8024A22C 24040038 */  addiu      $a0, $zero, 0x38
/* 172C50 8024A230 0C051A8B */  jal        set_window_update
/* 172C54 8024A234 0200282D */   daddu     $a1, $s0, $zero
/* 172C58 8024A238 24040039 */  addiu      $a0, $zero, 0x39
/* 172C5C 8024A23C 0C051A8B */  jal        set_window_update
/* 172C60 8024A240 0200282D */   daddu     $a1, $s0, $zero
/* 172C64 8024A244 2404003A */  addiu      $a0, $zero, 0x3A
/* 172C68 8024A248 0C051A8B */  jal        set_window_update
/* 172C6C 8024A24C 0200282D */   daddu     $a1, $s0, $zero
/* 172C70 8024A250 2404003B */  addiu      $a0, $zero, 0x3B
/* 172C74 8024A254 0C051A8B */  jal        set_window_update
/* 172C78 8024A258 0200282D */   daddu     $a1, $s0, $zero
/* 172C7C 8024A25C 92640003 */  lbu        $a0, 0x3($s3)
/* 172C80 8024A260 3C058024 */  lui        $a1, %hi(filemenu_update_select_file)
/* 172C84 8024A264 24A57818 */  addiu      $a1, $a1, %lo(filemenu_update_select_file)
/* 172C88 8024A268 0C051A8B */  jal        set_window_update
/* 172C8C 8024A26C 24840038 */   addiu     $a0, $a0, 0x38
/* 172C90 8024A270 0C052219 */  jal        sfx_play_sound
/* 172C94 8024A274 240400C9 */   addiu     $a0, $zero, 0xC9
/* 172C98 8024A278 24040032 */  addiu      $a0, $zero, 0x32
/* 172C9C 8024A27C 0C051A8B */  jal        set_window_update
/* 172CA0 8024A280 24050001 */   addiu     $a1, $zero, 0x1
/* 172CA4 8024A284 3C048016 */  lui        $a0, %hi(gWindows)
/* 172CA8 8024A288 24848910 */  addiu      $a0, $a0, %lo(gWindows)
/* 172CAC 8024A28C 2402008F */  addiu      $v0, $zero, 0x8F
/* 172CB0 8024A290 A482064E */  sh         $v0, 0x64E($a0)
/* 172CB4 8024A294 24020045 */  addiu      $v0, $zero, 0x45
/* 172CB8 8024A298 A4820650 */  sh         $v0, 0x650($a0)
/* 172CBC 8024A29C 2402002C */  addiu      $v0, $zero, 0x2C
/* 172CC0 8024A2A0 80830643 */  lb         $v1, 0x643($a0)
/* 172CC4 8024A2A4 A4820652 */  sh         $v0, 0x652($a0)
/* 172CC8 8024A2A8 2402FFFF */  addiu      $v0, $zero, -0x1
/* 172CCC 8024A2AC 1062000B */  beq        $v1, $v0, .Lfilemenu_8024A2DC
/* 172CD0 8024A2B0 2485064C */   addiu     $a1, $a0, 0x64C
/* 172CD4 8024A2B4 00031140 */  sll        $v0, $v1, 5
/* 172CD8 8024A2B8 00441021 */  addu       $v0, $v0, $a0
/* 172CDC 8024A2BC 94420010 */  lhu        $v0, 0x10($v0)
/* 172CE0 8024A2C0 00021400 */  sll        $v0, $v0, 16
/* 172CE4 8024A2C4 00021C03 */  sra        $v1, $v0, 16
/* 172CE8 8024A2C8 000217C2 */  srl        $v0, $v0, 31
/* 172CEC 8024A2CC 00621821 */  addu       $v1, $v1, $v0
/* 172CF0 8024A2D0 00031843 */  sra        $v1, $v1, 1
/* 172CF4 8024A2D4 080928B8 */  j          .Lfilemenu_8024A2E0
/* 172CF8 8024A2D8 2463FFDE */   addiu     $v1, $v1, -0x22
.Lfilemenu_8024A2DC:
/* 172CFC 8024A2DC 2403007E */  addiu      $v1, $zero, 0x7E
.Lfilemenu_8024A2E0:
/* 172D00 8024A2E0 3C028015 */  lui        $v0, %hi(gCurrentLanguage)
/* 172D04 8024A2E4 8C42AE4C */  lw         $v0, %lo(gCurrentLanguage)($v0)
/* 172D08 8024A2E8 3C048016 */  lui        $a0, %hi(gWindows)
/* 172D0C 8024A2EC 24848910 */  addiu      $a0, $a0, %lo(gWindows)
/* 172D10 8024A2F0 A4A30000 */  sh         $v1, 0x0($a1)
/* 172D14 8024A2F4 2403FFE3 */  addiu      $v1, $zero, -0x1D
/* 172D18 8024A2F8 A48305CE */  sh         $v1, 0x5CE($a0)
/* 172D1C 8024A2FC 24030019 */  addiu      $v1, $zero, 0x19
/* 172D20 8024A300 00021040 */  sll        $v0, $v0, 1
/* 172D24 8024A304 3C018025 */  lui        $at, %hi(D_filemenu_80250900)
/* 172D28 8024A308 00220821 */  addu       $at, $at, $v0
/* 172D2C 8024A30C 94220900 */  lhu        $v0, %lo(D_filemenu_80250900)($at)
/* 172D30 8024A310 A48305D2 */  sh         $v1, 0x5D2($a0)
/* 172D34 8024A314 A48205D0 */  sh         $v0, 0x5D0($a0)
/* 172D38 8024A318 00021400 */  sll        $v0, $v0, 16
/* 172D3C 8024A31C 00021C03 */  sra        $v1, $v0, 16
/* 172D40 8024A320 000217C2 */  srl        $v0, $v0, 31
/* 172D44 8024A324 00621821 */  addu       $v1, $v1, $v0
/* 172D48 8024A328 00032843 */  sra        $a1, $v1, 1
/* 172D4C 8024A32C 808305C3 */  lb         $v1, 0x5C3($a0)
/* 172D50 8024A330 2402FFFF */  addiu      $v0, $zero, -0x1
/* 172D54 8024A334 1062000B */  beq        $v1, $v0, .Lfilemenu_8024A364
/* 172D58 8024A338 248705CC */   addiu     $a3, $a0, 0x5CC
/* 172D5C 8024A33C 00031140 */  sll        $v0, $v1, 5
/* 172D60 8024A340 00441021 */  addu       $v0, $v0, $a0
/* 172D64 8024A344 94420010 */  lhu        $v0, 0x10($v0)
/* 172D68 8024A348 00021400 */  sll        $v0, $v0, 16
/* 172D6C 8024A34C 00021C03 */  sra        $v1, $v0, 16
/* 172D70 8024A350 000217C2 */  srl        $v0, $v0, 31
/* 172D74 8024A354 00621821 */  addu       $v1, $v1, $v0
/* 172D78 8024A358 00031843 */  sra        $v1, $v1, 1
/* 172D7C 8024A35C 080928DB */  j          .Lfilemenu_8024A36C
/* 172D80 8024A360 00651023 */   subu      $v0, $v1, $a1
.Lfilemenu_8024A364:
/* 172D84 8024A364 240200A0 */  addiu      $v0, $zero, 0xA0
/* 172D88 8024A368 00451023 */  subu       $v0, $v0, $a1
.Lfilemenu_8024A36C:
/* 172D8C 8024A36C 0000282D */  daddu      $a1, $zero, $zero
/* 172D90 8024A370 00A0302D */  daddu      $a2, $a1, $zero
/* 172D94 8024A374 A4E20000 */  sh         $v0, 0x0($a3)
/* 172D98 8024A378 3C048025 */  lui        $a0, %hi(filemenu_menus+0x4)
/* 172D9C 8024A37C 8C84E988 */  lw         $a0, %lo(filemenu_menus+0x4)($a0)
/* 172DA0 8024A380 24020001 */  addiu      $v0, $zero, 0x1
/* 172DA4 8024A384 3C018025 */  lui        $at, %hi(filemenu_currentMenu)
/* 172DA8 8024A388 A0221758 */  sb         $v0, %lo(filemenu_currentMenu)($at)
/* 172DAC 8024A38C 08092A4C */  j          .Lfilemenu_8024A930
/* 172DB0 8024A390 24020003 */   addiu     $v0, $zero, 0x3
.Lfilemenu_8024A394:
/* 172DB4 8024A394 3C108016 */  lui        $s0, %hi(gWindows)
/* 172DB8 8024A398 26108910 */  addiu      $s0, $s0, %lo(gWindows)
/* 172DBC 8024A39C 240200D3 */  addiu      $v0, $zero, 0xD3
/* 172DC0 8024A3A0 A60205B0 */  sh         $v0, 0x5B0($s0)
/* 172DC4 8024A3A4 92630003 */  lbu        $v1, 0x3($s3)
/* 172DC8 8024A3A8 24020006 */  addiu      $v0, $zero, 0x6
/* 172DCC 8024A3AC 14620018 */  bne        $v1, $v0, .Lfilemenu_8024A410
/* 172DD0 8024A3B0 2C620004 */   sltiu     $v0, $v1, 0x4
/* 172DD4 8024A3B4 0C052219 */  jal        sfx_play_sound
/* 172DD8 8024A3B8 240400C9 */   addiu     $a0, $zero, 0xC9
/* 172DDC 8024A3BC A2600004 */  sb         $zero, 0x4($s3)
/* 172DE0 8024A3C0 3C058024 */  lui        $a1, %hi(filemenu_update_show_options_left)
/* 172DE4 8024A3C4 24A57304 */  addiu      $a1, $a1, %lo(filemenu_update_show_options_left)
/* 172DE8 8024A3C8 0C051A8B */  jal        set_window_update
/* 172DEC 8024A3CC 24040033 */   addiu     $a0, $zero, 0x33
/* 172DF0 8024A3D0 3C058024 */  lui        $a1, %hi(filemenu_update_show_options_right)
/* 172DF4 8024A3D4 24A57378 */  addiu      $a1, $a1, %lo(filemenu_update_show_options_right)
/* 172DF8 8024A3D8 0C051A8B */  jal        set_window_update
/* 172DFC 8024A3DC 24040034 */   addiu     $a0, $zero, 0x34
/* 172E00 8024A3E0 24040035 */  addiu      $a0, $zero, 0x35
/* 172E04 8024A3E4 3C108024 */  lui        $s0, %hi(filemenu_update_show_options_bottom)
/* 172E08 8024A3E8 261073EC */  addiu      $s0, $s0, %lo(filemenu_update_show_options_bottom)
/* 172E0C 8024A3EC 0C051A8B */  jal        set_window_update
/* 172E10 8024A3F0 0200282D */   daddu     $a1, $s0, $zero
/* 172E14 8024A3F4 24040037 */  addiu      $a0, $zero, 0x37
/* 172E18 8024A3F8 0C051A8B */  jal        set_window_update
/* 172E1C 8024A3FC 0200282D */   daddu     $a1, $s0, $zero
/* 172E20 8024A400 0260202D */  daddu      $a0, $s3, $zero
/* 172E24 8024A404 0000282D */  daddu      $a1, $zero, $zero
/* 172E28 8024A408 08092A4D */  j          .Lfilemenu_8024A934
/* 172E2C 8024A40C 24060002 */   addiu     $a2, $zero, 0x2
.Lfilemenu_8024A410:
/* 172E30 8024A410 1040014A */  beqz       $v0, .Lfilemenu_8024A93C
/* 172E34 8024A414 00000000 */   nop
/* 172E38 8024A418 92620003 */  lbu        $v0, 0x3($s3)
/* 172E3C 8024A41C 3C018007 */  lui        $at, %hi(gSaveSlotHasData)
/* 172E40 8024A420 00220821 */  addu       $at, $at, $v0
/* 172E44 8024A424 90223D74 */  lbu        $v0, %lo(gSaveSlotHasData)($at)
/* 172E48 8024A428 10400081 */  beqz       $v0, .Lfilemenu_8024A630
/* 172E4C 8024A42C 00000000 */   nop
/* 172E50 8024A430 0C052219 */  jal        sfx_play_sound
/* 172E54 8024A434 240400C9 */   addiu     $a0, $zero, 0xC9
/* 172E58 8024A438 3C058024 */  lui        $a1, %hi(filemenu_update_show_name_confirm)
/* 172E5C 8024A43C 24A57BDC */  addiu      $a1, $a1, %lo(filemenu_update_show_name_confirm)
/* 172E60 8024A440 0C051A8B */  jal        set_window_update
/* 172E64 8024A444 24040032 */   addiu     $a0, $zero, 0x32
/* 172E68 8024A448 24020079 */  addiu      $v0, $zero, 0x79
/* 172E6C 8024A44C A602064E */  sh         $v0, 0x64E($s0)
/* 172E70 8024A450 24020045 */  addiu      $v0, $zero, 0x45
/* 172E74 8024A454 A6020650 */  sh         $v0, 0x650($s0)
/* 172E78 8024A458 2402002C */  addiu      $v0, $zero, 0x2C
/* 172E7C 8024A45C 82030643 */  lb         $v1, 0x643($s0)
/* 172E80 8024A460 A6020652 */  sh         $v0, 0x652($s0)
/* 172E84 8024A464 2402FFFF */  addiu      $v0, $zero, -0x1
/* 172E88 8024A468 1062000B */  beq        $v1, $v0, .Lfilemenu_8024A498
/* 172E8C 8024A46C 2604064C */   addiu     $a0, $s0, 0x64C
/* 172E90 8024A470 00031140 */  sll        $v0, $v1, 5
/* 172E94 8024A474 00501021 */  addu       $v0, $v0, $s0
/* 172E98 8024A478 94420010 */  lhu        $v0, 0x10($v0)
/* 172E9C 8024A47C 00021400 */  sll        $v0, $v0, 16
/* 172EA0 8024A480 00021C03 */  sra        $v1, $v0, 16
/* 172EA4 8024A484 000217C2 */  srl        $v0, $v0, 31
/* 172EA8 8024A488 00621821 */  addu       $v1, $v1, $v0
/* 172EAC 8024A48C 00031843 */  sra        $v1, $v1, 1
/* 172EB0 8024A490 08092927 */  j          .Lfilemenu_8024A49C
/* 172EB4 8024A494 2463FFDE */   addiu     $v1, $v1, -0x22
.Lfilemenu_8024A498:
/* 172EB8 8024A498 2403007E */  addiu      $v1, $zero, 0x7E
.Lfilemenu_8024A49C:
/* 172EBC 8024A49C A4830000 */  sh         $v1, 0x0($a0)
/* 172EC0 8024A4A0 3C048016 */  lui        $a0, %hi(gWindows)
/* 172EC4 8024A4A4 24848910 */  addiu      $a0, $a0, %lo(gWindows)
/* 172EC8 8024A4A8 3C038015 */  lui        $v1, %hi(gCurrentLanguage)
/* 172ECC 8024A4AC 8C63AE4C */  lw         $v1, %lo(gCurrentLanguage)($v1)
/* 172ED0 8024A4B0 2402FFE3 */  addiu      $v0, $zero, -0x1D
/* 172ED4 8024A4B4 A48205CE */  sh         $v0, 0x5CE($a0)
/* 172ED8 8024A4B8 24020019 */  addiu      $v0, $zero, 0x19
/* 172EDC 8024A4BC 3C018025 */  lui        $at, %hi(D_filemenu_80250920)
/* 172EE0 8024A4C0 00230821 */  addu       $at, $at, $v1
/* 172EE4 8024A4C4 90230920 */  lbu        $v1, %lo(D_filemenu_80250920)($at)
/* 172EE8 8024A4C8 A48205D2 */  sh         $v0, 0x5D2($a0)
/* 172EEC 8024A4CC 00032842 */  srl        $a1, $v1, 1
/* 172EF0 8024A4D0 A48305D0 */  sh         $v1, 0x5D0($a0)
/* 172EF4 8024A4D4 808305C3 */  lb         $v1, 0x5C3($a0)
/* 172EF8 8024A4D8 2402FFFF */  addiu      $v0, $zero, -0x1
/* 172EFC 8024A4DC 1062000B */  beq        $v1, $v0, .Lfilemenu_8024A50C
/* 172F00 8024A4E0 248705CC */   addiu     $a3, $a0, 0x5CC
/* 172F04 8024A4E4 00031140 */  sll        $v0, $v1, 5
/* 172F08 8024A4E8 00441021 */  addu       $v0, $v0, $a0
/* 172F0C 8024A4EC 94420010 */  lhu        $v0, 0x10($v0)
/* 172F10 8024A4F0 00021400 */  sll        $v0, $v0, 16
/* 172F14 8024A4F4 00021C03 */  sra        $v1, $v0, 16
/* 172F18 8024A4F8 000217C2 */  srl        $v0, $v0, 31
/* 172F1C 8024A4FC 00621821 */  addu       $v1, $v1, $v0
/* 172F20 8024A500 00031843 */  sra        $v1, $v1, 1
/* 172F24 8024A504 08092945 */  j          .Lfilemenu_8024A514
/* 172F28 8024A508 00651023 */   subu      $v0, $v1, $a1
.Lfilemenu_8024A50C:
/* 172F2C 8024A50C 240200A0 */  addiu      $v0, $zero, 0xA0
/* 172F30 8024A510 00451023 */  subu       $v0, $v0, $a1
.Lfilemenu_8024A514:
/* 172F34 8024A514 0000282D */  daddu      $a1, $zero, $zero
/* 172F38 8024A518 24060001 */  addiu      $a2, $zero, 0x1
/* 172F3C 8024A51C A4E20000 */  sh         $v0, 0x0($a3)
/* 172F40 8024A520 3C048025 */  lui        $a0, %hi(filemenu_menus+0x4)
/* 172F44 8024A524 8C84E988 */  lw         $a0, %lo(filemenu_menus+0x4)($a0)
/* 172F48 8024A528 00C0102D */  daddu      $v0, $a2, $zero
/* 172F4C 8024A52C 3C018025 */  lui        $at, %hi(filemenu_currentMenu)
/* 172F50 8024A530 A0221758 */  sb         $v0, %lo(filemenu_currentMenu)($at)
/* 172F54 8024A534 08092A4D */  j          .Lfilemenu_8024A934
/* 172F58 8024A538 A0800004 */   sb        $zero, 0x4($a0)
.Lfilemenu_8024A53C:
/* 172F5C 8024A53C 92630003 */  lbu        $v1, 0x3($s3)
/* 172F60 8024A540 24020006 */  addiu      $v0, $zero, 0x6
/* 172F64 8024A544 14620018 */  bne        $v1, $v0, .Lfilemenu_8024A5A8
/* 172F68 8024A548 2C620004 */   sltiu     $v0, $v1, 0x4
/* 172F6C 8024A54C 0C052219 */  jal        sfx_play_sound
/* 172F70 8024A550 240400C9 */   addiu     $a0, $zero, 0xC9
/* 172F74 8024A554 A2600004 */  sb         $zero, 0x4($s3)
/* 172F78 8024A558 3C058024 */  lui        $a1, %hi(filemenu_update_show_options_left)
/* 172F7C 8024A55C 24A57304 */  addiu      $a1, $a1, %lo(filemenu_update_show_options_left)
/* 172F80 8024A560 0C051A8B */  jal        set_window_update
/* 172F84 8024A564 24040033 */   addiu     $a0, $zero, 0x33
/* 172F88 8024A568 3C058024 */  lui        $a1, %hi(filemenu_update_show_options_right)
/* 172F8C 8024A56C 24A57378 */  addiu      $a1, $a1, %lo(filemenu_update_show_options_right)
/* 172F90 8024A570 0C051A8B */  jal        set_window_update
/* 172F94 8024A574 24040034 */   addiu     $a0, $zero, 0x34
/* 172F98 8024A578 24040035 */  addiu      $a0, $zero, 0x35
/* 172F9C 8024A57C 3C108024 */  lui        $s0, %hi(filemenu_update_show_options_bottom)
/* 172FA0 8024A580 261073EC */  addiu      $s0, $s0, %lo(filemenu_update_show_options_bottom)
/* 172FA4 8024A584 0C051A8B */  jal        set_window_update
/* 172FA8 8024A588 0200282D */   daddu     $a1, $s0, $zero
/* 172FAC 8024A58C 24040037 */  addiu      $a0, $zero, 0x37
/* 172FB0 8024A590 0C051A8B */  jal        set_window_update
/* 172FB4 8024A594 0200282D */   daddu     $a1, $s0, $zero
/* 172FB8 8024A598 0260202D */  daddu      $a0, $s3, $zero
/* 172FBC 8024A59C 0000282D */  daddu      $a1, $zero, $zero
/* 172FC0 8024A5A0 08092A4D */  j          .Lfilemenu_8024A934
/* 172FC4 8024A5A4 24060001 */   addiu     $a2, $zero, 0x1
.Lfilemenu_8024A5A8:
/* 172FC8 8024A5A8 104000E4 */  beqz       $v0, .Lfilemenu_8024A93C
/* 172FCC 8024A5AC 00000000 */   nop
/* 172FD0 8024A5B0 92620003 */  lbu        $v0, 0x3($s3)
/* 172FD4 8024A5B4 3C018007 */  lui        $at, %hi(gSaveSlotHasData)
/* 172FD8 8024A5B8 00220821 */  addu       $at, $at, $v0
/* 172FDC 8024A5BC 90223D74 */  lbu        $v0, %lo(gSaveSlotHasData)($at)
/* 172FE0 8024A5C0 1040001B */  beqz       $v0, .Lfilemenu_8024A630
/* 172FE4 8024A5C4 00000000 */   nop
/* 172FE8 8024A5C8 0C052219 */  jal        sfx_play_sound
/* 172FEC 8024A5CC 240400C9 */   addiu     $a0, $zero, 0xC9
/* 172FF0 8024A5D0 92630003 */  lbu        $v1, 0x3($s3)
/* 172FF4 8024A5D4 24020003 */  addiu      $v0, $zero, 0x3
/* 172FF8 8024A5D8 A2620004 */  sb         $v0, 0x4($s3)
/* 172FFC 8024A5DC 3C018025 */  lui        $at, %hi(filemenu_loadedFileIdx)
/* 173000 8024A5E0 AC231754 */  sw         $v1, %lo(filemenu_loadedFileIdx)($at)
/* 173004 8024A5E4 08092A4F */  j          .Lfilemenu_8024A93C
/* 173008 8024A5E8 00000000 */   nop
.Lfilemenu_8024A5EC:
/* 17300C 8024A5EC 92630003 */  lbu        $v1, 0x3($s3)
/* 173010 8024A5F0 14620008 */  bne        $v1, $v0, .Lfilemenu_8024A614
/* 173014 8024A5F4 2C620004 */   sltiu     $v0, $v1, 0x4
/* 173018 8024A5F8 0C052219 */  jal        sfx_play_sound
/* 17301C 8024A5FC 240400C9 */   addiu     $a0, $zero, 0xC9
/* 173020 8024A600 A2700004 */  sb         $s0, 0x4($s3)
/* 173024 8024A604 0260202D */  daddu      $a0, $s3, $zero
/* 173028 8024A608 0000282D */  daddu      $a1, $zero, $zero
/* 17302C 8024A60C 08092A4D */  j          .Lfilemenu_8024A934
/* 173030 8024A610 24060002 */   addiu     $a2, $zero, 0x2
.Lfilemenu_8024A614:
/* 173034 8024A614 104000C9 */  beqz       $v0, .Lfilemenu_8024A93C
/* 173038 8024A618 00000000 */   nop
/* 17303C 8024A61C 92630003 */  lbu        $v1, 0x3($s3)
/* 173040 8024A620 3C028025 */  lui        $v0, %hi(filemenu_loadedFileIdx)
/* 173044 8024A624 8C421754 */  lw         $v0, %lo(filemenu_loadedFileIdx)($v0)
/* 173048 8024A628 14430005 */  bne        $v0, $v1, .Lfilemenu_8024A640
/* 17304C 8024A62C 00000000 */   nop
.Lfilemenu_8024A630:
/* 173050 8024A630 0C052219 */  jal        sfx_play_sound
/* 173054 8024A634 2404021D */   addiu     $a0, $zero, 0x21D
/* 173058 8024A638 08092A4F */  j          .Lfilemenu_8024A93C
/* 17305C 8024A63C 00000000 */   nop
.Lfilemenu_8024A640:
/* 173060 8024A640 3C018025 */  lui        $at, 0x8025
/* 173064 8024A644 AC231740 */  sw         $v1, (0x80251740 & 0xFFFF)($at)
/* 173068 8024A648 92620003 */  lbu        $v0, 0x3($s3)
/* 17306C 8024A64C 3C018007 */  lui        $at, %hi(gSaveSlotHasData)
/* 173070 8024A650 00220821 */  addu       $at, $at, $v0
/* 173074 8024A654 90223D74 */  lbu        $v0, %lo(gSaveSlotHasData)($at)
/* 173078 8024A658 1440006C */  bnez       $v0, .Lfilemenu_8024A80C
/* 17307C 8024A65C 00000000 */   nop
/* 173080 8024A660 0C052219 */  jal        sfx_play_sound
/* 173084 8024A664 240400C9 */   addiu     $a0, $zero, 0xC9
/* 173088 8024A668 3C028025 */  lui        $v0, %hi(filemenu_menus+0x8)
/* 17308C 8024A66C 8C42E98C */  lw         $v0, %lo(filemenu_menus+0x8)($v0)
/* 173090 8024A670 3C048016 */  lui        $a0, %hi(gWindows)
/* 173094 8024A674 24848910 */  addiu      $a0, $a0, %lo(gWindows)
/* 173098 8024A678 3C018025 */  lui        $at, %hi(filemenu_currentMenu)
/* 17309C 8024A67C A0301758 */  sb         $s0, %lo(filemenu_currentMenu)($at)
/* 1730A0 8024A680 A0510004 */  sb         $s1, 0x4($v0)
/* 1730A4 8024A684 3C028015 */  lui        $v0, %hi(gCurrentLanguage)
/* 1730A8 8024A688 8C42AE4C */  lw         $v0, %lo(gCurrentLanguage)($v0)
/* 1730AC 8024A68C 3C038025 */  lui        $v1, %hi(D_filemenu_80250954)
/* 1730B0 8024A690 00621821 */  addu       $v1, $v1, $v0
/* 1730B4 8024A694 90630954 */  lbu        $v1, %lo(D_filemenu_80250954)($v1)
/* 1730B8 8024A698 24020027 */  addiu      $v0, $zero, 0x27
/* 1730BC 8024A69C A48205F2 */  sh         $v0, 0x5F2($a0)
/* 1730C0 8024A6A0 00032842 */  srl        $a1, $v1, 1
/* 1730C4 8024A6A4 A48305F0 */  sh         $v1, 0x5F0($a0)
/* 1730C8 8024A6A8 808305E3 */  lb         $v1, 0x5E3($a0)
/* 1730CC 8024A6AC 2402FFFF */  addiu      $v0, $zero, -0x1
/* 1730D0 8024A6B0 1062000B */  beq        $v1, $v0, .Lfilemenu_8024A6E0
/* 1730D4 8024A6B4 248605EC */   addiu     $a2, $a0, 0x5EC
/* 1730D8 8024A6B8 00031140 */  sll        $v0, $v1, 5
/* 1730DC 8024A6BC 00441021 */  addu       $v0, $v0, $a0
/* 1730E0 8024A6C0 94420010 */  lhu        $v0, 0x10($v0)
/* 1730E4 8024A6C4 00021400 */  sll        $v0, $v0, 16
/* 1730E8 8024A6C8 00021C03 */  sra        $v1, $v0, 16
/* 1730EC 8024A6CC 000217C2 */  srl        $v0, $v0, 31
/* 1730F0 8024A6D0 00621821 */  addu       $v1, $v1, $v0
/* 1730F4 8024A6D4 00031843 */  sra        $v1, $v1, 1
/* 1730F8 8024A6D8 080929BC */  j          .Lfilemenu_8024A6F0
/* 1730FC 8024A6DC 00651023 */   subu      $v0, $v1, $a1
.Lfilemenu_8024A6E0:
/* 173100 8024A6E0 240200A0 */  addiu      $v0, $zero, 0xA0
/* 173104 8024A6E4 00451023 */  subu       $v0, $v0, $a1
/* 173108 8024A6E8 3C048016 */  lui        $a0, %hi(gWindows)
/* 17310C 8024A6EC 24848910 */  addiu      $a0, $a0, %lo(gWindows)
.Lfilemenu_8024A6F0:
/* 173110 8024A6F0 A4C20000 */  sh         $v0, 0x0($a2)
/* 173114 8024A6F4 948205F2 */  lhu        $v0, 0x5F2($a0)
/* 173118 8024A6F8 00021400 */  sll        $v0, $v0, 16
/* 17311C 8024A6FC 00021C03 */  sra        $v1, $v0, 16
/* 173120 8024A700 000217C2 */  srl        $v0, $v0, 31
/* 173124 8024A704 00621821 */  addu       $v1, $v1, $v0
/* 173128 8024A708 00032843 */  sra        $a1, $v1, 1
/* 17312C 8024A70C 808305E3 */  lb         $v1, 0x5E3($a0)
/* 173130 8024A710 2402FFFF */  addiu      $v0, $zero, -0x1
/* 173134 8024A714 1062000B */  beq        $v1, $v0, .Lfilemenu_8024A744
/* 173138 8024A718 248605EE */   addiu     $a2, $a0, 0x5EE
/* 17313C 8024A71C 00031140 */  sll        $v0, $v1, 5
/* 173140 8024A720 00441021 */  addu       $v0, $v0, $a0
/* 173144 8024A724 94420012 */  lhu        $v0, 0x12($v0)
/* 173148 8024A728 00021400 */  sll        $v0, $v0, 16
/* 17314C 8024A72C 00021C03 */  sra        $v1, $v0, 16
/* 173150 8024A730 000217C2 */  srl        $v0, $v0, 31
/* 173154 8024A734 00621821 */  addu       $v1, $v1, $v0
/* 173158 8024A738 00031843 */  sra        $v1, $v1, 1
/* 17315C 8024A73C 080929D3 */  j          .Lfilemenu_8024A74C
/* 173160 8024A740 00651023 */   subu      $v0, $v1, $a1
.Lfilemenu_8024A744:
/* 173164 8024A744 24020078 */  addiu      $v0, $zero, 0x78
/* 173168 8024A748 00451023 */  subu       $v0, $v0, $a1
.Lfilemenu_8024A74C:
/* 17316C 8024A74C 2404002F */  addiu      $a0, $zero, 0x2F
/* 173170 8024A750 24050001 */  addiu      $a1, $zero, 0x1
/* 173174 8024A754 0C051A8B */  jal        set_window_update
/* 173178 8024A758 A4C20000 */   sh        $v0, 0x0($a2)
/* 17317C 8024A75C 24040032 */  addiu      $a0, $zero, 0x32
/* 173180 8024A760 0C051A8B */  jal        set_window_update
/* 173184 8024A764 24050002 */   addiu     $a1, $zero, 0x2
/* 173188 8024A768 3C118025 */  lui        $s1, %hi(filemenu_loadedFileIdx)
/* 17318C 8024A76C 26311754 */  addiu      $s1, $s1, %lo(filemenu_loadedFileIdx)
/* 173190 8024A770 0C00ACD3 */  jal        fio_load_game
/* 173194 8024A774 8E240000 */   lw        $a0, 0x0($s1)
/* 173198 8024A778 10400070 */  beqz       $v0, .Lfilemenu_8024A93C
/* 17319C 8024A77C 00000000 */   nop
/* 1731A0 8024A780 3C108025 */  lui        $s0, 0x8025
/* 1731A4 8024A784 26101740 */  addiu      $s0, $s0, (0x80251740 & 0xFFFF)
/* 1731A8 8024A788 3C068007 */  lui        $a2, %hi(gSaveSlotMetadata)
/* 1731AC 8024A78C 24C63D14 */  addiu      $a2, $a2, %lo(gSaveSlotMetadata)
/* 1731B0 8024A790 8E040000 */  lw         $a0, 0x0($s0)
/* 1731B4 8024A794 8E250000 */  lw         $a1, 0x0($s1)
/* 1731B8 8024A798 0080102D */  daddu      $v0, $a0, $zero
/* 1731BC 8024A79C 00041840 */  sll        $v1, $a0, 1
/* 1731C0 8024A7A0 00621821 */  addu       $v1, $v1, $v0
/* 1731C4 8024A7A4 000318C0 */  sll        $v1, $v1, 3
/* 1731C8 8024A7A8 00661821 */  addu       $v1, $v1, $a2
/* 1731CC 8024A7AC 00051040 */  sll        $v0, $a1, 1
/* 1731D0 8024A7B0 00451021 */  addu       $v0, $v0, $a1
/* 1731D4 8024A7B4 000210C0 */  sll        $v0, $v0, 3
/* 1731D8 8024A7B8 00461021 */  addu       $v0, $v0, $a2
/* 1731DC 8024A7BC 8C480000 */  lw         $t0, 0x0($v0)
/* 1731E0 8024A7C0 8C490004 */  lw         $t1, 0x4($v0)
/* 1731E4 8024A7C4 8C4A0008 */  lw         $t2, 0x8($v0)
/* 1731E8 8024A7C8 8C4B000C */  lw         $t3, 0xC($v0)
/* 1731EC 8024A7CC AC680000 */  sw         $t0, 0x0($v1)
/* 1731F0 8024A7D0 AC690004 */  sw         $t1, 0x4($v1)
/* 1731F4 8024A7D4 AC6A0008 */  sw         $t2, 0x8($v1)
/* 1731F8 8024A7D8 AC6B000C */  sw         $t3, 0xC($v1)
/* 1731FC 8024A7DC 8C480010 */  lw         $t0, 0x10($v0)
/* 173200 8024A7E0 8C490014 */  lw         $t1, 0x14($v0)
/* 173204 8024A7E4 AC680010 */  sw         $t0, 0x10($v1)
/* 173208 8024A7E8 0C00AD07 */  jal        fio_save_game
/* 17320C 8024A7EC AC690014 */   sw        $t1, 0x14($v1)
/* 173210 8024A7F0 8E030000 */  lw         $v1, 0x0($s0)
/* 173214 8024A7F4 24020001 */  addiu      $v0, $zero, 0x1
/* 173218 8024A7F8 3C018007 */  lui        $at, %hi(gSaveSlotHasData)
/* 17321C 8024A7FC 00230821 */  addu       $at, $at, $v1
/* 173220 8024A800 A0223D74 */  sb         $v0, %lo(gSaveSlotHasData)($at)
/* 173224 8024A804 08092A4F */  j          .Lfilemenu_8024A93C
/* 173228 8024A808 00000000 */   nop
.Lfilemenu_8024A80C:
/* 17322C 8024A80C 0C052219 */  jal        sfx_play_sound
/* 173230 8024A810 240400C9 */   addiu     $a0, $zero, 0xC9
/* 173234 8024A814 3C058024 */  lui        $a1, %hi(filemenu_update_show_name_confirm)
/* 173238 8024A818 24A57BDC */  addiu      $a1, $a1, %lo(filemenu_update_show_name_confirm)
/* 17323C 8024A81C 0C051A8B */  jal        set_window_update
/* 173240 8024A820 24040032 */   addiu     $a0, $zero, 0x32
/* 173244 8024A824 3C048016 */  lui        $a0, %hi(gWindows)
/* 173248 8024A828 24848910 */  addiu      $a0, $a0, %lo(gWindows)
/* 17324C 8024A82C 24020079 */  addiu      $v0, $zero, 0x79
/* 173250 8024A830 A482064E */  sh         $v0, 0x64E($a0)
/* 173254 8024A834 24020045 */  addiu      $v0, $zero, 0x45
/* 173258 8024A838 A4820650 */  sh         $v0, 0x650($a0)
/* 17325C 8024A83C 2402002C */  addiu      $v0, $zero, 0x2C
/* 173260 8024A840 80830643 */  lb         $v1, 0x643($a0)
/* 173264 8024A844 A4820652 */  sh         $v0, 0x652($a0)
/* 173268 8024A848 2402FFFF */  addiu      $v0, $zero, -0x1
/* 17326C 8024A84C 1062000B */  beq        $v1, $v0, .Lfilemenu_8024A87C
/* 173270 8024A850 2485064C */   addiu     $a1, $a0, 0x64C
/* 173274 8024A854 00031140 */  sll        $v0, $v1, 5
/* 173278 8024A858 00441021 */  addu       $v0, $v0, $a0
/* 17327C 8024A85C 94420010 */  lhu        $v0, 0x10($v0)
/* 173280 8024A860 00021400 */  sll        $v0, $v0, 16
/* 173284 8024A864 00021C03 */  sra        $v1, $v0, 16
/* 173288 8024A868 000217C2 */  srl        $v0, $v0, 31
/* 17328C 8024A86C 00621821 */  addu       $v1, $v1, $v0
/* 173290 8024A870 00031843 */  sra        $v1, $v1, 1
/* 173294 8024A874 08092A20 */  j          .Lfilemenu_8024A880
/* 173298 8024A878 2463FFDE */   addiu     $v1, $v1, -0x22
.Lfilemenu_8024A87C:
/* 17329C 8024A87C 2403007E */  addiu      $v1, $zero, 0x7E
.Lfilemenu_8024A880:
/* 1732A0 8024A880 3C028015 */  lui        $v0, %hi(gCurrentLanguage)
/* 1732A4 8024A884 8C42AE4C */  lw         $v0, %lo(gCurrentLanguage)($v0)
/* 1732A8 8024A888 3C048016 */  lui        $a0, %hi(gWindows)
/* 1732AC 8024A88C 24848910 */  addiu      $a0, $a0, %lo(gWindows)
/* 1732B0 8024A890 A4A30000 */  sh         $v1, 0x0($a1)
/* 1732B4 8024A894 2403FFD5 */  addiu      $v1, $zero, -0x2B
/* 1732B8 8024A898 A48305CE */  sh         $v1, 0x5CE($a0)
/* 1732BC 8024A89C 24030027 */  addiu      $v1, $zero, 0x27
/* 1732C0 8024A8A0 00021040 */  sll        $v0, $v0, 1
/* 1732C4 8024A8A4 3C018025 */  lui        $at, %hi(D_filemenu_80250940)
/* 1732C8 8024A8A8 00220821 */  addu       $at, $at, $v0
/* 1732CC 8024A8AC 94220940 */  lhu        $v0, %lo(D_filemenu_80250940)($at)
/* 1732D0 8024A8B0 A48305D2 */  sh         $v1, 0x5D2($a0)
/* 1732D4 8024A8B4 A48205D0 */  sh         $v0, 0x5D0($a0)
/* 1732D8 8024A8B8 00021400 */  sll        $v0, $v0, 16
/* 1732DC 8024A8BC 00021C03 */  sra        $v1, $v0, 16
/* 1732E0 8024A8C0 000217C2 */  srl        $v0, $v0, 31
/* 1732E4 8024A8C4 00621821 */  addu       $v1, $v1, $v0
/* 1732E8 8024A8C8 00032843 */  sra        $a1, $v1, 1
/* 1732EC 8024A8CC 808305C3 */  lb         $v1, 0x5C3($a0)
/* 1732F0 8024A8D0 2402FFFF */  addiu      $v0, $zero, -0x1
/* 1732F4 8024A8D4 1062000B */  beq        $v1, $v0, .Lfilemenu_8024A904
/* 1732F8 8024A8D8 248705CC */   addiu     $a3, $a0, 0x5CC
/* 1732FC 8024A8DC 00031140 */  sll        $v0, $v1, 5
/* 173300 8024A8E0 00441021 */  addu       $v0, $v0, $a0
/* 173304 8024A8E4 94420010 */  lhu        $v0, 0x10($v0)
/* 173308 8024A8E8 00021400 */  sll        $v0, $v0, 16
/* 17330C 8024A8EC 00021C03 */  sra        $v1, $v0, 16
/* 173310 8024A8F0 000217C2 */  srl        $v0, $v0, 31
/* 173314 8024A8F4 00621821 */  addu       $v1, $v1, $v0
/* 173318 8024A8F8 00031843 */  sra        $v1, $v1, 1
/* 17331C 8024A8FC 08092A43 */  j          .Lfilemenu_8024A90C
/* 173320 8024A900 00651023 */   subu      $v0, $v1, $a1
.Lfilemenu_8024A904:
/* 173324 8024A904 240200A0 */  addiu      $v0, $zero, 0xA0
/* 173328 8024A908 00451023 */  subu       $v0, $v0, $a1
.Lfilemenu_8024A90C:
/* 17332C 8024A90C 0000282D */  daddu      $a1, $zero, $zero
/* 173330 8024A910 24060001 */  addiu      $a2, $zero, 0x1
/* 173334 8024A914 A4E20000 */  sh         $v0, 0x0($a3)
/* 173338 8024A918 3C048025 */  lui        $a0, %hi(filemenu_menus+0x4)
/* 17333C 8024A91C 8C84E988 */  lw         $a0, %lo(filemenu_menus+0x4)($a0)
/* 173340 8024A920 00C0102D */  daddu      $v0, $a2, $zero
/* 173344 8024A924 3C018025 */  lui        $at, %hi(filemenu_currentMenu)
/* 173348 8024A928 A0221758 */  sb         $v0, %lo(filemenu_currentMenu)($at)
/* 17334C 8024A92C 24020002 */  addiu      $v0, $zero, 0x2
.Lfilemenu_8024A930:
/* 173350 8024A930 A0820004 */  sb         $v0, 0x4($a0)
.Lfilemenu_8024A934:
/* 173354 8024A934 0C091B29 */  jal        filemenu_set_selected
/* 173358 8024A938 00000000 */   nop
.Lfilemenu_8024A93C:
/* 17335C 8024A93C 3C028025 */  lui        $v0, %hi(filemenu_pressedButtons)
/* 173360 8024A940 8C421744 */  lw         $v0, %lo(filemenu_pressedButtons)($v0)
/* 173364 8024A944 30424000 */  andi       $v0, $v0, 0x4000
/* 173368 8024A948 10400081 */  beqz       $v0, .Lfilemenu_8024AB50
/* 17336C 8024A94C 00000000 */   nop
/* 173370 8024A950 82620004 */  lb         $v0, 0x4($s3)
/* 173374 8024A954 14400003 */  bnez       $v0, .Lfilemenu_8024A964
/* 173378 8024A958 0260202D */   daddu     $a0, $s3, $zero
/* 17337C 8024A95C 08092A5E */  j          .Lfilemenu_8024A978
/* 173380 8024A960 24050002 */   addiu     $a1, $zero, 0x2
.Lfilemenu_8024A964:
/* 173384 8024A964 04400006 */  bltz       $v0, .Lfilemenu_8024A980
/* 173388 8024A968 28420004 */   slti      $v0, $v0, 0x4
/* 17338C 8024A96C 10400004 */  beqz       $v0, .Lfilemenu_8024A980
/* 173390 8024A970 0260202D */   daddu     $a0, $s3, $zero
/* 173394 8024A974 24050001 */  addiu      $a1, $zero, 0x1
.Lfilemenu_8024A978:
/* 173398 8024A978 0C091B29 */  jal        filemenu_set_selected
/* 17339C 8024A97C 24060002 */   addiu     $a2, $zero, 0x2
.Lfilemenu_8024A980:
/* 1733A0 8024A980 82630004 */  lb         $v1, 0x4($s3)
/* 1733A4 8024A984 24020001 */  addiu      $v0, $zero, 0x1
/* 1733A8 8024A988 10620037 */  beq        $v1, $v0, .Lfilemenu_8024AA68
/* 1733AC 8024A98C 28620002 */   slti      $v0, $v1, 0x2
/* 1733B0 8024A990 10400005 */  beqz       $v0, .Lfilemenu_8024A9A8
/* 1733B4 8024A994 24040002 */   addiu     $a0, $zero, 0x2
/* 1733B8 8024A998 10600009 */  beqz       $v1, .Lfilemenu_8024A9C0
/* 1733BC 8024A99C 24040033 */   addiu     $a0, $zero, 0x33
/* 1733C0 8024A9A0 08092AD4 */  j          .Lfilemenu_8024AB50
/* 1733C4 8024A9A4 00000000 */   nop
.Lfilemenu_8024A9A8:
/* 1733C8 8024A9A8 10640046 */  beq        $v1, $a0, .Lfilemenu_8024AAC4
/* 1733CC 8024A9AC 24020003 */   addiu     $v0, $zero, 0x3
/* 1733D0 8024A9B0 5062005B */  beql       $v1, $v0, .Lfilemenu_8024AB20
/* 1733D4 8024A9B4 A2640004 */   sb        $a0, 0x4($s3)
/* 1733D8 8024A9B8 08092AD4 */  j          .Lfilemenu_8024AB50
/* 1733DC 8024A9BC 00000000 */   nop
.Lfilemenu_8024A9C0:
/* 1733E0 8024A9C0 3C128024 */  lui        $s2, %hi(filemenu_update_hidden_options_left)
/* 1733E4 8024A9C4 2652759C */  addiu      $s2, $s2, %lo(filemenu_update_hidden_options_left)
/* 1733E8 8024A9C8 0C051A8B */  jal        set_window_update
/* 1733EC 8024A9CC 0240282D */   daddu     $a1, $s2, $zero
/* 1733F0 8024A9D0 24040034 */  addiu      $a0, $zero, 0x34
/* 1733F4 8024A9D4 3C118024 */  lui        $s1, %hi(filemenu_update_hidden_options_right)
/* 1733F8 8024A9D8 26317600 */  addiu      $s1, $s1, %lo(filemenu_update_hidden_options_right)
/* 1733FC 8024A9DC 0C051A8B */  jal        set_window_update
/* 173400 8024A9E0 0220282D */   daddu     $a1, $s1, $zero
/* 173404 8024A9E4 24040035 */  addiu      $a0, $zero, 0x35
/* 173408 8024A9E8 3C108024 */  lui        $s0, %hi(filemenu_update_hidden_options_bottom)
/* 17340C 8024A9EC 261076C8 */  addiu      $s0, $s0, %lo(filemenu_update_hidden_options_bottom)
/* 173410 8024A9F0 0C051A8B */  jal        set_window_update
/* 173414 8024A9F4 0200282D */   daddu     $a1, $s0, $zero
/* 173418 8024A9F8 24040036 */  addiu      $a0, $zero, 0x36
/* 17341C 8024A9FC 0C051A8B */  jal        set_window_update
/* 173420 8024AA00 0200282D */   daddu     $a1, $s0, $zero
/* 173424 8024AA04 24040037 */  addiu      $a0, $zero, 0x37
/* 173428 8024AA08 0C051A8B */  jal        set_window_update
/* 17342C 8024AA0C 0200282D */   daddu     $a1, $s0, $zero
/* 173430 8024AA10 24040038 */  addiu      $a0, $zero, 0x38
/* 173434 8024AA14 0C051A8B */  jal        set_window_update
/* 173438 8024AA18 0240282D */   daddu     $a1, $s2, $zero
/* 17343C 8024AA1C 24040039 */  addiu      $a0, $zero, 0x39
/* 173440 8024AA20 0C051A8B */  jal        set_window_update
/* 173444 8024AA24 0220282D */   daddu     $a1, $s1, $zero
/* 173448 8024AA28 2404003A */  addiu      $a0, $zero, 0x3A
/* 17344C 8024AA2C 0C051A8B */  jal        set_window_update
/* 173450 8024AA30 0240282D */   daddu     $a1, $s2, $zero
/* 173454 8024AA34 2404003B */  addiu      $a0, $zero, 0x3B
/* 173458 8024AA38 0C051A8B */  jal        set_window_update
/* 17345C 8024AA3C 0220282D */   daddu     $a1, $s1, $zero
/* 173460 8024AA40 3C058024 */  lui        $a1, %hi(filemenu_update_hidden_title)
/* 173464 8024AA44 24A57664 */  addiu      $a1, $a1, %lo(filemenu_update_hidden_title)
/* 173468 8024AA48 0C051A8B */  jal        set_window_update
/* 17346C 8024AA4C 2404002D */   addiu     $a0, $zero, 0x2D
/* 173470 8024AA50 0C052219 */  jal        sfx_play_sound
/* 173474 8024AA54 240400D6 */   addiu     $a0, $zero, 0xD6
/* 173478 8024AA58 0C00CE04 */  jal        set_game_mode
/* 17347C 8024AA5C 2404000F */   addiu     $a0, $zero, 0xF
/* 173480 8024AA60 08092AD4 */  j          .Lfilemenu_8024AB50
/* 173484 8024AA64 00000000 */   nop
.Lfilemenu_8024AA68:
/* 173488 8024AA68 A2600004 */  sb         $zero, 0x4($s3)
/* 17348C 8024AA6C 0260202D */  daddu      $a0, $s3, $zero
/* 173490 8024AA70 0000282D */  daddu      $a1, $zero, $zero
/* 173494 8024AA74 0C091B29 */  jal        filemenu_set_selected
/* 173498 8024AA78 24060002 */   addiu     $a2, $zero, 0x2
/* 17349C 8024AA7C 3C058024 */  lui        $a1, %hi(filemenu_update_show_options_left)
/* 1734A0 8024AA80 24A57304 */  addiu      $a1, $a1, %lo(filemenu_update_show_options_left)
/* 1734A4 8024AA84 0C051A8B */  jal        set_window_update
/* 1734A8 8024AA88 24040033 */   addiu     $a0, $zero, 0x33
/* 1734AC 8024AA8C 3C058024 */  lui        $a1, %hi(filemenu_update_show_options_right)
/* 1734B0 8024AA90 24A57378 */  addiu      $a1, $a1, %lo(filemenu_update_show_options_right)
/* 1734B4 8024AA94 0C051A8B */  jal        set_window_update
/* 1734B8 8024AA98 24040034 */   addiu     $a0, $zero, 0x34
/* 1734BC 8024AA9C 24040035 */  addiu      $a0, $zero, 0x35
/* 1734C0 8024AAA0 3C108024 */  lui        $s0, %hi(filemenu_update_show_options_bottom)
/* 1734C4 8024AAA4 261073EC */  addiu      $s0, $s0, %lo(filemenu_update_show_options_bottom)
/* 1734C8 8024AAA8 0C051A8B */  jal        set_window_update
/* 1734CC 8024AAAC 0200282D */   daddu     $a1, $s0, $zero
/* 1734D0 8024AAB0 24040037 */  addiu      $a0, $zero, 0x37
/* 1734D4 8024AAB4 0C051A8B */  jal        set_window_update
/* 1734D8 8024AAB8 0200282D */   daddu     $a1, $s0, $zero
/* 1734DC 8024AABC 08092AD2 */  j          .Lfilemenu_8024AB48
/* 1734E0 8024AAC0 00000000 */   nop
.Lfilemenu_8024AAC4:
/* 1734E4 8024AAC4 A2600004 */  sb         $zero, 0x4($s3)
/* 1734E8 8024AAC8 0260202D */  daddu      $a0, $s3, $zero
/* 1734EC 8024AACC 24050001 */  addiu      $a1, $zero, 0x1
/* 1734F0 8024AAD0 0C091B29 */  jal        filemenu_set_selected
/* 1734F4 8024AAD4 24060002 */   addiu     $a2, $zero, 0x2
/* 1734F8 8024AAD8 3C058024 */  lui        $a1, %hi(filemenu_update_show_options_left)
/* 1734FC 8024AADC 24A57304 */  addiu      $a1, $a1, %lo(filemenu_update_show_options_left)
/* 173500 8024AAE0 0C051A8B */  jal        set_window_update
/* 173504 8024AAE4 24040033 */   addiu     $a0, $zero, 0x33
/* 173508 8024AAE8 3C058024 */  lui        $a1, %hi(filemenu_update_show_options_right)
/* 17350C 8024AAEC 24A57378 */  addiu      $a1, $a1, %lo(filemenu_update_show_options_right)
/* 173510 8024AAF0 0C051A8B */  jal        set_window_update
/* 173514 8024AAF4 24040034 */   addiu     $a0, $zero, 0x34
/* 173518 8024AAF8 24040035 */  addiu      $a0, $zero, 0x35
/* 17351C 8024AAFC 3C108024 */  lui        $s0, %hi(filemenu_update_show_options_bottom)
/* 173520 8024AB00 261073EC */  addiu      $s0, $s0, %lo(filemenu_update_show_options_bottom)
/* 173524 8024AB04 0C051A8B */  jal        set_window_update
/* 173528 8024AB08 0200282D */   daddu     $a1, $s0, $zero
/* 17352C 8024AB0C 24040037 */  addiu      $a0, $zero, 0x37
/* 173530 8024AB10 0C051A8B */  jal        set_window_update
/* 173534 8024AB14 0200282D */   daddu     $a1, $s0, $zero
/* 173538 8024AB18 08092AD2 */  j          .Lfilemenu_8024AB48
/* 17353C 8024AB1C 00000000 */   nop
.Lfilemenu_8024AB20:
/* 173540 8024AB20 3C058025 */  lui        $a1, %hi(filemenu_loadedFileIdx)
/* 173544 8024AB24 8CA51754 */  lw         $a1, %lo(filemenu_loadedFileIdx)($a1)
/* 173548 8024AB28 0260202D */  daddu      $a0, $s3, $zero
/* 17354C 8024AB2C 000537C2 */  srl        $a2, $a1, 31
/* 173550 8024AB30 00A63021 */  addu       $a2, $a1, $a2
/* 173554 8024AB34 00063043 */  sra        $a2, $a2, 1
/* 173558 8024AB38 00061040 */  sll        $v0, $a2, 1
/* 17355C 8024AB3C 00A22823 */  subu       $a1, $a1, $v0
/* 173560 8024AB40 0C091B29 */  jal        filemenu_set_selected
/* 173564 8024AB44 00052840 */   sll       $a1, $a1, 1
.Lfilemenu_8024AB48:
/* 173568 8024AB48 0C052219 */  jal        sfx_play_sound
/* 17356C 8024AB4C 240400CA */   addiu     $a0, $zero, 0xCA
.Lfilemenu_8024AB50:
/* 173570 8024AB50 3C048016 */  lui        $a0, %hi(gWindows)
/* 173574 8024AB54 24848910 */  addiu      $a0, $a0, %lo(gWindows)
/* 173578 8024AB58 82620004 */  lb         $v0, 0x4($s3)
/* 17357C 8024AB5C 3C038015 */  lui        $v1, %hi(gCurrentLanguage)
/* 173580 8024AB60 8C63AE4C */  lw         $v1, %lo(gCurrentLanguage)($v1)
/* 173584 8024AB64 00021080 */  sll        $v0, $v0, 2
/* 173588 8024AB68 00621821 */  addu       $v1, $v1, $v0
/* 17358C 8024AB6C 3C028025 */  lui        $v0, %hi(D_filemenu_80250910)
/* 173590 8024AB70 00431021 */  addu       $v0, $v0, $v1
/* 173594 8024AB74 90420910 */  lbu        $v0, %lo(D_filemenu_80250910)($v0)
/* 173598 8024AB78 808305A3 */  lb         $v1, 0x5A3($a0)
/* 17359C 8024AB7C 00022842 */  srl        $a1, $v0, 1
/* 1735A0 8024AB80 A48205B0 */  sh         $v0, 0x5B0($a0)
/* 1735A4 8024AB84 2402FFFF */  addiu      $v0, $zero, -0x1
/* 1735A8 8024AB88 1062000B */  beq        $v1, $v0, .Lfilemenu_8024ABB8
/* 1735AC 8024AB8C 248605AC */   addiu     $a2, $a0, 0x5AC
/* 1735B0 8024AB90 00031140 */  sll        $v0, $v1, 5
/* 1735B4 8024AB94 00441021 */  addu       $v0, $v0, $a0
/* 1735B8 8024AB98 94420010 */  lhu        $v0, 0x10($v0)
/* 1735BC 8024AB9C 00021400 */  sll        $v0, $v0, 16
/* 1735C0 8024ABA0 00021C03 */  sra        $v1, $v0, 16
/* 1735C4 8024ABA4 000217C2 */  srl        $v0, $v0, 31
/* 1735C8 8024ABA8 00621821 */  addu       $v1, $v1, $v0
/* 1735CC 8024ABAC 00031843 */  sra        $v1, $v1, 1
/* 1735D0 8024ABB0 08092AF0 */  j          .Lfilemenu_8024ABC0
/* 1735D4 8024ABB4 00651023 */   subu      $v0, $v1, $a1
.Lfilemenu_8024ABB8:
/* 1735D8 8024ABB8 240200A0 */  addiu      $v0, $zero, 0xA0
/* 1735DC 8024ABBC 00451023 */  subu       $v0, $v0, $a1
.Lfilemenu_8024ABC0:
/* 1735E0 8024ABC0 A4C20000 */  sh         $v0, 0x0($a2)
/* 1735E4 8024ABC4 8FBF0020 */  lw         $ra, 0x20($sp)
/* 1735E8 8024ABC8 8FB3001C */  lw         $s3, 0x1C($sp)
/* 1735EC 8024ABCC 8FB20018 */  lw         $s2, 0x18($sp)
/* 1735F0 8024ABD0 8FB10014 */  lw         $s1, 0x14($sp)
/* 1735F4 8024ABD4 8FB00010 */  lw         $s0, 0x10($sp)
/* 1735F8 8024ABD8 03E00008 */  jr         $ra
/* 1735FC 8024ABDC 27BD0028 */   addiu     $sp, $sp, 0x28
