.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel kkj_19_GetItemNameRaw
/* B6435C 80240B8C 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* B64360 80240B90 AFB10014 */  sw         $s1, 0x14($sp)
/* B64364 80240B94 0080882D */  daddu      $s1, $a0, $zero
/* B64368 80240B98 AFBF0018 */  sw         $ra, 0x18($sp)
/* B6436C 80240B9C AFB00010 */  sw         $s0, 0x10($sp)
/* B64370 80240BA0 8E22000C */  lw         $v0, 0xC($s1)
/* B64374 80240BA4 8C500000 */  lw         $s0, 0x0($v0)
/* B64378 80240BA8 0C0B2AAF */  jal        evt_get_variable
/* B6437C 80240BAC 0200282D */   daddu     $a1, $s0, $zero
/* B64380 80240BB0 0040282D */  daddu      $a1, $v0, $zero
/* B64384 80240BB4 0000202D */  daddu      $a0, $zero, $zero
/* B64388 80240BB8 3C038024 */  lui        $v1, %hi(kkj_19_BakingIngredientsNames)
/* B6438C 80240BBC 24631E50 */  addiu      $v1, $v1, %lo(kkj_19_BakingIngredientsNames)
.LPAL_80240BC0:
/* B64390 80240BC0 8C620000 */  lw         $v0, 0x0($v1)
/* B64394 80240BC4 14A20007 */  bne        $a1, $v0, .LPAL_80240BE4
/* B64398 80240BC8 24840001 */   addiu     $a0, $a0, 0x1
/* B6439C 80240BCC 0220202D */  daddu      $a0, $s1, $zero
/* B643A0 80240BD0 8C660004 */  lw         $a2, 0x4($v1)
/* B643A4 80240BD4 0C0B2C26 */  jal        evt_set_variable
/* B643A8 80240BD8 0200282D */   daddu     $a1, $s0, $zero
/* B643AC 80240BDC 080902FC */  j          .LPAL_80240BF0
/* B643B0 80240BE0 00000000 */   nop
.LPAL_80240BE4:
/* B643B4 80240BE4 2882000A */  slti       $v0, $a0, 0xA
/* B643B8 80240BE8 1440FFF5 */  bnez       $v0, .LPAL_80240BC0
/* B643BC 80240BEC 24630008 */   addiu     $v1, $v1, 0x8
.LPAL_80240BF0:
/* B643C0 80240BF0 8FBF0018 */  lw         $ra, 0x18($sp)
/* B643C4 80240BF4 8FB10014 */  lw         $s1, 0x14($sp)
/* B643C8 80240BF8 8FB00010 */  lw         $s0, 0x10($sp)
/* B643CC 80240BFC 24020002 */  addiu      $v0, $zero, 0x2
/* B643D0 80240C00 03E00008 */  jr         $ra
/* B643D4 80240C04 27BD0020 */   addiu     $sp, $sp, 0x20
