.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.11.1 */

# Handwritten function
glabel __osGetSR
/* 47A50 8006C650 40026000 */  mfc0      $v0, $12 # handwritten instruction
/* 47A54 8006C654 03E00008 */  jr        $ra
/* 47A58 8006C658 00000000 */   nop
/* 47A5C 8006C65C 00000000 */  nop
