.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.11.1 */

glabel func_JP_8006CB90
/* 47F90 8006CB90 00000000 */  nop
/* 47F94 8006CB94 00000000 */  nop
/* 47F98 8006CB98 00000000 */  nop
/* 47F9C 8006CB9C 00000000 */  nop
