.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel create_status_icon_danger
/* 23AD8 800486D8 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 23ADC 800486DC 00041040 */  sll        $v0, $a0, 1
/* 23AE0 800486E0 00441021 */  addu       $v0, $v0, $a0
/* 23AE4 800486E4 00021080 */  sll        $v0, $v0, 2
/* 23AE8 800486E8 00441023 */  subu       $v0, $v0, $a0
/* 23AEC 800486EC 3C03800A */  lui        $v1, %hi(D_800A0F44)
/* 23AF0 800486F0 8C63F6B4 */  lw         $v1, %lo(D_800A0F44)($v1)
/* 23AF4 800486F4 00021100 */  sll        $v0, $v0, 4
/* 23AF8 800486F8 AFBF0018 */  sw         $ra, 0x18($sp)
/* 23AFC 800486FC AFB10014 */  sw         $s1, 0x14($sp)
/* 23B00 80048700 AFB00010 */  sw         $s0, 0x10($sp)
/* 23B04 80048704 00628821 */  addu       $s1, $v1, $v0
/* 23B08 80048708 2403F7FF */  addiu      $v1, $zero, -0x801
/* 23B0C 8004870C 8E220000 */  lw         $v0, 0x0($s1)
/* 23B10 80048710 822400A8 */  lb         $a0, 0xA8($s1)
/* 23B14 80048714 00431024 */  and        $v0, $v0, $v1
/* 23B18 80048718 1480002C */  bnez       $a0, .LPAL_800487CC
/* 23B1C 8004871C AE220000 */   sw        $v0, 0x0($s1)
/* 23B20 80048720 24020001 */  addiu      $v0, $zero, 0x1
/* 23B24 80048724 A22200A8 */  sb         $v0, 0xA8($s1)
/* 23B28 80048728 3C038015 */  lui        $v1, %hi(gCurrentLanguage)
/* 23B2C 8004872C 8C63AE4C */  lw         $v1, %lo(gCurrentLanguage)($v1)
/* 23B30 80048730 24020001 */  addiu      $v0, $zero, 0x1
/* 23B34 80048734 10620011 */  beq        $v1, $v0, .LPAL_8004877C
/* 23B38 80048738 28620002 */   slti      $v0, $v1, 0x2
/* 23B3C 8004873C 10400005 */  beqz       $v0, .LPAL_80048754
/* 23B40 80048740 24020002 */   addiu     $v0, $zero, 0x2
/* 23B44 80048744 10600009 */  beqz       $v1, .LPAL_8004876C
/* 23B48 80048748 0200202D */   daddu     $a0, $s0, $zero
/* 23B4C 8004874C 080121ED */  j          .LPAL_800487B4
/* 23B50 80048750 00000000 */   nop
.LPAL_80048754:
/* 23B54 80048754 1062000D */  beq        $v1, $v0, .LPAL_8004878C
/* 23B58 80048758 24020003 */   addiu     $v0, $zero, 0x3
/* 23B5C 8004875C 1062000F */  beq        $v1, $v0, .LPAL_8004879C
/* 23B60 80048760 0200202D */   daddu     $a0, $s0, $zero
/* 23B64 80048764 080121ED */  j          .LPAL_800487B4
/* 23B68 80048768 00000000 */   nop
.LPAL_8004876C:
/* 23B6C 8004876C 3C048010 */  lui        $a0, %hi(D_PAL_80107214)
/* 23B70 80048770 24847214 */  addiu      $a0, $a0, %lo(D_PAL_80107214)
/* 23B74 80048774 080121E9 */  j          .LPAL_800487A4
/* 23B78 80048778 00000000 */   nop
.LPAL_8004877C:
/* 23B7C 8004877C 3C048010 */  lui        $a0, %hi(D_PAL_8010734C)
/* 23B80 80048780 2484734C */  addiu      $a0, $a0, %lo(D_PAL_8010734C)
/* 23B84 80048784 080121E9 */  j          .LPAL_800487A4
/* 23B88 80048788 00000000 */   nop
.LPAL_8004878C:
/* 23B8C 8004878C 3C048010 */  lui        $a0, %hi(D_PAL_80107484)
/* 23B90 80048790 24847484 */  addiu      $a0, $a0, %lo(D_PAL_80107484)
/* 23B94 80048794 080121E9 */  j          .LPAL_800487A4
/* 23B98 80048798 00000000 */   nop
.LPAL_8004879C:
/* 23B9C 8004879C 3C048010 */  lui        $a0, %hi(D_PAL_801075BC)
/* 23BA0 800487A0 248475BC */  addiu      $a0, $a0, %lo(D_PAL_801075BC)
.LPAL_800487A4:
/* 23BA4 800487A4 0C050015 */  jal        hud_element_create
/* 23BA8 800487A8 00000000 */   nop
/* 23BAC 800487AC 0040802D */  daddu      $s0, $v0, $zero
/* 23BB0 800487B0 0200202D */  daddu      $a0, $s0, $zero
.LPAL_800487B4:
/* 23BB4 800487B4 0C050D6C */  jal        hud_element_set_flags
/* 23BB8 800487B8 24050002 */   addiu     $a1, $zero, 0x2
/* 23BBC 800487BC 0200202D */  daddu      $a0, $s0, $zero
/* 23BC0 800487C0 0C050D6C */  jal        hud_element_set_flags
/* 23BC4 800487C4 24050080 */   addiu     $a1, $zero, 0x80
/* 23BC8 800487C8 AE3000AC */  sw         $s0, 0xAC($s1)
.LPAL_800487CC:
/* 23BCC 800487CC 8FBF0018 */  lw         $ra, 0x18($sp)
/* 23BD0 800487D0 8FB10014 */  lw         $s1, 0x14($sp)
/* 23BD4 800487D4 8FB00010 */  lw         $s0, 0x10($sp)
/* 23BD8 800487D8 03E00008 */  jr         $ra
/* 23BDC 800487DC 27BD0020 */   addiu     $sp, $sp, 0x20
