#pragma _permuter latedefine start
#pragma _permuter latedefine end
typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned long u32;
typedef signed char s8;
typedef short s16;
typedef long s32;
typedef float f32;
typedef struct _PermuterTemp1 Vtx_tn;
extern float sqrtf(float value);
#pragma intrinsic(sqrtf);
typedef s32 Bytecode;
typedef s32 ApiStatus;
struct Evt;
typedef ApiStatus (*ApiFunc)(struct Evt *, s32);
typedef Bytecode EvtSource[0];
typedef struct Vec2b
{
  s8 x;
  s8 y;
} Vec2b;
typedef struct Vec2bu
{
  u8 x;
  u8 y;
} Vec2bu;
typedef struct Vec3f
{
  f32 x;
  f32 y;
  f32 z;
} Vec3f;
typedef struct Vec2s
{
  s16 x;
  s16 y;
} Vec2s;
typedef struct Vec3s
{
  s16 x;
  s16 y;
  s16 z;
} Vec3s;
typedef struct Matrix4s
{
  s16 whole[4][4];
  s16 frac[4][4];
} Matrix4s;
typedef struct BlurBuffer
{
  s8 unk_00;
  s8 index;
  char unk_02[2];
  f32 x[20];
  f32 y[20];
  f32 z[20];
} BlurBuffer;
typedef s16 Palette16[16];
typedef struct Npc
{
  s32 flags;
  void (*onUpdate)(struct Npc *);
  void (*onRender)(struct Npc *);
  f32 yaw;
  f32 planarFlyDist;
  f32 jumpScale;
  f32 moveSpeed;
  f32 jumpVelocity;
  struct BlurBuffer *blurBuf;
  s32 spriteInstanceID;
  union
  {
    u16 h;
    u32 w;
  } currentAnim;
  s32 unk_2C;
  f32 animationSpeed;
  f32 renderYaw;
  Vec3f pos;
  Vec3f rotation;
  f32 rotationVerticalPivotOffset;
  Vec3f scale;
  Vec3f moveToPos;
  Vec3f colliderPos;
  s32 shadowIndex;
  f32 shadowScale;
  s32 unk_80;
  s16 unk_84;
  s16 unk_86;
  s16 isFacingAway;
  s16 yawCamOffset;
  s16 turnAroundYawAdjustment;
  s16 duration;
  Vec3s homePos;
  s16 unk_96;
  s16 unk_98;
  s16 unk_9A;
  s16 unk_9C;
  s16 unk_9E;
  s16 unk_A0;
  u16 unk_A2;
  s8 npcID;
  char unk_A5;
  s16 collisionRadius;
  s16 collisionHeight;
  s8 renderMode;
  s8 unk_AB;
  u8 alpha;
  u8 alpha2;
  char unk_AE[2];
  s32 **extraAnimList;
  s8 unk_B4;
  s8 unk_B5;
  s8 unk_B6;
  s8 unk_B7;
  char unk_B8[8];
  s8 unk_C0;
  s8 paletteCount;
  char unk_C2[2];
  s32 *spritePaletteList;
  Palette16 localPaletteData[16];
  Palette16 *localPalettes[16];
  s16 unk_308;
  s16 unk_30A;
  s16 unk_30C;
  s16 unk_30E;
  s16 unk_310;
  s16 unk_312;
  s16 unk_314;
  s16 unk_316;
  f32 screenSpaceOffset2D[2];
  f32 verticalStretch;
  struct EffectInstance *decorations[2];
  s8 decorationType[2];
  s8 changedDecoration[2];
  s8 decorationInitialised[2];
  s16 decorationUnk[2];
  char unk_336[10];
} Npc;
typedef union
{
  struct
  {
    s16 genericFlagIndex;
    char unk_2;
  } bytes;
  s32 flags;
} TriggerFlags;
typedef struct Trigger
{
  TriggerFlags flags;
  s32 params1;
  s32 params2;
  s32 (*functionHandler)(struct Trigger *);
  EvtSource *scriptSource;
  struct Evt *runningScript;
  s32 priority;
  s32 scriptVars[3];
  s32 unk_28;
  s32 unk_2C;
  u8 unk_30;
  char unk_31[3];
  s32 runningScriptID;
} Trigger;
typedef struct Evt
{
  u8 state;
  u8 currentArgc;
  u8 currentOpcode;
  u8 priority;
  u8 groupFlags;
  s8 blocked;
  s8 loopDepth;
  s8 switchDepth;
  Bytecode *ptrNextLine;
  Bytecode *ptrReadPos;
  s8 labelIndices[16];
  void *labelPositions[16];
  void *userData;
  struct Evt *blockingParent;
  struct Evt *childScript;
  struct Evt *parentScript;
  s32 functionTemp[4];
  ApiFunc callFunction;
  s32 varTable[16];
  s32 varFlags[3];
  s32 loopStartTable[8];
  s32 loopCounterTable[8];
  s8 switchBlockState[8];
  s32 switchBlockValue[8];
  s32 *buffer;
  s32 *array;
  s32 *flagArray;
  s32 id;
  union
  {
    s32 enemyID;
    s32 actorID;
    struct Enemy *enemy;
    struct Actor *actor;
  } owner1;
  union
  {
    s32 npcID;
    s32 triggerID;
    struct Npc *npc;
    struct Trigger *trigger;
  } owner2;
  f32 timeScale;
  f32 frameCounter;
  s32 unk_158;
  Bytecode *ptrFirstLine;
  Bytecode *ptrSavedPosition;
  Bytecode *ptrCurrentLine;
} Evt;
typedef struct BattleStatusUnk BattleStatusUnk;
typedef struct FGModelData FGModelData;
typedef struct BattleStatus
{
  s32 flags1;
  s32 flags2;
  s32 varTable[16];
  u8 currentSubmenu;
  char unk_49[3];
  s8 unk_4C;
  s8 unk_4D;
  s8 unk_4E;
  s8 unk_4F;
  s8 unk_50;
  s8 unk_51;
  s8 unk_52;
  s8 stratsLastCursorPos;
  char unk_54[8];
  s8 unk_5C;
  s8 unk_5D;
  char unk_5E[4];
  s8 unk_62;
  s8 unk_63;
  char unk_64[12];
  s16 unk_70;
  char unk_72[2];
  s32 unk_74;
  u8 totalStarPoints;
  u8 pendingStarPoints;
  u8 incrementStarPointDelay;
  u8 damageTaken;
  u8 changePartnerAllowed;
  char unk_7D[4];
  s8 actionSuccess;
  char unk_82;
  s8 unk_83;
  s8 unk_84;
  s8 unk_85;
  s8 unk_86;
  s8 blockResult;
  u8 itemUsesLeft;
  u8 hpDrainCount;
  s8 unk_8A;
  s8 hustleTurns;
  char unk_8C;
  s8 unk_8D;
  s8 initialEnemyCount;
  char unk_8F[1];
  s16 unk_90;
  s8 unk_92;
  char unk_93;
  s8 unk_94;
  s8 unk_95;
  s8 hammerCharge;
  s8 jumpCharge;
  char unk_98;
  u8 rushesFlags;
  s8 outtaSightActive;
  s8 turboChargeTurnsLeft;
  u8 turboChargeAmount;
  s8 waterBlockTurnsLeft;
  u8 waterBlockAmount;
  char unk_9F;
  s32 *unk_A0;
  s8 cloudNineTurnsLeft;
  u8 cloudNineDodgeChance;
  char unk_A6[2];
  s32 cloudNineEffect;
  char unk_AC;
  s8 unk_AD;
  s8 hammerLossTurns;
  s8 jumpLossTurns;
  s8 itemLossTurns;
  char unk_B1[3];
  void (*preUpdateCallback)(void);
  void (*unk_B8)(void);
  struct Evt *controlScript;
  s32 controlScriptID;
  struct Evt *camMovementScript;
  s32 camMovementScriptID;
  Vec3f unk_CC;
  struct Actor *playerActor;
  struct Actor *partnerActor;
  struct Actor *enemyActors[24];
  s16 enemyIDs[24];
  char unk_170;
  s8 numEnemyActors;
  s16 currentTurnEnemyID;
  struct Actor *currentTurnEnemy;
  s8 moveCategory;
  char unk_179;
  s16 selectedItemID;
  s16 selectedMoveID;
  s16 currentAttackDamage;
  s16 lastAttackDamage;
  char unk_182[2];
  s32 currentTargetListFlags;
  s32 currentAttackElement;
  s32 currentAttackEventSuppression;
  s32 currentAttackStatus;
  u8 statusChance;
  u8 statusDuration;
  char unk_196;
  u8 targetHomeIndex;
  u8 powerBounceCounter;
  s8 wasStatusInflicted;
  u8 unk_19A;
  char unk_19B[5];
  s16 currentTargetID;
  s8 currentTargetPart;
  char unk_1A3;
  s16 currentTargetID2;
  s8 currentTargetPart2;
  s8 battlePhase;
  s16 attackerActorID;
  char unk_1AA[4];
  s16 submenuIcons[24];
  u8 submenuMoves[24];
  u8 submenuEnabled[24];
  u8 submenuMoveCount;
  char unk_20F;
  s32 currentButtonsDown;
  s32 currentButtonsPressed;
  s32 currentButtonsHeld;
  s32 stickX;
  s32 stickY;
  s32 inputBitmask;
  s32 dpadX;
  s32 dpadY;
  s32 holdInputBuffer[64];
  s32 pushInputBuffer[64];
  s8 holdInputBufferPos;
  s8 inputBufferPos;
  s8 unk_432;
  char unk_433;
  s32 *unk_434;
  FGModelData *foregroundModelData;
  BattleStatusUnk *unk_43C;
  u8 tattleFlags[27];
  char unk_45B[5];
} BattleStatus;
typedef struct Shadow
{
  s32 flags;
  u8 listIndex;
  u8 unk_05;
  u8 unk_06;
  char unk_07;
  s16 entityModelID;
  s16 vertexSegment;
  Vtx_tn **vertexArray;
  Vec3f position;
  Vec3f scale;
  Vec3f rotation;
  char unk_34[0x4];
  Matrix4s transformMatrix;
} Shadow;
typedef struct SelectableTarget
{
  s16 actorID;
  s16 partID;
  Vec3s pos;
  char unk_0A[7];
  u8 homeCol;
  u8 homeRow;
  u8 layer;
} SelectableTarget;
typedef struct ActorPartMovement
{
  char unk_00[12];
  Vec3f goalPos;
  char unk_18[12];
  f32 jumpScale;
  f32 moveSpeed;
  char unk_2C[32];
  s32 varTable[16];
} ActorPartMovement;
typedef struct ActorPart
{
  s32 flags;
  s32 targetFlags;
  struct ActorPartDesc *staticData;
  struct ActorPart *nextPart;
  struct ActorPartMovement *movement;
  Vec3s partOffset;
  Vec3s visualOffset;
  Vec3f partOffsetFloat;
  Vec3f absolutePosition;
  Vec3f rotation;
  Vec3s rotationPivotOffset;
  char unk_4A[2];
  Vec3f scale;
  Vec3f currentPos;
  f32 yaw;
  s16 unkOffset[2];
  Vec2s targetOffset;
  s16 unk_70;
  Vec2bu size;
  u8 verticalStretch;
  s8 unk_75;
  s8 unk_76;
  char unk_77[1];
  u32 *defenseTable;
  s32 eventFlags;
  s32 partFlags3;
  s32 unk_84;
  s32 currentAnimation;
  s32 unk_8C;
  f32 animationRate;
  u32 *idleAnimations;
  s16 opacity;
  char unk_9A[2];
  s32 shadowIndex;
  f32 shadowScale;
  s32 partTypeData[6];
  s16 actorTypeData2b[2];
  struct DecorationTable *decorationTable;
} ActorPart;
typedef struct DecorationTable
{
  char unk_00[1729];
  s8 unk_6C1;
  char unk_6C2[11];
  s8 unk_6CD;
  char unk_6CE[6];
  s32 *unk_6D4;
  char unk_6D8[120];
  s8 unk_750;
  s8 unk_751;
  s8 unk_752;
  char unk_753[17];
  s8 unk_764;
  s8 unk_765;
  s8 unk_766;
  s8 unk_767;
  s8 unk_768;
  char unk_769[3];
  s16 unk_76C[16];
  char unk_78C[76];
  s8 unk_7D8;
  s8 unk_7D9;
  char unk_7DA;
  s8 unk_7DB;
  s16 scale[16];
  s16 posX[16];
  s16 posY[16];
  s16 posZ[16];
  u8 rotationPivotOffsetX[16];
  u8 rotationPivotOffsetY[16];
  u8 rotX[16];
  u8 rotY[16];
  u8 rotZ[16];
  u8 effectType;
  char unk_8AD[3];
  struct Temp8025D160 *unk_8B0[2];
  s8 decorationType[2];
  u8 unk_8BA[2];
  u8 unk_8BC[2];
  s16 unk_8C0[6];
  char unk_8BE[30];
} DecorationTable;
typedef struct Encounter
{
  s32 count;
  struct Enemy *enemy[16];
  u16 battle;
  s16 stage;
  s16 encounterID;
  char unk_4C[0x12];
} Encounter;
typedef struct ActorMovement
{
  Vec3f currentPos;
  Vec3f goalPos;
  Vec3f unk_18;
  char unk_24[24];
  f32 acceleration;
  f32 speed;
  f32 velocity;
  f32 angle;
  f32 distance;
} ActorMovement;
typedef struct ChompChainAnimationState ChompChainAnimationState;
typedef struct ActorState
{
  Vec3f currentPos;
  Vec3f goalPos;
  Vec3f unk_18;
  char unk_24[24];
  f32 acceleration;
  f32 speed;
  f32 velocity;
  f32 angle;
  f32 distance;
  f32 bounceDivisor;
  char unk_54[0x4];
  s32 animJumpRise;
  s32 animJumpFall;
  s32 animJumpLand;
  s16 moveTime;
  s16 moveArcAmplitude;
  char unk_68[3];
  u8 jumpPartIndex;
  ChompChainAnimationState *unk_6C;
  char unk_70[12];
  s32 varTable[16];
} ActorState;
typedef struct Actor
{
  s32 flags;
  char unk_04[4];
  struct ActorDesc *staticActorData;
  ActorState state;
  ActorMovement fly;
  f32 flyElapsed;
  char unk_11C[4];
  s16 flyTime;
  s16 flyArcAmplitude;
  char unk_124[17];
  u8 footStepCounter;
  u8 actorType;
  char unk_137;
  Vec3f homePos;
  Vec3f currentPos;
  Vec3s headOffset;
  Vec3s healthBarPosition;
  Vec3f rotation;
  Vec3s rotationPivotOffset;
  char unk_16E[2];
  Vec3f scale;
  Vec3f scaleModifier;
  f32 scalingFactor;
  f32 yaw;
  Vec2bu size;
  s16 actorID;
  s8 unk_194;
  s8 unk_195;
  s8 unk_196;
  s8 unk_197;
  Vec2b unk_198;
  s8 unk_19A;
  char unk_19B[1];
  s32 actorTypeData1[6];
  s16 actorTypeData1b[2];
  s8 currentHP;
  s8 maxHP;
  char unk_1BA[2];
  u8 hpFraction;
  char unk_1BD[3];
  EvtSource *idleScriptSource;
  EvtSource *takeTurnScriptSource;
  EvtSource *onHitScriptSource;
  EvtSource *onTurnChanceScriptSource;
  struct Evt *idleScript;
  struct Evt *takeTurnScript;
  struct Evt *onHitScript;
  struct Evt *onTurnChangeScript;
  s32 idleScriptID;
  s32 takeTurnID;
  s32 onHitID;
  s32 onTurnChangeID;
  s8 lastEventType;
  u8 turnPriority;
  u8 enemyIndex;
  u8 numParts;
  struct ActorPart *partsTable;
  s16 lastDamageTaken;
  u16 hpChangeCounter;
  s16 damageCounter;
  char unk_1FE[2];
  s32 **unk_200;
  char unk_204[3];
  s8 extraCoinBonus;
  s8 unk_208;
  char unk_209[3];
  u32 *statusTable;
  s8 debuff;
  s8 debuffDuration;
  s8 staticStatus;
  s8 staticDuration;
  s8 stoneStatus;
  s8 stoneDuration;
  s8 koStatus;
  s8 koDuration;
  s8 transStatus;
  s8 transDuration;
  char unk_21A[2];
  u8 status;
  char unk_21D[3];
  s8 isGlowing;
  s8 attackBoost;
  s8 defenseBoost;
  s8 chillOutAmount;
  s8 chillOutTurns;
  char unk_225[3];
  struct EffectInstance *unk_228;
  struct SelectableTarget targetData[24];
  s8 targetListLength;
  s8 targetIndexList[24];
  s8 selectedTargetIndex;
  s8 targetPartIndex;
  char unk_427;
  s16 targetActorID;
  char unk_42A[2];
  struct Shadow *shadow;
  f32 shadowScale;
  s16 renderMode;
  s16 hudElementDataIndex;
  s32 x[2];
  struct HudElement *ptrDefuffIcon;
} Actor;
typedef struct EncounterStatus
{
  s32 flags;
  s8 eFirstStrike;
  s8 hitType;
  s8 hitTier;
  char unk_07;
  s8 unk_08;
  s8 battleOutcome;
  s8 unk_0A;
  s8 merleeCoinBonus;
  u8 damageTaken;
  char unk_0D;
  s16 coinsEarned;
  char unk_10;
  u8 allowFleeing;
  s8 unk_12;
  u8 dropWhackaBump;
  s32 songID;
  s32 unk_18;
  s8 numEncounters;
  s8 currentAreaIndex;
  u8 currentMapIndex;
  u8 currentEntryIndex;
  s8 mapID;
  s8 resetMapEncounterFlags;
  char unk_22[2];
  s32 *npcGroupList;
  struct Encounter *encounterList[24];
  struct Encounter *currentEncounter;
  struct Enemy *currentEnemy;
  s32 fadeOutAmount;
  s32 unk_94;
  s32 fadeOutAccel;
  s32 battleStartCountdown;
  char unk_A0[16];
  s32 defeatFlags[60][12];
  s16 recentMaps[2];
  char unk_FB4[4];
} EncounterStatus;
typedef struct Temp8025D160
{
  s32 unk_00;
  char unk_04[8];
  struct Temp8025D160_2 *unk_0C;
} Temp8025D160;
typedef struct Temp8025D160_2
{
  s32 unk_00;
  f32 unk_04;
  f32 unk_08;
  f32 unk_0C;
  char unk_10[12];
  s32 unk_1C;
  s32 unk_20;
  char unk_24[8];
  s32 unk_2C;
  s32 unk_30;
  f32 unk_34;
} Temp8025D160_2;
typedef struct NpcSettings
{
  char unk_00[4];
  s16 height;
  s16 radius;
  void *otherAI;
  EvtSource *onInteract;
  EvtSource *ai;
  EvtSource *onHit;
  EvtSource *aux;
  EvtSource *onDefeat;
  s32 flags;
  char unk_24[4];
  s16 level;
  s16 unk_2A;
} NpcSettings;
typedef struct EnemyDrops EnemyDrops;
typedef union _PermuterTemp2 EnemyTerritory;
typedef struct Enemy
{
  s32 flags;
  s8 encounterIndex;
  s8 encountered;
  u8 scriptGroup;
  s8 unk_07;
  s16 npcID;
  s16 spawnPos[3];
  Vec3s unk_10;
  char unk_16[2];
  struct NpcSettings *npcSettings;
  EvtSource *initBytecode;
  EvtSource *interactBytecode;
  EvtSource *aiBytecode;
  EvtSource *hitBytecode;
  EvtSource *auxBytecode;
  EvtSource *defeatBytecode;
  struct Evt *initScript;
  struct Evt *interactScript;
  struct Evt *aiScript;
  struct Evt *hitScript;
  struct Evt *auxScript;
  struct Evt *defeatScript;
  s32 initScriptID;
  s32 interactScriptID;
  s32 aiScriptID;
  s32 hitScriptID;
  s32 auxScriptID;
  s32 defeatScriptID;
  void *unk_64;
  char unk_68[4];
  s32 varTable[16];
  char unk_AC[4];
  s32 unk_B0;
  s8 unk_B4;
  s8 unk_B5;
  char unk_B6[2];
  EvtSource *unk_B8;
  struct Evt *unk_BC;
  s32 unk_C0;
  s32 unk_C4;
  s32 unk_C8;
  s32 *animList;
  EnemyTerritory *territory;
  EnemyDrops *drops;
  u32 tattleMsg;
  char unk_DC[20];
} Enemy;
Actor *get_actor(s32 actorID);
void sfx_play_sound_at_position(s32 soundID, s32 value2, f32 posX, f32 posY, f32 posZ);
ApiStatus b_area_kpa_UnkSfxFunc(Evt *script, s32 isInitialCall)
{
  Actor *actor = get_actor(script->owner1.actorID);
  f32 distZ;
  f32 distZ_2;
  f32 distX;
  f32 distY;
  s32 test;
  if (isInitialCall)
  {
    distX = actor->state.goalPos.x - actor->currentPos.x;
    distY = actor->state.goalPos.y - actor->currentPos.y;
    distZ = actor->state.goalPos.z - actor->currentPos.z;
    script->functionTemp[0] = ((sqrtf(((distX * distX) + (distY * distY)) + (distZ * distZ)) / actor->state.speed) * 0.5f) + 1.0f;
    sfx_play_sound_at_position(0x359, 0.0f, actor->currentPos.x, actor->currentPos.y, actor->currentPos.z);
  }

  test = script->functionTemp[0];
  script->functionTemp[0]--;
  if (test > 0)
  {
    return 0;
  }

  sfx_play_sound_at_position(0x759, 0, actor->currentPos.x, actor->currentPos.y, actor->currentPos.z);
  return 2;
}

