#include "isk_06.h"
#include "effects.h"

EvtScript N(EVS_MakeEntities) = {
    EVT_CALL(MakeItemEntity, ITEM_STAR_PIECE, 335, -130, -550, ITEM_SPAWN_MODE_FIXED_NEVER_VANISH, GF_ISK06_Item_StarPiece)
    EVT_CALL(MakeItemEntity, ITEM_RUINS_KEY, 304, -270, -434, ITEM_SPAWN_MODE_KEY, GF_ISK06_Item_RuinsKey)
    EVT_PLAY_EFFECT(EFFECT_FLAME, FX_FLAME_RED, 415, -253, -291, EVT_FLOAT(0.3), LVar0)
    EVT_PLAY_EFFECT(EFFECT_FLAME, FX_FLAME_RED, 291, -253, -415, EVT_FLOAT(0.3), LVar0)
    EVT_RETURN
    EVT_END
};
