#include "include_asset.h"
INCLUDE_IMG("pause/banner_hp.png", pause_banner_hp_png);
INCLUDE_PAL("pause/banner_hp.pal", pause_banner_hp_pal);
INCLUDE_IMG("pause/banner_fp.png", pause_banner_fp_png);
INCLUDE_PAL("pause/banner_fp.pal", pause_banner_fp_pal);
INCLUDE_IMG("pause/banner_bp.png", pause_banner_bp_png);
INCLUDE_PAL("pause/banner_bp.pal", pause_banner_bp_pal);
INCLUDE_IMG("pause/banner_boots.png", pause_banner_boots_png);
INCLUDE_PAL("pause/banner_boots.pal", pause_banner_boots_pal);
INCLUDE_IMG("pause/banner_hammer.png", pause_banner_hammer_png);
INCLUDE_PAL("pause/banner_hammer.pal", pause_banner_hammer_pal);
INCLUDE_IMG("pause/banner_star_energy.png", pause_banner_star_energy_png);
INCLUDE_PAL("pause/banner_star_energy.pal", pause_banner_star_energy_pal);
INCLUDE_IMG("pause/available.png", pause_available_png);
INCLUDE_PAL("pause/available.pal", pause_available_pal);
INCLUDE_IMG("pause/prompt_check_abilities.png", pause_prompt_check_abilities_png);
INCLUDE_PAL("pause/prompt_check_abilities.pal", pause_prompt_check_abilities_pal);
