#include "include_asset.h"
INCLUDE_IMG("pause/banner_hp.png.bin", pause_banner_hp_png);
INCLUDE_PAL("pause/banner_hp.pal.bin", pause_banner_hp_pal);
INCLUDE_IMG("pause/banner_fp.png.bin", pause_banner_fp_png);
INCLUDE_PAL("pause/banner_fp.pal.bin", pause_banner_fp_pal);
INCLUDE_IMG("pause/banner_bp.png.bin", pause_banner_bp_png);
INCLUDE_PAL("pause/banner_bp.pal.bin", pause_banner_bp_pal);
INCLUDE_IMG("pause/banner_boots.png.bin", pause_banner_boots_png);
INCLUDE_PAL("pause/banner_boots.pal.bin", pause_banner_boots_pal);
INCLUDE_IMG("pause/banner_hammer.png.bin", pause_banner_hammer_png);
INCLUDE_PAL("pause/banner_hammer.pal.bin", pause_banner_hammer_pal);
INCLUDE_IMG("pause/banner_star_energy.png.bin", pause_banner_star_energy_png);
INCLUDE_PAL("pause/banner_star_energy.pal.bin", pause_banner_star_energy_pal);
INCLUDE_IMG("pause/available.png.bin", pause_available_png);
INCLUDE_PAL("pause/available.pal.bin", pause_available_pal);
INCLUDE_IMG("pause/prompt_check_abilities.png.bin", pause_prompt_check_abilities_png);
INCLUDE_PAL("pause/prompt_check_abilities.pal.bin", pause_prompt_check_abilities_pal);
