#include "world/common/enemy/MeleeHitbox_30.inc.c"
#include "world/common/enemy/MeleeHitbox_31.inc.c"
#include "world/common/enemy/MeleeHitbox_32.inc.c"
#include "world/common/enemy/MeleeHitbox_33.inc.c"
#include "world/common/enemy/MeleeHitbox_CanSeePlayer.inc.c"
#include "world/common/enemy/MeleeHitbox_Control.inc.c"
#include "world/common/enemy/MeleeHitbox_Main.inc.c" // unused?

#include "world/common/enemy/PiranhaPlantAI_00.inc.c"
#include "world/common/enemy/PiranhaPlantAI_01.inc.c"
#include "world/common/enemy/PiranhaPlantAI_10.inc.c"
#include "world/common/enemy/PiranhaPlantAI_11.inc.c"
#include "world/common/enemy/PiranhaPlantAI_12.inc.c"
#include "world/common/enemy/PiranhaPlantAI_13.inc.c"
#include "world/common/enemy/PiranhaPlantAI_14.inc.c"
#include "world/common/enemy/PiranhaPlantAI_Main.inc.c"
