void func_8004B440(SoundManager* manager, u8 arg1, u8 arg2, AuGlobals* arg3, u8 arg4);
void snd_load_sfx_groups_from_SEF(SoundManager* sndMgr);
void snd_clear_sfx_queue(SoundManager* manager);
void snd_enqueue_sfx_event(SoundManager* manager, s32 soundID, s16 volume, s16 pitchShift, u8 pan);
void func_8004B748(SoundManager* manager);
s32 func_8004B9E4(SoundManager* manager, s32 arg1);
void func_8004BA54(SoundManager* manager, s32 arg1);
// INCLUDE_ASM(s32, "audio/26840_len_20d0", func_8004BA74);
void func_8004C0E4(SoundManager* manager, SoundPlayer* player, s8* readPos, SoundSFXEntry* sfxEntry, s32 arg4, s32 arg5);
void snd_set_bits_C00(SoundManager* manager, u32 soundID);
void _snd_stop_sound_by_id(SoundManager* manager, u32 soundID);
void func_8004C300(SoundManager* manager, u32 soundID);
void snd_set_modifiers(SoundManager* manager, SoundSFXEntry* sfxEntry);
void snd_set_player_modifiers(SoundPlayer* player, SoundSFXEntry* sfxEntry);
s16 snd_sound_manager_update(SoundManager* manager);
void func_8004C578(SoundManager* manager, SoundPlayer* player, AlUnkVoice* arg2, u8 arg3);
s16 snd_get_scaled_volume(SoundManager* manager, SoundPlayer* player);
void func_8004C884(SoundManager* manager, SoundPlayer* player, AlUnkVoice* arg2, u8 arg3);
void snd_set_voice_volume(AlUnkVoice* voice, SoundManager* manager, SoundPlayer* player);
u8 func_8004CDF8(s32 arg0, s32 arg1, s32 arg2);
void snd_SEFCmd_00_SetVolume(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_01_SetPan(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_02_SetInstrument(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_03_SetReverb(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_04(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_05(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_06(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_07(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_08(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_09_StartLoop(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_0A_EndLoop(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_0B(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_0C(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_0D(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_0E(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_0F(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_10_Jump(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_11_Restart(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_12_NOP(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_SetUnkA1(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_SetUnkA2(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_SetUnkA3(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_16(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_17(SoundManager* manager, SoundPlayer* player);
void snd_SEFCmd_18(SoundManager* manager, SoundPlayer* player);
s32 func_8004D428(s32 arg0, s32 arg1, s32 arg2);
u8 func_8004D484(s32 arg0, s32 arg1, s32 arg2);
void func_8004D4BC(SoundManager* manager);
