void func_8004D510(BGMPlayer* player);
BGMPlayer* snd_get_player_with_song_name(s32 songString);
s32 snd_dispatch_bgm_player_event(SongUpdateEvent* event);
MusicError func_8004DA0C(s32 songName);
void func_8004DA74(void);
void func_8004DAA8(BGMPlayer* player);
MusicError snd_is_song_playing(s32 songName);
s32 func_8004DB28(BGMPlayer* player);
MusicError func_8004DB4C(SongUpdateEvent* s);
MusicError func_8004DC80(s32 songName);
MusicError func_8004DCB8(SongUpdateEvent* update, s32 clearChanged);
MusicError func_8004DE2C(SongUpdateEvent* update);
void func_8004DFD4(AuGlobals* globals);
s32 func_8004E0F4(SongUpdateEvent* update);
void bgm_player_init(BGMPlayer* player, s32 arg1, s32 arg2, AuGlobals* arg3);
void bgm_set_effect_indices(BGMPlayer* player, u8* list);
void snd_update_bgm_fade(BGMPlayer* player);
void func_8004E444(BGMPlayer* arg0);
s32 func_8004E4B8(BGMPlayer* player);
void snd_initialize_bgm_player(BGMPlayer* player);
void func_8004E844(BGMPlayer* player, s32 arg1);
void func_8004E880(BGMPlayer* player, s32 sampleRate, s32 divisor);
void snd_bgm_state_2(BGMPlayer* player);
void func_8004EA34(BGMPlayer* player, u32 cmd);
// INCLUDE_ASM(s32, "audio/28910_len_5090", func_8004EAD4);
void snd_bgm_state_4(BGMPlayer* player);
void func_8004EC68(BGMPlayer *player);
void snd_BGMCmd_E0_MasterTempo(BGMPlayer* player, BGMPlayerTrack* track);
s32 snd_bpm_to_tempo(BGMPlayer* player, u32 tempo);
void snd_BGMCmd_E1_MasterVolume(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_E2_MasterPitchShift(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_E3(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_E6_MasterEffect(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_E4_MasterTempoFade(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_E5_MasterVolumeFade(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_E8_TrackOverridePatch(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_E9_SubTrackVolume(BGMPlayer* arg0, BGMPlayerTrack* track);
void snd_BGMCmd_F6_TrackVolumeFade(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_EA_SubTrackPan(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_EB_SubTrackReverb(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_EC_SegTrackVolume(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_ED_SubTrackCoarseTune(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_EE_SubTrackFineTune(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_EF_SegTrackTune(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_F0_TrackTremolo(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_F1_TrackTremoloSpeed(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_F2_TrackTremoloTime(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_F3_TrackTremoloStop(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_F4(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_F5_TrackVoice(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_F7_SubTrackReverbType(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_FD(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_FE(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_FC_Jump(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_FF(BGMPlayer* player, BGMPlayerTrack* track);
void snd_BGMCmd_NOP(BGMPlayer* player, BGMPlayerTrack* track);
u8 func_80050568(BGMPlayer* player, u8 arg1, u8 arg2);
s16 func_800505E4(s32 arg0, s32 arg1, u8 arg2);
u8 func_80050654(s32 arg0, u8 volume, u8 arg2);
u8 func_8005068C(s32 arg0, u8 arg1, u8 arg2);
void snd_set_bgm_proximity_mix(s32 songName, u32 mix);
void func_80050770(BGMPlayer* player, f32 arg1);
void func_80050818(BGMPlayer* player, s32 arg1);
void func_8005083C(BGMPlayer* player, s32 trackIdx, s16 arg2, u8 arg3);
void func_8005087C(BGMPlayer* player, s32* arg1, s32 arg2);
void func_80050888(BGMPlayer* player, BGMPlayerTrack* track, s32 target, s32 duration);
void func_80050900(BGMPlayer* player);
MusicError func_80050970(SongUpdateEvent* arg0);
