#include "../common/Credits.h"

CreditsEntry N(Credits_Names)[] = {
    {
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 33,
    },
    {
        .msgID = MSG_Credits_0071,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0072,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0066,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0065,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0075,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0073,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0055,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0051,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0059,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_005A,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0053,
        .posX = STANDARD_POS_X,
        .posY = 182,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_005B,
        .posX = STANDARD_POS_X,
        .posY = 195,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_005C,
        .posX = STANDARD_POS_X,
        .posY = 208,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_005D,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_005E,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_005F,
        .posX = STANDARD_POS_X,
        .posY = 182,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0060,
        .posX = STANDARD_POS_X,
        .posY = 195,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0061,
        .posX = STANDARD_POS_X,
        .posY = 208,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0068,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_PAL_Credits_009E,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0085,
        .posX = STANDARD_POS_X,
        .posY = 182,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0086,
        .posX = STANDARD_POS_X,
        .posY = 195,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0087,
        .posX = STANDARD_POS_X,
        .posY = 208,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 50,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 33,
    },
    {
        .msgID = MSG_Credits_0052,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 142,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 200,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 33,
    },
    {
        .msgID = MSG_Credits_006A,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 40,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 156,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 200,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0054,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 142,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 200,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 33,
    },
    {
        .msgID = MSG_Credits_006D,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 142,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 200,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 33,
    },
    {
        .msgID = MSG_Credits_006C,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 156,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 200,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_006B,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 142,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 200,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 33,
    },
    {
        .msgID = MSG_Credits_006E,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 142,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 200,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 50,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = -1,
    },
};
