#include "../common/Credits.h"

CreditsEntry N(Credits_Jobs)[] = {
    {
        .msgID = MSG_Credits_0019,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 2270,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 2340,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = 60,
    },
    {
        .msgID = MSG_Credits_001A,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 200,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 270,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_001B,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 430,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 500,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_001D,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 200,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 270,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_001C,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 430,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 500,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_001E,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 200,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 30,
        .perCharDelayOut = 0,
        .next = 270,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = 60,
    },
#if VERSION_IQUE
// *©2000-2004* NINTENDO
//      *©2004* IQUE
    {
        .msgID = MSG_Credits_0007,
        .posX = 120,
        .posY = 172,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 60,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 160,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 50,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0008,
        .posX = 200,
        .posY = 172,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 60,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 160,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 50,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_008A,
        .posX = 135,
        .posY = 188,
        .palette = 0,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 60,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 160,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 50,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0089,
        .posX = 185,
        .posY = 188,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 60,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 160,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 50,
        .perCharDelayOut = 0,
        .next = 270,
        .flags = CREDITS_FLAG_1,
    },
#else
// *©2001* NINTENDO
    {
        .msgID = MSG_Credits_0007,
        .posX = 131,
        .posY = 182,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 60,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 160,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 50,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0008,
        .posX = 189,
        .posY = 182,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 60,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 160,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 50,
        .perCharDelayOut = 0,
        .next = 270,
        .flags = CREDITS_FLAG_1,
    },
#endif
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = 30,
    },
#if VERSION_IQUE
//      *GAME BY*
// INTELLIGENT SYSTEMS
//  IQUE ENGINEERING
    {
        .msgID = MSG_Credits_0005,
        .posX = STANDARD_POS_X,
        .posY = 160,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 60,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 160,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 50,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0006,
        .posX = STANDARD_POS_X,
        .posY = 176,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 60,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 160,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 50,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0088,
        .posX = 160,
        .posY = 192,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 60,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 160,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 50,
        .perCharDelayOut = 0,
        .next = 270,
        .flags = CREDITS_FLAG_1,
    },
#else
//      *GAME BY*
// INTELLIGENT SYSTEMS
    {
        .msgID = MSG_Credits_0005,
        .posX = STANDARD_POS_X,
        .posY = 172,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 60,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 160,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 50,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0006,
        .posX = STANDARD_POS_X,
        .posY = 188,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 60,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 160,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 50,
        .perCharDelayOut = 0,
        .next = 270,
        .flags = CREDITS_FLAG_1,
    },
#endif
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = -1,
    },
};
