#include "../common/Credits.h"

CreditsEntry N(Credits_Jobs)[] = {
    {
        .msgID = MSG_Credits_0019,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 1735,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 1793,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 50,
    },
    {
        .msgID = MSG_Credits_001A,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 175,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 233,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_001B,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 375,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 433,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_001D,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 175,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 233,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_001C,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 375,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 433,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_001E,
        .posX = STANDARD_POS_X,
        .posY = 170,
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 2,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 175,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 233,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 60,
    },
    {
        .msgID = MSG_Credits_0005,
        .posX = STANDARD_POS_X,
        .posY = 172,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 50,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 40,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0006,
        .posX = STANDARD_POS_X,
        .posY = 188,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 50,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 40,
        .perCharDelayOut = 0,
        .next = 300,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = 25,
    },
    {
        .msgID = MSG_PAL_Credits_009F,
        .posX = STANDARD_POS_X,
        .posY = 166,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 50,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 40,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_PAL_Credits_00A0,
        .posX = STANDARD_POS_X,
        .posY = 176,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 50,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 40,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_PAL_Credits_00A1,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 50,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 40,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_PAL_Credits_00A2,
        .posX = STANDARD_POS_X,
        .posY = 200,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = 50,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 210,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 40,
        .perCharDelayOut = 0,
        .next = 300,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 0,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 0,
        .perCharDelayOut = 0,
        .next = -1,
    },
};
