// indices into gItemHudScripts for hud scripts used by the item table
#define HS_INDEX_HudScript_Item_SpicySoup               0x1
#define HS_INDEX_HudScript_Item_ApplePie                0x2
#define HS_INDEX_HudScript_Item_HoneyUltra              0x3
#define HS_INDEX_HudScript_Item_MapleUltra              0x4
#define HS_INDEX_HudScript_Item_JellyUltra              0x5
#define HS_INDEX_HudScript_Item_Koopasta                0x6
#define HS_INDEX_HudScript_Item_FriedShroom             0x7
#define HS_INDEX_HudScript_Item_ShroomCake              0x8
#define HS_INDEX_HudScript_Item_ShroomSteak             0x9
#define HS_INDEX_HudScript_Item_HotShroom               0xA
#define HS_INDEX_HudScript_Item_SweetShroom             0xB
#define HS_INDEX_HudScript_Item_HealthyJuice            0xC
#define HS_INDEX_HudScript_Item_BlandMeal               0xD
#define HS_INDEX_HudScript_Item_YummyMeal               0xE
#define HS_INDEX_HudScript_Item_DeluxeFeast             0xF
#define HS_INDEX_HudScript_Item_SpecialShake            0x10
#define HS_INDEX_HudScript_Item_BigCookie               0x11
#define HS_INDEX_HudScript_Item_Cake                    0x12
#define HS_INDEX_HudScript_Item_Mistake                 0x13
#define HS_INDEX_HudScript_Item_KoopaTea                0x14
#define HS_INDEX_HudScript_Item_HoneySuper              0x15
#define HS_INDEX_HudScript_Item_MapleSuper              0x16
#define HS_INDEX_HudScript_Item_JellySuper              0x17
#define HS_INDEX_HudScript_Item_Spaghetti               0x18
#define HS_INDEX_HudScript_Item_EggMissile              0x19
#define HS_INDEX_HudScript_Item_FriedEgg                0x1A
#define HS_INDEX_HudScript_Item_HoneyShroom             0x1B
#define HS_INDEX_HudScript_Item_HoneyCandy              0x1C
#define HS_INDEX_HudScript_Item_ElectroPop              0x1D
#define HS_INDEX_HudScript_Item_FirePop                 0x1E
#define HS_INDEX_HudScript_Item_LimeCandy               0x1F
#define HS_INDEX_HudScript_Item_CocoPop                 0x20
#define HS_INDEX_HudScript_Item_LemonCandy              0x21
#define HS_INDEX_HudScript_Item_JellyPop                0x22
#define HS_INDEX_HudScript_Item_StrangeCake             0x23
#define HS_INDEX_HudScript_Item_KookyCookie             0x24
#define HS_INDEX_HudScript_Item_FrozenFries             0x25
#define HS_INDEX_HudScript_Item_PotatoSalad             0x26
#define HS_INDEX_HudScript_Item_NuttyCake               0x27
#define HS_INDEX_HudScript_Item_MapleShroom             0x28
#define HS_INDEX_HudScript_Item_BoiledEgg               0x29
#define HS_INDEX_HudScript_Item_YoshiCookie             0x2A
#define HS_INDEX_HudScript_Item_JellyShroom             0x2B
#define HS_INDEX_HudScript_Item_Unused_02C              0x2C
#define HS_INDEX_HudScript_Item_Unused_02D              0x2D
#define HS_INDEX_HudScript_Item_Unused_02E              0x2E
#define HS_INDEX_HudScript_Item_Unused_02F              0x2F
#define HS_INDEX_HudScript_Item_Unused_030              0x30
#define HS_INDEX_HudScript_Item_Heart                   0x31
#define HS_INDEX_HudScript_Item_Coin                    0x32
#define HS_INDEX_HudScript_Item_HeartPiece              0x33
#define HS_INDEX_HudScript_Item_StarPoint               0x34
#define HS_INDEX_HudScript_Item_HeartPoint              0x35
#define HS_INDEX_HudScript_Item_FlowerPoint             0x36
#define HS_INDEX_HudScript_Item_StarPiece               0x37
#define HS_INDEX_HudScript_Item_Jump                    0x38
#define HS_INDEX_HudScript_Item_SpinJump                0x39
#define HS_INDEX_HudScript_Item_TornadoJump             0x3A
#define HS_INDEX_HudScript_Item_Hammer                  0x3B
#define HS_INDEX_HudScript_Item_SuperHammer             0x3C
#define HS_INDEX_HudScript_Item_UltraHammer             0x3D
#define HS_INDEX_HudScript_Item_LuckyStar               0x3E
#define HS_INDEX_HudScript_Item_Map                     0x3F
#define HS_INDEX_HudScript_Item_KoopaFortressKey        0x40
#define HS_INDEX_HudScript_Item_RuinsKey                0x41
#define HS_INDEX_HudScript_Item_TubbaCastleKey          0x42
#define HS_INDEX_HudScript_Item_CrystalPalaceKey        0x43
#define HS_INDEX_HudScript_Item_BowserCastleKey         0x44
#define HS_INDEX_HudScript_Item_Dolly                   0x45
#define HS_INDEX_HudScript_Item_KooperShell             0x46
#define HS_INDEX_HudScript_Item_PulseStone              0x47
#define HS_INDEX_HudScript_Item_Artifact                0x48
#define HS_INDEX_HudScript_Item_VolcanoVase             0x49
#define HS_INDEX_HudScript_Item_PyramidStone            0x4A
#define HS_INDEX_HudScript_Item_DiamondStone            0x4B
#define HS_INDEX_HudScript_Item_LunarStone              0x4C
#define HS_INDEX_HudScript_Item_ForestPass              0x4D
#define HS_INDEX_HudScript_Item_BooRecordOutline        0x4E
#define HS_INDEX_HudScript_Item_BooRecord               0x4F
#define HS_INDEX_HudScript_Item_BooWeight               0x50
#define HS_INDEX_HudScript_Item_BooPortrait             0x51
#define HS_INDEX_HudScript_Item_MysticalKey             0x52
#define HS_INDEX_HudScript_Item_IronKey                 0x53
#define HS_INDEX_HudScript_Item_ToyTrain                0x54
#define HS_INDEX_HudScript_Item_FryingPan               0x55
#define HS_INDEX_HudScript_Item_Dictionary              0x56
#define HS_INDEX_HudScript_Item_MysteryNote             0x57
#define HS_INDEX_HudScript_Item_SuspiciousNote          0x58
#define HS_INDEX_HudScript_Item_MagicalSeed1            0x59
#define HS_INDEX_HudScript_Item_MagicalSeed2            0x5A
#define HS_INDEX_HudScript_Item_MagicalSeed3            0x5B
#define HS_INDEX_HudScript_Item_MagicalSeed4            0x5C
#define HS_INDEX_HudScript_Item_CrystalBerry            0x5D
#define HS_INDEX_HudScript_Item_WaterStone              0x5E
#define HS_INDEX_HudScript_Item_MagicalBean             0x5F
#define HS_INDEX_HudScript_Item_FertileSoil             0x60
#define HS_INDEX_HudScript_Item_MiracleWater            0x61
#define HS_INDEX_HudScript_Item_UltraStone              0x62
#define HS_INDEX_HudScript_Item_ToadDoll                0x63
#define HS_INDEX_HudScript_Item_Calculator              0x64
#define HS_INDEX_HudScript_Item_Screwdriver             0x65
#define HS_INDEX_HudScript_Item_Cookbook                0x66
#define HS_INDEX_HudScript_Item_JadeRaven               0x67
#define HS_INDEX_HudScript_Item_SnowmanBucket           0x68
#define HS_INDEX_HudScript_Item_SnowmanScarf            0x69
#define HS_INDEX_HudScript_Item_RedKey                  0x6A
#define HS_INDEX_HudScript_Item_BlueKey                 0x6B
#define HS_INDEX_HudScript_Item_KootPackage             0x6C
#define HS_INDEX_HudScript_Item_KootRedJar              0x6D
#define HS_INDEX_HudScript_Item_Melody                  0x6E
#define HS_INDEX_HudScript_Item_Lyrics                  0x6F
#define HS_INDEX_HudScript_Item_Mailbag                 0x70
#define HS_INDEX_HudScript_Item_StarStone               0x71
#define HS_INDEX_HudScript_Item_SneakyParasol           0x72
#define HS_INDEX_HudScript_Item_PeachKey                0x73
#define HS_INDEX_HudScript_Item_UNK_1DC210              0x74
#define HS_INDEX_HudScript_Item_UNK_1DC430              0x75
#define HS_INDEX_HudScript_Item_UNK_1DC650              0x76
#define HS_INDEX_HudScript_Item_UNK_1DC870              0x77
#define HS_INDEX_HudScript_Item_FirstDegreeCard         0x78
#define HS_INDEX_HudScript_Item_SecondDegreeCard        0x79
#define HS_INDEX_HudScript_Item_ThirdDegreeCard         0x7A
#define HS_INDEX_HudScript_Item_FourthDegreeCard        0x7B
#define HS_INDEX_HudScript_Item_Diploma                 0x7C
#define HS_INDEX_HudScript_Item_CrystalBall             0x7D
#define HS_INDEX_HudScript_Item_GoldCredit              0x7E
#define HS_INDEX_HudScript_Item_SilverCredit            0x7F
#define HS_INDEX_HudScript_Item_KootKoopaLegends        0x80
#define HS_INDEX_HudScript_Item_KootTheTape             0x81
#define HS_INDEX_HudScript_Item_KootLuigiAutograph      0x82
#define HS_INDEX_HudScript_Item_KootEmptyWallet         0x83
#define HS_INDEX_HudScript_Item_KootMerluvleeAutograph  0x84
#define HS_INDEX_HudScript_Item_KootShell               0x85
#define HS_INDEX_HudScript_Item_KootPhoto               0x86
#define HS_INDEX_HudScript_Item_KootGlasses             0x87
#define HS_INDEX_HudScript_Item_Letter                  0x88
#define HS_INDEX_HudScript_Item_Unused_089              0x89
#define HS_INDEX_HudScript_Item_Unused_08A              0x8A
#define HS_INDEX_HudScript_Item_Unused_08B              0x8B
#define HS_INDEX_HudScript_Item_Unused_08C              0x8C
#define HS_INDEX_HudScript_Item_Unused_08D              0x8D
#define HS_INDEX_HudScript_Item_Unused_08E              0x8E
#define HS_INDEX_HudScript_Item_Unused_08F              0x8F
#define HS_INDEX_HudScript_Item_SpinSmash               0x90
#define HS_INDEX_HudScript_Item_Multibounce             0x91
#define HS_INDEX_HudScript_Item_PowerPlus               0x92
#define HS_INDEX_HudScript_Item_DodgeMaster             0x93
#define HS_INDEX_HudScript_Item_PowerBounce             0x94
#define HS_INDEX_HudScript_Item_SpikeShield             0x95
#define HS_INDEX_HudScript_Item_FirstAttack             0x96
#define HS_INDEX_HudScript_Item_HPPlus                  0x97
#define HS_INDEX_HudScript_Item_QuakeHammer             0x98
#define HS_INDEX_HudScript_Item_DoubleDip               0x99
#define HS_INDEX_HudScript_Item_PowerQuake              0x9A
#define HS_INDEX_HudScript_Item_MegaQuake               0x9B
#define HS_INDEX_HudScript_Item_SleepStomp              0x9C
#define HS_INDEX_HudScript_Item_SmashCharge             0x9D
#define HS_INDEX_HudScript_Item_SSmashChg               0x9E
#define HS_INDEX_HudScript_Item_AutoSmash               0x9F
#define HS_INDEX_HudScript_Item_FireShield              0xA0
#define HS_INDEX_HudScript_Item_JumpCharge              0xA1
#define HS_INDEX_HudScript_Item_SJumpChg                0xA2
#define HS_INDEX_HudScript_Item_AutoJump                0xA3
#define HS_INDEX_HudScript_Item_DDownPound              0xA4
#define HS_INDEX_HudScript_Item_AutoMultibounce         0xA5
#define HS_INDEX_HudScript_Item_DizzyStomp              0xA6
#define HS_INDEX_HudScript_Item_HammerThrow             0xA7
#define HS_INDEX_HudScript_Item_SmashCharge0            0xA8
#define HS_INDEX_HudScript_Item_PrettyLucky             0xA9
#define HS_INDEX_HudScript_Item_FeelingFine             0xAA
#define HS_INDEX_HudScript_Item_AttackFXA               0xAB
#define HS_INDEX_HudScript_Item_AllorNothing            0xAC
#define HS_INDEX_HudScript_Item_HPDrain                 0xAD
#define HS_INDEX_HudScript_Item_JumpCharge0             0xAE
#define HS_INDEX_HudScript_Item_SlowGo                  0xAF
#define HS_INDEX_HudScript_Item_FPPlus                  0xB0
#define HS_INDEX_HudScript_Item_MegaRush                0xB1
#define HS_INDEX_HudScript_Item_IcePower                0xB2
#define HS_INDEX_HudScript_Item_DefendPlus              0xB3
#define HS_INDEX_HudScript_Item_PayOff                  0xB4
#define HS_INDEX_HudScript_Item_MoneyMoney              0xB5
#define HS_INDEX_HudScript_Item_ChillOut                0xB6
#define HS_INDEX_HudScript_Item_HappyHeart              0xB7
#define HS_INDEX_HudScript_Item_ZapTap                  0xB8
#define HS_INDEX_HudScript_Item_Berserker               0xB9
#define HS_INDEX_HudScript_Item_RightOn                 0xBA
#define HS_INDEX_HudScript_Item_RunawayPay              0xBB
#define HS_INDEX_HudScript_Item_Refund                  0xBC
#define HS_INDEX_HudScript_Item_FlowerSaver             0xBD
#define HS_INDEX_HudScript_Item_TripleDip               0xBE
#define HS_INDEX_HudScript_Item_FlowerFanatic           0xBF
#define HS_INDEX_HudScript_Item_PowerJump               0xC0
#define HS_INDEX_HudScript_Item_SuperJump               0xC1
#define HS_INDEX_HudScript_Item_MegaJump                0xC2
#define HS_INDEX_HudScript_Item_PowerSmash1             0xC3
#define HS_INDEX_HudScript_Item_SuperSmash              0xC4
#define HS_INDEX_HudScript_Item_MegaSmash               0xC5
#define HS_INDEX_HudScript_Item_LuckyDay                0xC6
#define HS_INDEX_HudScript_Item_MegaHPDrain             0xC7
#define HS_INDEX_HudScript_Item_BumpAttack              0xC8
#define HS_INDEX_HudScript_Item_PUpDDown                0xC9
#define HS_INDEX_HudScript_Item_PDownDUp                0xCA
#define HS_INDEX_HudScript_Item_HeartFinder             0xCB
#define HS_INDEX_HudScript_Item_FlowerFinder            0xCC
#define HS_INDEX_HudScript_Item_DizzyAttack             0xCD
#define HS_INDEX_HudScript_Item_SpeedySpin              0xCE
#define HS_INDEX_HudScript_Item_SpinAttack              0xCF
#define HS_INDEX_HudScript_Item_ISpy                    0xD0
#define HS_INDEX_HudScript_Item_PowerRush               0xD1
#define HS_INDEX_HudScript_Item_LastStand               0xD2
#define HS_INDEX_HudScript_Item_CloseCall               0xD3
#define HS_INDEX_HudScript_Item_CrazyHeart              0xD4
#define HS_INDEX_HudScript_Item_Unused_0D5              0xD5
#define HS_INDEX_HudScript_Item_Unused_0D6              0xD6
#define HS_INDEX_HudScript_Item_Unused_0D7              0xD7
#define HS_INDEX_HudScript_Item_ShrinkSmash             0xD8
#define HS_INDEX_HudScript_Item_ShrinkStomp             0xD9
#define HS_INDEX_HudScript_Item_DDownJump               0xDA
#define HS_INDEX_HudScript_Item_DamageDodge             0xDB
#define HS_INDEX_HudScript_Item_EarthquakeJump          0xDC
#define HS_INDEX_HudScript_Item_HappyFlower             0xDD
#define HS_INDEX_HudScript_Item_Unused_0DE              0xDE
#define HS_INDEX_HudScript_Item_Unused_0DF              0xDF
#define HS_INDEX_HudScript_Item_DeepFocus               0xE0
#define HS_INDEX_HudScript_Item_SuperFocus              0xE1
#define HS_INDEX_HudScript_Item_Kaiden                  0xE2
#define HS_INDEX_HudScript_Item_QuickChange             0xE3
#define HS_INDEX_HudScript_Item_Unused_0E4              0xE4
#define HS_INDEX_HudScript_Item_Unused_0E5              0xE5
#define HS_INDEX_HudScript_Item_Unused_0E6              0xE6
#define HS_INDEX_HudScript_Item_Unused_0E7              0xE7
#define HS_INDEX_HudScript_Item_Peekaboo                0xE8
#define HS_INDEX_HudScript_Item_GroupFocus              0xE9
#define HS_INDEX_HudScript_Item_AttackFXD               0xEA
#define HS_INDEX_HudScript_Item_AttackFXB               0xEB
#define HS_INDEX_HudScript_Item_AttackFXE               0xEC
#define HS_INDEX_HudScript_Item_AttackFXC               0xED
#define HS_INDEX_HudScript_Item_AttackFXF               0xEE
#define HS_INDEX_HudScript_Item_Unused_0EF              0xEF
#define HS_INDEX_HudScript_Item_HealthyHealthy          0xF0
#define HS_INDEX_HudScript_Item_Unused_0F1              0xF1
#define HS_INDEX_HudScript_Item_Unused_0F2              0xF2
#define HS_INDEX_HudScript_Item_Unused_0F3              0xF3
#define HS_INDEX_HudScript_Item_Unused_0F4              0xF4
#define HS_INDEX_HudScript_Item_Unused_0F5              0xF5
#define HS_INDEX_HudScript_Item_Unused_0F6              0xF6
#define HS_INDEX_HudScript_Item_Unused_0F7              0xF7
#define HS_INDEX_HudScript_Item_Mushroom                0xF8
#define HS_INDEX_HudScript_Item_SuperShroom             0xF9
#define HS_INDEX_HudScript_Item_UltraShroom             0xFA
#define HS_INDEX_HudScript_Item_LifeShroom              0xFB
#define HS_INDEX_HudScript_Item_DriedShroom             0xFC
#define HS_INDEX_HudScript_Item_TastyTonic              0xFD
#define HS_INDEX_HudScript_Item_SuperSoda               0xFE
#define HS_INDEX_HudScript_Item_BlueBerry               0xFF
#define HS_INDEX_HudScript_Item_RedBerry                0x100
#define HS_INDEX_HudScript_Item_YellowBerry             0x101
#define HS_INDEX_HudScript_Item_BubbleBerry             0x102
#define HS_INDEX_HudScript_Item_Goomnut                 0x103
#define HS_INDEX_HudScript_Item_KoopaLeaf               0x104
#define HS_INDEX_HudScript_Item_DriedPasta              0x105
#define HS_INDEX_HudScript_Item_Lime                    0x106
#define HS_INDEX_HudScript_Item_Lemon                   0x107
#define HS_INDEX_HudScript_Item_DriedFruit              0x108
#define HS_INDEX_HudScript_Item_StrangeLeaf             0x109
#define HS_INDEX_HudScript_Item_CakeMix                 0x10A
#define HS_INDEX_HudScript_Item_Egg                     0x10B
#define HS_INDEX_HudScript_Item_Coconut                 0x10C
#define HS_INDEX_HudScript_Item_Melon                   0x10D
#define HS_INDEX_HudScript_Item_StinkyHerb              0x10E
#define HS_INDEX_HudScript_Item_IcedPotato              0x10F
#define HS_INDEX_HudScript_Item_HoneySyrup              0x110
#define HS_INDEX_HudScript_Item_MapleSyrup              0x111
#define HS_INDEX_HudScript_Item_JamminJelly             0x112
#define HS_INDEX_HudScript_Item_WhackasBump             0x113
#define HS_INDEX_HudScript_Item_Apple                   0x114
#define HS_INDEX_HudScript_Item_BakingSalt              0x115
#define HS_INDEX_HudScript_Item_BakingSugar             0x116
#define HS_INDEX_HudScript_Item_BakingEgg               0x117
#define HS_INDEX_HudScript_Item_BakingCream             0x118
#define HS_INDEX_HudScript_Item_BakingStrawberry        0x119
#define HS_INDEX_HudScript_Item_BakingButter            0x11A
#define HS_INDEX_HudScript_Item_BakingCleanser          0x11B
#define HS_INDEX_HudScript_Item_BakingWater             0x11C
#define HS_INDEX_HudScript_Item_BakingFlour             0x11D
#define HS_INDEX_HudScript_Item_BakingMilk              0x11E
#define HS_INDEX_HudScript_Item_Unused_11F              0x11F
#define HS_INDEX_HudScript_Item_FireFlower              0x120
#define HS_INDEX_HudScript_Item_SnowmanDoll             0x121
#define HS_INDEX_HudScript_Item_ThunderRage             0x122
#define HS_INDEX_HudScript_Item_ThunderBolt             0x123
#define HS_INDEX_HudScript_Item_ShootingStar            0x124
#define HS_INDEX_HudScript_Item_DustyHammer             0x125
#define HS_INDEX_HudScript_Item_Pebble                  0x126
#define HS_INDEX_HudScript_Item_Unused_127              0x127
#define HS_INDEX_HudScript_Item_StoneCap                0x128
#define HS_INDEX_HudScript_Item_VoltShroom              0x129
#define HS_INDEX_HudScript_Item_PowerStar               0x12A
#define HS_INDEX_HudScript_Item_Parasol                 0x12B
#define HS_INDEX_HudScript_Item_MagicMirror             0x12C
#define HS_INDEX_HudScript_Item_Unused_12D              0x12D
#define HS_INDEX_HudScript_Item_Unused_12E              0x12E
#define HS_INDEX_HudScript_Item_Unused_12F              0x12F
#define HS_INDEX_HudScript_Item_SleepySheep             0x130
#define HS_INDEX_HudScript_Item_XBandage                0x131
#define HS_INDEX_HudScript_Item_POWBlock                0x132
#define HS_INDEX_HudScript_Item_HustleDrink             0x133
#define HS_INDEX_HudScript_Item_StopWatch               0x134
#define HS_INDEX_HudScript_Item_DizzyDial               0x135
#define HS_INDEX_HudScript_Item_Unused_136              0x136
#define HS_INDEX_HudScript_Item_Unused_137              0x137
#define HS_INDEX_HudScript_Item_PleaseComeBack          0x138
#define HS_INDEX_HudScript_Item_Unused_139              0x139
#define HS_INDEX_HudScript_Item_FrightJar               0x13A
#define HS_INDEX_HudScript_Item_Mystery                 0x13B
#define HS_INDEX_HudScript_Item_RepelGel                0x13C
#define HS_INDEX_HudScript_Item_InsecticideHerb         0x13D
#define HS_INDEX_HudScript_Item_Unused_13E              0x13E
#define HS_INDEX_HudScript_Item_Unused_13F              0x13F
#define HS_INDEX_HudScript_Item_Present                 0x140
#define HS_INDEX_HudScript_Item_CakeDone                0x141
#define HS_INDEX_HudScript_Item_CakeBare                0x142
#define HS_INDEX_HudScript_Item_CakePan                 0x143
#define HS_INDEX_HudScript_Item_CakeBatter              0x144
#define HS_INDEX_HudScript_Item_CakeBowl                0x145
#define HS_INDEX_HudScript_Item_CakeMixed               0x146
#define HS_INDEX_HudScript_Item_CakeWithIcing           0x147
#define HS_INDEX_HudScript_Item_CakeWithBerries         0x148
#define HS_INDEX_HudScript_Item_PartnerAttack           0x149
#define HS_INDEX_HudScript_Item_Hammer1Icon             0x14A
#define HS_INDEX_HudScript_Item_Hammer2Icon             0x14B
#define HS_INDEX_HudScript_Item_Hammer3Icon             0x14C
#define HS_INDEX_HudScript_Item_Boots1Icon              0x14D
#define HS_INDEX_HudScript_Item_Boots2Icon              0x14E
#define HS_INDEX_HudScript_Item_Boots3Icon              0x14F
#define HS_INDEX_HudScript_Item_ItemsIcon               0x150
