.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.11.1 */

glabel guMtxCatF
/* 40FC0 80065BC0 27BDFFC0 */  addiu     $sp, $sp, -0x40
/* 40FC4 80065BC4 24820040 */  addiu     $v0, $a0, 0x40
/* 40FC8 80065BC8 24A30010 */  addiu     $v1, $a1, 0x10
/* 40FCC 80065BCC 03A05021 */  addu      $t2, $sp, $zero
.LIQUE_80065BD0:
/* 40FD0 80065BD0 00A03821 */  addu      $a3, $a1, $zero
.LIQUE_80065BD4:
/* 40FD4 80065BD4 C4840000 */  lwc1      $f4, 0x0($a0)
/* 40FD8 80065BD8 C4E60000 */  lwc1      $f6, 0x0($a3)
/* 40FDC 80065BDC 46062202 */  mul.s     $f8, $f4, $f6
/* 40FE0 80065BE0 C48A0004 */  lwc1      $f10, 0x4($a0)
/* 40FE4 80065BE4 C4F00010 */  lwc1      $f16, 0x10($a3)
/* 40FE8 80065BE8 46105482 */  mul.s     $f18, $f10, $f16
/* 40FEC 80065BEC 46124200 */  add.s     $f8, $f8, $f18
/* 40FF0 80065BF0 C4840008 */  lwc1      $f4, 0x8($a0)
/* 40FF4 80065BF4 C4E60020 */  lwc1      $f6, 0x20($a3)
/* 40FF8 80065BF8 46062482 */  mul.s     $f18, $f4, $f6
/* 40FFC 80065BFC 46124200 */  add.s     $f8, $f8, $f18
/* 41000 80065C00 C48A000C */  lwc1      $f10, 0xC($a0)
/* 41004 80065C04 C4F00030 */  lwc1      $f16, 0x30($a3)
/* 41008 80065C08 46105482 */  mul.s     $f18, $f10, $f16
/* 4100C 80065C0C 46124200 */  add.s     $f8, $f8, $f18
/* 41010 80065C10 E5480000 */  swc1      $f8, 0x0($t2)
/* 41014 80065C14 24E70004 */  addiu     $a3, $a3, 0x4
/* 41018 80065C18 14E3FFEE */  bne       $a3, $v1, .LIQUE_80065BD4
/* 4101C 80065C1C 254A0004 */   addiu    $t2, $t2, 0x4
/* 41020 80065C20 24840010 */  addiu     $a0, $a0, 0x10
/* 41024 80065C24 1482FFEA */  bne       $a0, $v0, .LIQUE_80065BD0
/* 41028 80065C28 00000000 */   nop
/* 4102C 80065C2C E4C8003C */  swc1      $f8, 0x3C($a2)
/* 41030 80065C30 8FA80000 */  lw        $t0, 0x0($sp)
/* 41034 80065C34 8FA90004 */  lw        $t1, 0x4($sp)
/* 41038 80065C38 8FAA0008 */  lw        $t2, 0x8($sp)
/* 4103C 80065C3C 8FAB000C */  lw        $t3, 0xC($sp)
/* 41040 80065C40 8FAC0010 */  lw        $t4, 0x10($sp)
/* 41044 80065C44 8FAD0014 */  lw        $t5, 0x14($sp)
/* 41048 80065C48 8FAE0018 */  lw        $t6, 0x18($sp)
/* 4104C 80065C4C 8FAF001C */  lw        $t7, 0x1C($sp)
/* 41050 80065C50 8FB80020 */  lw        $t8, 0x20($sp)
/* 41054 80065C54 8FB90024 */  lw        $t9, 0x24($sp)
/* 41058 80065C58 8FA20028 */  lw        $v0, 0x28($sp)
/* 4105C 80065C5C 8FA3002C */  lw        $v1, 0x2C($sp)
/* 41060 80065C60 8FA40030 */  lw        $a0, 0x30($sp)
/* 41064 80065C64 8FA50034 */  lw        $a1, 0x34($sp)
/* 41068 80065C68 8FA70038 */  lw        $a3, 0x38($sp)
/* 4106C 80065C6C ACC80000 */  sw        $t0, 0x0($a2)
/* 41070 80065C70 ACC90004 */  sw        $t1, 0x4($a2)
/* 41074 80065C74 ACCA0008 */  sw        $t2, 0x8($a2)
/* 41078 80065C78 ACCB000C */  sw        $t3, 0xC($a2)
/* 4107C 80065C7C ACCC0010 */  sw        $t4, 0x10($a2)
/* 41080 80065C80 ACCD0014 */  sw        $t5, 0x14($a2)
/* 41084 80065C84 ACCE0018 */  sw        $t6, 0x18($a2)
/* 41088 80065C88 ACCF001C */  sw        $t7, 0x1C($a2)
/* 4108C 80065C8C ACD80020 */  sw        $t8, 0x20($a2)
/* 41090 80065C90 ACD90024 */  sw        $t9, 0x24($a2)
/* 41094 80065C94 ACC20028 */  sw        $v0, 0x28($a2)
/* 41098 80065C98 ACC3002C */  sw        $v1, 0x2C($a2)
/* 4109C 80065C9C ACC40030 */  sw        $a0, 0x30($a2)
/* 410A0 80065CA0 ACC50034 */  sw        $a1, 0x34($a2)
/* 410A4 80065CA4 ACC70038 */  sw        $a3, 0x38($a2)
/* 410A8 80065CA8 03E00008 */  jr        $ra
/* 410AC 80065CAC 27BD0040 */   addiu    $sp, $sp, 0x40
/* 410B0 80065CB0 00000000 */  nop
/* 410B4 80065CB4 00000000 */  nop
/* 410B8 80065CB8 00000000 */  nop
/* 410BC 80065CBC 00000000 */  nop
