name: PR
on: [pull_request]

jobs:
  delete-matched-asm:
    name: Check matched assembly files are deleted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./coverage.py --fail-undeleted
  lint:
    name: Lint/format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          lines-changed-only: diff
          tidy-checks: ''

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the linting checks!"
