name: PR
on: [pull_request]

jobs:
  delete-matched-asm:
    name: Check matched assembly files are deleted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./coverage.py --fail-undeleted
  lint:
    name: Format and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Git
        run: |
          git log --oneline --graph --max-count=100
          git log --oneline --graph --max-count=100 HEAD origin/main
      - name: clang-format
        run: |
          git clang-format-14 --diff origin/main HEAD
      - name: Lint
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          lines-changed-only: diff
          tidy-checks: ''
          version: '15'
      - name: Fail if lint failed
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
