name: PR
on: [pull_request]

jobs:
  delete-matched-asm:
    name: Check matched assembly files are deleted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./coverage.py --fail-undeleted
  clang-format:
    name: See what clang-format thinks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch base branch
        run: git fetch origin $GITHUB_BASE_REF
      - name: Run clang-format
        run: |
          git clang-format-14 main --diff
