.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.11.1 */

glabel osContInit
/* 3BDE0 800609E0 3C028009 */  lui       $v0, %hi(__osContinitialized)
/* 3BDE4 800609E4 8C4229D0 */  lw        $v0, %lo(__osContinitialized)($v0)
/* 3BDE8 800609E8 27BDFF80 */  addiu     $sp, $sp, -0x80
/* 3BDEC 800609EC AFB40070 */  sw        $s4, 0x70($sp)
/* 3BDF0 800609F0 0080A021 */  addu      $s4, $a0, $zero
/* 3BDF4 800609F4 AFB60078 */  sw        $s6, 0x78($sp)
/* 3BDF8 800609F8 00A0B021 */  addu      $s6, $a1, $zero
/* 3BDFC 800609FC AFB50074 */  sw        $s5, 0x74($sp)
/* 3BE00 80060A00 00C0A821 */  addu      $s5, $a2, $zero
/* 3BE04 80060A04 AFBF007C */  sw        $ra, 0x7C($sp)
/* 3BE08 80060A08 AFB3006C */  sw        $s3, 0x6C($sp)
/* 3BE0C 80060A0C AFB20068 */  sw        $s2, 0x68($sp)
/* 3BE10 80060A10 AFB10064 */  sw        $s1, 0x64($sp)
/* 3BE14 80060A14 10400003 */  beqz      $v0, .LIQUE_80060A24
/* 3BE18 80060A18 AFB00060 */   sw       $s0, 0x60($sp)
/* 3BE1C 80060A1C 080182D7 */  j         .LIQUE_80060B5C
/* 3BE20 80060A20 00001021 */   addu     $v0, $zero, $zero
.LIQUE_80060A24:
/* 3BE24 80060A24 24040001 */  addiu     $a0, $zero, 0x1
/* 3BE28 80060A28 3C018009 */  lui       $at, %hi(__osContinitialized)
/* 3BE2C 80060A2C 0C019164 */  jal       osGetTime
/* 3BE30 80060A30 AC2429D0 */   sw       $a0, %lo(__osContinitialized)($at)
/* 3BE34 80060A34 00409021 */  addu      $s2, $v0, $zero
/* 3BE38 80060A38 00609821 */  addu      $s3, $v1, $zero
/* 3BE3C 80060A3C 16400022 */  bnez      $s2, .LIQUE_80060AC8
/* 3BE40 80060A40 24020004 */   addiu    $v0, $zero, 0x4
/* 3BE44 80060A44 16400007 */  bnez      $s2, .LIQUE_80060A64
/* 3BE48 80060A48 27B10040 */   addiu    $s1, $sp, 0x40
/* 3BE4C 80060A4C 3C020165 */  lui       $v0, (0x165A0BB >> 16)
/* 3BE50 80060A50 3442A0BB */  ori       $v0, $v0, (0x165A0BB & 0xFFFF)
/* 3BE54 80060A54 0053102B */  sltu      $v0, $v0, $s3
/* 3BE58 80060A58 1440001B */  bnez      $v0, .LIQUE_80060AC8
/* 3BE5C 80060A5C 24020004 */   addiu    $v0, $zero, 0x4
/* 3BE60 80060A60 27B10040 */  addiu     $s1, $sp, 0x40
.LIQUE_80060A64:
/* 3BE64 80060A64 02202021 */  addu      $a0, $s1, $zero
/* 3BE68 80060A68 27B00058 */  addiu     $s0, $sp, 0x58
/* 3BE6C 80060A6C 02002821 */  addu      $a1, $s0, $zero
/* 3BE70 80060A70 0C018DB0 */  jal       osCreateMesgQueue
/* 3BE74 80060A74 24060001 */   addiu    $a2, $zero, 0x1
/* 3BE78 80060A78 00004021 */  addu      $t0, $zero, $zero
/* 3BE7C 80060A7C 00004821 */  addu      $t1, $zero, $zero
/* 3BE80 80060A80 27A40020 */  addiu     $a0, $sp, 0x20
/* 3BE84 80060A84 24060000 */  addiu     $a2, $zero, 0x0
/* 3BE88 80060A88 3C070165 */  lui       $a3, (0x165A0BC >> 16)
/* 3BE8C 80060A8C 34E7A0BC */  ori       $a3, $a3, (0x165A0BC & 0xFFFF)
/* 3BE90 80060A90 00F3102B */  sltu      $v0, $a3, $s3
/* 3BE94 80060A94 00F33823 */  subu      $a3, $a3, $s3
/* 3BE98 80060A98 00D23023 */  subu      $a2, $a2, $s2
/* 3BE9C 80060A9C 00C23023 */  subu      $a2, $a2, $v0
/* 3BEA0 80060AA0 AFA80010 */  sw        $t0, 0x10($sp)
/* 3BEA4 80060AA4 AFA90014 */  sw        $t1, 0x14($sp)
/* 3BEA8 80060AA8 AFB10018 */  sw        $s1, 0x18($sp)
/* 3BEAC 80060AAC 0C0191A0 */  jal       osSetTimer
/* 3BEB0 80060AB0 AFB0001C */   sw       $s0, 0x1C($sp)
/* 3BEB4 80060AB4 02202021 */  addu      $a0, $s1, $zero
/* 3BEB8 80060AB8 02002821 */  addu      $a1, $s0, $zero
/* 3BEBC 80060ABC 0C018DCC */  jal       osRecvMesg
/* 3BEC0 80060AC0 24060001 */   addiu    $a2, $zero, 0x1
/* 3BEC4 80060AC4 24020004 */  addiu     $v0, $zero, 0x4
.LIQUE_80060AC8:
/* 3BEC8 80060AC8 3C01800A */  lui       $at, %hi(__osMaxControllers)
/* 3BECC 80060ACC A02291D2 */  sb        $v0, %lo(__osMaxControllers)($at)
/* 3BED0 80060AD0 0C01833C */  jal       __osPackRequestData
/* 3BED4 80060AD4 00002021 */   addu     $a0, $zero, $zero
/* 3BED8 80060AD8 24040001 */  addiu     $a0, $zero, 0x1
/* 3BEDC 80060ADC 3C11800B */  lui       $s1, %hi(__osContPifRam)
/* 3BEE0 80060AE0 2631F910 */  addiu     $s1, $s1, %lo(__osContPifRam)
/* 3BEE4 80060AE4 0C018F98 */  jal       __osSiRawStartDma
/* 3BEE8 80060AE8 02202821 */   addu     $a1, $s1, $zero
/* 3BEEC 80060AEC 02802021 */  addu      $a0, $s4, $zero
/* 3BEF0 80060AF0 27B00058 */  addiu     $s0, $sp, 0x58
/* 3BEF4 80060AF4 02002821 */  addu      $a1, $s0, $zero
/* 3BEF8 80060AF8 0C018DCC */  jal       osRecvMesg
/* 3BEFC 80060AFC 24060001 */   addiu    $a2, $zero, 0x1
/* 3BF00 80060B00 00002021 */  addu      $a0, $zero, $zero
/* 3BF04 80060B04 0C018F98 */  jal       __osSiRawStartDma
/* 3BF08 80060B08 02202821 */   addu     $a1, $s1, $zero
/* 3BF0C 80060B0C 02802021 */  addu      $a0, $s4, $zero
/* 3BF10 80060B10 02002821 */  addu      $a1, $s0, $zero
/* 3BF14 80060B14 24060001 */  addiu     $a2, $zero, 0x1
/* 3BF18 80060B18 0C018DCC */  jal       osRecvMesg
/* 3BF1C 80060B1C 00408821 */   addu     $s1, $v0, $zero
/* 3BF20 80060B20 02C02021 */  addu      $a0, $s6, $zero
/* 3BF24 80060B24 0C0182E1 */  jal       __osContGetInitData
/* 3BF28 80060B28 02A02821 */   addu     $a1, $s5, $zero
/* 3BF2C 80060B2C 240200FD */  addiu     $v0, $zero, 0xFD
/* 3BF30 80060B30 3C01800A */  lui       $at, %hi(__osContLastCmd)
/* 3BF34 80060B34 A02291F0 */  sb        $v0, %lo(__osContLastCmd)($at)
/* 3BF38 80060B38 0C018FD0 */  jal       __osSiCreateAccessQueue
/* 3BF3C 80060B3C 00000000 */   nop
/* 3BF40 80060B40 3C04800E */  lui       $a0, %hi(__osEepromTimerQ)
/* 3BF44 80060B44 24848E20 */  addiu     $a0, $a0, %lo(__osEepromTimerQ)
/* 3BF48 80060B48 3C05800A */  lui       $a1, %hi(__osEepromTimerMsg)
/* 3BF4C 80060B4C 24A591F4 */  addiu     $a1, $a1, %lo(__osEepromTimerMsg)
/* 3BF50 80060B50 0C018DB0 */  jal       osCreateMesgQueue
/* 3BF54 80060B54 24060001 */   addiu    $a2, $zero, 0x1
/* 3BF58 80060B58 02201021 */  addu      $v0, $s1, $zero
.LIQUE_80060B5C:
/* 3BF5C 80060B5C 8FBF007C */  lw        $ra, 0x7C($sp)
/* 3BF60 80060B60 8FB60078 */  lw        $s6, 0x78($sp)
/* 3BF64 80060B64 8FB50074 */  lw        $s5, 0x74($sp)
/* 3BF68 80060B68 8FB40070 */  lw        $s4, 0x70($sp)
/* 3BF6C 80060B6C 8FB3006C */  lw        $s3, 0x6C($sp)
/* 3BF70 80060B70 8FB20068 */  lw        $s2, 0x68($sp)
/* 3BF74 80060B74 8FB10064 */  lw        $s1, 0x64($sp)
/* 3BF78 80060B78 8FB00060 */  lw        $s0, 0x60($sp)
/* 3BF7C 80060B7C 03E00008 */  jr        $ra
/* 3BF80 80060B80 27BD0080 */   addiu    $sp, $sp, 0x80

glabel __osContGetInitData
/* 3BF84 80060B84 27BDFFE8 */  addiu     $sp, $sp, -0x18
/* 3BF88 80060B88 00A03821 */  addu      $a3, $a1, $zero
/* 3BF8C 80060B8C 3C0A800B */  lui       $t2, %hi(__osContPifRam)
/* 3BF90 80060B90 254AF910 */  addiu     $t2, $t2, %lo(__osContPifRam)
/* 3BF94 80060B94 00003021 */  addu      $a2, $zero, $zero
/* 3BF98 80060B98 00004021 */  addu      $t0, $zero, $zero
/* 3BF9C 80060B9C 3C03800A */  lui       $v1, %hi(__osMaxControllers)
/* 3BFA0 80060BA0 906391D2 */  lbu       $v1, %lo(__osMaxControllers)($v1)
/* 3BFA4 80060BA4 00806021 */  addu      $t4, $a0, $zero
/* 3BFA8 80060BA8 10600026 */  beqz      $v1, .LIQUE_80060C44
/* 3BFAC 80060BAC AFB00010 */   sw       $s0, 0x10($sp)
/* 3BFB0 80060BB0 240B0001 */  addiu     $t3, $zero, 0x1
/* 3BFB4 80060BB4 24A50002 */  addiu     $a1, $a1, 0x2
/* 3BFB8 80060BB8 3C098000 */  lui       $t1, %hi(__osBbPakAddress)
/* 3BFBC 80060BBC 25290374 */  addiu     $t1, $t1, %lo(__osBbPakAddress)
.LIQUE_80060BC0:
/* 3BFC0 80060BC0 894D0000 */  lwl       $t5, 0x0($t2)
/* 3BFC4 80060BC4 994D0003 */  lwr       $t5, 0x3($t2)
/* 3BFC8 80060BC8 894E0004 */  lwl       $t6, 0x4($t2)
/* 3BFCC 80060BCC 994E0007 */  lwr       $t6, 0x7($t2)
/* 3BFD0 80060BD0 ABAD0000 */  swl       $t5, 0x0($sp)
/* 3BFD4 80060BD4 BBAD0003 */  swr       $t5, 0x3($sp)
/* 3BFD8 80060BD8 ABAE0004 */  swl       $t6, 0x4($sp)
/* 3BFDC 80060BDC BBAE0007 */  swr       $t6, 0x7($sp)
/* 3BFE0 80060BE0 93A20002 */  lbu       $v0, 0x2($sp)
/* 3BFE4 80060BE4 304200C0 */  andi      $v0, $v0, 0xC0
/* 3BFE8 80060BE8 00021102 */  srl       $v0, $v0, 4
/* 3BFEC 80060BEC 1440000C */  bnez      $v0, .LIQUE_80060C20
/* 3BFF0 80060BF0 A0A20001 */   sb       $v0, 0x1($a1)
/* 3BFF4 80060BF4 00CB2004 */  sllv      $a0, $t3, $a2
/* 3BFF8 80060BF8 01042025 */  or        $a0, $t0, $a0
/* 3BFFC 80060BFC 93A20005 */  lbu       $v0, 0x5($sp)
/* 3C000 80060C00 93A30004 */  lbu       $v1, 0x4($sp)
/* 3C004 80060C04 00021200 */  sll       $v0, $v0, 8
/* 3C008 80060C08 00621825 */  or        $v1, $v1, $v0
/* 3C00C 80060C0C A4E30000 */  sh        $v1, 0x0($a3)
/* 3C010 80060C10 8D220000 */  lw        $v0, 0x0($t1)
/* 3C014 80060C14 308800FF */  andi      $t0, $a0, 0xFF
/* 3C018 80060C18 0002102B */  sltu      $v0, $zero, $v0
/* 3C01C 80060C1C A0A20000 */  sb        $v0, 0x0($a1)
.LIQUE_80060C20:
/* 3C020 80060C20 25290004 */  addiu     $t1, $t1, 0x4
/* 3C024 80060C24 24C60001 */  addiu     $a2, $a2, 0x1
/* 3C028 80060C28 254A0008 */  addiu     $t2, $t2, 0x8
/* 3C02C 80060C2C 24A50004 */  addiu     $a1, $a1, 0x4
/* 3C030 80060C30 3C03800A */  lui       $v1, %hi(__osMaxControllers)
/* 3C034 80060C34 906391D2 */  lbu       $v1, %lo(__osMaxControllers)($v1)
/* 3C038 80060C38 00C3102A */  slt       $v0, $a2, $v1
/* 3C03C 80060C3C 1440FFE0 */  bnez      $v0, .LIQUE_80060BC0
/* 3C040 80060C40 24E70004 */   addiu    $a3, $a3, 0x4
.LIQUE_80060C44:
/* 3C044 80060C44 3C028000 */  lui       $v0, %hi(__osBbIsBb)
/* 3C048 80060C48 8C420388 */  lw        $v0, %lo(__osBbIsBb)($v0)
/* 3C04C 80060C4C 10400025 */  beqz      $v0, .LIQUE_80060CE4
/* 3C050 80060C50 8FB00010 */   lw       $s0, 0x10($sp)
/* 3C054 80060C54 3C058000 */  lui       $a1, %hi(__osBbHackFlags)
/* 3C058 80060C58 8CA5038C */  lw        $a1, %lo(__osBbHackFlags)($a1)
/* 3C05C 80060C5C 10A00021 */  beqz      $a1, .LIQUE_80060CE4
/* 3C060 80060C60 00031880 */   sll      $v1, $v1, 2
/* 3C064 80060C64 00E33823 */  subu      $a3, $a3, $v1
/* 3C068 80060C68 00051080 */  sll       $v0, $a1, 2
/* 3C06C 80060C6C 00471021 */  addu      $v0, $v0, $a3
/* 3C070 80060C70 24040001 */  addiu     $a0, $zero, 0x1
/* 3C074 80060C74 00A42004 */  sllv      $a0, $a0, $a1
/* 3C078 80060C78 34830001 */  ori       $v1, $a0, 0x1
/* 3C07C 80060C7C 00031827 */  nor       $v1, $zero, $v1
/* 3C080 80060C80 01031824 */  and       $v1, $t0, $v1
/* 3C084 80060C84 88ED0000 */  lwl       $t5, 0x0($a3)
/* 3C088 80060C88 98ED0003 */  lwr       $t5, 0x3($a3)
/* 3C08C 80060C8C ABAD0008 */  swl       $t5, 0x8($sp)
/* 3C090 80060C90 BBAD000B */  swr       $t5, 0xB($sp)
/* 3C094 80060C94 884D0000 */  lwl       $t5, 0x0($v0)
/* 3C098 80060C98 984D0003 */  lwr       $t5, 0x3($v0)
/* 3C09C 80060C9C A8ED0000 */  swl       $t5, 0x0($a3)
/* 3C0A0 80060CA0 B8ED0003 */  swr       $t5, 0x3($a3)
/* 3C0A4 80060CA4 31020001 */  andi      $v0, $t0, 0x1
/* 3C0A8 80060CA8 00A21004 */  sllv      $v0, $v0, $a1
/* 3C0AC 80060CAC 00621825 */  or        $v1, $v1, $v0
/* 3C0B0 80060CB0 01042024 */  and       $a0, $t0, $a0
/* 3C0B4 80060CB4 00A42007 */  srav      $a0, $a0, $a1
/* 3C0B8 80060CB8 00641825 */  or        $v1, $v1, $a0
/* 3C0BC 80060CBC 3C028000 */  lui       $v0, %hi(__osBbHackFlags)
/* 3C0C0 80060CC0 8C42038C */  lw        $v0, %lo(__osBbHackFlags)($v0)
/* 3C0C4 80060CC4 306800FF */  andi      $t0, $v1, 0xFF
/* 3C0C8 80060CC8 00021080 */  sll       $v0, $v0, 2
/* 3C0CC 80060CCC 00471021 */  addu      $v0, $v0, $a3
/* 3C0D0 80060CD0 8BAD0008 */  lwl       $t5, 0x8($sp)
/* 3C0D4 80060CD4 9BAD000B */  lwr       $t5, 0xB($sp)
/* 3C0D8 80060CD8 A84D0000 */  swl       $t5, 0x0($v0)
/* 3C0DC 80060CDC B84D0003 */  swr       $t5, 0x3($v0)
/* 3C0E0 80060CE0 8FB00010 */  lw        $s0, 0x10($sp)
.LIQUE_80060CE4:
/* 3C0E4 80060CE4 A1880000 */  sb        $t0, 0x0($t4)
/* 3C0E8 80060CE8 03E00008 */  jr        $ra
/* 3C0EC 80060CEC 27BD0018 */   addiu    $sp, $sp, 0x18

glabel __osPackRequestData
/* 3C0F0 80060CF0 27BDFFF8 */  addiu     $sp, $sp, -0x8
/* 3C0F4 80060CF4 308800FF */  andi      $t0, $a0, 0xFF
/* 3C0F8 80060CF8 00003021 */  addu      $a2, $zero, $zero
/* 3C0FC 80060CFC 3C03800B */  lui       $v1, %hi(__osContPifRam)
/* 3C100 80060D00 2463F910 */  addiu     $v1, $v1, %lo(__osContPifRam)
.LIQUE_80060D04:
/* 3C104 80060D04 AC600000 */  sw        $zero, 0x0($v1)
/* 3C108 80060D08 24C60001 */  addiu     $a2, $a2, 0x1
/* 3C10C 80060D0C 28C2000F */  slti      $v0, $a2, 0xF
/* 3C110 80060D10 1440FFFC */  bnez      $v0, .LIQUE_80060D04
/* 3C114 80060D14 24630004 */   addiu    $v1, $v1, 0x4
/* 3C118 80060D18 3C02800B */  lui       $v0, %hi(__osContPifRam + 0x3C)
/* 3C11C 80060D1C 2442F94C */  addiu     $v0, $v0, %lo(__osContPifRam + 0x3C)
/* 3C120 80060D20 2447FFC4 */  addiu     $a3, $v0, -0x3C
/* 3C124 80060D24 00003021 */  addu      $a2, $zero, $zero
/* 3C128 80060D28 24040001 */  addiu     $a0, $zero, 0x1
/* 3C12C 80060D2C 240300FF */  addiu     $v1, $zero, 0xFF
/* 3C130 80060D30 AC440000 */  sw        $a0, 0x0($v0)
/* 3C134 80060D34 3C05800A */  lui       $a1, %hi(__osMaxControllers)
/* 3C138 80060D38 90A591D2 */  lbu       $a1, %lo(__osMaxControllers)($a1)
/* 3C13C 80060D3C 24020003 */  addiu     $v0, $zero, 0x3
/* 3C140 80060D40 A3A30000 */  sb        $v1, 0x0($sp)
/* 3C144 80060D44 A3A40001 */  sb        $a0, 0x1($sp)
/* 3C148 80060D48 A3A20002 */  sb        $v0, 0x2($sp)
/* 3C14C 80060D4C A3A80003 */  sb        $t0, 0x3($sp)
/* 3C150 80060D50 A3A30004 */  sb        $v1, 0x4($sp)
/* 3C154 80060D54 A3A30005 */  sb        $v1, 0x5($sp)
/* 3C158 80060D58 A3A30006 */  sb        $v1, 0x6($sp)
/* 3C15C 80060D5C 10A0000F */  beqz      $a1, .LIQUE_80060D9C
/* 3C160 80060D60 A3A30007 */   sb       $v1, 0x7($sp)
.LIQUE_80060D64:
/* 3C164 80060D64 8BA90000 */  lwl       $t1, 0x0($sp)
/* 3C168 80060D68 9BA90003 */  lwr       $t1, 0x3($sp)
/* 3C16C 80060D6C 8BAA0004 */  lwl       $t2, 0x4($sp)
/* 3C170 80060D70 9BAA0007 */  lwr       $t2, 0x7($sp)
/* 3C174 80060D74 A8E90000 */  swl       $t1, 0x0($a3)
/* 3C178 80060D78 B8E90003 */  swr       $t1, 0x3($a3)
/* 3C17C 80060D7C A8EA0004 */  swl       $t2, 0x4($a3)
/* 3C180 80060D80 B8EA0007 */  swr       $t2, 0x7($a3)
/* 3C184 80060D84 3C02800A */  lui       $v0, %hi(__osMaxControllers)
/* 3C188 80060D88 904291D2 */  lbu       $v0, %lo(__osMaxControllers)($v0)
/* 3C18C 80060D8C 24C60001 */  addiu     $a2, $a2, 0x1
/* 3C190 80060D90 00C2102A */  slt       $v0, $a2, $v0
/* 3C194 80060D94 1440FFF3 */  bnez      $v0, .LIQUE_80060D64
/* 3C198 80060D98 24E70008 */   addiu    $a3, $a3, 0x8
.LIQUE_80060D9C:
/* 3C19C 80060D9C 240200FE */  addiu     $v0, $zero, 0xFE
/* 3C1A0 80060DA0 A0E20000 */  sb        $v0, 0x0($a3)
/* 3C1A4 80060DA4 03E00008 */  jr        $ra
/* 3C1A8 80060DA8 27BD0008 */   addiu    $sp, $sp, 0x8
/* 3C1AC 80060DAC 00000000 */  nop
